### ISSUE TITLE
species_names not working

### ISSUE THREAD

**Issue by luthermiles** [modflowpy/flopy#1005]
Hi all. I'm creating a multispecies reactive transport model and I would like for my UCN output files to bear their respective species' name. I've tried doing this with a list and dictionary - just won't work. What am I doing wrong? Help, please. 

Also, is the kinetic biodegradation reaction package ever going to be supported by FloPy? I'm having to prepare the input file offline and rerun the MT3D-USGS exe. 

`sconc = 0
sconc2 = 9.28
sconc3 = 105
sconc4 = 0.0659
sconc5 = 0.0497
sconc6 = 64.3
sconc7 = 9.92e-6

species_names={sconc:['phenol'], 
               sconc2:['oxygen'], 
               sconc3:['nitrate'], 
               sconc4:['manganese'], 
               sconc5:['iron'], 
               sconc6:['sulphate'],
               sconc7:['methane']}

btn = fpmt.Mt3dBtn(mt, prsity=0.125, icbund=1, ncomp=7, mcomp=7, 
                  savucn=True, chkmas=True, munit='G', nprs=0,
                  species_names=species_names, sconc=sconc,
                  sconc2=sconc2, sconc3=sconc3, sconc4=sconc4,
                  sconc5=sconc5, sconc6=sconc6, sconc7=sconc7)`

**Comment by langevin-usgs** [comment]
As far as I can tell, the `species_name argument` doesn't do anything in the flopy mt3d source code.  It is stored there, but it won't do what you want it to do.  

There may be a sneaky way to rename your ucn files the way you want, although I haven't tried it.  After you create your mt model, you might be able to make calls like this:

```
mt.add_output('phenol.ucn', 201, binflag=True)
mt.add_output('oxygen.ucn', 202, binflag=True)
mt.add_output('nitrate.ucn', 203, binflag=True)
mt.add_output('manganese.ucn', 204, binflag=True)
mt.add_output('iron.ucn', 205, binflag=True)
mt.add_output('sulfate.ucn', 206, binflag=True)
mt.add_output('methane.ucn', 207, binflag=True)
```
It's a long shot, and may very well not work, so there are no guarantees here.

Regarding the additional reaction options for MT3D-USGS, I do think those would be worth adding.  Perhaps we can get @emorway-usgs to do this in his free time?

**Comment by luthermiles** [comment]
Thanks, it worked. The same method also sort of worked for the .MAS file outputs, but those weren't in a readable text format.
