### ISSUE TITLE
Concentration modeling with USG and Flopy

### ISSUE THREAD

**Issue by pablinus68** [modflowpy/flopy#1010]
Hi everybody, I am trying to build a MODFLOW-USG model using FLOPY. I know that the beta version of USG allows to simulate concentration changes, I think with the BCT and PCB packages, but I do not know how to create these objects using flopy. Could anyone send me some example scripts to do that ? Thanks !!!

**Comment by jdhughes-usgs** [comment]
@langevin-usgs can we close this?

**Comment by langevin-usgs** [comment]
We are not currently working to support these packages, but would be willing to accept contributions from our users (in the form of pull requests) if anyone wants to take this on.
