### ISSUE TITLE
GridIntersect not working anymore

### ISSUE THREAD

**Issue by ebake310** [modflowpy/flopy#1016]
I updated my version of FloPy to 3.3.2 and now none of my code to intersect my model grid with linestrings and polygons works. At first I was receiving the error: 'GridIntersect' object has no attribute 'intersect_linestring' and 'GridIntersect' object has no attribute 'intersect_polygon' and I read that the function has just changed to the more generic function 'intersect'. However, when I run this new function it just results in an empty rec_array. 

For example, I have tried all three ways of creating the grid intersection object:
ixobj = flopy.utils.gridintersect.GridIntersect(gwf_bound.modelgrid, method="vertex", rtree=False)
ixobj = flopy.utils.gridintersect.GridIntersect(gwf_bound.modelgrid, method="structured")
ixobj = flopy.utils.gridintersect.GridIntersect(gwf_bound.modelgrid)
followed by:
rint_Tic = ixobj.intersect(rshp.geometry[0]) # rshp is the shapefile read in using geopandas containing a linestring
(I also tried the function 'intersects' but this also results in an empty array)
but it just yields an empty array:
rec.array([],dtype=[('cellids', '0'), ('vertices', '0'), ('lengths', '<f8'), ('ixshapes', '0')])

I am having this same problem with all of the shapefile types (e.g. linestrings, polygons, and points)

**Comment by langevin-usgs** [comment]
Hey, that is frustrating.  I ran into the same problem, but was able to get the generic intersect method to work just fine.  The notebook here shows how I was able to get it to work:  https://modflow6-examples.readthedocs.io/en/master/_notebooks/ex-gwf-advtidal.html.  We probably should have kept backward compatibility for people like you, which we will try to do in the future.  I do like a single intersect() entry point, though.  It is much cleaner.

**Comment by ebake310** [comment]
So to make sure I am understanding, you manually used shapely to create the polygons and then ran that through the intersect function, rather than importing a shapefile?

recharge_zone_1 = Polygon(shell=[(0, 0), (3000, 0), (3000, 5500), (1000, 7500), (0, 7500), (0, 0),],)

**Comment by langevin-usgs** [comment]
In that particular case, I knew the coordinates of the polygon so I did not have to read them from a shapefile.  So yes, I created the shapely polygon directly.

**Comment by ebake310** [comment]
ixobj = flopy.utils.gridintersect.GridIntersect(gwf_bound.modelgrid, method="vertex", rtree=True)
from shapely.geometry import LineString
line = LineString([(487919.359607, 5.025300e+06), (487525.999461, 5.025038e+06), (487495.147685, 5.024514e+06),(499045.228573, 5.010293e+06)])
rint_Tic = ixobj.intersect(line)

I tried this code but the rec_array is still empty. It seems to be exactly what you did, just intersecting a line instead of a polygon.

**Comment by ebake310** [comment]
Thanks, just got it to work!

**Comment by oscarfasanchez** [comment]
I have a really complex polygon :/
so...what should I do? :(

**Comment by langevin-usgs** [comment]
@oscarfasanchez, please make the simplest example that shows what is not working and paste the example here, and we can take a look.
