### ISSUE TITLE
Extend PlotView object support to work with Gridgen object with DISU grids

### ISSUE THREAD

**Issue by javgs-bd** [modflowpy/flopy#1018]
[This jupyter example](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3.3_PlotMapView.ipynb) shows that, in order to use the PlotView object with a DISU Unstructured grid for MF6, the user has to build an UnstructuredGrid discretization object. 

The example works by loading external files containing information for the verts and iverts arguments of the UnstructuredGrid object, and while prints are provided for both lists, the description ultimately means the user has to actually build those list . 

From the available print of this code,
```
for icell, vertlist in enumerate(iverts[:5]):
    print('List of vertices for cell {}: {}'.format(icell, vertlist))

```
and from this description, 
> iverts is also a 2-dimensional list, where the outer list is of size ncells, and the inner list is a list of the vertex numbers that comprise the cell.

one should be able to gather the info needed to proceed. However, if the model building process has started by using the Gridgen module, one has already available the get_gridprops_disu6() which provides lists 'vertices' and 'cell2d'.

Passing those lists to the UnstructuredGrid object seems to be the intention in the [documentation](https://modflowpy.github.io/flopydoc/unstructuredgrid.html?highlight=unstructured#flopy.discretization.unstructuredgrid.UnstructuredGrid): However, cell2d is not actually in the parameter list of the object.

Is this (passing the cell2d list) something that could be implemented in the UnstructureGrid object in order to facilitate the use of PlotView and PlotCrossSection objects?

**Comment by langevin-usgs** [comment]
Hi @javgs-bd, yes something is off here.  The docstrings for the UnstructuredGrid object mentions cell2d, but as you noticed, it doesn't accept cell2d as an argument.  However, the UnstructuredGrid `__init__` constructor does accept vertices and iverts.  iverts is a list of size nodes.  And in this list are lists of vertex numbers for each cell.  You can get verts and iverts directly from the flopy gridgen object using the `get_verts_iverts()` method.  So with this information, you should be able to create the UnstructuredGrid object and possible do some plotting.

Alternatively, If you were to create a flopy modflow6 simulation that has a gwf object, it would have created the UnstructuredGrid object automatically for you.  For example:

```

# process with gridgen to create gridgen object (gobj)

sim = flopy.mf6.MFSimulation(sim_name=name, sim_ws=ws, exe_name='mf6')
tdis = flopy.mf6.ModflowTdis(sim)
ims = flopy.mf6.ModflowIms(sim)
gwf = flopy.mf6.ModflowGwf(sim, modelname=name, save_flows=True)
disu = flopy.mf6.ModflowGwfdisu(gwf, **gobj.get_gridprops_disu6())
```

At this point, gwf should have a valid unstructured modelgrid, which you can access as:

```
gwf.modelgrid
```

I suspect the UnstructuredGrid plotting is fairly fragile at this time, especially for grids that have a different number of cells in each layer or do not have layers at all.  I'll see if I can beef up the examples for gridgen.

**Comment by javgs-bd** [comment]
Many thanks @langevin-usgs, all this is really good information.
I had missed the `get_verts_iverts()` method from the flopy gridgen module. That worked straight away to get the vert and ivert lists. I also had the gwf object of my MF6 simulation, so, I was able to try both suggestions. 
Howerver, I keep getting the same error for either of them, and I guess it comes down to the fact that (if I understand correctly) the UnstructureGrid object is expecting the same number of nodes for each layer. Apologies for the long reply but I tried to traceback this as much as I could.

This is what I'm trying with the gridgen object. 
The grid has multiple layers, with variable number of nodes/cells per layer. I actually can plot the grid without any problem using the plot() method of the gridgen object, so I believe there is no problem with that. I'm naming as ggen the gridgen object as _ggen_, and what I'm doing to get the UnstructuredGrid object is this:

```
geometry = ggen.get_nod_recarray()
geometry = geometry.view(np.recarray)

vertices, iverts = ggen.get_verts_iverts(len(geometry['node']))
ncpl             = ggen.get_nodelay() 
xg               = geometry['x']  
yg               = geometry['y']  

ug = UnstructuredGrid(vertices , iverts , xg, yg, ncpl=ncpl)
```

Which gives the following error:
```
Traceback (most recent call last):

  File "full_path_to_wfolder\script.py", line 291, in <module>
    ug = UnstructuredGrid(vertices , iverts , xg, yg, ncpl=ncpl)

  File "win_user_path\.conda\envs\flopy\lib\site-packages\flopy\discretization\unstructuredgrid.py", line 75, in __init__
    assert np.all([n == len(iverts) for n in ncpl])

AssertionError
```

On the other hand, if forget about the ggen object and try to access the modelgrid attribute of the gwf object, I get the same error. Here is what I'm doing to build the model and get UnstructuredGrid object:

```
ggen_props = ggen.get_gridprops_disu6()

root_name = 'model'
model_folder = './model'


sim = flopy.mf6.MFSimulation(
                              sim_name = root_name,          
                              exe_name = "mf6",             
                              version  = "mf6",             
                              sim_ws   = model_folder       
                             )


gwf = flopy.mf6.ModflowGwf(
                            sim, 
                            modelname       = root_name,                             
                            model_nam_file  = root_name + '.nam' 
                          )


tdis = flopy.mf6.ModflowTdis(
                              sim,                            
                              pname      = "tdis",             
                              time_units = "days", 
                              nper       = 1,                  
                              perioddata = [(1.0, 1, 1.0)]     
                            )


dis = flopy.mf6.ModflowGwfdisu(
                               gwf,
                               length_units = 'meters',
                               nogrb        = False,
                               xorigin      = x_ul,                  #--- x,ul and y_ul are real word coordinates 
                               yorigin      = y_ul,                  #--- (floats) of the model upper left corner
                               angrot       = arot,                  #--- arot is the angle of rotation (float)
                               nodes        = ggen_props['nodes'],
                               nja          = ggen_props['nja'],
                               nvert        = ggen_props['nvert'],
                               top          = ggen_props['top'],                        
                               bot          = ggen_props['bot'],
                               area         = ggen_props['area'],
                               iac          = ggen_props['iac'],
                               ja           = ggen_props['ja'],
                               ihc          = ggen_props['ihc'],
                               cl12         = ggen_props['cl12'],
                               hwva         = ggen_props['hwva'],
                               angldegx     = ggen_props['angldegx'],                               
                               vertices     = ggen_props['vertices'],
                               cell2d       = ggen_props['cell2d'],                               
                              )

mgrid = gwf.modelgrid

```

Which gives the following error:

```
Traceback (most recent call last):

  File "full_path_to_wfolder\script.py", line 297, in <module>
    mgrid = gwf.modelgrid

  File "win_user_path\.conda\envs\flopy\lib\site-packages\flopy\mf6\mfmodel.py", line 436, in modelgrid
    self._modelgrid = UnstructuredGrid(

  File "win_user_path\.conda\envs\flopy\lib\site-packages\flopy\discretization\unstructuredgrid.py", line 75, in __init__
    assert np.all([n == len(iverts) for n in ncpl])

TypeError: 'NoneType' object is not iterable
```

By looking at the code of UnstructuredGrid where my scripts are failing, 

```
        if iverts is not None:
            if self.layered:
                assert np.all([n == len(iverts) for n in ncpl])
                assert np.array(self.xcellcenters).shape[0] == self.ncpl[0]
                assert np.array(self.ycellcenters).shape[0] == self.ncpl[0]
            else:
                msg = "Length of iverts must equal ncpl.sum " "({} {})".format(
                    len(iverts), ncpl
                )
                assert len(iverts) == np.sum(ncpl), msg
                assert np.array(self.xcellcenters).shape[0] == self.ncpl
                assert np.array(self.ycellcenters).shape[0] == self.ncpl
```

I can see that flopy is always assuming this is a layered model. I thought it could succeed if I flaged the call to UnstructuredGrid with layered=false, but then I get the following:

```
Traceback (most recent call last):

  File "full_path_to_wfolder\script.py", line 291, in <module>
    ug = UnstructuredGrid(vertices, iverts , xg, yg, ncpl=ncpl, layered=False)

  File "win_user_path\.conda\envs\flopy\lib\site-packages\flopy\discretization\unstructuredgrid.py", line 83, in __init__
    assert np.array(self.xcellcenters).shape[0] == self.ncpl

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```
I checked what 'np.array(vertices).shape[0]' gave me and it is a number that is neither the sum of all ncpl elements nor one of them. Maybe it is the number of unique vertices?. In any case seems that it is not what the UnstructureGrid code is expecting to compare with ncpl.

I could try to generate a full minimal example using a simple disu grid, to verify if the error keeps happening, but maybe this bunch of checks already helps.

**Comment by langevin-usgs** [comment]
Yeah, I've been working on it this morning trying to get a minimal example up and running.  I can get it to work for DISV, when the grid is the same for all layers, but it doesn't look like the UnstructuredGrid modelgrid object is set up to work with many of the other utilities, like plotting, for example.  

The following will create an UnstructuredGrid object using the gridgen object (called g below).  Note that the trick is pass in a list for ncpl, where the list is the number of cells in each layer.  

```
#  Create and plot an UnstructuredGrid object 
ncells = g.get_nodes()
xcyc = g.get_cellxy(ncells)
verts, iverts = g.get_verts_iverts(ncells)
ncpl = g.get_nodelay()
ugrid = flopy.discretization.UnstructuredGrid(ncpl=ncpl,
                                              vertices=verts, 
                                              iverts=iverts, 
                                              xcenters=xcyc[:, 0], 
                                              ycenters=xcyc[:, 1],
                                             )

# the get_cell_vertices() method is working
print(ugrid.get_cell_vertices(1))
```

There is some cleanup to do with these discretization objects, and once that's done I'm optimistic I can get the plotting functional.  I'm going to finish up with the DISV gridgen example first, and then work on a fully unstructured DISU example.

**Comment by javgs-bd** [comment]
Thank you, and yes, I applied the suggested block of code and I keep getting the same error. I guess it is the variable number of cells per layers then. Will look forward for any update. Thanks again.
