### ISSUE TITLE
buggs about compiling SEAWAT

### ISSUE THREAD

**Issue by nossi1998bb** [modflowpy/flopy#1022]
(I'm Japanese and not good at English)
I use macOS. I wanted to use Flopy and SWI2 so I downloaded Xcode and gfortran. Next, I compiled modflow2005 successfully(typed"python make_..."). But I failed to compile SEAWAT. Terminal says "file not found". Could you please the way SEAWET is successfully downloaded.

**Comment by langevin-usgs** [comment]
You don't need to compile the program.  You can download executables, including SEAWAT, for your Mac here:  https://github.com/MODFLOW-USGS/executables
