### ISSUE TITLE
flopy.plot.PlotMapView in USG

### ISSUE THREAD

**Issue by manupy-hub** [modflowpy/flopy#1024]
Hi I created a model in USG unstructured with Gridgen.
I wanted to plot in a similar way as I have done in Mf2005 and MF6 but it does not work for USG. Is it implemented?

# USG Model object
mu = flopy.modflow.Modflow(model_ws=modflow_dir, modelname='ModelUSG', 
                           version='mfusg', exe_name='mfusg')

m=flopy.plot.PlotMapView(
    model=mu,
    modelgrid=None)

AttributeError: 'NoneType' object has no attribute 'grid_type'

I was thinking that maybe I need the modelgrid, but how can I obtain this in USG?

Thank you!

**Comment by langevin-usgs** [comment]
Related to #896 and #1018.  Much of the unstructured grid support is not implemented yet, but we're working on it.

**Comment by langevin-usgs** [comment]
See the gridgen notebook for an example of how to use the new plotting capabilities for MODFLOW-USG.
