### ISSUE TITLE
Is MODLFLOW-USG transport supported?

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1025]
I see there is a module for developing the bct package for MODFLOW-USG Transport:

https://modflowpy.github.io/flopydoc/mfbct.html

However, in MODFLOW-USG transport, concentrations are written to the same boundary conditions packages as the flow simulation. There seems to be no functionality or examples for this.

Does flopy support MODFLOW-USG Transport simulations? If so, are there any examples?

Thanks

**Comment by langevin-usgs** [comment]
This bct flopy module was developed a while back and has not been maintained and curated with the transport version of MODFLOW-USG.  So unfortunately, you are own your own with this module for now.  We've been doing some work to update the unstructured grid support and plotting, mostly for MODFLOW 6, but we are hoping to find some time to add better support for MODFLOW-USG as well.
