### ISSUE TITLE
get_destination_pathline_data returns all pathlines traveling through dest_cells

### ISSUE THREAD

**Issue by TroelsNV** [modflowpy/flopy#1029]
This is not really a bug, but maybe a clarification is needed in the documentation, or the code should be changed.

In: get_destination_pathline_data function from modpathfile.py, all pathlines are returned that travels through the specific destination cell. The part of the code is copied below.

line 397:  dest_cells = np.array(dest_cells, dtype=raslice.dtype)  # get destination cells
line 398:  inds = np.in1d(raslice, dest_cells)  # return boolean array based on destination cells
line 399:  epdest = ra[inds].copy().view(np.recarray)  # return cells where the pathline travels through

Line 398 returns a boolean array of all particle traces that goes through a specific cell, and not only the particles that end in the specific destination cells.

Maybe it should be more clearly defined that it is not necessarily the particles that end in the cell but also particles traveling through.

An example can be seen in this setup, where a well is located in cell [[(2000739,)]], but some particles travel through without stopping in the cell.

[model_ws.zip](https://github.com/modflowpy/flopy/files/5672282/model_ws.zip)

**Comment by langevin-usgs** [comment]
I believe this is in response to #993.  Thanks @TroelsNV!
