### ISSUE TITLE
flopy version 3.3.2 raise a problem to open a previous flopy MODFLOW 6 model

### ISSUE THREAD

**Issue by MostafaGomaa93** [modflowpy/flopy#1030]
I was building 5 months ago a MODLFOW 6 model with Flopy and it was running, Now I update the Flopy to the latest version (3.3.2) and the model was not able to run, raising up the following SFR package problem

ERROR REPORT:

  1. Programming error in memory manager. Variable 'IMOVER' in
     'STEADY_STATE/SFR' cannot be assigned because it does not exist in
     memory manager.
     
I am also not able to install back the previous Flopy version, always the command (pip install Flopy) install Flopy 3.3.2

**Comment by jlarsen-usgs** [comment]
@MostafaGomaa93, to install an older version of flopy (ex. 3.3.1).
```
pip uninstall flopy
pip install flopy==3.3.1
```
I hope this helps until this error is resolved.

**Comment by MostafaGomaa93** [comment]
@jlarsen-usgs yes, it works
Many thanks

**Comment by langevin-usgs** [comment]
@MostafaGomaa93, it would be good to know why the new version doesn't work for you.  We've made changes to both flopy and mf6.  If you are using new versions of both, then it should work.  If you figure out what's different, please let us know.  It sounds like something simple.
