### ISSUE TITLE
The application of Moadpath6 in flopy.plot.PlotCrossSection

### ISSUE THREAD

**Issue by wsc1008-cugb** [modflowpy/flopy#1031]
When I use "plot_pathline" to plot the CrossSection result, which from 0 layer to bottom, there was an AttributeError: 'PlotCrossSection' object has no attribute 'plot_pathline', how to solve this problem and make it success to plot. Thanks.

**Comment by jlarsen-usgs** [comment]
@wsc1008-cugb 

This feature, along with `plot_endpoint` and `plot_timeseries` has been added in the most recent updates to flopy's plotting library.
