### ISSUE TITLE
flow-ja-face observation in modflow 6 GWF Model

### ISSUE THREAD

**Issue by rubencalje** [modflowpy/flopy#1036]
For a large Modflow 6 model I am unable to save all budgets (flow-ja-face), because of the large size my budget file would take. I am interested in the vertical flow from the first layer though, and I am unable to choose specific layers for budget output in modflow 6 (right?).

Therefore I would like to use the Observation (OBS) Utility for a GWF Model (page 39 in https://water.usgs.gov/ogw/modflow/mf6io.pdf), using the flow-ja-face observation-type. There does not seem to be an observations-argument or obs-attribute for the flopy.mf6.ModflowGwf or flopy.mf6.ModflowGwfnpf classes. Am I looking in the wrong place, or is it just not possible (jet) using flopy?

Thanks for your time!

**Comment by langevin-usgs** [comment]
You need to create an obs input file.  Here is an example for a transport model, but the same concept should work for GWF.  Will this work?

```
    # observations
    obs_data0 = [('flow1', 'flow-ja-face', (0, 0, 0), (0, 0, 1))]
    obs_recarray = {'{}.obs.csv'.format(gwtname): obs_data0}
    obs = flopy.mf6.ModflowUtlobs(gwt, pname='gwt_obs',
                                  filename='{}.obs'.format(gwtname),
                                  digits=15, print_input=True,
                                  continuous=obs_recarray)
```

**Comment by rubencalje** [comment]
Wow, that is fast. That was exactly I what I was looking for, thank you!
