### ISSUE TITLE
Loading modflow 6 model, utl_struct_objs?

### ISSUE THREAD

**Issue by ifariasg** [modflowpy/flopy#1038]
I'm trying to load an already existing modflow 6 model using flopy.

So far I understand I need :
- mf6.modflow.MFSimulation
- mf6.data.mfstructure.MFModelStructure

then use those objects with the "mf6.MFModel.load_base" method. My problem right now is with the "MFModelStructure" which requires the "utl_struct_objs" argument. I've tried searching for any reference or example structure but I seem to be getting down a rabbit hole in the documentation.
The closest I seem to get to that structure comes from"mf6.data.mfstructure.MFInputFileStructure" but that function also requires arguments that are not clear in the docs.

Any idea as to what specific part of the docs I should be looking at as a pointer?

**Comment by dbrakenhoff** [comment]
Have you checked out the [notebook here](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_mf6_tutorial.ipynb)? If you scroll down a bit it has code on how to load MF6 models. Maybe that's what you're looking for?

**Comment by ifariasg** [comment]
> 
> 
> Have you checked out the [notebook here](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_mf6_tutorial.ipynb)? If you scroll down a bit it has code on how to load MF6 models. Maybe that's what you're looking for?

This worked, thanks. I apologize also as this question should have been made through stackoverflow. 
Closing.
