### ISSUE TITLE
Error writing disv file for an unstructured grid (cells with variable, 3-5, vertices)

### ISSUE THREAD

**Issue by Veethahavya** [modflowpy/flopy#1039]
Greetings!

I am trying to create a MF6 unstructured grid with cells having vertices anywhere between 3-5 vertices from an unstructured netCDF UGRID file. I have prepared the **vertices** and **cell2d** as instructed in the documentation.

However, I have received an error as seen below:

> writing simulation...
>   writing simulation name file...
>   writing simulation tdis package...
>   writing ims package ims...
>   writing model wasenmoos...
>     writing model name file...
>     writing package disv...
> Traceback (most recent call last):
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\data\mfdatalist.py", line 1026, in _get_file_entry_record
>     to_string(
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\data\mfdatautil.py", line 205, in to_string
>     return str(int(val) + 1)
> 
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\mfpackage.py", line 1245, in _write_block
>     dataset.get_file_entry(ext_file_action=ext_file_action)
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\data\mfdatalist.py", line 601, in get_file_entry
>     return self._get_file_entry(values_only, ext_file_action)
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\data\mfdatalist.py", line 698, in _get_file_entry
>     self._get_file_entry_record(
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\data\mfdatalist.py", line 1052, in _get_file_entry_record
>     raise MFDataException(
> 
> MFDataException: An error occurred in data element "cell2d" model "gwf6" package "disv". The error occurred while converting data to a string in the "_get_file_entry_record" method.
> Additional Information:
> (1) An error occurred while converting data to a string. This error occurred while processing "cell2d" line icvert data item "1".(data path: ('wasenmoos', 'disv', 'cell2d', 'cell2d')).
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\xxx\xxx\xxx\res\MF6\src\IOgen.py", line 55, in <module>
>     sim.write_simulation()
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\modflow\mfsimulation.py", line 1401, in write_simulation
>     model.write(ext_file_action=ext_file_action)
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\mfmodel.py", line 801, in write
>     pp.write(ext_file_action=ext_file_action)
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\mfpackage.py", line 2218, in write
>     self._write_blocks(fd, ext_file_action)
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\mfpackage.py", line 2320, in _write_blocks
>     block.write(fd, ext_file_action=ext_file_action)
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\mfpackage.py", line 1152, in write
>     self._write_block(fd, self.block_headers[0], ext_file_action)
> 
>   File "C:\Users\xxx\anaconda3\lib\site-packages\flopy\mf6\mfpackage.py", line 1269, in _write_block
>     raise MFDataException(
> 
> MFDataException: An error occurred in data element "cell2d" model "wasenmoos" package "disv". The error occurred while converting data to a string in the "_get_file_entry_record" method.
> Additional Information:
> (1) An error occurred while converting data to a string. This error occurred while processing "cell2d" line icvert data item "1".(data path: ('wasenmoos', 'disv', 'cell2d', 'cell2d')).
> (2) Error occurred while writing data "cell2d" in block "cell2d" to file "C:\Users\xxx\xxx\xxx\xxx\MF6\src\wasenmoos\.\wasenmoos.disv".

Looking a bit into the error, I see a strange conditional statement that has same operations for both cases. And I wonder if it was written to be so or if this might indeed be the source of the error: in mfdatautil.py>line200:

>     elif data_type == DatumType.integer:
>         if data_item is not None and data_item.numeric_index:
>             if isinstance(val, str):
>                 return str(int(val) + 1)
>             else:
>                 return str(int(val) + 1)
>         return str(int(val))

***************************************************************************************************************************************************************
**My code:**
```
import netCDF4 as nc
import numpy as np
import flopy as fp
import os

def getDisV(nc_path):
	netNC = nc.Dataset(nc_path)
	nodes = netNC["mesh2d_node_x"].shape[0]
	node_index = np.array(range(0,nodes))
	nodeX = np.array(netNC["mesh2d_node_x"][:])
	nodeY = np.array(netNC["mesh2d_node_y"][:])
	verteces = []
	for n in node_index:
		verteces.append([node_index[n], nodeX[n], nodeY[n]])
	elements = netNC["mesh2d_face_nodes"].shape[0]
	elem_index = np.array(range(0,elements))
	elemental_nodes_ma = netNC["mesh2d_face_nodes"][:]
	elemental_nodes_ma = elemental_nodes_ma-1
	elemental_nodes_ma = np.flip(elemental_nodes_ma, axis=1)
	elemental_nodes = [en.compressed().tolist() for en in elemental_nodes_ma]
	elemX = np.array(netNC["mesh2d_face_x"][:])
	elemY = np.array(netNC["mesh2d_face_y"][:])
	cell2d = []
	for e in elem_index:
		cell2d.append([elem_index[e], elemX[e], elemY[e], len(elemental_nodes[e]), elemental_nodes[e]])
	return verteces, cell2d, elements, verteces, elem_index

workspace = os.path.join("wasenmoos")
name = "wasenmoos"
sim = fp.mf6.MFSimulation(sim_name=name, exe_name='mf6', version='mf6', sim_ws=workspace)
tdis = fp.mf6.ModflowTdis(sim, pname='tdis', nper=1, perioddata=[(1.0, 1, 1.0)]) #look up defining actual time fp/docs/pp63-4
ims = fp.mf6.ModflowIms(sim, pname="ims", complexity="SIMPLE")
model_nam_file = '{}.nam'.format(name)
gwf = fp.mf6.ModflowGwf(sim, modelname=name, model_nam_file=model_nam_file)
verteces, cell2d, elements, verteces, elem_index = getDisV("../../GWSWEX/delft/wasenmoos_net.nc")
disv = fp.mf6.ModflowGwfdisv(gwf, nlay=1, top=0, botm=-10, ncpl=elements, vertices=verteces, cell2d=cell2d)
start = 3*np.ones((1,elements)) #lay,cells
ic = fp.mf6.ModflowGwfic(gwf,pname="ic", strt=start)
npf = fp.mf6.ModflowGwfnpf(gwf, icelltype=1, k=1, save_flows=True)
chd_cells = np.random.choice(elem_index, size=100)
chd_ids = []
sp_data = []
for i in range(0,100):
	chd_ids.append([0, chd_cells[i]])
	sp_data.append([chd_ids[i], 2.5]) #constant head of 2.5 for random 100 cells
chd = fp.mf6.ModflowGwfchd(gwf, maxbound=len(chd_ids), stress_period_data=sp_data, save_flows=True)
headfile = "{}.hds".format(name)
head_filerecord = [headfile]
budgetfile = "{}.cbb".format(name)
budget_filerecord = [budgetfile]
saverecord = [("HEAD", "ALL"), ("BUDGET", "ALL")]
printrecord = [("HEAD", "LAST")]
oc = fp.mf6.ModflowGwfoc(gwf, saverecord=saverecord, head_filerecord=head_filerecord, budget_filerecord=budget_filerecord, printrecord=printrecord)
sim.write_simulation()
success, buff = sim.run_simulation()
```

**Comment by langevin-usgs** [comment]
The following is an example of valid cell2d and vertices arguments.  Can you confirm that yours have a similar form?

```
        cell2d = [[0, 16.666666666666668, 13.333333333333334, 3, 4, 2, 7],
                  [1, 3.3333333333333335, 6.666666666666667, 3, 4, 0, 5],
                  [2, 6.666666666666667, 16.666666666666668, 3, 1, 8, 4],
                  [3, 3.3333333333333335, 13.333333333333334, 3, 5, 1, 4],
                  [4, 6.666666666666667, 3.3333333333333335, 3, 6, 0, 4],
                  [5, 13.333333333333334, 3.3333333333333335, 3, 4, 3, 6],
                  [6, 16.666666666666668, 6.666666666666667, 3, 7, 3, 4],
                  [7, 13.333333333333334, 16.666666666666668, 3, 8, 2, 4]]
        vertices = [[0, 0.0, 0.0],
                    [1, 0.0, 20.0],
                    [2, 20.0, 20.0],
                    [3, 20.0, 0.0],
                    [4, 10.0, 10.0],
                    [5, 0.0, 10.0],
                    [6, 10.0, 0.0],
                    [7, 20.0, 10.0],
                    [8, 10.0, 20.0]]

```

**Comment by Veethahavya** [comment]
Hi Langevin,
Thank you very much for the swift and helpful reply!
My code had rather generated cell2d in the format - ...[0, 16.666666666666668, 13.333333333333334, _[3, 4, 2, 7]_]...
the issue is solved, cheers!
