### ISSUE TITLE
Non-zero based column output from mfdis.get_lrc()

### ISSUE THREAD

**Issue by phaehnel** [modflowpy/flopy#1040]
Hi there,

during my current work with flopy 3.3.2 I ran into the problem that the mfdis.get_lrc() method does return layer and row information with zero base (for first layer and row of the model) but the output for columns starts with 1.
Could that be caused by line 577 in the mfdis.py script:
 line 577: v.append((k - 1, i - 1, j))
causing j to be handed back in line 578 instead of j-1?

Greetings,
Patrick

**Comment by langevin-usgs** [comment]
Yes, this is a problem, as also indicated here: https://github.com/modflowpy/flopy/commit/52ecd98a11fc4f459c9bd0b59cb854ff402eeb08#commitcomment-46556384.  Will try to get this fixed for next release.

**Comment by langevin-usgs** [comment]
This should be fixed with #1049
