### ISSUE TITLE
error with flopy.mf6.utils.reference.StructuredSpatialReference.from_gridspec()

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1047]
when I call:
flopy.mf6.utils.reference.StructuredSpatialReference.from_gridspec()
I get errors. The errors can be fixed by:
1. commenting out line 190 - #lines = f.readlines()
2. change line from delr.append(int(r)) to delr.append(float(r))
3. change line from delc.append(int(r)) to delc.append(float(r))

**Comment by jlarsen-usgs** [comment]
@RyanConway91 

I'd reccomend using `flopy.discretization.StructuredGrid.from_gridspec()`. It is my understanding that the `SpatialReference` classes are deprecated and will eventually be removed from the code. @spaulins-usgs , is this correct?

**Comment by spaulins-usgs** [comment]
@jlarsen-usgs Correct
