### ISSUE TITLE
allow get_reduced_pumping in mflistfile to be used outside of list file

### ISSUE THREAD

**Issue by andyrich** [modflowpy/flopy#1048]
the wel package can optionally have reduced wells written to external file. the mflistfile get_reduced_pumping should allow for this. this fix can be achieved by removing the assert line in that file:

`            assert open(self.f.name).read().find(sCheck) > 0,\
                'Pumping reductions not written to list file. ' +\
                'Try removing "noprint" keyword from well file.'`

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs since this is a NWT option is this something that has been implemented?

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs, @andyrich 

The option to read this file in from an external (to the lst file) file has not yet been implemented. It looks like the easiest way to support this is to give the user an option of passing in the external file name to `MFListBudget.get_reduced_pumping()`.

Another option would be to move the reduced pumping record reader code into it's own function where: 
1) the user can call it independently from the `MFListBudget` object when this data set is saved as external.  
2) `MFListBudget` still contains the structued/unstructured list budget specific code and then passes relevant parameters to the new method.

Any thoughts or preferences on this?

**Comment by jlarsen-usgs** [comment]
@andyrich 

external pumping reduction files can now be read using `flopy.utils.observationfile.get_reduced_pumping()`. I opted for making this it's own function, becasue in this instance the pumping reduction file is completely seperate from the list file.

**Comment by andyrich** [comment]
awesome - will it work with AG package reduced pumping output, too? this feature would probably be used much less frequently, but if you're tinkering now could be the time to make that change.

**Comment by jlarsen-usgs** [comment]
@andyrich 

It looks like AG package reduced pumping output files are mostly delimitted ascii files, similar to csv. I think these could be read by adding an optional delimiter parameter to the `flopy.utils.observationfile.CsvFile` class and using it's functionality. I'll give it a test and report back.

**Comment by andyrich** [comment]
@jlarsen-usgs the AG package reduced pumping looks similar to the wel package, at least with how i'm having it output:
![image](https://user-images.githubusercontent.com/16653125/127234362-fc6afd1d-bd75-424e-94b0-c0258857f94c.png)

**Comment by jlarsen-usgs** [comment]
@andyrich 

I'm working on an update to be able to read this from the list file using `MfListBudget.get_reduced_pumping`. I'll try to include it in the PR.
