### ISSUE TITLE
Bug: write_input() after changing `external_path`

### ISSUE THREAD

**Issue by jbellino-usgs** [modflowpy/flopy#105]
After loading a model and changing the workspace, the external path can be set manually: `ml.external_path=newextpth`. However `self.ext_filename` is not updated in the various Util3d objects in the model. When `write_input()` is called, each layer of a given 3d array is written to the same filename which is the defualt name for the given `Util3d` object (e.g. `botm.ref`, `ibound.ref`, etc.). If one of these `Util3d` objects is updated (e.g. `ml.bas6.ibound=new_ibound_array`), the names are updated and the files are written properly (e.g. botm_layer_1.ref, etc.).

Current workaround is to force a refresh of the Util3d objects:
`ml.dis.botm = ml.dis.botm.array`

**Comment by jtwhite79** [comment]
Just pushed an attempted fix for this - ``Util3d.load()`` wasn't assigning layer-specific names to the ``Util2d`` instances.

**Comment by jbellino-usgs** [comment]
The fix looks good, model results are as expected. Thanks!
