### ISSUE TITLE
Particle ID incorrectly incremented

### ISSUE THREAD

**Issue by jjstarn-usgs** [modflowpy/flopy#1053]
"**Particle ID**" can be either generated by MODPATH or specified by the user to maintain particle identities.  It is not subject to zero based correction by adding 1.  In modpath 7 and flopy 3.3.2, 1 is incorrectly added to the user specified particle IDs.  This breaks any link the user has with specific particles.  I'm not where it happens, but for a similar variable, **tracerparticleid**, one is added on line 643 of mp7sim.py.  I searched for +1 + 1 +=1 += 1  and didn't find it.

**Comment by jdhughes-usgs** [comment]
@jjstarn-usgs seems like a perfect thing for you to address. Otherwise could you provide a minimal test case that can be used to fix the bug and added to the CI?

**Comment by jjstarn-usgs** [comment]
The codes changed so much I looked at it last.  I 'll take a stab at it and see if I can figure it out.

Jon Jeffrey Starn Ph.D.
Research hydrologist
USGS New England Water Science Center
101 Pitkin Street
East Hartford, CT 06108
________________________________
