### ISSUE TITLE
Support for reading budget terms of MODFLOW 6 Transport simulation list file

### ISSUE THREAD

**Issue by prashanth31** [modflowpy/flopy#1056]
flopy.utils.mflistfile.Mf6ListBudget currently doesn't seem to have code to read in modflow 6 transport budgets from the list file. Can this code be added ?

**Comment by langevin-usgs** [comment]
Any chance this works?

```
budgetkey = "MASS BUDGET FOR ENTIRE MODEL"
b = ListBudget("gwtmodel.bud", budgetkey=budgetkey)
```

**Comment by prashanth31** [comment]
Thanks! That was perfect.
