### ISSUE TITLE
HTTPError: 403 Client Error: rate limit exceeded for url

### ISSUE THREAD

**Issue by mwtoews** [modflowpy/flopy#1059]
This seemingly random error pops up from GitHub Actions with macos-latest. The known issue, https://github.com/actions/virtual-environments/issues/602 describes why this happens:
> GitHub counts requests for rate limit. For unauthorized requests, it limits by IP. All macOS VMs have the same IP address because of infrastructure.

I'm not familiar with the GHA setup enough to know if the necessary actions support a repo-token to solve the issue, but thought I'd pass the info along to any takers.

**Comment by jdhughes-usgs** [comment]
This should be resolved by the latest pymake changes that limit use of the github API except in case of trying to get a specific tag (release tag).

**Comment by mwtoews** [comment]
This issue has re-appeared with #1465
