### ISSUE TITLE
VisibleDeprecationWarning

### ISSUE THREAD

**Issue by krotzoll** [modflowpy/flopy#106]
In the latest development version, I am getting getting a warning after the following lines. How do I fix this one?

cbf = flopy.utils.CellBudgetFile(modelname+'.cbc')
ts_stressF = cbf.get_kstpkper()
kstpkperF = ts_stressF[-1]
frf = cbf.get_data(kstpkper=kstpkperF, text='FLOW RIGHT FACE')[0]

print frf
[[[ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  ..., 
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]]]

C:\Anaconda\lib\site-packages\flopy\utils\binaryfile.py:856: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  self.file.seek(ipos, 0)

**Comment by langevin-usgs** [comment]
what version of Python are you using?

**Comment by krotzoll** [comment]
because I still pestools, I am back to 2.7.11

**Comment by JoerivanEngelen** [comment]
I think this has to do with numpy. In the CellBudgetFile class there are several times when a 1-length  ndarray with dtype int64 is used as an index. When I updated to the new version of numpy yesterday, suddenly loading .cbc's gave me the following error: 

> TypeError: only integer scalar arrays can be converted to a scalar index 

The error can be easily reproduced with the following lines of code:
`import numpy as np

li = [1,2,3,4]
li[np.array([1])]`

With numpy version 1.12.0b1:
> TypeError: only integer scalar arrays can be converted to a scalar index 

With numpy version 1.11.1:
>C:\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\start_ipython_kernel.py:1: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future

Btw: I am using python version 3.4.5

**Comment by laat0003** [comment]
Thanks for this Joeri,

I ran into the same problem after upgrading to the latest version of Flopy.

Tariq

**Comment by jdhughes-usgs** [comment]
This is fixed in the development version of FloPy. Let us know if you run into any similar issues.
