### ISSUE TITLE
Error with MF6 EVT package minimum stress period data record entries 

### ISSUE THREAD

**Issue by kendal30** [modflowpy/flopy#1062]
I am using Flopy version 3.3.2, and encountered an error with the EVT package in MF6 not present in an earlier version, 3.2.12. 

The error arose from the method `get_min_record_entries` requiring 6 entries in the EVT package. This appears to have come about because that method counts non-optional `period` type inputs, and two inputs (`pxdp` and `petm`) are non-optional, though have length given by `nseg - 1`. Thus, `get_min_record_entries` expects 6 inputs, when I only provide 4.

The `stress_period_data.empty` method for the EVT package properly gives me an empty record array without the `pxdp` and `petm` inputs (though I can't seem to get it to not give me the optional `petm0` record; the `surf_rate_specified` option doesn't seem to work there). 

I was able to work around the error by manually editing the `dfn` array in the `mfgwfevt.py` package to indicate that `pxdp` and `petm` are optional--though of course this is just a workaround. An actual fix would seem to require that the `get_min_record_entries` would recognize a 0-length required input, as is the case for `pxdp` and `petm`. I couldn't quite figure out how to implement that, so I thought I'd post an issue because I'm certain one of you can fix this pretty quickly.

Thank you!

**Comment by langevin-usgs** [comment]
@spaulins-usgs, this looks like one for you.  Can you take a look?  Thanks.

**Comment by spaulins-usgs** [comment]
@kendal30 I just checked in a fix for this which is available on the develop branch.
