### ISSUE TITLE
Update PlotCrossSection for Unstructured Grids

### ISSUE THREAD

**Issue by jlarsen-usgs** [modflowpy/flopy#1086]
Migrated discussion from Pull Request #1078. @javgs-bd

> Hi @jlarsen-usgs I can't seem to make it work. I've tried by loading a MF-USG model with check=false, and then calling
> xsect = flopy.plot.PlotCrossSection(model=model, line={'line': line})
> 
> I get an error saying
> 
> File ".......conda\envs\flopy-develop\lib\site-packages\flopy\plot\crosssection.py", line 77, in init
> if self.mg.top is None or self.mg.botm is None:
> 
> AttributeError: 'NoneType' object has no attribute 'top'
> 
> I tracked that back and realized that when loading a mf-usg model, the model does not get a modelgrid atribute, even when the DISU package is loaded. modelgrid remains as None.
> 
> I tried building the unstructured grid object separately by using a gsf file and pulling the required arrays (vert, iverts, top, bot, xc, yc, etc...). then calling:
> 
> xsect = flopy.plot.PlotCrossSection(modelgrid=ug, line={'line': line})
> 
> and I got
> 
> File ".......conda\envs\flopy-develop\lib\site-packages\flopy\plot\crosssection.py", line 220, in init
> top = self.mg.top.reshape(1, self.mg.ncpl)
> 
> TypeError: only integer scalar arrays can be converted to a scalar index.
> 
> I still have to track this one, but it does not seem to be working straightforward as flopy.plot.PlotMapView and the plot_grid function does.

**Comment by jlarsen-usgs** [comment]
@javgs-bd

Thanks for giving unstructured PlotCrossSection plotting a test. There seem to be two seperate issues here.

1) The modelgrid is not being automatically generated for your MF-USG DISU based model. I'll need to check to see why it woudn't be built. However, if it did get built it would still be lacking coordinate information (vertices, iverts, xcenters, and ycenters), because this is not defined in MF-USG and the user would need to update or rebuild the grid to add this info. 

2) I'll need to take a look through the code and update the array reshaping. For unstructured grids it looks like `PlotCrossSection` should use `self.mg.nnodes` in place of `self.mg.ncpl`

Can you provide a minimal example that I could load and test (DISU file, BAS file, vertices, iverts, xcenters, and ycenters)?

**Comment by langevin-usgs** [comment]
Because mfusg doesn't have coordinate information, all of the plotting routines require the user to create a modelgrid object externally and assign it to the usg flopy object before any of the plotting routines will work.  See the mfusg gridgen example here: https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_gridgen.ipynb

**Comment by javgs-bd** [comment]
Thanks @jlarsen-usgs and @langevin-usgs. I'll try to send a minimal example, including the arrays for the ug object. Unfortunately it might take some days.

**Comment by jlarsen-usgs** [comment]
@javgs-bd 

Closing this issue with PR #1088

**Comment by javgs-bd** [comment]
Many thanks @jlarsen-usgs, apologies for not getting back.
