### ISSUE TITLE
Flow observations for 'STR'

### ISSUE THREAD

**Issue by vivekgrewal28** [modflowpy/flopy#1096]
Hi,

This is the first time I am posting on Github so kindly bear with me.

I need to add flow observations to an existing model which has a built-in stream via 'STR' package. In other words, I need to make an 'STOB' file/package. I tried using the ModflowFlwob package but it seems that 'flowtype must be CHD, GHB, DRN, or RIV'. 

Is there any other flopy module which can be used to add flow/budget observations to 'STR'? Or is 'STOB' not supported on flopy currently? I might make an 'STOB' text file myself, please suggest if there is any other/better way to do this. Thanks!

**Comment by jdhughes-usgs** [comment]
STOB are not currently supported and is currently considered a low-priority enhancement. I suspect the `ModflowFlwob` class could be extended to support `STOB`. Feel free to submit a pull-request if you would like to implement the enhancement. Will close for now.
