### ISSUE TITLE
Reading data from PathlineFile is slow

### ISSUE THREAD

**Issue by Gael-de-Sailly** [modflowpy/flopy#1098]
Hi,

I'm using MODPATH 6 and encountering performance issues with data reading.
I can't provide a minimal working example easily, but my model has 40401 pathlines and 926690 points (that makes 23 points per pathline on average), and I use `PathlineFile.get_alldata()` to extract the data:
```python3
pathobj = flopy.utils.PathlineFile(path+'.mppth'))
path_data = pathobj.get_alldata()
```

It spends `143s` on `get_alldata` while my MODFLOW + MODPATH models together take only `16.091s` to run.
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  179.221  179.221 /home/gael/Documents/Codes/./Xtemp_testmodpath.py:15(run)
        1    0.008    0.008  159.899  159.899 /home/gael/Documents/Codes/modpathsim.py:62(export_data)
        1    6.902    6.902  158.693  158.693 /home/gael/Documents/Codes/modpathsim.py:12(extract_data)
        1    0.000    0.000  143.554  143.554 /home/gael/miniconda3/envs/hydromodpy/lib/python3.9/site-packages/flopy/utils/modpathfile.py:351(get_alldata)
        1    0.073    0.073  143.554  143.554 /home/gael/miniconda3/envs/hydromodpy/lib/python3.9/site-packages/flopy/utils/modpathfile.py:390(<listcomp>)
    40401  132.793    0.003  143.480    0.004 /home/gael/miniconda3/envs/hydromodpy/lib/python3.9/site-packages/flopy/utils/modpathfile.py:295(get_data)
        2    0.000    0.000   16.091    8.045 /home/gael/miniconda3/envs/hydromodpy/lib/python3.9/site-packages/flopy/mbase.py:1351(run_model)
        2    0.000    0.000   16.091    8.045 /home/gael/miniconda3/envs/hydromodpy/lib/python3.9/site-packages/flopy/mbase.py:1647(run_model)
       27   16.084    0.596   16.084    0.596 {method 'readline' of '_io.BufferedReader' objects}
  1896343    9.098    0.000   13.093    0.000 /home/gael/miniconda3/envs/hydromodpy/lib/python3.9/site-packages/numpy/core/records.py:518(__getitem__)
```

I found that `get_alldata` [iteratively calls `get_data`](https://github.com/modflowpy/flopy/blob/4104cf5/flopy/utils/modpathfile.py#L390-L393), while `get_data` [searches in the whole array](https://github.com/modflowpy/flopy/blob/4104cf5/flopy/utils/modpathfile.py#L344), leading to square complexity. I may come soon with a PR to fix this, but I am unsure I would do it very well, considering I'm not familiar with flopy code, yet.

**Comment by jlarsen-usgs** [comment]
Updated the `get_alldata` method to avoid using the `get_data` method.
