### ISSUE TITLE
Lake example is not creating hds file even after successful completion of modlfow

### ISSUE THREAD

**Issue by Kirubaharan** [modflowpy/flopy#11]
I am using ubuntu and modflow version 2005 and trying to execute the lake example .
```python
name = 'lake_example'
h1 = 100
h2 = 90
Nlay = 10
N = 101
L = 400.0
H = 50.0
k = 1.0

ml = fmf.Modflow(modelname=name, exe_name='/home/kiruba/Downloads/Unix/src/mf2005', version='mf2005', model_ws='mf_files/')



bot = np.linspace(-H/Nlay,-H,Nlay)
delrow = delcol = L/(N-1)
dis = fmf.ModflowDis(ml,nlay=Nlay,nrow=N,ncol=N,delr=delrow,delc=delcol,top=0.0,botm=bot,laycbd=0)

Nhalf = (N-1)/2
ibound = np.ones((Nlay,N,N), 'int32')
ibound[:,0,:] = -1; ibound[:,-1,:] = -1; ibound[:,:,0] = -1; ibound[:,:,-1] = -1
ibound[0,Nhalf,Nhalf] = -1
start = h1 * np.ones((N,N))
start[Nhalf,Nhalf] = h2
bas = fmf.ModflowBas(ml,ibound=ibound,strt=start)
print "o"
lpf = fmf.ModflowLpf(ml, hk=k)
pcg = fmf.ModflowPcg(ml)
oc = fmf.ModflowOc(ml)
ml.write_input()
ml.run_model3()```

My output is : 
                               MODFLOW-2005     
    U.S. GEOLOGICAL SURVEY MODULAR FINITE-DIFFERENCE GROUND-WATER FLOW MODEL
                             Version 1.11.00 8/8/2013                        

 Using NAME file: lake_example.nam 
 Run start date and time (yyyy/mm/dd hh:mm:ss): 2015/02/11 13:51:00

 Solving:  Stress period:     1    Time step:     1    Ground-Water Flow Eqn.
 Run end date and time (yyyy/mm/dd hh:mm:ss): 2015/02/11 13:51:00
 Elapsed run time:  0.005 Seconds

  Normal termination of simulation
Process finished with exit code 0

The hds file is not created in the directory.

**Comment by langevin-usgs** [comment]
Couple of questions for you, Kirubaharan:

I see that you are using ml.run_model3().  run_model3 is not supported in flopy version 3.  I wonder if you have the correct version installed.  You may need to update to flopy version 3.

It looks like the model ran.  Have you checked the 'mf_files/' folder to see if there is a .hds file in there?

**Comment by Kirubaharan** [comment]
I am sorry, I have installed a new version but failed to delete the old one, now the model run and created hds file in mf_files
But I am getting the following error

/home/kiruba/.local/lib/python2.7/site-packages/flopy/utils/binaryfile.py:237: RuntimeWarning: overflow encountered in int_scalars
  self.databytes = header['ncol'] * header['nrow'] * self.realtype(1).nbytes
Traceback (most recent call last):
  File "/home/kiruba/PycharmProjects/area_of_curve/hydrology/gw_tut.py", line 92, in <module>
    hds = fut.HeadFile(ml.model_ws+name+'.hds')
  File "/home/kiruba/.local/lib/python2.7/site-packages/flopy/utils/binaryfile.py", line 562, in __init__
    super(HeadFile, self).__init__(filename, precision, verbose)
  File "/home/kiruba/.local/lib/python2.7/site-packages/flopy/utils/binaryfile.py", line 218, in __init__
    self._build_index()
  File "/home/kiruba/.local/lib/python2.7/site-packages/flopy/utils/binaryfile.py", line 257, in _build_index
    self.file.seek(self.databytes, 1)
IOError: [Errno 22] Invalid argument

**Comment by Kirubaharan** [comment]
I have compiled the modflow to create unformatted fortran file as output, otherwise modflow is not able to produce any output. If you are familiar with how to extract data from unformatted fortran file, please explain. I am planning to use the fortranfile python library to read the data, but it needs file ending and header_prec parameters, which I dont have any clue.

http://wiki.scipy.org/Cookbook/FortranIO/FortranFile

**Comment by langevin-usgs** [comment]
You may still be using an old flopy version.  Print flopy.__version__.  The value should be 3.0.1 or something like that.  The hds.get_data() no longer takes (kstp=1, kper=1).  You must specify those in a tuple as hds.get_data(kstpker=(1,1)).  See this page:

http://modflowpy.github.io/flopydoc/binaryfile.html

**Comment by Kirubaharan** [comment]
I am using 3.0.1 version. I am not able to go beyond this line of code, `hds = fut.HeadFile(ml.model_ws+name+'.hds')`

I am getting following error:
/home/kiruba/.local/lib/python2.7/site-packages/flopy/utils/binaryfile.py:237: RuntimeWarning: overflow encountered in int_scalars
  self.databytes = header['ncol'] * header['nrow'] * self.realtype(1).nbytes
Traceback (most recent call last):
  File "/home/kiruba/PycharmProjects/area_of_curve/hydrology/gw_tut.py", line 94, in <module>
    hds = fut.HeadFile(ml.model_ws+name+'.hds')
  File "/home/kiruba/.local/lib/python2.7/site-packages/flopy/utils/binaryfile.py", line 562, in __init__
    super(HeadFile, self).__init__(filename, precision, verbose)
  File "/home/kiruba/.local/lib/python2.7/site-packages/flopy/utils/binaryfile.py", line 218, in __init__
    self._build_index()
  File "/home/kiruba/.local/lib/python2.7/site-packages/flopy/utils/binaryfile.py", line 257, in _build_index
    self.file.seek(self.databytes, 1)
IOError: [Errno 22] Invalid argument

**Comment by jdhughes-usgs** [comment]
Lake example on git hub updated to reflect flopy3 changes.

**Comment by juancastilla** [comment]
Hello,
I am getting started with Flopy3 and came across the same error posted above by Kirubaharan, when executing the Lake example. I am using Mac and mf2005. Modflow runs the model and creates the .hds file without any problems.

This is the line that is creating problems:

hds = fu.HeadFile(os.path.join(workspace, name+'.hds'))

Any help will be much appreciated!

**Comment by jdhughes-usgs** [comment]
Try changing the following in openspec.inc

change
     DATA ACCESS/'SEQUENTIAL'/
to
     DATA ACCESS/'STREAM'/

and recompile. ACCESS = STREAM creates a binary unformatted file without record padding.

**Comment by juancastilla** [comment]
Hi Joe, 

Thanks for the reply. Flopy is running on my machine and generating the .hds file. The problem is simple: how do we read the .hds (unformatted binary) file into an np array???

You work in mac, right?

I will try your suggestion now and let you know.

Cheers

Juan

**Comment by juancastilla** [comment]
It worked! By changing ACCESS=STREAM I was able to read the .hds file. Thanks Joe :)

**Comment by jdhughes-usgs** [comment]
Good to hear. I do use a mac so have run into this issue before.

**Comment by apryet** [comment]
Great, thanks for the trick with ACCESS=STREAM. I have been struggling to find a way to read the binary file on OS X. Now it works !

**Comment by Kirubaharan** [comment]
Its working in Linux/ Ubuntu finally :). You have to use the following options while compiling the Modflow.
In makefile, use  `F90= gfortran` .
In openspec.inc 
change ` DATA ACCESS/'SEQUENTIAL'/ ` to  ` DATA ACCESS/'STREAM'/`
change  ` DATA FORM/'BINARY'/ ` to  ` DATA FORM/'UNFORMATTED'/`
