### ISSUE TITLE
recent change in tables argument of mf6.ModflowGwflak 

### ISSUE THREAD

**Issue by emorway-usgs** [modflowpy/flopy#1103]
@scottrp As of the last release of mf6/FloPy, the `tables` argument in the mf6 LAK package didn't require these two optional arguments: "TAB6", "FILEIN".  In other words, the following worked:

```
lak = flopy.mf6.ModflowGwflak(
    gwf, 
    time_conversion=86400.0,
    ...
    ntables=1,
    tables=[0, tab6_filename],
    ...
)
```

But a recently working script stopped working until these two arguments were added, as follows:

```
lak = flopy.mf6.ModflowGwflak(
    gwf, 
    time_conversion=86400.0,
    ...
    ntables=1,
    tables=[0, "TAB6", "FILEIN", tab6_filename],
    ...
)
```
Perhaps this is only be an issue for TAB6, since it has lake number in front (compared to other FILEIN lines, like TS6, for example)?

**Comment by spaulins-usgs** [comment]
@emorway-usgs  This could be a problem with the data verification code.  You can confirm this by turning data verification off and seeing if it works.  You can turn data verification off with the simulation object's verify_data attribute:

sim.verify_data = False

**Comment by emorway-usgs** [comment]
@scottrp I inserted the line of script you suggested immediately before the LAK instantiation code, but it bombed with the same error message that was produced without `sim.verify_data = False`.  It seems that for the time being, the following in required for the tables argument of ModflowGwflak:
```
...
tables=[0, "TAB6", "FILEIN", tab6_filename]
...
```
It is easy enough to include the `"TAB6", "FILEIN"` items, but at one point these were not necessary.  Currently, the docstrings indicate all that is needed is: `tables : [lakeno, tab6_filename]`

Perhaps the idea is to require them?  If so, I think it would be helpful to update the docstrings to reflect this change.

**Comment by spaulins-usgs** [comment]
@emorway-usgs  I think it is reasonable to require them.  I am working on an overhaul of the docstrings and documentation now and will make sure to include this.

**Comment by langevin-usgs** [comment]
@scottrp, just an FYI that I don't think we require the user to specify those keywords for TS6, TAS6, OBS6, and other FILEIN records.  We need to be careful that we don't break existing functionality.

**Comment by spaulins-usgs** [comment]
@langevin-usgs  In the TS6, TAS6, and OBS6 cases the keywords are at the beginning of the list, while in the LAK tables the keywords are in the middle of the list.  Flopy code looks for keywords at the beginning of the input and if it does not find them it assumes the user left them out and adds them in.

Flopy can fill in keywords in the middle of a list, but it can potentially run into problems when there is optional or potentially repeating data before the keyword.  Is it safe to assume that all keywords in a list will never have optional or potentially repeating data before them?  If so, I agree that we can just fill in missing keywords regardless of where they appear in the list.

**Comment by langevin-usgs** [comment]
I think it's okay to require that all of them be present in this case of the lake tables.  But the question is, how would someone know that?  These little gotchas are tough to figure out, and the error messages don't seem to provide any help.  Maybe that's the answer?  Can the error message be more useful?

**Comment by spaulins-usgs** [comment]
The error message currently does tell you what input variable it failed on.  I will look into displaying something about the format of input it is expecting, and if possible something about the actual input text that it fails on.

**Comment by jdhughes-usgs** [comment]
@emorway-usgs Reopen this issue if it has not been resolved.
