### ISSUE TITLE
Input formatting: coherence between modflow 2005 and flopy

### ISSUE THREAD

**Issue by mathieu-couplet** [modflowpy/flopy#1104]
Dear developers.

I am a very beginner in hydrology and modflow modelling. I recently tried to load a model, which can be run with mf2005 without any difficulties, with flopy: it fails while loading an FHB package.
The name file was generated by ModelMuse, however I am not sure for the FHB file. I am not able to provide the input data here unfortunately.

One of the reason of the failure is the presence of newlines inside an array (data set 4b), whereas flopy (mffhb.py) assumes (if I am not wrong) that all the values of such an array are in an unique line.

I am not sure of how to interpret the documentation:
"Input for FHB1 is read from the file that has file type "FHB" in the name file.. All input is free format, which requires each of the numbered data groups to start on a new input record. More than one record can be used for any data group and numbers within data groups must be separated by at least one space or a comma. Integer data types cannot include a decimal point. Blank spaces are not treated as zeros. For an example annotated input data set, refer to figure 8 in Leake and Lilly 1997."
-> "More than one record can be used for any data group": does it mean that newlines are allowed and that flopy is wrong?
-> The reference Leake and Lilly 1997 is not available.

Can I expect flopy to evolve so as to be more permissive about the input formatting, in coherence with modflow 2005, or should I use personal reformatting script on my side? 

Thanks you,
kind regards,
MC.

**Comment by langevin-usgs** [comment]
I think if you can provide us with a small FHB example that runs fine with MODFLOW-2005 but cannot be loaded with flopy, then we would be willing to fix the flopy FHB load problem.

**Comment by jdhughes-usgs** [comment]
Will fix (if example provided) or close in 3.3.5
