### ISSUE TITLE
How to use the latest version of flopy(3.34?)

### ISSUE THREAD

**Issue by wsc1008-cugb** [modflowpy/flopy#1106]
I want to use the  "plot_pathline" to plot the CrossSection result, which from 0 layer to bottom, there was an AttributeError: 'PlotCrossSection' object has no attribute 'plot_pathline', it is said that in the new version this function will be added. How could I donwload the latest one?

**Comment by dbrakenhoff** [comment]
From the readme:

`pip install https://github.com/modflowpy/flopy/zipball/develop`

Hope that helps!

**Comment by wsc1008-cugb** [comment]
> From the readme:
> 
> `pip install https://github.com/modflowpy/flopy/zipball/develop`
> 
> Hope that helps!

Thank you very much. But there was an error when I installing the package: pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read)).

I use both Pycharm and cmd to pip the flopy 3.3.4, how could you install it successfully?
