### ISSUE TITLE
Still about plot_pathline in plot_crosssection

### ISSUE THREAD

**Issue by wsc1008-cugb** [modflowpy/flopy#1108]
I want to use the "plot_pathline" to plot the CrossSection result, which from 0 layer to bottom.
I have used the latest version of flopy, and try an example which is similar with the flopy3_modpath6_example.ipynb, there is such error:

`fig = plt.figure(figsize=(80, 25))

ax = fig.add_subplot(1, 1, 1, aspect='equal')

mx = flopy.plot.PlotCrossSection(ax=ax, model=swt, line={'row': 0})

ibound = mx.plot_ibound()

grid = mx.plot_grid(color='0.3', alpha=0.1)

quadmesh = mx.plot_bc('WEL', kper=4)

contour_set = mx.contour_array(hds, levels=np.arange(np.min(hds),np.max(hds),0.5), colors='b')

plt.clabel(contour_set, inline=True, fontsize=35)

mx.plot_endpoint(well_epd, direction='starting', colorbar=True)

#for now, each particle must be plotted individually 
#(plot_pathline() will plot a single line for recarray with multiple particles)
#for pid in np.unique(well_pathlines.particleid):
#modelmap.plot_pathline(pthobj.get_data(pid), layer='all', colors='red');

mx.plot_pathline(well_pathlines, method='cell', colors='red')`

![image](https://user-images.githubusercontent.com/74029851/117566107-41a1f880-b0e7-11eb-8375-90d2c9ec8217.png)

**Comment by jlarsen-usgs** [comment]
@wsc1008-cugb

the IndexError message shows changes to the code that does not match the source code within the flopy development repository.

lines 2759 and 2760 within the repository are:
```
nmin = np.min(v_norm[cell])
nmax = np.max(v_norm[cell])
```
instead of

```
nmin = np.min(v_norm[cell] + 1)
nmax = np.max(v_norn[cell] + 1)
```

Please update your version of flopy to the most recent repo version using

```
pip install -U https://github.com/modflowpy/flopy/zipball/develop
```

**Comment by jlarsen-usgs** [comment]
@wsc1008-cugb 

Unfortunately, the copy of your source code does not match that in the flopy repo based on the error message. If you remove the "+ 1" from 2759 and 2760 of plotutil.py you should not get this error. Flopy uses a zero based indexing scheme, the "+ 1" is causing your error.

**Comment by wsc1008-cugb** [comment]
> @wsc1008-cugb
> 
> Unfortunately, the copy of your source code does not match that in the flopy repo based on the error message. If you remove the "+ 1" from 2759 and 2760 of plotutil.py you should not get this error. Flopy uses a zero based indexing scheme, the "+ 1" is causing your error.

I‘m so sorry to bother you agian, I mistook the image at first. I have tried without any change at the beginning, it didn't work. So then I added the "+1" and "-1" at 2759 and 2760 to make it work, but I failed agian. Here is the first time I tried. There is the same error.

![image](https://user-images.githubusercontent.com/74029851/117914468-fd486f80-b315-11eb-8a20-2f36b0c44a6b.png)

**Comment by jlarsen-usgs** [comment]
@wsc1008-cugb 
Thanks for the clarification. I've recreated the issue and found that the modpath intersection method is not handling layered data correctly. I'm currently working on a fix for this.

**Comment by wsc1008-cugb** [comment]
@jlarsen-usgs Thank you very much, it works!
