### ISSUE TITLE
Extraneous kwargs "model_ws" provided to MFModel

### ISSUE THREAD

**Issue by wkitlasten** [modflowpy/flopy#1115]
I have several gwf models under the same simulation and would like to have them under their own subfolders (because I'm crazy like that). When I try:

```
flopy.mf6.ModflowGwf(sim, model_ws=m_ws,
                                modelname=m_name,
                                model_nam_file=m_name+'.nam',
                                save_flows=True)
```

I get:

```
c:\programdata\anaconda3\envs\py37\lib\site-packages\flopy\mf6\modflow\mfgwf.py in __init__(self, simulation, modelname, model_nam_file, version, exe_name, model_rel_path, list, print_input, print_flows, save_flows, newtonoptions, packages, **kwargs)
    102             exe_name=exe_name,
    103             model_rel_path=model_rel_path,
--> 104             **kwargs
    105         )
    106 

c:\programdata\anaconda3\envs\py37\lib\site-packages\flopy\mf6\mfmodel.py in __init__(self, simulation, model_type, modelname, model_nam_file, version, exe_name, add_to_simulation, structure, model_rel_path, verbose, **kwargs)
    178                 "MFModel.".format(kwargs_str)
    179             )
--> 180             raise FlopyException(excpt_str)
    181 
    182         # build model name file

FlopyException: FlopyException: Extraneous kwargs "model_ws" provided to MFModel. ()
```
It works fine if I remove the 'model_ws' kwarg. From what I can tell, the ["latest" mfgwf module](https://flopy.readthedocs.io/en/latest/source/flopy.mf6.modflow.mfgwf.html?highlight=flopy.mf6.ModflowGwf) should take the 'model_ws' kwarg, no?

I am using flopy version: 3.3.3

**Comment by langevin-usgs** [comment]
Did you try using a relative path?  model_rel_path?  Which should be a path relative to the simulation folder?

**Comment by wkitlasten** [comment]
Should the model_rel_path be added to the package filenames in the gwf.nam file (and presumably any external files)? That is, does mf6.exe always work from the sim directory, or does mf6.exe operate from each gwf subdirectory while that gwf is running?

My model is in a subdirectory called "model0" so model_rel_path is "model0". Flopy is writing all the files there, as expected. But the gwf.nam file has:

```
BEGIN packages
  DIS6  south_island.dis  dis
...
```

Which produces:

`1. *** ERROR OPENING FILE "south_island.dis" ON UNIT 1005`

If I manually edit the gwf.nam file to:

`DIS6  model0/south_island.dis  dis`

DIS6 is read and the error is issued for the next package.

**Comment by langevin-usgs** [comment]
@wkitlasten, you are probably going to have to set the file names for each package to include the relative path, which is easy to do with the filename argument.  Maybe just something like:

```
basename = os.path.join(model_rel_path, "mymodel")
dis = flopy.mf6.ModflowGwfdis(gwf, ..., filename=basename + ".dis")
riv = flopy.mf6.ModflowGwfriv(gwf, ..., filename=basename + ".riv")
```

This should allow you to keep things organized.  There might be something more sophisticated built into flopy for doing this automatically.  Any thoughts @spaulins-usgs?

**Comment by langevin-usgs** [comment]
I should also mention that all file references (in name files and elsewhere in input files) must be written relative to where mf6[.exe] was started.  Because mf6 must be started in the same folder as mfsim.nam, then all files must include relative paths (absolute paths would also work, but not recommended) to the folder containing mfsim.nam.

**Comment by spaulins-usgs** [comment]
@wkitlasten, flopy does have a method that will set each package to include a relative path for you.  After you have created all of your packages call:

gwf. set_model_relative_path("mymodel")

This will set all of the model's current packages to the "mymodel" folder.  You can find an example of set_model_relative_path in the flopy3_mf6_tutorial "Adding a Model Relative Path" section.
