### ISSUE TITLE
Spatial reference information with mf6 modelgrid object?

### ISSUE THREAD

**Issue by wkitlasten** [modflowpy/flopy#1122]
Is there a straightforward way of getting spatial reference information while loading a flopy.mf6.ModflowGwf model? When building the model I use `gwf.modelgrid.set_coord_info()`, and `gwf.modelgrid` has the appropriate spatial information. But after I write and I load the simulation:

```
sim.write_simulation()
sim=flopy.mf6.MFSimulation.load()
gwf=sim.get_model()
```

`gwf.modelgrid` no longer has the spatial information. 

I get what I need by writing a gridspec file using `sr=flopy.utils.reference.SpatialReference()`, `sr.write_gridSpec()` and then loading it using `sr=flopy.utils.reference.SpatialReference.from_gridspec()`. Unless I'm mistaken (highly probable) `gwf.modelgrid.set_coord_info()` takes xll and yll, but `flopy.utils.reference.SpatialReference.from_gridspec()` returns xul and yul... which is just a little awkward... making me think there must be a better way?

**Comment by mwtoews** [comment]
I'll confirm that `set_coord_info` isn't working as expected, as I would have expected this data to be synchronised with the DIS* package options to be saved when written.

A workaround is to set both `modelgrid` and `dis` properties with the same data:
```python
xorigin = 1000.0
yorigin = 2000.0
gwf.modelgrid.set_coord_info(xoff=xorigin, yoff=yorigin)
gwf.dis.xorigin.set_data(xorigin)
gwf.dis.yorigin.set_data(yorigin)
```

**Comment by wkitlasten** [comment]
I am using a gridspec file for portability. The xorigin, yorigin seems to work. I would have thought the modelgrid info would be saved to the dis file...

Here's the simplest test I can come up with:

```
import os
import flopy
import numpy as np

sim_name='sr_test'
model_name='my_model'
nlay = 1
nrow, ncol = 10, 10
xll, yll = 617822.3, 5114820.7 # origin of the model (lower left corner)
dxdy = 250 # grid spacing (in model units)
rot = 29 # rotation (positive counterclockwise)
model_epsg = 26915

sim = flopy.mf6.MFSimulation(sim_name=sim_name,exe_name="mf6",
                             version="mf6",sim_ws=sim_name)
tdis = flopy.mf6.ModflowTdis(sim,pname="tdis",time_units="DAYS",
                             nper=1,perioddata=[1.0,1,1.0])

gwf = flopy.mf6.ModflowGwf(sim, modelname=model_name)
dis = flopy.mf6.ModflowGwfdis(gwf,nlay=nlay,nrow=nrow,ncol=ncol,delr=dxdy,delc=dxdy,top=10,botm=0)
gwf.modelgrid.set_coord_info(xoff=xll, yoff=yll, 
                           angrot=0, epsg=model_epsg)
ic_package = flopy.mf6.ModflowGwfic(gwf, strt=0)
ims_package = flopy.mf6.ModflowIms(sim)
npf = flopy.mf6.ModflowGwfnpf(gwf, k=1)
sim.write_simulation()

# grab sr and write to gridspec
sr = flopy.utils.reference.SpatialReference(delr=gwf.dis.delr.data,
                    delc=gwf.dis.delc.data, xll=xll, yll=yll, rotation=0, epsg=model_epsg)
sr.write_gridSpec(model_name+'.spc')

# gwf.modelgrid has correct spatial info
print(gwf.modelgrid)

# reload the model
sim=flopy.mf6.MFSimulation.load(sim_ws=sim_name)
gwf=sim.get_model(model_name)
# no spatial info
print(gwf.modelgrid)

# read gridspec and set_coord_info
sr=flopy.utils.reference.SpatialReference.from_gridspec(model_name+'.spc')
gwf.modelgrid.set_coord_info(xoff=sr.xul, yoff=sr.yul-np.sum(gwf.dis.delr.data), 
                           angrot=sr.rotation, epsg=sr.epsg)

# model has correct spatial data
print(gwf.modelgrid)
```

**Comment by wkitlasten** [comment]
Okay, using xorigin, yorigin when creating the dis results in it being written to the .dis file. (gwf.modelgrid.set_coord_info() does not).

Thanks @mwtoews 

```
dis = flopy.mf6.ModflowGwfdis(gwf,xorigin=xll, yorigin=yll,
                              nlay=nlay,nrow=nrow,ncol=ncol,delr=dxdy,delc=dxdy,top=10,botm=0)
```
