### ISSUE TITLE
rcloserecord in ims modflow 6

### ISSUE THREAD

**Issue by Olsthoorn** [modflowpy/flopy#1123]
I have this as input for IMS, the issue is the rcloserecord

ims_kwargs = dict(
        print_option = 'SUMMARY',
        complexity = 'MODERATE',
        no_ptcrecord = 'ALL', # or FIRST

        outer_maximum = 200,
        outer_dvclose = 1e-3,
        under_relaxation = 'DBD',
        under_relaxation_theta = 0.8,
        under_relaxation_kappa = 0.001,
        under_relaxation_gamma = 0.0,
        under_relaxation_momentum = 0.001,
        backtracking_number = 10,
        backtracking_tolerance = 1.05,
        backtracking_reduction_factor = 0.2,
        backtracking_residual_limit = 0.002,

        inner_maximum = 200,
        inner_dvclose = 1e-3,
        rcloserecord = (0.1, 'STRICT'),
        linear_acceleration = 'BICGSTAB',
        relaxation_factor = 0.97, # may be zero (default)
        preconditioner_levels = 5,
        preconditioner_drop_tolerance = 1e-4,
        number_orthogonalizations = 3, # default = 0
        scaling_method = 'L2NORM',
        reordering_method = 'RCM',
)

I use it this way:

# Solver
ims = flopy.mf6.ModflowIms(sim, pname='ims', **ims_kwargs)

The get the following error from MODFLOW

FloPy is using the following  executable to run the model: /Users/Theo/GRWMODELS/mfLab/trunk/bin/mf6.mac
                                   MODFLOW 6
                U.S. GEOLOGICAL SURVEY MODULAR HYDROLOGIC MODEL
                            VERSION 6.2.1 02/18/2021

  MODFLOW 6 compiled May  6 2021 00:38:39 with GFORTRAN compiler (ver. 10.2.0)

This software has been approved for release by the U.S. Geological 
Survey (USGS). Although the software has been subjected to rigorous 
review, the USGS reserves the right to update the software as needed 
pursuant to further analysis and review. No warranty, expressed or 
implied, is made by the USGS or the U.S. Government as to the 
functionality of the software and related material nor shall the 
fact of release constitute any such warranty. Furthermore, the 
software is released on condition that neither the USGS nor the U.S. 
Government shall be held liable for any damages resulting from its 
authorized or unauthorized use. Also refer to the USGS Water 
Resources Software User Rights Notice for complete use, copyright, 
and distribution information.

 Run start date and time (yyyy/mm/dd hh:mm:ss): 2021/05/27 23:25:37

 Writing simulation list file: mfsim.lst
 Using Simulation name file: mfsim.nam

ERROR REPORT:

  1. File unit 1013: Error converting "(0.1" to a real number in following
     line:
  2. INNER_RCLOSE  (0.1, 'STRICT')

UNIT ERROR REPORT:

  1. ERROR OCCURRED WHILE READING FILE 'yasin_mf6.ims'

STOP 2
Traceback (most recent call last):

 ...   raise Exception("MODFLOW 6 did not terminate normally.")

Exception: MODFLOW 6 did not terminate normally.

Which is caused by the input of ims that was generated by flopy

# File generated by Flopy version 3.3.3 on 05/27/2021 at 23:25:36.
BEGIN options
  PRINT_OPTION  summary
  COMPLEXITY  moderate
  NO_PTC  ALL
END options

BEGIN nonlinear
  OUTER_DVCLOSE       0.00100000
  OUTER_MAXIMUM  200
  UNDER_RELAXATION  dbd
  UNDER_RELAXATION_GAMMA       0.00000000
  UNDER_RELAXATION_THETA       0.80000000
  UNDER_RELAXATION_KAPPA       0.00100000
  UNDER_RELAXATION_MOMENTUM       0.00100000
  BACKTRACKING_NUMBER  10
  BACKTRACKING_TOLERANCE       1.05000000
  BACKTRACKING_REDUCTION_FACTOR       0.20000000
  BACKTRACKING_RESIDUAL_LIMIT       0.00200000
END nonlinear

BEGIN linear
  INNER_MAXIMUM  200
  INNER_DVCLOSE       0.00100000
  inner_rclose  (0.1, 'STRICT')
  LINEAR_ACCELERATION  bicgstab
  RELAXATION_FACTOR       0.97000000
  PRECONDITIONER_LEVELS  5
  PRECONDITIONER_DROP_TOLERANCE  1.00000000E-04
  NUMBER_ORTHOGONALIZATIONS  3
  SCALING_METHOD  l2norm
  REORDERING_METHOD  rcm
END linear

Which shows that the rcloserecord specified above was incorrectly transferred to the input for for MODFLOW. See line "inner_close (0.1, 'STRICT')

**Comment by langevin-usgs** [comment]
Hi @Olsthoorn, hope you are well!  The syntax you are looking for is:

```
rcloserecord=[0.1, "strict"],
```

Sorry that this is a bit cumbersome.  It is because all of these flopy classes are generated automatically.  

You can often search the autotest folder of the modflow6 repository for syntax examples:  https://github.com/MODFLOW-USGS/modflow6/tree/develop/autotest
