### ISSUE TITLE
write .gsf file or .vtu file from disu files

### ISSUE THREAD

**Issue by NigelKinney** [modflowpy/flopy#1127]
Hello,
I was trying to export a .gsf (grid specification file) or .vtu file from a MODFLOW-USG model, so that other people can use other graphical user interface to view them. GUIs usually require .gsf or .vtu files as the native MODFLOW-USG file do not have them. I wonder if there's any possibility to do that using flopy?
Thank you!

**Comment by jdhughes-usgs** [comment]
Improvements to VTK export is in progress but we will only be able to support MODFLOW 6 DISU export of vertex information is provided.

See #873
