### ISSUE TITLE
MODFLOW 6 Tutorial 1 error

### ISSUE THREAD

**Issue by KyleHorner** [modflowpy/flopy#1128]
Hello,

As can be seen from the figures plotted at the end of the example, the current code has the cell with the low head (90) in the wrong location (upper left quadrant rather than dead centre).

The second line of the CHD Package section should be amended to:
chd_rec.append(((0, int(N / 2), int(N / 2)), h2))

Cheers (and thanks for all your work)!
Kyle

**Comment by jdhughes-usgs** [comment]
Modified text to indicate it is in the center of the upper-left quadrant.

Closed as part of #1141
