### ISSUE TITLE
Modflow 6 Quickstart error

### ISSUE THREAD

**Issue by KyleHorner** [modflowpy/flopy#1129]
Hey again,

I could not produce the plot in the quickstart example when using Jupyter Notebook.

It does work for me when I extract head and cell budget data using the binaryfile utility:

hds = flopy.utils.binaryfile.HeadFile(head_file)
head = hds.get_data()
bud = flopy.utils.binaryfile.CellBudgetFile(budget_file) 

Cheers!
Kyle

**Comment by jdhughes-usgs** [comment]
You have to use the development version of flopy to use the Quickstart shown on the README.md on the GitHub development branch, which is the default branch that is shown on the GitHub repo. Also, the latest version on [readthedocs](https://flopy.readthedocs.io/en/latest/index.html) is tied to the development branch. 

We will try to better clarify this on README.md in the next version.

#458
