### ISSUE TITLE
bug? write_input() not selecting for SelpackList

### ISSUE THREAD

**Issue by leilamac** [modflowpy/flopy#113]
write_input() in mbase.py isn't selecting for SelPackList but is printing everything regardless of the contents. Think the solution is to further indent lines 539 to 544. 

Don't see it fixed in the developer version so hope I'm not repeating my previous mistake.. 

def write_input(self, SelPackList=False, check=False):
.........
        if SelPackList == False:
            for p in self.packagelist:
                if self.verbose:
                    print('   Package: ', p.name[0])
                # prevent individual package checks from running after model-level package check above
                # otherwise checks are run twice
                # or the model level check proceedure would have to be split up
                # or each package would need a check arguemnt,
                # or default for package level check would have to be False
                try:
                    p.write_file(check=False)
                except TypeError:
                    p.write_file()
        else:
            for pon in SelPackList:
                for i, p in enumerate(self.packagelist):
                    if pon in p.name:
                        if self.verbose:
                            print('   Package: ', p.name[0])
# everything under here needed to be further indented so it is skipped if 'if pon in p.name' = False
                        try:
                            p.write_file(check=False)
                        except TypeError:
                            p.write_file()
                            break

**Comment by langevin-usgs** [comment]
I think you're right.  I made the fix and just pushed to develop.  Please let me know if this works.  Feel free to close the issue if so.  Thanks!
