### ISSUE TITLE
MF6 export to VTK files?

### ISSUE THREAD

**Issue by Matt-Webb1** [modflowpy/flopy#1131]
Hi, I'm not sure if this is an issue (it may be a missing feature or an error in my code), but I was looking at using the vtk.export_heads function on a heads file generated by a MF6 model. 
```
model = flopy.mf6.MFSimulation.load(sim_name=mf6_simname, version='mf6', exe_name='mf6', sim_ws=sim_path)
vtk.export_heads(model, headsFile, headOutputFolder, kstpkper=[(0,0), (0, 1)], nanval=-999.99) 
```
However, running code of that form results in attribute errors (verbose, model, ...). I can see that the loaded object does not have a verbose or model attribute, but if I load an MF2K model with `flopy.modflow.Modflow.load()` then I can see the loaded object does have verbose and model attributes. Is it just the case the MF6 models are not yet supported for this yet? Or did I use the wrong code to try to achieve that?

Interestingly the MF6 saved .hds file format _is_ compatible with `vtk.export_heads() `since I can create a spatially identical MF2K model (if it is R/C/L mesh anyway) to act as a surrogate for the MF6 model, modify the code, and the export works fine.

Thanks!

**Comment by langevin-usgs** [comment]
Hi @Matt-Webb1, I think the problem is that your "model" is actually the simulation.  Does this work?

```
sim = flopy.mf6.MFSimulation.load(sim_name=mf6_simname, version='mf6', exe_name='mf6', sim_ws=sim_path)
list_of_gwf_models = sim.gwf
model = sim.gwf[0]
# or maybe model = sim.get_model()
vtk.export_heads(model, headsFile, headOutputFolder, kstpkper=[(0,0), (0, 1)], nanval=-999.99) 
```

or alternatively, just export the whole model

```
vtk.export_model(sim.get_model(), sim_path)
```

**Comment by Matt-Webb1** [comment]
Ah, I see the difference now. Both your suggestions worked. Thanks for taking the time to figure that out!

**Comment by Matt-Webb1** [comment]
On the same topic, is there a way to export the concentration data to VTK from a MF6 model (i.e. a .con file)?

With yout help the `vtk.export_model() ` now provides the structure, and `vtk.export_heads()` provides the flow, but there wasn't a corresponding function for transport results export. I tried using the export_array() function but couldn't get it to work.

A second related note: is there a way to export the cbb file to VTK? The `.export_cbc()` function presumably only works on .cbc files.

**Comment by Matt-Webb1** [comment]
Figured this out, just needed to use the 'text' argument to differentiate the heads file from a concentration file.
