### ISSUE TITLE
Plot AssertionError when mflay option is used is used

### ISSUE THREAD

**Issue by Smith0710** [modflowpy/flopy#1132]
The plot method produces an AssertionError when the mflay option is set and figsave() is invoked by also setting the filename_base option. For example:
1. This works: simulation.plot(SelPackList=['npf'], filename_base='Fig', kper=0)
2. This doesn't:  simulation.plot(SelPackList=['npf'], filename_base='Fig', mflay=0, kper=0)

The error appears to be caused by the assert check at line #1385 of \flopy\plot\plotutil.py, which expects the number of filenames for figsave() to be equal to maxlay.

**Comment by jlarsen-usgs** [comment]
I'll take a look at this issue
