### ISSUE TITLE
run_model() Failing on upw package, how to troubleshoot/identify what i'm missing?

### ISSUE THREAD

**Issue by gmerritt123** [modflowpy/flopy#1137]
Hi, I am a longtime feflow/feflow python api user taking a run at building a modflow model using flopy. First off I'm not sure if this is the right place to post this (please direct me elsewhere if so). I've instantiated a  flopy.modflow.Modflow instance and set its .version to 'mfnwt'. The 'MODFLOW-NWT_64.exe' is assigned to the .exe_name attribute.

I've assembled the following package instances:

![image](https://user-images.githubusercontent.com/58000181/123110926-87522080-d40a-11eb-9fe4-b409f73016f1.png)

.runmodel produces:

![image](https://user-images.githubusercontent.com/58000181/123111603-08a9b300-d40b-11eb-844d-ac22dd54e4e7.png)

And when I inspect the .list, it seems to be failing at the upw file read:

![image](https://user-images.githubusercontent.com/58000181/123111794-30991680-d40b-11eb-93be-b42970c2c3c0.png)

Can anyone elaborate on what I might be missing to get this "no named parameters" statement?

I've run the .check method, there are no issues with my parameter arrays. Here's a printout of my .upw attributes:

![image](https://user-images.githubusercontent.com/58000181/123113214-5ffc5300-d40c-11eb-9eb4-9029fd5670c9.png)

And (in case it helps) a printout of my code to instantiate it:

![image](https://user-images.githubusercontent.com/58000181/123119828-da7ba180-d411-11eb-93d1-279e01b4a5a8.png)

I'm a little bit sketched out by the header in the .nam file saying modflow-2005, should it not say modflow nwt? I know nwt is required for the upw package - am I missing an additional place to enforce that nwt should used? Or is there a flag/attribute in my upw I should inspect (I've already gone through this pretty extensively so doubt it at this point). Or are there flags/attributes in the .dis/.bas6 instances that might be causing this (it looks like the .list file reads these successfully, then craps out at the .upw.

Another thing I've noticed is that flopy is not writing the upw file in "free" format: 

![image](https://user-images.githubusercontent.com/58000181/123120952-c1272500-d412-11eb-89d5-a1bf14286a6a.png)

And the documentation for the .upw (here - https://water.usgs.gov/nrp/gwsoftware/modflow2000/MFDOC/index.html ) says:

![image](https://user-images.githubusercontent.com/58000181/123121450-2bd86080-d413-11eb-91af-428718562a1c.png)

So... is flopy not writing things "free format" a problem for upw then?

Any tips much appreciated!   

Edit: added some more info

**Comment by mwtoews** [comment]
The "No named parameters" excerpt is not an error, it just states that the package is not using parameters (i.e. [NPUPW](https://water.usgs.gov/ogw/modflow-nwt/MODFLOW-NWT-Guide/upw_upstream_weighting_package.htm) is zero). Was this the last line in the .list file? You should keep `iphdry=0` for UPW (this is the default).

**Comment by gmerritt123** [comment]
Thanks. Yes it is the last line in the .list file. Thanks for the iphdry tip, I just tried it out: still getting same thing...

**Comment by jlarsen-usgs** [comment]
@gmerritt123 

I've seen this error before and it is caused by not having the NWT solver package active. Add the NWT package to your model and it should resolve this issue.
