### ISSUE TITLE
Raster class fails with unsigned integer types 

### ISSUE THREAD

**Issue by flalbat** [modflowpy/flopy#1144]
Hello,
Raster class of flopy.utils does not work with rasters including unsigned integer data (like uint8). If it is a definitive limitation of that class, this may be written in the docstring. If not but too complex to automatically determine all dtypes, an optional parameter may be added to enable the user to give dtype of the raster.

**Comment by jlarsen-usgs** [comment]
@flalbat 

I'll put in a PR to take care of this issue. 

There are lists of default dtypes that the Raster class looks for to set raster metadata, and unsigned ints are currently not included in these.
