### ISSUE TITLE
Viscosity package for MODFLOW 6

### ISSUE THREAD

**Issue by Martin-Pujol** [modflowpy/flopy#1150]
Hi,

Not really an issue but more of a request.

I am keen to move to MODFLOW 6 but unfortunately as far as I understand the new BUY package only allows density to vary but not the viscosity. As we have been using SEAWAT for modelling thermal breakthrough for geothermal applications this is an essential package for us.

Just wondering if there are any plans to develop a viscosity package for MODFLOW 6?

Thanks

**Comment by jdhughes-usgs** [comment]
This is a MODFLOW 6 issue. Closing for now.
