### ISSUE TITLE
Check fails when checking values of top array

### ISSUE THREAD

**Issue by jbellino-usgs** [modflowpy/flopy#117]
When loading a DIS file, `dis.check()` [looks for NANs](https://github.com/modflowpy/flopy/blob/f979207af316a6a4c668edbae9cbc1c553c52ad1/flopy/modflow/mfdis.py#L514-L515) in `dis.top.array`. The call to `check.values()` looks for cells that meet a certain criteria and [gets the indices](https://github.com/modflowpy/flopy/blob/8c3509c91b40f4fcf5a5c1877fc450b8cb45901c/flopy/utils/check.py#L418) of those cells and makes a call to `check._get_summary_array()` where a [dtype is created](`check._get_summary_array()`), including fields for lay, row, and col (k, i, j). Because `dis.top.array` is a 2-d array, the dtype created has too many fields and a ValueError is thrown.

**Comment by aleaf** [comment]
Jason, can you send me the dis file you are working with? Thanks

**Comment by langevin-usgs** [comment]
Jason/Andy, PR has been merged.  Please close. 

And if the elevator tries to bring you down
Go crazy, punch a higher floor

**Comment by jbellino-usgs** [comment]
Lol. We need to make elevators great again.
