### ISSUE TITLE
strangeness with comments in external files with `set_sim_path` and `set_all_data_external`

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#1183]
Im trying to load an existing model and write it into a new dir with external files:

```
sim = fp.mf6.MFSimulation.load(sim_ws="existing")
sim.simulation_data.mfpath.set_sim_path("new")
sim.set_all_data_external(check_data=False)
sim.write_simulation()
```

When I do that with the attached model, the external `.wel_stress_period_data_1.txt` file in the "new" directory has some interesting formatting at the top:

```
1 27 73      -0.01040000  19/14__0  # k i j q boundname 
 
 # k i j q boundname 
 
 # k i j q boundname
  3 27 73      -0.01040000  19/14__2
  1 25 71      -0.01040000  19/15__0
  3 25 71      -0.01040000  19/15__2
  1 43 72      -0.00950000  19/16__0
  3 43 72      -0.00950000  19/16__2
```

Seems like the comment line at the top of the existing external wel input list file is tripping things up?

Thanks!

[existing.zip](https://github.com/modflowpy/flopy/files/6963791/existing.zip)

**Comment by jtwhite79** [comment]
@spaulins-usgs - any movement here?

**Comment by langevin-usgs** [comment]
@jtwhite79, I think @spaulins-usgs is out of the office perhaps through the end of next week.  Hopefully he can get right on this when he gets back.

**Comment by spaulins-usgs** [comment]
@jtwhite79 I am now back and working on flopy issues.  I have one issue I am finishing up now that I started before vacation and then I will work on your issue next.

**Comment by spaulins-usgs** [comment]
@jtwhite79 Please download the latest develop version of flopy and verify that it fixes your problem.

**Comment by jtwhite79** [comment]
Thanks @spaulins-usgs !
