### ISSUE TITLE
Bitwise operation error when load a MF-USG model

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#1187]
I have tried to use the loading function `m1 = flopy.modflow.Modflow.load(fname, version='mfusg',verbose=False)` to load a few different MF-USG models from very simples ones (a transient version of the example model in the document) to real-world complex models. With some careful twisting, it can load the data if `check=False` is applied. However, I have difficulty passing the check function. ALthough the error messages are different for different models, they are related to the code below,
`C:\Anaconda\envs\py3\lib\site-packages\flopy\pakbase.py in _check_storage(self, chk, storage_coeff)`

```
    417             chk.values(

    418                 sarrays["sy"],

--> 419                 active & (sarrays["sy"] < 0),

    420                 "zero or negative specific yield values",

    421                 "Error",
```

> **TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''**

I have attached a simple model below for testing. It is the first example model with the latest release. I only changed the steady-state model to a transient model. 
[01A_nestedgrid_nognc_TR.zip](https://github.com/modflowpy/flopy/files/6990792/01A_nestedgrid_nognc_TR.zip)

**Comment by flydream0428** [comment]
@mwtoews, Thanks a lot, Mike. I have tested this. The fix works for the demo model attached above. 
However, I am facing another issue now with the adding of `dtype=bool` with my real-world model. 
I guess this is because I have different numbers of active nodes for different layers in the model. 
I am sorry that the simple model only has 1 layer. I cannot reproduce the error with it. 
Any fix for this? 
```
C:\Anaconda\envs\py3\lib\site-packages\flopy\pakbase.py in _check_storage(self, chk, storage_coeff)
    403                     ).flatten()
    404                     active = np.asarray(
--> 405                         [active[sl] for sl in node_k_slices], dtype=bool
    406                     ).flatten()
    407                 else:

C:\Anaconda\envs\py3\lib\site-packages\numpy\core\_asarray.py in asarray(a, dtype, order, like)
    100         return _asarray_with_like(a, dtype=dtype, order=order, like=like)
    101 
--> 102     return array(a, dtype, copy=False, order=order)
    103 
    104 
```

> **ValueError:** setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.

**Comment by langevin-usgs** [comment]
@cnicol-gwlogic, any chance you could have a quick look at this one?

**Comment by flydream0428** [comment]
The error can be reproduced by running, 
`np.asarray([[True,True],[False,False,False]],dtype=bool)`

**Comment by cnicol-gwlogic** [comment]
Hi Tao, can you upload your example somewhere for me? I've been using
variable disu.nodelay models no problem with this change, so can't
reproduce your issue.

**Comment by flydream0428** [comment]
Hi @cnicol-gwlogic, I have zipped part of the model files here. The whole model is too big for this, so I only included a few files. 
https://www.dropbox.com/s/ch0uz9l5pszalak/MF-USG_test.zip?dl=0

**Comment by cnicol-gwlogic** [comment]
@flydream0428  I've taken a look and submitted a fix for this. I know that model well. Note this one uses usg-beta / John Doherty's version, so you will likely come across other issues with this model in flopy, because the custom stuff like Richards equation, negative storage, etc is not supported (I noticed check points out some extreme LPF values because of this - so who knows what will end up in what flopy thinks are your hk/vka/ss/sy arrays). Be wary. I suggest custom work would be needed to handle this model in flopy.

**Comment by flydream0428** [comment]
Hi Chris, Thanks a lot for your help. I fully agree with you. It's a bit
risky to use flopy here due to the home-made modification by John. In the
beginning, I thought it will help others if I can spend some time debugging
this with flopy.
Now, I realise that the overall support for MFUSG is very limited. At the
moment, I can load a USG model with flopy. However, most packages are not
supported for creating. I will write my own code for this.

**Comment by cnicol-gwlogic** [comment]
No worries. I would like to include the basic usg-beta capabilities in flopy (eg. LPF richards arrays), but I'm not sure there would be appetite for it from the USGS' point of view, having to deal with enough code already. Happy to help with that if that is not the case though. 

You can usually still do useful things with flopy and usg-beta models anyway, like load/plot a grid or cross section (disu loads fine), including head / drawdown plots etc, and plotting standard boundary conditions.
