### ISSUE TITLE
Does flopy allow for loading and modifying externally-created input files (in my case they are MF6 input files from Model Muse)

### ISSUE THREAD

**Issue by sbferen** [modflowpy/flopy#1199]
I am a new user of Flopy but familiar with Modlflow. My question/issue relates to if Flopy enables loading and modifying existing input files that were created outside of Flopy, in my case the input files were generated using Model Muse. I would like to use Flopy to conduct a sensitivity analysis that evaluates the effect of varying model parameters such as K, Sy, conductance, and layer thickness. The script-based approach seems ideal for conducting an iterative parameter sweep that automates the input, running, and exporting of model results. However, I am not sure if Flopy supports loading and modifying externally-created input files. 

I have been able to load my model and run a simulation, but after a couple days of effort have not made any headway on figuring out how to modify the input files for my model, which is the critical step to enabling my sensitivity analysis . The example notebooks do not appear to address a situation where a user wants to modify properties of an existing package that was not created in Flopy,. The workflow that I have envisioned has the following steps: 1) load the model using **flopy.mf6.MFSimulation.load**, 2) modify the Sy, K, layer thickness using the **set_data** method (ex: **sto_package.sy.set_data**), 3) write new simulation input files, and 4) run the simulation with the new parameter values and repeating this many hundreds of times to cover my parameter combinations. 

Where I am stuck is that I cannot figure out how to call/load an existing packages so its values can be modified. For example, is there a way to use the sto_package  = flopy.mf6.ModflowGwfsto(___) to load the storage input file that was generated by Model Muse and then modify the Sy value using Flopy? It occurs to me that Flopy might only allow the user to modify simulation settings/data that were created inside of Flopy. 

Any insight about my issue would be much appreciated. 

Thanks, 
Stephen

**Comment by jlarsen-usgs** [comment]
@sbferen 

Yes, flopy provides this support. The modflow 6 tutorials show how to do this. In your case see: [https://flopy.readthedocs.io/en/3.3.4/_notebooks/tutorial07_mf6_data.html#Layered-Data](https://flopy.readthedocs.io/en/3.3.4/_notebooks/tutorial07_mf6_data.html#Layered-Data)

Here is a small code snippet to get you started 
```
sim = flopy.mf6.MFSimulation.load(sim_ws="my_sim_folder", exe_name="mf6.exe")
model = sim.get_model("my_model_name")

# get specific yield
sy = model.sto.sy

# then do stuff with sy here
sy[0] *= 1.1

# set the new data
model.sto.sy.set_data(sy)

# write simulation to a new folder
sim.simulation_data.mfpath.set_sim_path("new_sim_folder")
sim.write_simulation()
sim.run_simulation()
```

**Comment by sbferen** [comment]
Thank you for for the quick reply! The example code snippet is very helpful, thanks!
