### ISSUE TITLE
Package replace not working when adding another package of the same type

### ISSUE THREAD

**Issue by langevin-usgs** [modflowpy/flopy#12]
The following code demonstrates the problem:

import flopy

mf = flopy.modflow.Modflow('test')
dis = flopy.modflow.ModflowDis(mf)

stress_period_data = {0: [[0, 0, 0, -1.]]}
wel = flopy.modflow.ModflowWel(mf, stress_period_data=stress_period_data)

stress_period_data = {0: [[0, 0, 0, -2.]]}
wel = flopy.modflow.ModflowWel(mf, stress_period_data=stress_period_data)

stress_period_data = {0: [[0, 0, 0, -3.]]}
wel = flopy.modflow.ModflowWel(mf, stress_period_data=stress_period_data)

mf.write_input()

The fix is to modify the mbase module and explicitly assign the package to the packagelist position.  Will commit this fix after more testing.

    def add_package(self, p):
        """
        Add a package.

        Parameters
        ----------
        p : Package object

        """
        for i, pp in enumerate(self.packagelist):
            if pp.allowDuplicates:
                continue
            elif (isinstance(p, type(pp))):
                print '****Warning -- two packages of the same type: ',type(p),type(pp)                 
                print 'replacing existing Package...'                
                # pp = p
                self.packagelist[i] = p
                return        
        if self.verbose:
            print 'adding Package: ', p.name[0]
        self.packagelist.append(p)

**Comment by mbakker7** [comment]
Chris, others,

Would it make more sense to store packages in a dictionary rather than a
list?
Each package already has a name. 'wel', 'ghb', etc.
Let's use that name as the key in the dictiononary.
It is explicit and easy to manipulate.

Second question: is there a reason for allowDuplicates? When is that used?
With a dictionary that would be more difficult.

Thoughts?

Mark

**Comment by jtwhite79** [comment]
I think I added allowDuplicates a while ago, but I honestly can't remember
why.  Does anyone else ever use it?

I think moving to a package dictionary is a great idea.

J

**Comment by langevin-usgs** [comment]
I also do not remember why we allow duplicates.  But in the next MODFLOW
version, we are planning to allow multiple packages of the same type, so
maybe we should stick with the list for now?













*Christian LangevinResearch HydrologistOffice of GroundwaterU.S. Geological
Survey411 National CenterReston, VA 20192Office: 703-648-4169Fax:
703-648-6693Email: langevin@usgs.gov
<langevin@usgs.gov>https://profile.usgs.gov/langevin
<https://profile.usgs.gov/langevin>*

**Comment by mbakker7** [comment]
Fine with me.
