### ISSUE TITLE
Incorporate pygridgen/pygridtools?

### ISSUE THREAD

**Issue by phobson** [modflowpy/flopy#121]
I noticed that FloPy and can interface with the `gridgen-c` executable.

I don't quite yet grok the complete workflow of that interface, but I wonder if there would be some benefit to interfacing to pygridgen/pygridtools?

pygridgen was originally authored by Dr. Hetland at Texas A&M. I maintain a modern fork of the project here:
https://github.com/phobson/pygridgen
http://phobson.github.io/pygridgen/tutorial/gridgen_examples.html

And then to minimize the divergence of my fork from Dr. Hetland's (there's still hope he'll pull in my changes), I created pygridtools for a higher-level interface:
https://github.com/Geosyntec/pygridtools
http://geosyntec.github.io/pygridtools/tutorial/02_ShapefilesAndCellMasks.html#loading-data-from-shapefiles-via-pygridtools-iotools

Again, I'm still parsing the code that interfaces with `gridgen-c`, so this might all be moot if all flowpy needs is a pair of numpy arrays.

**Comment by langevin-usgs** [comment]
Paul, it looks like there are two different programs called gridgen.  The gridgen that is currently supported (somewhat) in Flopy is the version distributed by the USGS (http://water.usgs.gov/ogw/gridgen/).  I had not seen the gridgen-c program that you mentioned.

**Comment by phobson** [comment]
Ahh. I see. 

I'll keep digging and see if there's a way to take pygridgen grids and making them useful for flopy. In meantime I'll close this issue. 

Apologies for the noise.
