### ISSUE TITLE
Inconsistent information between .lst file and bf.CellBudgetFile 

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1213]
Hello,
I have model that is using GHBs. When I load the cbb:

`bf.CellBudgetFile("geofortis_prop_well_chd.cbb").list_unique_records()`

CHDs are listed and no GHBs appear:
RECORD           IMETH
----------------------
FLOW-JA-FACE         1
CHD                  6

There are **no** CHDs in the model, as confirmed by the lst file.

Additionally, when I sum the "CHD" flows (which should be GHB flows), the values I get are not what appears in the lst file:

`a_chd_flx = bf.CellBudgetFile("geofortis_prop_well_chd.cbb").get_data(text='CHD')[0]['q']
flx_out = a_chd_flx[a_chd_flx<0].sum()
flx_in =  a_chd_flx[a_chd_flx>0].sum()`

The values I am getting are the same as reported by Groundwater Vistas, so it seems flopy and GWV are having the same issue. 

The goal is to convert GHB fluxes to WELs for my external boundary conditions. I expect that if I pull GHB fluxes and assign them to wells, the head distribution should not change. Is this not correct?

**Comment by langevin-usgs** [comment]
I took the quickstart example on the main flopy page and converted it from ghb to chd as follows:

```
import os
import flopy
ws = './mymodel'
name = 'mymodel'
sim = flopy.mf6.MFSimulation(sim_name=name, sim_ws=ws, exe_name='mf6')
tdis = flopy.mf6.ModflowTdis(sim)
ims = flopy.mf6.ModflowIms(sim)
gwf = flopy.mf6.ModflowGwf(sim, modelname=name, save_flows=True)
dis = flopy.mf6.ModflowGwfdis(gwf, nrow=10, ncol=10)
ic = flopy.mf6.ModflowGwfic(gwf)
npf = flopy.mf6.ModflowGwfnpf(gwf, save_specific_discharge=True)
#chd = flopy.mf6.ModflowGwfchd(gwf, stress_period_data=[[(0, 0, 0), 1.],
#                                                       [(0, 9, 9), 0.]])
ghb = flopy.mf6.ModflowGwfghb(gwf, stress_period_data=[[(0, 0, 0), 1., 100.],
                                                       [(0, 9, 9), 0., 100.]])

budget_file = name + '.bud'
head_file = name + '.hds'
oc = flopy.mf6.ModflowGwfoc(gwf,
                            budget_filerecord=budget_file,
                            head_filerecord=head_file,
                            saverecord=[('HEAD', 'ALL'), ('BUDGET', 'ALL')])
sim.write_simulation()
sim.run_simulation()

head = gwf.output.head().get_data()
bud = gwf.output.budget()
bud.list_unique_records()
```

The output passed back from the list_unique_records() is what we would expect.  

```
RECORD           IMETH
----------------------
FLOW-JA-FACE         1
DATA-SPDIS           6
GHB                  6
```

If you can produce a small example that shows the error, then we can take a look, but I suspect there is something else going on.  Closing this issue.
