### ISSUE TITLE
set_data for botm using list

### ISSUE THREAD

**Issue by wkitlasten** [modflowpy/flopy#1231]
I am trying to set the bottom elevations of my MF6 layers using `gwf.dis.botm.set_data(data)`. My data:

```
data=[{'filename': 'wairau.bottoms_layer1.dat', 'factor': 1.0, 'iprn': -1}, 
{'filename': 'wairau.bottoms_layer2.dat', 'factor': 1.0, 'iprn': -1}, 
{'filename': 'wairau.bottoms_layer3.dat', 'factor': 1.0, 'iprn': -1}, 
{'filename': 'wairau.bottoms_layer4.dat', 'factor': 1.0, 'iprn': -1}, 
{'filename': 'wairau.bottoms_layer5.dat', 'factor': 1.0, 'iprn': -1}, 
{'filename': 'wairau.bottoms_layer6.dat', 'factor': 1.0, 'iprn': -1}]
```
Is there anything obviously wrong with my approach? If so, ignore the following attempt to track the issue:

I am getting the following error:

 ```
File "d:\modelling\flopy\flopy\mf6\data\mfdataarray.py", line 871, in _set_data
    data, layer, multiplier, key=self._current_key

  File "d:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 877, in set_data
    self._set_array(data, layer, multiplier, key, autofill)

  File "d:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 961, in _set_array
    success = self._set_array_layer(data, layer, multiplier, key)

  File "d:\modelling\flopy\flopy\mf6\data\mfdatastorage.py", line 1072, in _set_array_layer
    layer_storage = self.layer_storage[self._resolve_layer(layer)]

  File "d:\modelling\flopy\flopy\utils\datautil.py", line 482, in __getitem__
    item_ptr = item_ptr[index]

IndexError: list index out of range
```

The issue seems to stem from the conditional in the `_set_array` method in DataStorage (line 940):

```
if (
            layer is None
            and self.data_structure_type == DataStructureType.ndarray
            and len(data) == self.layer_storage.get_total_size()
            and not isinstance(data, dict)
        ):
```

 since it appears `self.layer_storage.get_total_size()` = 1 when it reaches that point and success = False.

**Comment by spaulins-usgs** [comment]
@wkitlasten You are probably correct that the issue stems from the conditional in _set_array.  FloPy reaching line 961:

    success = self._set_array_layer(data, layer, multiplier, key)

indicates that the conditional you mentioned above returned False.  Most likely it returned False because your data is not the dimensions FloPy is expecting.  Specifically, the third conditional:

    and len(data) == self.layer_storage.get_total_size()

will fail if the botm data you passed in does not have the correct number of layers.  When you called:

    gwf.dis.botm.set_data(data)

you passed in a list of six dictionaries.  Please verify that your model has six layers.

**Comment by wkitlasten** [comment]
@spaulins-usgs , I have tried it with several models, all with len(data)==nlays. get_total_size() always returns 1, as far as I can tell. Maybe I need to just pass each layer individually?

**Comment by langevin-usgs** [comment]
@spaulins-usgs, would he need "data" as part of the dictionary for each layer, as indicated here? https://flopy.readthedocs.io/en/3.3.4/_notebooks/tutorial08_mf6_data.html

**Comment by spaulins-usgs** [comment]
@langevin-usgs No, if you specify a filename with "data" FloPy assumes that the file you a specifying already contains the data.

**Comment by spaulins-usgs** [comment]
@wkitlasten Could you post your script?  Or at least the part leading up to where you call botm.setdata?  That would help me reproduce the problem.

**Comment by wkitlasten** [comment]
I added a similar block to the [mf6_A_simple_model ](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_mf6_A_simple-model.ipynb) example and it works fine:

```
dz=10
botm_data=[]
for i in range(Nlay):
    botm=-np.ones((N,N))*(i+1)*dz
    fname=f"my_botm.layer{i+1}.dat"
    np.savetxt(os.path.join(workspace,fname),botm)
    botm_data.append({'filename': fname, 'factor':1.0,
                            'iprn':-1})
gwf.dis.botm.set_data(data)
```
So (not surprisingly) the issue is all mine! So I will close this issue and add it to my long list of issues.

But any suggestions on what to check would be greatly appreciated. So far I have checked:

0) my data lists look the same
1)  gwf.dis.nlay.data == len(data)
2) all my arrays load and plot in numpy
3) gwf.dis.nrow.data == botm.shape[0] and gwf.dis.ncol.data == botm.shape[1]

failing in my model:
```
botm_data=
[{'filename': 'wairau.bottoms_layer1.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'wairau.bottoms_layer2.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'wairau.bottoms_layer3.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'wairau.bottoms_layer4.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'wairau.bottoms_layer5.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'wairau.bottoms_layer6.dat', 'factor': 1.0, 'iprn': -1}]
```

working in example w 6 layers for consistency:
```
botm_data=
[{'filename': 'my_botm_layer1.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'my_botm_layer2.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'my_botm_layer3.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'my_botm_layer4.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'my_botm_layer5.dat', 'factor': 1.0, 'iprn': -1},
 {'filename': 'my_botm_layer6.dat', 'factor': 1.0, 'iprn': -1}]
```

```
print(gwf.dis.nlay.data == len(data))
for d in botm_data:
    a=np.loadtxt(os.path.join(workspace,d['filename']))
    plt.imshow(a)
    plt.show()
    print(gwf.dis.nrow.data == a.shape[0] and gwf.dis.ncol.data == a.shape[1])
```

**Comment by spaulins-usgs** [comment]
@wkitlasten Chris pointed out that there could potentially be a problem with layered vs non-layered data.  To see if this is the problem you can try forcing FloPy to create layered data with the following line:

    gwf.dis.botm.make_layered()

After you call make_layered you can then call set_data:

    gwf.dis.botm.set_data(botm_data)

**Comment by wkitlasten** [comment]
Hey thanks @langevin-usgs and @spaulins-usgs, `make_layered()` worked!

I was building a basic gwf model with the horizontal extend defined, but generic layering:

```
flopy.mf6.ModflowGwfdis(gwf, nlay = nlay,
                                nrow = nrow ,ncol = ncol,
                                delr = dy, delc = dx,
                                xorigin = xll, yorigin = yll,
                                top = 1,botm = 0)
```
`gwf.dis.botm.layer_shape()` returns (15,0) but `gwf.write()` produces a .dis file without botm layered. I never actually wrote that basic .dis file to see if botm was layered. Now I know!
