### ISSUE TITLE
Can not access head file (.hds) using Flopy

### ISSUE THREAD

**Issue by spartan44L** [modflowpy/flopy#1232]
`head = gwf.output.head().get_data()`

The above line on the FlopyQucik.py shows following error:

head = gwf.output.head().get_data()
Traceback (most recent call last):

  File "C:\Users\.../3093209259.py", line 1, in <module>
    head = gwf.output.head().get_data()

  File "H:\Anaconda3\envs\Flopy\lib\site-packages\flopy\mf6\mfmodel.py", line 218, in __getattr__
    raise AttributeError(item)

AttributeError: output`

**Comment by jlarsen-usgs** [comment]
What version of flopy are you using? The `.output` property is a relatively new addition to flopy's mf6 functionality.

**Comment by spartan44L** [comment]
Hello jlarsen, 

I have been using the Flopy 3.3.4.

**Comment by jdhughes-usgs** [comment]
@spartan44L have you tried the development version of flopy? If so and you still are having this problem can you confirm that 1) you are using MODFLOW 6 (this functionality only works with MODFLOW 6 models) and 2) that the size of your head file is not 0 bytes.

**Comment by jdhughes-usgs** [comment]
@spartan44L is this still an issue? I will close this issue if I don't hear otherwise.
