### ISSUE TITLE
Cannot open mf6 simulation with a space in the TDIS package file name

### ISSUE THREAD

**Issue by tim-mitchell** [modflowpy/flopy#1236]
Importing the attached modflow model fails.
[MODFLOW 6 DISV - 1.zip](https://github.com/modflowpy/flopy/files/7159666/MODFLOW.6.DISV.-.1.zip)
using `flopy.mf6.MFSimulation.load(sim_ws=r'D:\Modflow\MODFLOW 6 DISV - 1')`

In `MFSimulation.register_package` the name_file tdis attribute is set to `package.filename`
flopy/mf6/modflow/mfsimulation.py:1822
However the `MFScalar.set_data` method splits the string and keeps the last part
flopy/mf6/data/mfdatascalar.py:168

**Comment by spaulins-usgs** [comment]
@tim-mitchell This issue should be fixed with the latest commit.
