### ISSUE TITLE
ZONBUD does not work MF6 model with exchange

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1250]
ZONBUD does not work MF6 model with exchange. The actual zbud6.exe does however.

**Comment by jlarsen-usgs** [comment]
@RyanConway91 

Are you using Zonbud6? This class runs the zbud6 executable. [How to use ZB6](https://flopy.readthedocs.io/en/3.3.4/_notebooks/tutorial01_mf6_output.html#Creating-and-running-ZoneBudget-for-MF6)
```
zonbud = ml.output.zonebudget(zarr)
zonbud.change_model_ws(sim_ws)
zonbud.write_input()
zonbud.run_model()
```

**Comment by RyanConway91** [comment]
I was using flopy.utils.zonbud. I was not aware of the ml.output.zonebudget() method. Thanks!
