### ISSUE TITLE
Cleaning cbb file with exchanges for MODPATH 7

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1251]
I have some nested (r,c,l dis) model results I want to use MP7 on. It seems MP7 will not work on the cbb file if exchanges flows are written to the cbb. I believe the best current solution is to re-run the nested models separately with wells inplace of the exchanges , where the well flux was read from the exchange flows. 

It would be great if flopy had the functionality to "clean up" an exchange CBB flow file and basically make a "exchange wells" cbb file without actually having to re-run the model.

**Comment by langevin-usgs** [comment]
Ideally, we should fix MODPATH to work correctly.  If the budget save settings are specified properly, the nested model cbb file should have the exchange flows in them (they will be labeled with FLOW_JA_FACE).  But it sounds like MODPATH is choking on them.  I've filed an issue on the MODPATH repo as that may be a better place for it (https://github.com/MODFLOW-USGS/modpath-v7/issues/26).  Coding something into flopy is not really a long-term solution.  By the way, there is ongoing work to implement a particle tracking model into MODFLOW 6.  That will be our best long-term solution.
