### ISSUE TITLE
Module named config and Figspecs not found

### ISSUE THREAD

**Issue by josht6022** [modflowpy/flopy#1271]
### Discussed in https://github.com/modflowpy/flopy/discussions/1270

<div type='discussions-op-text'>

<sup>Originally posted by **josht6022** October 20, 2021</sup>
I am working on example 44. Zero-Order Production in a Dual-Domain System.
[(https://modflow6-examples.readthedocs.io/en/latest/_notebooks/ex-gwt-mt3dsupp632.htm)]

It seems that the **config** and **figspecs** libraries are not working.

Are they called something different now? Thank you for your response.
![image](https://user-images.githubusercontent.com/40776914/138177382-3ef6b58f-64ee-4b61-8fe0-43dd37c0c64f.png)
</div>

**Comment by langevin-usgs** [comment]
I'll take a look at this and let you know in the Discussions when it's fixed.  We moved some things around and so maybe those examples need an update.  Thanks for pointing this out.  Will close this issue.
