### ISSUE TITLE
problems of compiling the sln file in msvs

### ISSUE THREAD

**Issue by haifan-upc** [modflowpy/flopy#1277]
I opened the mf6.sln file in the msvs folder and tried to compile it using VS2019. However, the exe file can not be created, and "the thread 0xcc4 has exited with code 2(0x2)" and  "the thread 0x590 has exited with code 2(0x2)" are reported. How to deal with this problem. Thanks.

**Comment by langevin-usgs** [comment]
This is not a problem with flopy.  You can ask on the MODFLOW Github page, but without more information we won't be able to help.
