### ISSUE TITLE
Modflow no longer flushes buffer to files upon ending program under MacOS Monterey

### ISSUE THREAD

**Issue by Olsthoorn** [modflowpy/flopy#1286]
This is a new issue beyond **flopy** on the Mac. After updating to the new **MacOs Monterey**, and running **modflow2005** via **flopy** to **normal termination**, **flopy** stumbles over reading the **binary head file**, saying it it can't convert the read data to the desired shape of the layer. Further, the **listfile** is no longer complete; it now misses a few of the last lines it normally prints. I analyzed the *binary head file* by writing a python routine to read it, which then revealed that, indeed, the binary head file was incomplete; it missed the last 2 layers and ended with a number bytes making an incomplete layer.

I appeared to me that the last internal buffers for writing to the output files were not flushed before the program finished. This never happened in the past with the same code. After recompiling **modflow2005** with the newest **gfortran 11.2 version for MaxOS Montery**, I got the same issue. I then added the statement **CALL FLUSH()** just before the end of the main fortran file **mf2005.f,** which fully solved the problem. Hence, this appears to be a MacOs Montery system problem which, likely will affect all Mac Modflow users when they update to MacOS Montery. But as said, the issue can be readily solved with the extra cal to the builtin fortran flush function.

The same happens in **Seawat**. I did not yet run *mt3dms* and *mf6*, which may also have this issue.

Below, I included a few of the last lines of the code of main program, in file **mf2005.f**, with the added **CALL FLUSH()** statement. (See the 3 lines starting with C TOlsthoorn).

This seems a general problem for Mac users on the new Monterey. I guess it never hurts to end the program with a final flush. Also now needed in Seawat and probably as well in mf6 and other fortran code.

(It took me five days to figure it out this totally unexpected issue, but am now happy it was solved and I can continue with my groundwater problem).

Regards
Theo Olsthoorn, Heemstede, The Netherlands

```
C
C10-----END OF PROGRAM.
      IF(NCVGERR.GT.0) THEN
        WRITE(*,*) 'FAILED TO MEET SOLVER CONVERGENCE CRITERIA ',
     1          NCVGERR,' TIME(S)'
      ELSE
        WRITE(*,*) ' Normal termination of simulation'
      END IF

C TOlsthoorn 2021-11-02, added extra flush to ensure all data is written
      WRITE(IOUT,*) ' --- T.Olsthoorn, flushing all buffers.  ---'
      CALL FLUSH()


      CALL USTOP(' ')
C
      END
      SUBROUTINE GETNAMFIL(FNAME)
C
```

**Comment by mwtoews** [comment]
Try using the [GFORTRAN_UNBUFFERED_ALL](https://gcc.gnu.org/onlinedocs/gfortran/GFORTRAN_005fUNBUFFERED_005fALL.html) environment variable.  Similarly, unbuffered I/O in Python scripts can be obtained with `python -u` ([docs](https://docs.python.org/3/using/cmdline.html#cmdoption-u)).

**Comment by ZitongZhou** [comment]
My Modflow and MT3DMS models are all outputing empty files now, and I have a feeling that it is the same issue as Theo ran into. I'm using the make_xxx.py to compile executables, for me mf2005.f file is automatically generated and then deleted when the make_mf2005.py is done running. How do you keep the .f files during compiling the executables?
