### ISSUE TITLE
set ftlfilename in flopy.mt3d.Mt3dms.load()

### ISSUE THREAD

**Issue by dbrakenhoff** [modflowpy/flopy#129]
When loading an existing MT3D model, wouldn't it be a good idea to set the filename for FTL output (if it exists)?

After loading one can manually set the mt.ftlfilename attribute, which also works, but it would be neater if  this is picked up by the load method.

**Comment by langevin-usgs** [comment]
@dbrakenhoff, quick question for you.  What is it that you are trying to do?  At the moment, flopy requires that you set the FTL name manually after the model has been loaded.  And this can be done with the following code, for example:

    namfile = 'p7mt.nam'
    mt = flopy.mt3d.mt.Mt3dms.load(namfile, model_ws=pth, verbose=True,
                                   exe_name=mt3d_exe)
    mt.model_ws = newpth
    ftlfile = 'p7.ftl'
    mt.ftlfilename = ftlfile
    mt.write_input()

Most of the time when we do a load, we change the workspace so that we can write the model elsewhere.  This causes complications for a file like the FTL file.  Do we path back to its original location?  Copy the FTL file to the new location?  Not sure of the best behavior.  Any thoughts?

**Comment by dbrakenhoff** [comment]
That's a good question...
 
I was trying to load an existing MT3D model and make some changes in the mt3d packages and rerun the mt3d model. It took me a  while to figure out how to get the model to use the existing FTL file. Initially, i thought it would be handled similarly to other packages as it was listed in the namefile. Setting the FTL manually works, i just couldn't find any documentation that that was the correct way to go about it.

As for the best behavior, I'm not entirely sure either. An MT3D model is inextricably linked to a modflow model and needs the FTL file to run. So in that sense, copying it would make sense. On the other hand, the FTL file is modflow output, and by copying it you "lose" the link to the modflow model that produced it. Perhaps including the path to the original file isn't such a bad idea? Or you could stick to the manual method and force the user to think about it explicitly. In that case it would help to add an instruction somewhere for the user to specify the FTL file location manually.

**Comment by langevin-usgs** [comment]
Based on your input, I decided to just add some instructions to the docstrings for the load method as follows:

        Notes
        -----
        The load method does not retain the name for the MODFLOW-generated
        FTL file.  This can be added manually after the MT3D model has been
        loaded.  The syntax for doing this manually is
        mt.ftlfilename = 'example.ftl'

        Examples
        --------

        >>> import flopy
        >>> f = 'example.nam'
        >>> mt = flopy.mt3d.mt.Mt3dms.load(f)
        >>> mt.ftlfilename = 'example.ftl'

Thanks for the input.  Am closing this issue.

**Comment by dbrakenhoff** [comment]
That works! Thanks!
