### ISSUE TITLE
Problem with loading STR package for a mfusg model

### ISSUE THREAD

**Issue by hjia1005** [modflowpy/flopy#1295]
All other packages are loaded successfully except STR. The following error message was displayed:

v = [tt(vv) for tt, vv in zip(type6, t)]
ValueError: invalid literal for int() with base 10: 14347.4667 - which is supposed to be the Flow. 

Then I checked the file mfstr.py, seems Flopy failed to recognize this is an unstructured grid type for this package, but it load other packages. It expects a type6 input for structured grid but this is a usg model. 
type6 = [
            np.int32,
            np.int32,
            np.int32,
            np.int32,
            np.int32,
            np.float32,
            np.float32,
            np.float32,
            np.float32,
            np.float32,
        ]
Any help will be appreciated!

**Comment by langevin-usgs** [comment]
@cnicol-gwlogic, any chance you could take a look at this?  I suspect there is a quick fix.

**Comment by hjia1005** [comment]
It worked, thank you very much @cnicol-gwlogic!
Are TVM and adaptive timesteps in OC in your next schedule?

**Comment by cnicol-gwlogic** [comment]
No worries @hjia1005. I had no immediate plans for oc ats or tvm, but neither would be too hard for basic read/write functionality. I'll give it a shot, sure.
