### ISSUE TITLE
MF6: model.output.budget().get_ts() method error

### ISSUE THREAD

**Issue by Smith0710** [modflowpy/flopy#1308]
In attempting to extract a budget timeseries from MF6 results using the .output.budget().get_ts() method the following error notification is occurring: "AssertionError: A modelgrid instance must be provided during instantiation to get IMETH=6 timeseries data"

Thanks

**Comment by spaulins-usgs** [comment]
Try giving the CellBudgetFile a modelgrid:

```
budget = model.output.budget()
budget.modelgrid = model.modelgrid
```

And then make your get_ts call:

`budget_frf = budget.get_ts((1, 1), "FLOW-JA-FACE")
`

**Comment by Smith0710** [comment]
Thanks very much @spaulins-usgs. This method works well. I also found the `.get_data()` method can be used with appropriate array pointers and retrieves results for all model cells for the given text type (e.g. 'DRN') without the need to specify a list of cell locations.
