### ISSUE TITLE
Shapefile export always meters?

### ISSUE THREAD

**Issue by mnfienen** [modflowpy/flopy#131]
I'm exporting a shapefile after reading in `dis.sr` from a model.spc (PEST-style) file and assigning `lenuni='feet'` and `proj4` is a prof4 string. But....units are feet. 

I want to add a couple things (that may already be there and I missed but couldn't find them):

1. Can `sr` handle feet? When I assign the proper projection, my shapefile is not located right on the earth but is far southwest (which would make sense if units are meters but should be feet)
2. Should we make a proj4 reader method for `dis.sr`? I would be happy to add it
3. Finally, can we add the projection file to the output? At the moment it looks like no PRJ file was written

**Comment by jtwhite79** [comment]
``sr`` can handle feet but there are some heuristics in ``sr`` to (try to) rectify differences in model units (specified with ```dis.lenuni```) and the proj units.  

Still need someone to step up and add some functionality to write ESRI PRJ files for shapefiles...
