### ISSUE TITLE
Error loading MF6 UCN file with utils.UcnFile, but works with utils.HeadFile

### ISSUE THREAD

**Issue by kallejahn** [modflowpy/flopy#1313]
When attempting to read a UCN file generated by MF6 using `flopy.utils.UcnFile` I have been getting the following error: 
``` 
C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flopy\utils\binaryfile.py:308: UserWarning: Possible error. ncol (538976334) * nrow (1309) > 10,000,000 
  warnings.warn(s)
```
I have also tested this on the MF6 UCN from the example problem **ex-gwt-mt3dms-p10**. I get a similar error: 
```
C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flopy\utils\binaryfile.py:308: UserWarning: Possible error. ncol (538976334) * nrow (40) > 10,000,000 
  warnings.warn(s)
```

However, I can read MF6 UCN files successfully using `flopy.utils.HeadFile(filename, text='CONCENTRATION')`. 

This works fine as a workaround, but I figure this `UcnFile()` issue is either a bug, or perhaps its incompatibility with MF6 UCN just needs to be documented? (Maybe it already is, sorry if I missed it!)

**I'm using flopy version 3.3.4, and MF6 version 6.2.1**

**Comment by jlarsen-usgs** [comment]
@kallejahn 
This sounds like an issue with the precision setting (occassionally "auto" doesn't determine the precision of binary files properly). Try using the call `flopy.utils.UcnFile(filename, precision="double")` and report back.

**Comment by kallejahn** [comment]
@jlarsen-usgs 
Thanks for taking a look! I'm getting the same UserWarning while setting "double" precision, even when just looking at the example problem **ex-gwt-mt3dms-p10**. I also tried creating a fresh conda environment, but still the same. 

In addition to the UserWarning, I'm also getting this IndexError. Forgot to include that in my first post, looks like there's maybe an issue reading the header in the binary file?

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp\2/ipykernel_26072/1016676403.py in <module>
      3 # ex_mt3d = flopy.utils.HeadFile(r"C:\WRDAPP\mf6.2.1\examples\ex-gwt-mt3dms-p10\gwt-p10-mf6.ucn",text='CONCENTRATION')
      4 filename = 'C:/WRDAPP/mf6.2.1/examples/ex-gwt-mt3dms-p10/gwt-p10-mf6.ucn'
----> 5 example = flopy.utils.UcnFile(filename=filename, precision='double')

C:\ProgramData\Anaconda3\envs\flopy21\lib\site-packages\flopy\utils\binaryfile.py in __init__(self, filename, text, precision, verbose, **kwargs)
    563             bintype="Ucn", precision=precision
    564         )
--> 565         super().__init__(filename, precision, verbose, kwargs)
    566         return
    567 

C:\ProgramData\Anaconda3\envs\flopy21\lib\site-packages\flopy\utils\binaryfile.py in __init__(self, filename, precision, verbose, kwargs)
    280 
    281     def __init__(self, filename, precision, verbose, kwargs):
--> 282         super().__init__(filename, precision, verbose, kwargs)
    283         return
    284 

C:\ProgramData\Anaconda3\envs\flopy21\lib\site-packages\flopy\utils\datafile.py in __init__(self, filename, precision, verbose, kwargs)
    199 
    200         # read through the file and build the pointer index
--> 201         self._build_index()
    202 
    203         # now that we read the data and know nrow and ncol,

C:\ProgramData\Anaconda3\envs\flopy21\lib\site-packages\flopy\utils\binaryfile.py in _build_index(self)
    312         ipos = 0
    313         while ipos < self.totalbytes:
--> 314             header = self._get_header()
    315             self.recordarray.append(header)
    316             if self.text.upper() not in header["text"]:

C:\ProgramData\Anaconda3\envs\flopy21\lib\site-packages\flopy\utils\binaryfile.py in _get_header(self)
    367         """
    368         header = binaryread(self.file, self.header_dtype, (1,))
--> 369         return header[0]
    370 
    371     def get_ts(self, idx):

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by jlarsen-usgs** [comment]
@kallejahn 

I think I see what's happening here. It looks like the binary headers from modflow-2005 compatible transport code is different than that of the modflow-6 transport code. You are correct that we do need to document this and/or update the `UcnFile()` code to let the user specify if they are working with MODFLOW6.

Also as an FYI:
If you have your modflow6 simulation loaded in flopy you can access output using the `.output` attribute on the model object. Example:
```
gwt = sim.get_model("my_transport_model")
ucn = gwt.output.concentration()
head = gwt.output.head()
bud = gwt.output.budget()
```

**Comment by langevin-usgs** [comment]
Sorry for the confusion.  With MODFLOW 6 transport, you have to use the HeadFile class with the text="CONCENTRATION" argument, as you've found.  @jlarsen-usgs's recommendation to use the .output method is the preferred way to access model results from MODFLOW 6.  The UcnFile class is specific to MT3D.
