### ISSUE TITLE
Cannot install flopy version 3.3.4 from pypi on Windows

### ISSUE THREAD

**Issue by jlarsen-usgs** [modflowpy/flopy#1314]
@jdhughes

I'm currently unable to install flopy 3.3.4 from the pypi release. There seems to be an issue with installation when using pypandoc to convert the rst file to the long_description variable. See error message below.

I can, however, install from the master branch of the github repository. 

![Clipboard](https://user-images.githubusercontent.com/19962180/144916630-c4c97643-01e6-4e70-8ff3-50d4922a327c.png)

**Comment by jdhughes-usgs** [comment]
I was able to install `flopy=3.3.4` in a fresh `python=3.9` conda environment without `pypandoc`. Reopen this issue if you are still having problems with the pip installation.
