### ISSUE TITLE
Problem with the refinement method of Gridgen

### ISSUE THREAD

**Issue by MostafaGomaa93** [modflowpy/flopy#1317]
I am creating a quadtree grid using the gridgen method. I have a problem with the level of refinement. The grid has 6 layers in which I select layer 1 only to be refined (See please line 95 of my attached code).

When I select the level of refinement = 3 or more, and although I select only layer 1 for the refinement, both layers 1 and 3 will be refined !!. I really have no idea why layer 3 is also refined! 
However, if I select the level of refinement = 2 or less, The problem is solved and layer 1 will be only refined.

The refinement level I need at the end is 3. In line 117 of my code, I plot layer 2, so that you can see it.

Attached is my code and the required files to run the code
https://we.tl/t-CVCAOuE1xV

Thanks a lot in advance

**Comment by MostafaGomaa93** [comment]
Another small issue:
Is there anyway to define the projection of the generated quadtree shapefile? I see this can be done with the grid generated by the dis package, but don't how to do it with the gridgen module

**Comment by jlarsen-usgs** [comment]
@MostafaGomaa93 

It looks like our gridgen module does not include the option to set `SMOOTHING_LEVEL_VERTICAL` or `SMOOTHING_LEVEL_HORIZONTAL`. Because the default is `SMOOTHING_LEVEL_VERTICAL=1`, the gridgen executable is smoothing layer 3 (below the layer that you've set refinement features on). I'll take a look at adding these to the `gridgen.py` module. 


I can also look into the issue of defining a projection for  your quadtree shapefile.

**Comment by langevin-usgs** [comment]
A word of caution that smoothing in the vertical direction is highly recommended.  I think we intentionally skipped adding support for shutting off vertical smoothing as the simulated flows can do very strange things.  I think it's fine to add support for this, but be wary of the simulated flow results.  Some of the challenges are described here: https://ngwa.onlinelibrary.wiley.com/doi/abs/10.1111/gwat.12389

**Comment by jlarsen-usgs** [comment]
Maybe the best way to add the vertical smoothing shutoff support is through a keyword argument. That way the support exists, for the rare instances that people want it, but isn't a standard parameter that users will commonly adjust.
