### ISSUE TITLE
MODPATH7 read pathlines: ValueError: could not convert string to float: '0.99232836-100'

### ISSUE THREAD

**Issue by rhugman** [modflowpy/flopy#1319]
G'day,

Not sure if this should be a Flopy issue or a MODPATH7 issue.

MODPATH7 occasionally writes very small numbers in scientific notation without the E; if I understand correctly this is to maintain column widths. (Similar issue to MODFLOW-USGS/modflow6#615)

When this happens, reading pathline files with the `flopy.utils.PathlineFile.get_destination_pathline_data()` or `get_destination_endpoint_data()` functions result in error messages like so:

`ValueError: could not convert string to float: '0.99232836-100'`

The error occurs when using np.loadtxt to read the pathline file. I used an (inelegant) workaround by adding a converter function to the np.loadtxt shown below. 
```
        def fixexp(t):
            if type(t)==bytes:
                t = t.decode()
            try:
                val = float(t)
            except ValueError:
                t = 'E+'.join(t.rsplit('+', 1))
                t = 'E-'.join(t.rsplit('-', 1))
                val = float(t)
            return val
```
This works for  `get_destination_pathline_data()`  but not for  `get_destination_endpoint_data()`. If I understand correctly, the latter relies on Pandas. (I have not dug into it very far).

Example model files & mp7.exe:
[m.zip](https://github.com/modflowpy/flopy/files/7738961/m.zip)

Cheers,
R

**Comment by dbrakenhoff** [comment]
Hi @rhugman,

I ran into a similar issue using Modpath7, I think: https://github.com/MODFLOW-USGS/modpath-v7/issues/27
This was fixed in the develop version of Modpath7, not sure if there has been an official release since then. Maybe that helps?

Kind regards,

Davíd

**Comment by rhugman** [comment]
Thanks @dbrakenhoff, that did the trick.
