### ISSUE TITLE
MODPATH: un-able to write stop zone info

### ISSUE THREAD

**Issue by bdestombe** [modflowpy/flopy#132]
Item 30 and 31 of the MP simulation script are currently not parsed correctly. Lines 269 - 273 of flopy/modpath/mpsim.py

In item 30 the user is currently required to enter a string instead of an integer. And in item 31 `f_sim.write(self.stop_zone.get_file_entry())` should be, `f_sim.write(self.zone.get_file_entry())`
And `zone` should then already be a Util3d array, thus a line in the `__init__` should be added which transforms the user input into a Util3d array.

**Comment by langevin-usgs** [comment]
Hey Bas, do you have pull requests with fixes for these MODPATH problems?  Would be good to fix them.  Not sure anyone on the flopy dev team has time at the moment.

**Comment by bdestombe** [comment]
Hi Chris, I will have a go at it as soon as I got it all working. Currently I am still struggling with file-units, external/internal files. 

I suspect that the following should be added to the `__init__,`
```python
self.zone = util_3d(model, (nlay,nrow,ncol), np.int, \
                    zone, name='zone', locat=self.unit_number[0]) 
```
This writes beautiful Util2d arrays to the simulation file. However, I get the following error when I try to run modpath,
```fortran
At line 681 of file ./src_temp/MP6Util.for (unit = 32, file = 'fort.32')
Fortran runtime error: End of file
```
where, the unit number of the simulation file is 32. Is it because the unit number of the simulation file is not listed in the nam file?
