### ISSUE TITLE
Plotting BC parameter fields

### ISSUE THREAD

**Issue by nikobenho** [modflowpy/flopy#1334]
Hi,

I would like to plot parameter fields of GHB and SFR conductance. I've looked through the example notebooks and found that the function `plot_bc()` accomplishes plotting of boundary conditions using a single color. However, I would like to plot the associated parameter field with each BC but couldn't find an example of this. Is it possible to do so at the moment?

Cheers

**Comment by jlarsen-usgs** [comment]
@nikobenho 

you can create an array of your bounday condition values from GHB and SFR using the `.to_array()` method.

Example:
```
reach_data = ml.sfr.reach_data
dictionary_of_arrays = reach_data.to_array(kper=0, mask=True)
strhc1 = dictionary_of_arrays["strhc1"]

pmv = flopy.plot.PlotMapView(ml, layer=0)
qm = pmv.plot_array(strhc1)
plt.colorbar(qm)
plt.show()
```
