### ISSUE TITLE
hds.get_kstpkper() returns 0 based kstp,kper while hds.kstpkper returns one based. 

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1338]
hds.get_kstpkper() returns 0 based kstp,kper while hds.kstpkper returns one based. 
hds = fp.utils.binaryfile.HeadFile(r"my.hds")

Is there a good reason for this? If not I would think both should be 0 based like most other stuff in flopy?

**Comment by wpbonelli** [comment]
Discussed briefly in #2000, may eventually consider deprecating 1-based attributes more comprehensively, for now just clarified the docstrings
