### ISSUE TITLE
ci: failure of t074_test_geospatial_util.py with pyshp 2.2.0

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#1346]
The latest version of pyshp (2.2.0 - released 2/2/2022) causes failure of t074_test_geospatial_util.py

@jlarsen-usgs or @mwtoews any interest in tackling this issue. I have updated the `requirements.txt` and `environment.yml` files to use the previous version as a temporary fix.

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs 

I can investigate this issue.

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs 
In pyshp 2.2.0 polygon vertices are sorted in the opposite direction as pyshp < 2.2.0. I'm checking through the code to make sure that this doesn't have any unintended consequences for the shapefile or plotting utilities and putting together a patch for `t074_test_geospatial_util.py`.
