### ISSUE TITLE
MODPATH: internal array gets confused for an external array

### ISSUE THREAD

**Issue by bdestombe** [modflowpy/flopy#136]
My goal is to store variables as internal arrays in the mpbas, mpsim files. However, Util_array keeps on thinking that I want  to store them as external arrays. Since there is a lot of inheriting of parent model structures / package models, this got quite confusing. There are two issues with this and I have been able to create a minimal (not) working example of one of these issues. The other issue is related to loading packages, in that case when you'd run them afterwards the arrays are written as external files, but I have not been able to exactly pinpoint that issue.

MWE: https://gist.github.com/bdestombe/6665d036dca7409f96343c1130b2ca04
The MWE not really realistic, there are no stresses, the flow solution doesn't converge etc. But hopefully it works enough to show the error messages. 

In this case a .mpsim file is written and the zone array (Util3D array)  is stored. However for each layer (Util2D array) the entry starts with a unit (a filename pointer) in this case 32, instead of the text INTERNAL.

For the .mpbas file, this is not a problem, since that unit is described in the .mpnam file.

By manually find/replace all the 32's into INTERNAL mp is able to correctly read the arrays.

**Comment by jtwhite79** [comment]
I suspect this is related to the ``BaseModel.array_free_format`` that the ``Modpath`` instance is setting to ``False``.  This tells ``Util2d`` to use the old style unit number control records instead of the keywords (e.g. ``internal``).  You can try resetting it right after you create the ``Modpath`` instance:
``mp = flopy.modpath.Modpath()``
``mp.array_free_format = True``

This util_array stuff is the gift that keeps on giving...

**Comment by bdestombe** [comment]
This is great! Thank you for your quick response. Indeed this did the trick.

I thought/was expecting it was inheriting this property from the modflow model `mf`, but like you said it gets overwritten.

It remains funny though, the same thing is done for MT3D and SEAWAT, but with those modules I have never encountered any of these issues. Both of these modules write the unit instead of `INTERNAL`, because the `.array_free_format` property is also set to `False`. Is it because the units of every package are written to the .nam files and the .mpsim file is the only exception (the entire modflow family is started with a name file, and only a modpath simulation is started with a simulation file which in turn looks for the name file)? 

Cheers!

**Comment by bdestombe** [comment]
Shall we keep this issue open until it ends up in the code?

In the __ init __ of MT3D, seawat and modpath should then be altered such that,
```python
self.array_free_format = False
```
will look like,
```python
# mp and mt3d
if self.__mf is not None:
    self.array_free_format = self.__mf.array_free_format
else:
    self.array_free_format = True

# swt, the mf model is created anyway
self.array_free_format = self.mf.array_free_format
```
