### ISSUE TITLE
The documentation of flopy function definitions are not beginner friendly

### ISSUE THREAD

**Issue by Atreyagaurav** [modflowpy/flopy#1364]
Hello, 

I have recently tried to use flopy to do some groundwater modeling and I'm finding it quite hard to understand what the functions are supposed to be doing, the function names are abbreviated so much that it feels like you already need to be expert or already be comfortable in using modflow to be able to use it. 

Example description (Almost every function I've yet looked at has description like this):
```
ModflowTdis defines a tdis package.
```

Which gives no information however to what that package specifically does. If one more line could be added to all such functions saying something like "tdis package is a Time Discretization package that does ...." then it'd be helpful for people who haven't used modflow before. 

Right now I'm having to guess what it does based on what parameters it takes, since parameters are explained in the docstrings. Since docstrings can be accessed from the code editor itself and we don't have to search or browse through the documentations online to understand the code, I feel like it should be really clear, specially in case like flopy where the function names look like it was taken directly from fortran function names and hence aren't python like.

**Comment by Atreyagaurav** [comment]
@spaulins-usgs  is there any progress on this? Any brach/fork you're working on this.

**Comment by cnicol-gwlogic** [comment]
I see what you're saying to a point. However: I hope this doesn't come across as rude, but if you're using flopy, you're ultimately using modflow. Given this, shouldn't users at least understand modflow (i.e. it's packages and what they do, including your tdis example) before using flopy? If users are not aware of what the tdis package is and does for example, I would suggest reading the modflow manual.

**Comment by spaulins-usgs** [comment]
@Atreyagaurav currently the flopy package documentation is automatically generated from package definition files provided by the MODFLOW-6 developers.  These package definition files currently do not contain general package description information, so flopy only provides a generic sentence describing the package.  The MODFLOW-6 developers are aware of this.  I am not sure if/when descriptions will be added to the definition files, so I recommend for now that you follow @cnicol-gwlogic's suggestion and use the MODFLOW-6 documentation to determine what the packages do.

**Comment by Atreyagaurav** [comment]
@cnicol-gwlogic I can understand your reasoning, though flopy looks like it was made for people who are used to modflow already to automate their tasks, since the library is written in python it'd be great to have a python like documentations. Because I'd assume making a python interface to modflow was supposed to make it easier to use for people.

If I take my example: when a professor introduced me to modflow, and I saw how to use it I gave up immediately because it was different than how I am used to using things, but once I learned about flopy I gave it a go and I really like how it was made. Even if it's not like other python libraries the pythonish syntax and interface was great to have combined with not having to generate the input files manually.

So if someone needs to browse through modflow documentations from the very start then the barrier to entry will be high and you'll have less people willing to try it. I believe if you make flopy easy to use for beginners then at least some fraction of them will venture into modflow docs to learn better anyway.

I do not disagree that one should know modflow better for them to use flopy, but as I said, things that could be done through python would be better to do it through python. I think you might be looking it from a perspective of someone who already knows stuffs about these so you know where to find certain things easily. I for one had really hard time going through modflow docs when flopy wasn't explaining enough and I made do by reading some of the flopy code to try to understand how the parameters I pass were being used.

 @spaulins-usgs 

> currently the flopy package documentation is automatically generated from package definition files provided by the MODFLOW-6 developers.

Does that mean you don't plan to change it from flopy side? You had assigned the issue to yourself so I thought you were working on it. And could you link me to where the package description files are on modflow? also how it was used to auto generate the docs maybe there could be some way to contribute.

**Comment by cnicol-gwlogic** [comment]
Sure @Atreyagaurav - but there is a big difference between understanding "how to use" something and understanding what you are using actually does (i.e. the groundwater science part of it).

**Comment by Atreyagaurav** [comment]
Yes there is a difference, but someone can't go from 0 to 100 in a single day, or you can't expect one to reach 100 and then start to use the tools. The tools should be easy enough to use for beginners so they get to experience it is useful, love it and then learn it better with each use and reach a level where they are comfortable. 

All I'm saying is if you can, or anyone, let's just make it a bit easier to use. To borrow your words, not to be rude but in software engineering field, ask anyone, I can't imagine a sentence "ModflowTdis defines a tdis package." being called useful documentation when it's all there is to describe your class. 

Reminds me of this https://memezila.com/wp-content/Code-comments-be-like-this-is-a-stop-sign-meme-1022.png

I just thought I should mention that here, in case others feel the same, or the developers or anyone else feels like it should be done so they could. And I saw someone self assign it and though "ok, so someone is going to do it", and it has been 2 months and no update so thought I'd ask. In the mean time I did have to jump through modflow docs, and when there was a bug I also had to learn how to write modflow input file and edit it manually after flopy made the files. So it's not that one shouldn't look at modflow at all, it's just that having proper documentation would be one step closer to making it so that you won't have to lose time jumping around. Like there are two classes `flopy.mf6.ModflowGwfrch` and `flopy.mf6.ModflowGwfrcha`, their documentation just says "defines rch/rcha" package. Wouldn't it be better to at least have something meaningful?

**Comment by spaulins-usgs** [comment]
@Atreyagaurav the package definition files can be found here in the flopy distribution:

https://github.com/modflowpy/flopy/tree/develop/flopy/mf6/data/dfn

and here in the MODFLOW-6 distribution:

https://github.com/MODFLOW-USGS/modflow6/tree/develop/doc/mf6io/mf6ivar/dfn

The MODFLOW-6 packages are constantly being updated and new packages added, so flopy was designed to auto-create the documented package and model interfaces based on the dfns provided in the MODFLOW-6 project.  Any implementation of package descriptions in flopy would need to be pulling these descriptions from files from the MODFLOW-6 project.

Sorry about holding onto the issue assigned to myself.  I originally assigned it to myself thinking that the information you wanted was more easily available to flopy.  I have cleared the assignee list.

**Comment by Atreyagaurav** [comment]
@spaulins-usgs  Thank you; I'll have a look at that. And how it is turned to docstrings. I really do hope there is a easy way to add package descriptions in the docstring.

**Comment by jdhughes-usgs** [comment]
@Atreyagaurav We will continue to improve the documentation but this is not something that will have a definite timeline for completion. Thanks for the comments and suggestions.
