### ISSUE TITLE
"dominant" option for flopy.utils.rasters.resample_to_grid?

### ISSUE THREAD

**Issue by wkitlasten** [modflowpy/flopy#1365]
I am resampling a finer resolution raster of categorical data (geologic classification) to my model grid. I use the geologic classification to assign properties, determine observations of interest, etc. It appears the resample_to_grid method is picking up the value at the center of the grid cell (or am I mistaken?), which doesn't necessarily represent the dominant category in the cell (e.g. if the center falls on a gravel channel in the middle of a cell dominated by silt or bedrock).

None of the available interpolation options will work for the categorical data. I can assign properties first and then resample using the "mean" to get an acceptable value for properties. However, I would also like to use the geologic classification to inform potential observation locations (e.g. 100 samples in cells dominated by gravel).

Thoughts on adding a "dominant" option for resample_to_grid?

**Comment by mwtoews** [comment]
The default for `method` is nearest, which typically represents values an the center of the grid cell.

This feature could be implemented using scipy's [mode](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mode.html#scipy.stats.mode), which is similar to GDAL's [mode](https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-r) resample method that "selects the value which appears most often of all the sampled points". It could be implemented [near here](https://github.com/modflowpy/flopy/blob/89af81fbe50c0f086d085067a4323947d0b6ff8c/flopy/utils/rasters.py#L408).

**Comment by jlarsen-usgs** [comment]
@wkitlasten 

I've had adding mode on my list and can implement it. I agree that it would be useful for resampling data sets like geologic data and land cover.
