### ISSUE TITLE
disu package not loading correctly AttributeError: 'NoneType' object has no attribute 'load'

### ISSUE THREAD

**Issue by rosskush** [modflowpy/flopy#1376]
Howdy, 

So this issue seems to be part of the new release 3.3.5, when loading a modflow usg model I am receiving an error 

`    mf = flopy.modflow.Modflow.load('mfusg.nam',version='mfusg',check=True,forgive=False,model_ws=model_ws,load_only=['disu'])
  File "C:\Users\rossk\miniconda3\envs\geopy38\lib\site-packages\flopy\modflow\mf.py", line 809, in load
    dis = disnamdata.package.load(
AttributeError: 'NoneType' object has no attribute 'load'
`

I tried to look back to trace the issue but it seems the `disnamdata.package` object is `NoneType `here:

https://github.com/modflowpy/flopy/blob/3a1d94a62c21acef19da477267cd6fad81b47802/flopy/modflow/mf.py#L808

This does not happen with release 3.3.4.

I would provide the modflow usg files however the project is not yet public.

Thanks!

**Comment by rosskush** [comment]
Actually I went ahead and tested it out with a USG version of freyberg if it helps.

https://github.com/rosskush/usg_freyberg

https://github.com/rosskush/usg_freyberg/blob/741cd3bddf4d6e52c4bafdce20a6610bc1b347f5/load_usg_freyberg.py#L7

**Comment by cnicol-gwlogic** [comment]
Hi,

Try this instead:
mf = flopy.mfusg.MfUsg.load('mfusg.nam',version='mfusg',check=True,forgive=False,model_ws=model_ws,load_only=['disu'])

We restructured the mfusg bits recently.

**Comment by rosskush** [comment]
This works great! Thanks.

This change explains why I had such a hard time following what was going on as I've been reading in usg models like this for several years, but it is a welcomed one!
