### ISSUE TITLE
When coords specific in MF6 dis, why are they not applied to modelgrid object?

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1387]
It seems like when I load a model I need to manually apply the coordinates in the dis to the modelgrid. It seems like the default should be to do this automatically?

sim = flopy.mf6.MFSimulation.load(sim_name="mfsim.nam", sim_ws = r"C:\offline\tb3\cal14",version='mf6', verbosity_level=0)
mdl = sim.get_model('mf6model')
mdl.modelgrid.set_coord_info(xoff = mdl.dis.xorigin.array, yoff = mdl.dis.yorigin.array)

**Comment by jlarsen-usgs** [comment]
@RyanConway91 

What version of FloPy are you using. I just tested this and coordinate information is transferring from the DIS file to the modelgrid as expected in the most recent development version.

Try upgrading to the develop branch and then inspect your modelgrid coordinate information. 
```
pip instal -U l https://github.com/modflowpy/flopy/zipball/develop
```

If this doesn't fix the problem, please reopen the issue and tag me in a comment. Closing the issue for now.
