### ISSUE TITLE
run_model() with local executable 

### ISSUE THREAD

**Issue by briochh** [modflowpy/flopy#1389]
I seem to be unable to run a model using a specific executable (rather than relying on executable on system path). I think we have some conflicting actions in the run_model() method.

For example, if I have a exe version in "relpath/bin/mfexe" and I pass this to the flopy model object:
`m.exe_name = os.path.join("relpath","bin","mfexe")`
the run_model() method checks for the existence of the executable (with some minor trimming/editing if req.) using the shutil.which() method, returning `exe`, but it does this from where python is currently running. 

Oddly, we then pass the original `exe_name` to Popen not the modified `exe`. Either way though I think `exe_name` and `exe` are relative to where python is running. But because we are passing `cwd=model_ws` to Popen I think we need to pass the executable either as an absolute or relative path from `model_ws` right? 

e.g. https://github.com/modflowpy/flopy/blob/e7832c5d8533ca871f0aed8c22b79b7434238252/flopy/mbase.py#L1720
could become `argv = [os.path.relpath(exe, model_ws)]`

Of course, the exe could be passed to `m.exe_name` a path relative to model_ws at the outset, however, the shtuil.which() method in `run_model()` will likely return None as that search is undertaken from where python is running, and not model_ws, and run_model() will throw an exception.

Always nervous about breaking stuff by playing with pathing but I think it would be good to allow more flexibility in exe location and support running exes that that not specifically on the PATH. As always, I might also be missing something!

**Comment by spaulins-usgs** [comment]
@briochh, while I am not 100% sure of the original intention of run_model(), I believe the initial shutil.which() method is just to catch a missing exe error and report a clear user-readable message before Popen is called (Popen will return a more cryptic error message to the end user).

model_ws is just the path argument that the modflow executable takes to find the namefile.  It has nothing to do with determining the executable path.  Relative exe_name paths are allowed, they just are not relative to the model, but relative to your python script.

If you think there is value in supporting exe_name paths relative to the model namefile, I recommend adding code that does not break the existing functionality, but instead tries to find exe_name relative to the model namefile only if the shutil.which() call fails.

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs can you follow up on this. Close if it is resolved.
