### ISSUE TITLE
AttributeError: 'ModflowNwt' object has no attribute 'modelgrid'

### ISSUE THREAD

**Issue by jshultzFSU** [modflowpy/flopy#1392]
Hello I am a new user experiencing some trouble with postprocessing of a created model. I am trying to process results from the North Florida Model (found here https://www.srwmd.org/125/North-Florida-Model-Version-2). This model was created in MODFLOW-NWT. I have been following examples found online but for some reason I get the following error when running my code (bottom). If anyone has any insight to this error I would appreciate it greatly. -Thanks
`Traceback (most recent call last):
  File "C:/Users/jeshu/AppData/Local/Programs/Python/Python39/Scripts/modelfigs.py", line 29, in <module>
    hdobj = flopy.utils.HeadFile(fname, model =nwt)
  File "C:\Users\jeshu\AppData\Local\Programs\Python\Python39\lib\site-packages\flopy\utils\binaryfile.py", line 495, in __init__
    super().__init__(filename, precision, verbose, kwargs)
  File "C:\Users\jeshu\AppData\Local\Programs\Python\Python39\lib\site-packages\flopy\utils\binaryfile.py", line 282, in __init__
    super().__init__(filename, precision, verbose, kwargs)
  File "C:\Users\jeshu\AppData\Local\Programs\Python\Python39\lib\site-packages\flopy\utils\datafile.py", line 189, in __init__
    self.mg = self.model.modelgrid
AttributeError: 'ModflowNwt' object has no attribute 'modelgrid'`
(my code_
`#run results for NF Model -Flopy

import sys
import os
import platform
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import shapefile
import flopy
import flopy.utils.binaryfile as bf
import pandas as pd

#load mf model

modelname = "test5_nwt_ref_corr_dis.nam"
modelpath = 'D:\\NFRUNS\\cmd_run2'
#Modflow Nwt -this works
mf1 = flopy.modflow.Modflow('test5_nwt_ref_corr_dis',
                            exe_name="D:\\NFRUNS\\MODFLOW-NWT_1.2.0\\MODFLOW-NWT_1.2.0\\bin\\MODFLOW-NWT.exe",
                            version="mfnwt",model_ws=modelpath)
nwt = flopy.modflow.ModflowNwt(mf1)

#Import model -error loading-
#ml = flopy.modflow.Modflow.load('D:\\NFRUNS\\cmd_run2\\test5_nwt_ref_corr_dis.nam', version = 'mfnwt')

#extract heads
fname ='D:\\NFRUNS\\cmd_run2\\test5.hds'
hdobj = flopy.utils.HeadFile(fname, model =nwt)
times = hdobj.get_times()
head = hdobj.plot(totim=times[-1],
                  masked_values=[-9999.0],
                  colorbar=True)
`

**Comment by jlarsen-usgs** [comment]
@jshultzFSU 

The reason you are not seeing an modelgrid on the `flopy.modflow.ModflowNwt()` object, is becasue this object creates a newtonian solver package. 

Remove the line `nwt = flopy.modflow.ModflowNwt(mf1)` unless your intention is to replace the existing solver.

To get your modelgrid object, use
```
modelgrid = mf1.modelgrid
```
