### ISSUE TITLE
NO GRB FILE SPECIFIED Error in ZoneBudget model obtained from gwf.output.zonebudget() 

### ISSUE THREAD

**Issue by Atreyagaurav** [modflowpy/flopy#1395]
So assuming the example in github readme with the basic model is run (you can insert contents from here at the end), a simple zonebudget model from the output of the gwf model doesn't run successfully.

Suppose this is my zonebudget model with few zones.
```python
import numpy as np


zones = np.ones((10, 10), dtype=int)
zones[(1, 1)] = 2
zones[(2, 2)] = 2
zones[(7, 7)] = 3
zones[(8, 8)] = 3

bm = gwf.output.zonebudget(zones)
bm.change_model_name(name)
bm.change_model_ws(ws)
bm.write_input() # I believe the problem is in this implementation.
bm.run_model(exe_name='modflow-zbud6') # error comes here.
print(bm.get_budget())
```

Gives following output:

```
FloPy is using the following executable to run the model: /usr/local/bin/modflow-zbud6
                              ZONEBUDGET Version 6
                             U.S. GEOLOGICAL SURVEY
                            VERSION 6.2.2 07/30/2021

ERROR REPORT:

  1. BUDGET FILE HAS "FLOW-JA-FACE" RECORD BUT NO GRB FILE SPECIFIED.
  2. ADD GRB ENTRY TO ZONE BUDGET NAME FILE.
```

The contents of `.zbnam` file written are like this:
```
BEGIN ZONEBUDGET
  ZON   01_git_ex.zon
  BUD   01_git_ex.bud
END ZONEBUDGET
```

But if I manually edit the content to:

```
BEGIN ZONEBUDGET
  ZON   01_git_ex.zon
  BUD   01_git_ex.bud
  GRB   01_git_ex.dis.grb
END ZONEBUDGET
```

And comment out the line with `save_inputs()` and run the model (or just the last `bm.run_simulation()`), then it runs fine and outputs the zonebudget. 

Looking at these two variables I think the problem is it is using package_dict to write zbnam, but I couldn't find the code where it was writing those files to test further.
```
>>> bm.package_dict
{'zon': <flopy.utils.zonbud.ZoneFile6 object at 0x7f38a272ada0>, 'bud': <flopy.utils.binaryfile.CellBudgetFile object at 0x7f38a272a920>}
>>> bm.zbnam_packages
{'zon': <class 'flopy.utils.zonbud.ZoneFile6'>, 'bud': <class 'flopy.utils.binaryfile.CellBudgetFile'>, 'grb': <class 'flopy.mf6.utils.binarygrid_util.MfGrdFile'>}
```

**Comment by langevin-usgs** [comment]
@jlarsen-usgs, can you take a look at this?  Seems like it should be something simple.  I confirmed with the example on the main flopy repo page that GRB doesn't get added to the name file.

**Comment by jlarsen-usgs** [comment]
@langevin-usgs I'll take a look at this sometime today.

**Comment by langevin-usgs** [comment]
@Atreyagaurav, thanks for pointing this out.  It should be fixed now thanks to @jlarsen-usgs.

**Comment by Atreyagaurav** [comment]
I've tried it on a new version installed directly from github with `pip install --upgrade git+https://github.com/modflowpy/flopy.git` and I can confirm it works now. Thank you.

**Comment by haugwitz** [comment]
Will this be in 3.3.6? 

I have the same issue and I am manually fixing the .zbnam file before running.

**Comment by Atreyagaurav** [comment]
@haugwitz  if you're doing it for your personal projects then you can install the github/dev branch from the command I wrote in my previous comment. That way you don't have to manually edit it.

**Comment by langevin-usgs** [comment]
Yes, this issue has already been fixed by @jlarsen-usgs.  As mentioned by @Atreyagaurav, the fix is available on our develop branch.
