### ISSUE TITLE
Correction to MFListBudget.get_dataframes() example snippet

### ISSUE THREAD

**Issue by wzell-usgs** [modflowpy/flopy#1398]
The example code at the top of https://flopy.readthedocs.io/en/3.3.5/source/flopy.utils.mflistfile.html suggests that the tuple of dataframes returned by .get_dataframes() is (inflows, outflows) rather than (incremental, cumulative) as shown later down on the docs page.

![image](https://user-images.githubusercontent.com/16402586/164246819-5c60fa91-8632-4e23-8bc8-5f791cbf9400.png)

**Comment by jlarsen-usgs** [comment]
@wzell-usgs 

Thanks for pointing this out. I'll update the docstrings for this so the documentation reflects incremental and cumulative dataframes.
