### ISSUE TITLE
3.3.5: addition of `.\` in front of package files in NAM files

### ISSUE THREAD

**Issue by kallejahn** [modflowpy/flopy#1402]
When run on Windows, flopy 3.3.5 places a `.\` in front of package files in MF6 `gwf.nam` and `gwt.nam` files (e.g. `DIS6  .\gwf.dis  dis`). Flopy 3.3.4 does not have the `.\`, so I'm guessing the addition has something to do with fixes made to relative paths? 

The added `.\` becomes an issue when running the Windows-generated models on a Linux cluster. Is there a new keyword that I've missed that allows us to turn off the addition of `.\`?

**Comment by langevin-usgs** [comment]
@spaulins-usgs were you going to look into this?

**Comment by spaulins-usgs** [comment]
@kallejahn this issue was fixed a couple of weeks ago as part of PR #1394.  Please try using the latest develop branch of flopy.  Note that PR #1394 also has some interface-breaking changes for sub-packages (documented in the comments of the PR), so you may need to modify your code slightly.

**Comment by kallejahn** [comment]
@spaulins-usgs Okay thanks, I'll start using the develop branch. Appreciate it!
