### ISSUE TITLE
Does this package support the mf2005 Conceptual Modeling method to model groundwater?

### ISSUE THREAD

**Issue by scchhh3** [modflowpy/flopy#1412]

**Comment by jlarsen-usgs** [comment]
@scchhh3 
This software supports mf2005. The online documentation contains tutorials that can help get you started [https://flopy.readthedocs.io/en/3.3.5/_notebooks/tutorial01_mf.html](https://flopy.readthedocs.io/en/3.3.5/_notebooks/tutorial01_mf.html)
