### ISSUE TITLE
question about conductance calculation in Tutorial02 

### ISSUE THREAD

**Issue by FHDeng** [modflowpy/flopy#142]
Hi,

I have a question about the conductance calculation in example Tutorial02. In the MODFLOW-2005 manual (chapter 5. Internal Flow Packages 5-5), in unconfined layer, when computing saturated thickness (Δv):

if HNEW >= TOP, Δv = TOP - BOT;
if TOP > HNEW > BOT, Δv = HNEW - BOT;
if HNEW <= BOT, Δv = 0.

In the Tutorial02 example, both stageleft and stageright are >= TOP. I am wondering why in the code, e.g., "condleft = hk \* (stageleft - zbot) \* delc" instead of "condleft = hk \* (ztop - zbot) \* delc"?

**Comment by langevin-usgs** [comment]
Yes, you are right.  It looks like we should set ztop to 10 so that the model is unconfined.  We'll leave this issue open until it is fixed in the next release.

**Comment by oscarfasanchez** [comment]
but nothing has changed in the tutorial, right?

**Comment by langevin-usgs** [comment]
Yes, the tutorial was changed April 2017 so that ztop is 10, which means the aquifer is unconfined.
