### ISSUE TITLE
How to provide ModflowGwfrcha() Module  with Aux Variable as Dictionary?

### ISSUE THREAD

**Issue by michelob23** [modflowpy/flopy#1421]
I am building a transport model and prescribing concentrations as an auxiliary variable with the RCH package. I can provide recharge to the ModflowGwfrcha() module as a dictionary with stress periods as keys. However, when I use the same structure with the auxiliary variable (concentration), I get an error. 

This works:
rch = flopy.mf6.ModflowGwfrcha(
    gwf,
    readasarrays=True,
    recharge=rch_dict,
    pname='rch'
)

This does not:
rch = flopy.mf6.ModflowGwfrcha(
    gwf,
    readasarrays=True,
    recharge=rch_dict,
    pname='rch',
    auxiliary=['conc'],
    aux={'conc': conc_dict},
)
KeyError: 'data'

This does not:
rch = flopy.mf6.ModflowGwfrcha(
    gwf,
    readasarrays=True,
    recharge=rch_dict,
    pname='rch',
    auxiliary=['conc'],
    aux=conc_dict,
)
(1) Unable to set data for aux variable. Expected 2 aux variables but got 218.
(2) Error occurred while adding dataset "aux" to block "period"

Perhaps more detailed documentation about the data input requirements/options for AUX variables on this page would help: https://flopy.readthedocs.io/en/3.3.5/source/flopy.mf6.modflow.mfgwfrcha.html

Alternatively, will there ever be Flopy support for Stress Package Concentration "SPC" input files?

**Comment by langevin-usgs** [comment]
Yes, this is a bit complicated.  Here is an example below, which was taken from here (https://github.com/MODFLOW-USGS/modflow6/blob/a185d95b91985e965f8a04ae353305dff19b9637/autotest/test_gwt_ssm05.py#L132).  The trick is that the aux data must be provided as a dictionary with the key equal to stress period and the value equal to a list with one entry for each aux variable.

```
    # array-based rch file
    recharge_rate = np.arange(nrow * ncol).reshape((nrow, ncol))
    recharge_concentration = np.arange(nrow * ncol).reshape((nrow, ncol))
    auxiliary = [("auxvar1", "auxvar2")]
    aux = {0: [[50.0], recharge_concentration]}
    rch2 = flopy.mf6.ModflowGwfrcha(
        gwf,
        print_flows=True,
        recharge=recharge_rate,
        pname="RCH-1",
        filename=f"{gwfname}.rch",
        auxiliary=auxiliary,
        aux=aux,
    )
```

Also, SPC should be supported now, though you may need the develop version of FloPy.  An example for SPC with FloPy is here (https://github.com/MODFLOW-USGS/modflow6/blob/a185d95b91985e965f8a04ae353305dff19b9637/autotest/test_gwt_ssm04.py#L291).

Hope this helps.  Will close the issue, but feel free to reopen or ask questions if you run into trouble.

**Comment by michelob23** [comment]
Excellent, thank you!
