### ISSUE TITLE
Problem assigning array to LPF package in MFUSG

### ISSUE THREAD

**Issue by javgs-bd** [modflowpy/flopy#1427]
I'm testing the following code from a notebook located in the Notebooks folder, and am getting the following error.
Basically, I'm loading the model, getting the hk array from the lpf package and then trying to assign that very same array to build the package again. If I understand well the error message, there is a problem with the shape of the array expected by the LPF package. 

I got this error originally when trying to assign a custom built array to the lpf package.

````
import os
import numpy as np
import flopy

#--------------------------------------------
#    Set model root name and working folder
#--------------------------------------------
    
model_name     = 'freyberg.usg.nam'
model_folder   = '../data/freyberg_usg'

#-----------------------------------------------------
#  Create MODFLOW object by loading the model 
#-----------------------------------------------------

gwf = flopy.mfusg.MfUsg.load(
                                   model_name,
                                   version       = 'mfusg', 
                                   model_ws      = model_folder, 
                                   )

print(gwf.get_package_list())

lpf          = gwf.get_package('lpf')
hk_array    = lpf.hk.array

print(hk_array)
print(hk_array.shape)

lpf     = flopy.mfusg.MfUsgLpf(
                                gwf,
                                hk         = hk_array,
                              )
````

![image](https://user-images.githubusercontent.com/74055695/172754024-b5c5c353-ccd6-4f3e-8021-b019a6235cb4.png)

**Comment by cnicol-gwlogic** [comment]
@javgs-bd - good question, it's not easy. It is caused by the .array call returning a flattened array for an unstructured model (i.e. all nodes in the model are in that array, and that array has shape [nodes] - ie it is as long as all nodes in the model, because most unstructred (mfusg) models would probably have a different number of nodes per layer, and so a jagged array by layer, which numpy / flopy won't easily handle. 

This is the easiest way I can think of offhand to get around it (there are other ways to do it without util2ds (which have rapidly increasing noticeable overhead for bigger arrays)):
```python
m = flopy.mfusg.MfUsg.load("freyberg.usg.nam", model_ws='freyberg_usg',
                               verbose=True, forgive=True, check=True)

hk = m.lpf.hk

new_hk = []
for (k, k_array) in enumerate(hk):
    print(k, k_array.shape)
    new_hk.append(k_array)
    # modify your util2d object's values' first 2 elements
    new_hk[-1][:,:2] = 999.9

lpf = flopy.mfusg.MfUsgLpf(m, hk=new_hk) 
# check the new 999.9 values are in there:
for (k, k_array) in enumerate(lpf.hk):
    print(k, k_array.array[:10])
```
I should probably add something specific to mfusg models in the various packages' modules to deal with this without user intervention.

**Comment by cnicol-gwlogic** [comment]
@javgs-bd sorry I just realised I didn't answer your question very directly. Try this approach instead:
```python
import numpy as np
import flopy


m = flopy.mfusg.MfUsg.load("freyberg.usg.nam", model_ws='freyberg_usg',
                               verbose=True, forgive=True, check=True)

print(m.lpf.hk.array.shape)
array_k_node_to = np.cumsum(m.disu.nodelay.array)
array_k_node_from = np.insert(
    arr=array_k_node_to[:-1],
    obj=0, values=[0])

print(array_k_node_from, array_k_node_to)

custom_array = np.ones(shape=[m.disu.nodes])
print(custom_array.shape)
# <or hk_array = lpf.hk.array # <-- flattened array m.disu.nodes long>
new_hk = []
for k, (k_node_from, k_node_to) in enumerate(
    zip(array_k_node_from, array_k_node_to)):
    print(k, k_node_from, k_node_to)
    custom_array[k_node_from:k_node_to] = float(k + 1)
    new_hk.append(custom_array[k_node_from:k_node_to].copy())

lpf = flopy.mfusg.MfUsgLpf(m, hk=new_hk)
for (k, k_array) in enumerate(lpf.hk):
    print(k, k_array.array[:10])
```

**Comment by javgs-bd** [comment]
Ok, thanks. I'll keep an eye on the packages that could be using flattened or jagged 3d lists. I guess the disu package would go into that list too (top & botm).

**Comment by cnicol-gwlogic** [comment]
@javgs-bd - this should hopefully be sorted via PR #1429
