### ISSUE TITLE
little errors importing old MODFLOW models from visual modflow

### ISSUE THREAD

**Issue by vcantarella** [modflowpy/flopy#1433]
Hi,

I am working with a visual modflow nwt model and I encountered subtle differences in how visual modflow writes some packages that crash the import from flopy. Interestingly, these models run just fine with the standard executable. I am not sure if it is of interest to flopy to be able to read these, but they might be found in many more models out there.

First, in the UPW file, visual modflow has written the first line like this:
`       154 -1.00e+30         0 `
And flopy is expecting the input like this:
` [IUPWCB HDRY NPUPW IPHDRY] `
Otherwise, it is expecting the IPHDRY value, so it crashes. From the manual, I thought the parameter is mandatory, but the model runs just fine.

Second, in the ZON file from the zone-budget. It has written the last line with a
`0`
This crashes the loop in the flopy code as it is either expecting a layer definition line or the zone values. Again, when I run the zone-budget executable with this file it runs just fine. 

In both cases, from reading the source code and identifying where it was crashing, I was able to edit the modflow files to import the model, however, I don't know if you find it interesting to be able to support those little changes or not. Visual MODFLOW has also their packages and if the user does not edit the `.nam` file it cannot be imported into flopy anyway.

**Comment by jlarsen-usgs** [comment]
@vcantarella 

I'm not able to recreate with `iphdry` with modflow-nwt version 1.3.0. When I remove the `iphdry` entry from the UPW input file modflow-nwt crashes while attempting to load that line. What version of nwt are you working with?

**Comment by vcantarella** [comment]
@jlarsen-usgs 
I am running Version 1.2.0 03/01/2020. I believe that is also the latest here: [executables-repo](https://github.com/MODFLOW-USGS/executables)

**Comment by jlarsen-usgs** [comment]
@vcantarella 
I just tested this with Version 1.2.0 03/01/2020 and can't reproduce a run. On windows, UPW read crashes for me when `iphdry` is omitted from the UPW file, in addition, I don't see anywhere in the source code that would allow. What operating system are you using?

**Comment by wpbonelli** [comment]
is this issue still present @vcantarella @jlarsen-usgs or has it been resolved?

**Comment by vcantarella** [comment]
Hi @wpbonelli, Thanks for looking into it. To be honest, I don't remember how I dealt with this. I now view this as not a flopy error, but It is related how an old software wrote the MODFLOW files. Skimming through the official manual, I have come to think that the file had been written wrongly.  Thus, I believe that it is not something worth pursuing and my opinion would be to close this issue.

**Comment by wpbonelli** [comment]
Ok, sounds good @vcantarella, thanks for the update. Please feel free to reopen if needed.
