### ISSUE TITLE
ListBudget doesn't get time accurately

### ISSUE THREAD

**Issue by hjia1005** [modflowpy/flopy#1435]
Hi,

I am trying to extract the length of time step from the model list file. It has a total of 418 timesteps. 
lst_file='model.lst'
mfl = flopy.utils.MfListBudget(lst_file)
times=mfl.get_times()
The extracted times are accurate for the first 303 timesteps, but from the 304th timestep, it shows integer days, which are not consistent with the list file.

However, for some other list files, the extract times are correct for the full timesteps. Can't figure out what could be the reason. I attached the model list file for you to check.

Thanks!
[model.zip](https://github.com/modflowpy/flopy/files/8988513/model.zip)

**Comment by hjia1005** [comment]
Thanks for your reply. I need to use the function mfl.get_times() to calculate the time step length since there is no existing function for that. However, because of the predefined width in the list file, 'TOTAL TIME' is rounded to an integer from  sp28 ts6 because the number of days reaches five digits. See below.

![image](https://user-images.githubusercontent.com/33449394/176054141-4ac9e22f-3c37-4de3-b540-8a13666c19b0.png)

I will write some code to extract the length of each time step for now. I would suggest a new function such as get_ts_length() to be added to the ListBudget Class. When ATS is used, we could only get the timestep length from the model output other than predefined time steps. It is very often used to generate the average flow rate per stress period.

Thanks again for all your hard work.

**Comment by spaulins-usgs** [comment]
@hjia1005, I added a get_tslens method to flopy.utils.MfListBudget which returns a list of time step lengths as read from the listing file.  While these time step lengths have to the same five digit output, they are smaller numbers than total time and will therefore provide more precision.  If you want to use get_tslens, the updated flopy code has been merged to the develop branch.

**Comment by hjia1005** [comment]
@spaulins-usgs Thanks!
