### ISSUE TITLE
Loading MNW2 - Error: list index out of range

### ISSUE THREAD

**Issue by emiliakrakowska** [modflowpy/flopy#1448]
I was able to import an existing Modflow-NWT model ".nam" file, wrote the input files and ran the model. The simulation time was normal. After that I also imported separately the MNW2 file and it was correct, however later I cannot import for the second time where it says "list index out of range". Even the ".nam" file is not writing the input files (shutting down on MNWI). Can you suggest why?
 MNW2 import code:
import sys
import os
import flopy

print(sys.version)
print("numpy version: {}".format(np.__version__))
try:
    print("pandas version: {}".format(pd.__version__))
except:
    pass
print("flopy version: {}".format(flopy.__version__))

mfexe = 'mfnwt'
if platform.system() == 'Windows':
    mfexe += ".exe"

modelname = "mis"
mis_import = flopy.modflow.Modflow(modelname, model_ws = cpth)
mnw2pth = os.path.join("mis.mnw")
mnw2 = flopy.modflow.ModflowMnw2.load(mnw2pth, mis_import)

**Comment by jdhughes-usgs** [comment]
@emiliakrakowska Have you tried to load the entire model `flopy.modflow.Modflow.load()`? You can load specific package with this method but the `DIS` and `BAS` packages should always be loaded since they define the spatial and temporal discretization. Let us know if this does not resolved the issue.

**Comment by emiliakrakowska** [comment]
thank you very much! MNW2 was successfully imported once DIS file was loaded first. Another issue is with writing the input files.I am trying to run an existing MF-NWT model on Flopy. Although "nam" file is imported, writing input files crashes always on MNWI. With existing models is it necessary to write input files? I can run the model normally, but list file is coming really huge. Can you suggest what can I do?

MNWI data:
80 82 81
