### ISSUE TITLE
Output control in version 3.2.5 for Seawat

### ISSUE THREAD

**Issue by JoerivanEngelen** [modflowpy/flopy#145]
I just updated to version 3.2.5 and I think I noticed a bug in the output control. 

In the script that worked for version 3.2.4, I used this code (simplified here):

```
mf = flopy.modflow.Modflow(input)
mswt = flopy.seawat.Seawat(input)
oc = flopy.modflow.ModflowOc(mf)
```

After updating to version 3.2.5, this did not work anymore. It would not save my heads and cbc's etc.
To let it work properly, I instead had to change the code to:

```
mf = flopy.modflow.Modflow(input)
mswt = flopy.seawat.Seawat(input)
oc = flopy.modflow.ModflowOc(mswt)
```
Is this on purpose, or just a bug?

**Comment by langevin-usgs** [comment]
This is on purpose.  3.2.5 had major changes to the underlying SEAWAT structure (see the release notes).  Now, the way it works is that you add all packages (both modflow and mt3d) directly to the seawat model.
