### ISSUE TITLE
GridIntersect.intersect error with polygons

### ISSUE THREAD

**Issue by oscarfasanchez** [modflowpy/flopy#1461]
Hello, I updated Flopy to the develop version 3.3.6(from 3.3.4) to work with the ATS package ( due to this issue https://github.com/modflowpy/flopy/issues/1426), but now the GridIntersect.intersect() function doesn't work well.

this is my code:

import  shapefile as SF

gravoso=sf.Reader(path_sh+"/Superficies/Cont_Qbg2.shp")
gravoso1=gravoso.shapeRecords()[0]
firstkg=gravoso1.shape.__geo_interface__
shp_geomkg=shape(firstkg)

gwf.modelgrid.plot()
ix = GridIntersect(gwf.modelgrid, method="structured", rtree=False)

resultkg= ix.intersect(shp_geomkg)
and shows the following error.

Traceback (most recent call last):

  File "<ipython-input-2-f81d89bae0ae>", line 1, in <module>
    resultkg= ix.intersect(shp_geomkg)

  File "C:\Users\Oscar\.conda\envs\pest\lib\site-packages\flopy\utils\gridintersect.py", line 241, in intersect
    rec = self._intersect_polygon_structured(shp)

  File "C:\Users\Oscar\.conda\envs\pest\lib\site-packages\flopy\utils\gridintersect.py", line 1402, in _intersect_polygon_structured
    rec.ixshapes = ixshapes

  File "C:\Users\Oscar\.conda\envs\pest\lib\site-packages\numpy\core\records.py", line 506, in __setattr__
    return self.setfield(val, *res)

  File "C:\Users\Oscar\.conda\envs\pest\lib\site-packages\shapely\geometry\polygon.py", line 300, in __array_interface__
    raise NotImplementedError(

NotImplementedError: A polygon does not itself provide the array interface. Its rings do.
I show the shape of my file in case it's the source of the problem
![image](https://user-images.githubusercontent.com/39230212/180468329-9a0f50f3-6604-493a-baea-4c1b61d1a02e.png)

**Comment by dbrakenhoff** [comment]
I'll look into this. I can't run it myself now, but does the problem also occur with `method="vertex"`?

It might also be a package version issue related to shapely? Which version of shapely are you on?

**Comment by oscarfasanchez** [comment]
Thanks, yes, it fails too with "vertex"
my shapely version is 1.7.1 (now and before when it worked with floppy 3.3.4)

**Comment by dbrakenhoff** [comment]
Hi @oscarfasanchez, it might be related to this issue between shapely and numpy: https://github.com/shapely/shapely/pull/1174.

Can you try upgrading Shapely and see if that solves the problem?

**Comment by oscarfasanchez** [comment]
yes, it worked! thanks
