### ISSUE TITLE
VTU scallars are distorted

### ISSUE THREAD

**Issue by oscarfasanchez** [modflowpy/flopy#1466]
Hello, I'm exporting a VTU file of heads
using  the following code

        vtkobj = vtk.Vtk(gwf, xml=True, pvd=True, vertical_exageration=1, point_scalars=True)
        vtkobj.add_heads(hds, kstpkper=kstpkper, masked_values=masked_values)
        vtkobj.write(os.path.join(pv_folder, "heads_output_test", "heads_scal.vtu"))

but I noticed that the data was distorted in the boundaries, I think scalars were interpolated with nan values(assuming nan as zeros I guess)

cells
![image](https://user-images.githubusercontent.com/39230212/180829992-94e6fdf1-4769-4d1c-bfe7-b88493a0ab76.png)

scallars points
![image](https://user-images.githubusercontent.com/39230212/180829622-a4ace766-d651-4d34-9d83-70ea165b87fc.png)

**Comment by jlarsen-usgs** [comment]
@oscarfasanchez 

I'll take a look at this issue.

**Comment by jlarsen-usgs** [comment]
@oscarfasanchez 

Just opened a pull request that fixes errant interpolation for point scalars. The issue was with checking cellids to assure that they are 1) in the active domain and 2) not a user supplied masked_value
