### ISSUE TITLE
Modflow external_path

### ISSUE THREAD

**Issue by w-bonelli** [modflowpy/flopy#1472]
Currently the `external_path` argument to `Modflow` is assumed to be [relative to the model workspace](https://github.com/modflowpy/flopy/blob/1757470fe0dd28ed6c68c95950de877bd0b4a94b/flopy/modflow/mf.py#L159). Absolute paths are not currently supported:

https://github.com/modflowpy/flopy/blob/5d0f5857d5ca5d5a92ad9207e0d8340acc214afa/autotest/test_modflow.py#L633

https://github.com/modflowpy/flopy/blob/5d0f5857d5ca5d5a92ad9207e0d8340acc214afa/autotest/test_modflow.py#L696

Are external paths understood to be relative to (hence under) the model workspace by definition? Or should absolute paths & external locations be supported as well?

**Comment by spaulins-usgs** [comment]
@w-bonelli, external_path is suppose to be a relative path.  In flopy for mf6, external files are based on relative paths, and I think the original flopy (for mf2005) is similar.  Note that the relative path does not have to be under the model workspace, you should be able to define a relative path outside the model workspace using "..".

You mentioned that external_path fails if set to anything but ".".  I see several test cases where external_path is initialized to something other than ".".  Are you able to set external_path to something other than "." in the model constructor?  Or does the problem only occur when changing external_path after the model has been constructed?

**Comment by w-bonelli** [comment]
Sorry @spaulins-usgs, I checked again and I was wrong, relative paths do generally work. Not just `.`

Removing these comments in #1522
