### ISSUE TITLE
How to make flopy aware that it is running on a linux system?

### ISSUE THREAD

**Issue by joha1** [modflowpy/flopy#148]
When I try to run the example model from [this paper](http://onlinelibrary.wiley.com/doi/10.1111/gwat.12413/full), the last `model.run_model()` results in a `Exception: The program mf2005.exe does not exist or is not executable.` error, just like [here](https://github.com/modflowpy/flopy/issues/42).
Well, of course `mf2005.exe` does not exist on a linux system.
However, `mf2005` without the exe does, and seems to run, when I enter it at a konsole, and also `echo $PATH` lists the folder where I have it compiled.
So, how do I make flopy aware of this fact?

_side note: searching for flopy and linux is kinda fun since google of course insists that I meant "floppy", and even when I tell it that I really mean "flopy", I still get mostly results about how to make a bootable flopy disk…_

**Comment by langevin-usgs** [comment]
All you need to do is pass the name of the modflow binary to the Modflow model constructor.  The default is exe_name='mf2005.exe', but you can change that to whatever you want.  We should probably remove the .exe from this default argument.


class Modflow(BaseModel):
    """
    MODFLOW Model Class.
    Parameters
    ----------
    modelname : string, optional
        Name of model.  This string will be used to name the MODFLOW input
        that are created with write_model. (the default is 'modflowtest')
    namefile_ext : string, optional
        Extension for the namefile (the default is 'nam')
    version : string, optional
        Version of MODFLOW to use (the default is 'mf2005').
    exe_name : string, optional
        The name of the executable to use (the default is
        'mf2005').
    listunit : integer, optional
        Unit number for the list file (the default is 2).
    model_ws : string, optional
        model workspace.  Directory name to create model data sets.
        (default is the present working directory).
    external_path : string
        Location for external files (default is None).
    verbose : boolean, optional
        Print additional information to the screen (default is False).
    load : boolean, optional
         (default is True).
    silent : integer
        (default is 0)

**Comment by joha1** [comment]
I suppose that is to be done in `mbase.py`?
I changed it in the `exe_name='mf2005.exe` line, but there is also some stuff from line 904 on:

    exe = which(exe_name)
    if exe is None:
        import platform
        if platform.system() in 'Windows':
            if not exe_name.lower().endswith('.exe'):
                exe = which(exe_name + '.exe')
    if exe is None:
        s = 'The program {} does not exist or is not executable.'.format(
            exe_name)
        raise Exception(s)

I'm not familiar with `platform`, but that seems like the reason why it wont work, when I simply change the above mentioned `exe_name` line.

**Comment by joha1** [comment]
As a workaround, I'm simply running modflow outside of ipython (`mf2005 gwexample.nam` in bash), however, that leads to the next issues: It can't create the hds file.
```
 *** ERROR OPENING FILE "gwexample.hds" ON UNIT    51
       SPECIFIED FILE STATUS: REPLACE
       SPECIFIED FILE FORMAT: BINARY              
       SPECIFIED FILE ACCESS: SEQUENTIAL          
       SPECIFIED FILE ACTION: READWRITE           
  -- STOP EXECUTION (SGWF2BAS7OPEN)
```
At first it seemed unrelated, but this is solved here: https://github.com/modflowpy/flopy/issues/11
The post by @Kirubaharan gives the helpful advice

> In makefile, use `F90= gfortran` .
>In openspec.inc
>change `DATA ACCESS/'SEQUENTIAL'/` to `DATA ACCESS/'STREAM'/`
>change `DATA FORM/'BINARY'/` to `DATA FORM/'UNFORMATTED'/`

for compiling mf2005. I am aware that this is not strictly a flopy issue, but couldn't information like this be a helpful addition to the instructions?

**Comment by mbakker7** [comment]
I don't think Chris asked you to change the code. What you need to do is when you define the model, you need to specify where your modflow executable is located and what it is called. For example: 
     
     ml = mf.Modflow(modelname='my_model', exe_name='/bin/mf2005')

**Comment by langevin-usgs** [comment]
Regarding the issue with compiling MODFLOW, it is also worth mentioning the pymake package (https://github.com/modflowpy/pymake).  There are python scripts in that package for compiling some of the different flavors of MODFLOW.  The script will automatically use the STREAM ACCESS approach for binary files.

**Comment by joha1** [comment]
> ` ml = mf.Modflow(modelname='my_model', exe_name='/bin/mf2005')`

Good to know! Seems to work perfectly. I was just jumping into the file referenced in the error message, but this seems to be the more obvious solution.

>(https://github.com/modflowpy/pymake)

That's very helpful!

**Comment by lososian** [comment]
Running to a similar issue here on tutorial 1. I know some of the keywords have changed since this issue was opened. Using a mf2005 file built by pymake. Running in to TypeError, looking to implement what was suggested by @mbakker7  
```
modelname= 'tutorial1'
mf = flopy.modflow.Modflow(modelname, exe_name='mf2005')
model = mf.Modflow(modelname, exe_name='/media/chrx/UNTITLED/Documents/FloPy/modflow/temp/mf2005')

```

**Comment by hammytheham** [comment]
Concur with @spencerbh, executable **does not work** when located on external disk. I put my executable in an applications folder called mf2005 and set ml = mf.Modflow(modelname='my_model', exe_name='/Applications/mf2005/mf2005') . Python scripts work on external.

**Comment by loukika** [comment]
m1= mf.Modflow(model='name', exe_name='C:\Program Files (x86)\QGIS 2.14\apps\Python27\Lib\site-packages\pymake\mf2005')
m1.run_model()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\site-packages\flopy\mbase.py", line 898, in run_model
    normal_msg=normal_msg)
  File "C:\PROGRA~2\QGIS2~1.14\apps\Python27\lib\site-packages\flopy\mbase.py", line 1285, in run_model
    raise Exception(s)
Exception: The program C:\Program Files (x86)\QGIS 2.14pps\Python27\Lib\site-packages\pymake\mf2005 does not exist or is not executable. 


where should i keep the path for executing modflow??

**Comment by langevin-usgs** [comment]
There are lots of different ways to do this, but here is what I recommend for Windows users.  The general concept can also be adapted for other OS's.  

I would create a folder somewhere under your user account, and I would call that folder "bin".  I would then put mf2005.exe in that bin folder.  You could also put modpath, seawat, mfnwt, etc., and any other executables that you would like to access, into that bin folder.

The next step is to add the path of this new bin folder to your environment variable called "Path".  On Windows 10, you can just start typing environment variables in the search bar and you should be able to find it.  

![image](https://user-images.githubusercontent.com/3372403/32657475-e3d602ba-c5e3-11e7-879d-a2f838bdd071.png)

In this window above, if you hit "edit", then another window comes up.  

![image](https://user-images.githubusercontent.com/3372403/32657504-fda45df4-c5e3-11e7-8386-c36487f85cbe.png)

In this window you can add the path to your new bin folder.

Once you've done this successfully, you will be able to run mf2005 from any terminal window without providing the whole path, as follows:  

![image](https://user-images.githubusercontent.com/3372403/32657664-9248998e-c5e4-11e7-8741-0d48bcd68fb1.png)

In flopy, you should now be able to use the following simpler form of the model constructor, in which exe_name is just the name of the modflow executable.

```
m1 = mf.Modflow(model='name', exe_name='mf2005')
```

That's my 2 cents.

**Comment by loukika** [comment]
Thank you sir .

**Comment by Hugovdberg** [comment]
Are there still any plans to remove the extension from the default `exe_name` parameters for the various models? As long as the executable in on the search path it will be found on Windows and Linux just fine, and I think it is nice to be platform agnostic in the defaults. Or would a pull request implementing that change be accepted? (I can do the change, but don't want to invest the time if it will not be accepted anyway).

**Comment by langevin-usgs** [comment]
@Hugovdberg, I like that idea and I agree with you that the default should work on all operating systems.  If you test it and find that it works for Windows, Linux and Mac, I think we would accept that PR.  I don't remember why we kept the .exe on the binary names, but I think there might have been a reason at one point.
