### ISSUE TITLE
[Quesiton] How to obtain water content in MODFLOW 6 with depth information

### ISSUE THREAD

**Issue by geohang** [modflowpy/flopy#1548]
Hi, all.

I am trying to extract the water content information from the MODFLOW 6 simulation. I set up the water content output file and also read it successfully, but it seems there is no depth information for the water content as the example in https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_uzf_example.ipynb. Does anyone know how to obtain the depth information? Thank you!
![image](https://user-images.githubusercontent.com/75149424/190881693-875cab5b-ad1c-4a91-8cdc-84febd48c01e.png)

best,
Hang

**Comment by emorway-usgs** [comment]
If I'm not mistaken, you also asked this on #1375, hopefully my response there answers your questions?  If so, would you mind closing this issue.

**Comment by geohang** [comment]
Sure, thank you!
