### ISSUE TITLE
After resetting simulation path, time array series files are not complete

### ISSUE THREAD

**Issue by valDallalba** [modflowpy/flopy#1594]
I notice a issue when loading a mf6 simulation, changing its simulation path, write its new files and then tried to run the simulation while using recharge array as time series It seems that the newly written rch files do not respect the time series array convention and thus cannot be used to run again.

```
simu  = fp.mf6.MFSimulation.load(sim_name='daily', exe_name=exe_name, sim_ws=model_load)
simu.set_sim_path('my/new/path')
simu.write_simulation()
simu.run_simulation()

ERROR REPORT:

 Error reading data for array: RCHARRAY_PRECIP
....
rcharray_precip.tas
```
I checked the rcharray_precip.tas newly created and it doesn't respect the original .tas file from the load directory. 

Old, working one, tas file which is a time series array like.

```
# File generated by Flopy version 3.3.6 on 10/18/2022 at 14:24:40.
BEGIN attributes
  NAME  rcharray_precip
  METHOD  LINEAR
END attributes

BEGIN time       0.00000000
  INTERNAL  FACTOR  1.0
    1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  1.00000000E-20  
```

Newly created tas file, not working, not time series array like : 

```
# File generated by Flopy version 3.3.6 on 10/18/2022 at 15:18:59.
BEGIN attributes
  NAME  rcharray_precip
  METHOD  linear
END attributes

BEGIN time       0.00000000
  INTERNAL  FACTOR  1.0
  
END time       0.00000000

BEGIN time   86400.00000000
  INTERNAL  FACTOR  1.0
...
```

I encountered this issue with a previous version of flopy when using the time series array. When writing the simulation file with flopy 3.3.4 the rch file was not written in the good format. This issue has been solved since then in flopy 3.3.6. So, I guess it is just a function that has not been updated or something.

I tried to manually copy the file in between the writing and simulation steps and everything is working fine with the other created file when using the original files rch.tas file.

**Comment by spaulins-usgs** [comment]
@valDallalba Verified this bug.  The bug is in the simulation load method.  I am currently working on a fix.

**Comment by spaulins-usgs** [comment]
@valDallalba, a fix for this issue has been checked into the flopy's develop branch.

**Comment by valDallalba** [comment]
@spaulins-usgs  Thanks for the quick fix! 
I'll try it soon in my next run! 

Cheers to all of the dev working on floppy ;)
