### ISSUE TITLE
No module named 'version'

### ISSUE THREAD

**Issue by stub68** [modflowpy/flopy#16]
I get this error then I try to import the flopy utils in the ipython environment. I had a similar error message when trying to install flopy using the pip install command. I have tried modifying the _init_.py script to just bypass the version script (by assigning the version and build directly), but then I get an error that says "no module named 'modflow'", which is the next import item in the  _init_.py script. What am I doing wrong?

**Comment by jtwhite79** [comment]
Are you trying to pip install or clone from github?  I just cloned from
github into a new directory and *version.py* was included and I was able to
run *setup.py install *without trouble.

**Comment by stub68** [comment]
I can install using the windows installer, but cant now run the utils in ipython. When I import the module I get the error.

**Comment by stub68** [comment]
I have re-installed but get the same error as follows. Is this because I'm using python 3.4 in Anaconda?



ImportError                               Traceback (most recent call last)
<ipython-input-3-34c69dd4d74c> in <module>()
      1 import numpy as np
----> 2 import flopy.modflow as mf

C:\Program Files\Anaconda3\lib\site-packages\flopy\__init__.py in <module>()
     23 __name__ = 'flopy'
     24 __author__ = 'Mark Bakker, Vincent Post, Chris Langevin, Joe Hughes, Jeremy White, Jeff Starn, Mike Fienen, and Alain Frances'
---> 25 from version import __version__, __build__
     26 
     27 #imports

ImportError: No module named 'version'

**Comment by langevin-usgs** [comment]
That is the problem.  FloPy works with Python 2.7.  We have not upgraded to
version 3.x yet.  Sorry.













*Christian LangevinResearch HydrologistOffice of GroundwaterU.S. Geological
Survey411 National CenterReston, VA 20192Office: 703-648-4169Fax:
703-648-6693Email: langevin@usgs.gov
<langevin@usgs.gov>https://profile.usgs.gov/langevin
<https://profile.usgs.gov/langevin>*
