### ISSUE TITLE
feature: use matplotlib contour for StructuredGrid

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#1605]
**Is your feature request related to a problem? Please describe.**
The contours for coarse discretization `StructuredGrid` model are not as good as `matplotlib.pyplot.contour()` for some problems.

**Describe the solution you'd like**
Use standard `matplotlib.pyplot.contour()` instead of `tricontour()` for `StructuredGrid`

**Describe alternatives you've considered**
Using `matplotlib.pyplot.contour()` instead of `PlotMapView().contour_array()`

**Additional context**
Comparison of current flopy `PlotMapView().contour_array()` with `matplotlib.pyplot.contour()`

<img width="540" alt="image" src="https://user-images.githubusercontent.com/2073498/198080387-0b779c82-1b9d-4b80-a15e-fa5e54c42298.png">

**Comment by mbakker7** [comment]
Another example. Symmetric case of two wells near a fixed-head boundary. Heads are indeed symmetric when contoured with `matplotlib.pyplot.contour` (red contours), but not with the `tricontour` that is used by flopy (black).
![joe3](https://user-images.githubusercontent.com/1363400/199219289-1af8d4a1-f967-4b21-aa6f-7c5daed46159.png)

**Comment by w-bonelli** [comment]
Some more comparisons from tests and example notebooks after switching this in #1614 

#### `flopy3.3_PlatMapView.ipynb`

|Tricontour|Contour|
|:----|:----|
| ![plotmapview_tri](https://user-images.githubusercontent.com/10502868/199245462-4814d133-4380-456f-bbeb-e7d30e3e9bc1.png) | ![plotmapview_contour](https://user-images.githubusercontent.com/10502868/199245477-8a393ac1-5462-4710-bc87-a12d8a3c2918.png) |

#### `test_plot.py::test_map_view_contour`

|Tricontour|Contour|
|:----|:----|
|![map_view_tricontour_nan](https://user-images.githubusercontent.com/10502868/199245511-38838a3b-2a32-4012-9323-56fc5077ed78.png) | ![map_view_contour_nan](https://user-images.githubusercontent.com/10502868/199245520-1537bd8c-1cc1-4c1a-8d0f-19d9a07a0eee.png) |

**Comment by javgs-bd** [comment]
Hi, will this affect DISU grids as well?

**Comment by w-bonelli** [comment]
@javgs-bd this only affects structured grids as implemented in #1615

**Comment by w-bonelli** [comment]
closed by #1615
