### ISSUE TITLE
bug: problem with concentration observations in the MWT package. OBS file not created

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#1607]
**Describe the bug**
I defined a MAW package in the GWF model and because I have some injections I wanted to define also a MWT package for the GWT model to assign the measured injection concentration. My idea was also to  get the model outputs of the Head, Rate and Concentrations for all the wells defined in the MAW and MWT packages. To do so I used the option "observation" available for both the MAW and MWT package. When I write the packages  I get an error releated to the observations declared in the MWT package. This is the error message:

`File "C:\Program Files\Python39\lib\site-packages\flopy\mf6\mfpackage.py", line 1388, in _write_block
    raise MFDataException(
flopy.mf6.mfbase.MFDataException: An error occurred in data element "continuous" model "tutorial01_mf6_t" package "obs_0". The error occurred while resolving data shape in the "_get_file_entry_record" method.
Additional Information:
(1) Verify that your data is the correct shape
(2) Error occurred while writing data "continuous" in block "continuous" to file "F:\Working_Folder\testing\.\tutorial01_mf6_t.mwt.obs"`

to reproduce the error I created the following script starting from the flow model used for the tutorial 1 available here: https://flopy.readthedocs.io/en/3.3.2/_notebooks/tutorial01_mf6.html. I added a well and enabled the transport component. My full code is below. I have not declared all the required packages to run the model, I just wanted to declare enough packages to be able to write them and get the error message above.

```
import flopy
import numpy as np


path_ws = r'F:\Working_Folder\testing'
name = "tutorial01_mf6"
h1 = 100
h2 = 90
Nlay = 10
N = 101
L = 400.0
H = 50.0
k = 1.0

sim = flopy.mf6.MFSimulation(
    sim_name=name, exe_name="mf6", version="mf6", sim_ws=path_ws
)

tdis = flopy.mf6.ModflowTdis(
    sim, pname="tdis", time_units="DAYS", nper=1, perioddata=[(1.0, 1, 1.0)]
)

ims = flopy.mf6.ModflowIms(sim, pname="ims", complexity="SIMPLE")

model_nam_file = "{}.nam".format(name)
gwf = flopy.mf6.ModflowGwf(sim, modelname=name, model_nam_file=model_nam_file)

bot = np.linspace(-H / Nlay, -H, Nlay)
delrow = delcol = L / (N - 1)
dis = flopy.mf6.ModflowGwfdis(
    gwf,
    nlay=Nlay,
    nrow=N,
    ncol=N,
    delr=delrow,
    delc=delcol,
    top=0.0,
    botm=bot,
)

start = h1 * np.ones((Nlay, N, N))
ic = flopy.mf6.ModflowGwfic(gwf, pname="ic", strt=start)

npf = flopy.mf6.ModflowGwfnpf(gwf, icelltype=1, k=k, save_flows=True)

chd_rec = []
chd_rec.append(((0, int(N / 4), int(N / 4)), h2))
for layer in range(0, Nlay):
    for row_col in range(0, N):
        chd_rec.append(((layer, row_col, 0), h1))
        chd_rec.append(((layer, row_col, N - 1), h1))
        if row_col != 0 and row_col != N - 1:
            chd_rec.append(((layer, 0, row_col), h1))
            chd_rec.append(((layer, N - 1, row_col), h1))
chd = flopy.mf6.ModflowGwfchd(
    gwf,
    maxbound=len(chd_rec),
    stress_period_data=chd_rec,
    save_flows=True,
)

iper = 0
ra = chd.stress_period_data.get_data(key=iper)

# Create the output control (`OC`) Package
headfile = "{}.hds".format(name)
head_filerecord = [headfile]
budgetfile = "{}.cbb".format(name)
budget_filerecord = [budgetfile]
saverecord = [("HEAD", "ALL"), ("BUDGET", "ALL")]
printrecord = [("HEAD", "LAST")]
oc = flopy.mf6.ModflowGwfoc(
    gwf,
    saverecord=saverecord,
    head_filerecord=head_filerecord,
    budget_filerecord=budget_filerecord,
    printrecord=printrecord,
)


well_packagedata = [(0, 0.1, 55, 100., 'SPECIFIED', 1, 'well1')]

hk_skin = 1.0e3
well_condata = [(0, 0, 9, 0., 0., hk_skin, 0.)]

well_data = [(0, 'STATUS', 'ACTIVE'), (0, 'RATE', -5.)]
well_perioddata = {0: well_data}

obs_wells = [('well1_head', 'head', 1), ('well1_rate', 'rate', 1)]
osb_rates_file_name = 'wells_out.csv'

maw = flopy.mf6.modflow.mfgwfmaw.ModflowGwfmaw(gwf, pname='maw', save_flows=True, nmawwells=1,
                                               packagedata=well_packagedata, connectiondata=well_condata,
                                               perioddata=well_perioddata, boundnames=True,
                                               observations={osb_rates_file_name: obs_wells})


gwt = flopy.mf6.modflow.ModflowGwt(sim, modelname='tutorial01_mf6_t')

# DISP package
alh = 30.  # m
alt = alh / 10.
alv = alt / 10.
dsp = flopy.mf6.modflow.mfgwtdsp.ModflowGwtdsp(gwt, alh=alh, alv=alv, ath1=alt, diffc=0.)

# MST package
mst = flopy.mf6.modflow.ModflowGwtmst(gwt, porosity=0.1)

# MWT package
mwt_packagedata = [(0, 1.5)]
mwt_data = [(0, 'STATUS', 'ACTIVE'), (0, 'RATE', 1.5)]
mwt_period_data = {0: mwt_data}

osb_conc_file_name = 'conc_well_obs.csv'
obs_wells_conc = [('well1_conc', 'concentration', 1)]

mwt = flopy.mf6.modflow.ModflowGwtmwt(gwt, packagedata=mwt_packagedata, mwtperioddata=mwt_period_data,
                                      observations={osb_conc_file_name: obs_wells_conc})

sim.write_simulation()
```

**To Reproduce**
1. run the script above

**Expected behavior**
I would expect the software to create the file "tutorial01_mf6_t.mwt.obs"

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - WINDOWS 10
 - running the code with PyCharm
 - flopy version = 3.3.5
 - - python version = 3.9

PS. in the preparation of the head and rate observation array, I had to use a non-zero indexed approach, i.e. rather than 0 I had to use 1 for the first bore (and only bore that I used in this simulation). I find this not really consistent with the rest.

**Comment by spaulins-usgs** [comment]
@giovannifi bug confirmed.  Working on a solution.

**Comment by spaulins-usgs** [comment]
@giovannifi, I tracked down the problem.  Your gwt model must have a dis package.  Both flopy and MODFLOW-6 require this.  If I add a dis package to the gwt model:

    dist = flopy.mf6.ModflowGwtdis(
        gwt,
        nlay=Nlay,
        nrow=N,
        ncol=N,
        delr=delrow,
        delc=delcol,
        top=0.0,
        botm=bot,
    )

Flopy will then write the simulation.  However, the gwt model still needs an ic package in order for MODFLOW-6 to run it.

**Comment by giovannifi** [comment]
All good, thanks for that. We can close this I guess
