### ISSUE TITLE
bug: MODPATH 7 error message due to unrecognized TDIS options keyword

### ISSUE THREAD

**Issue by Paszka1** [modflowpy/flopy#1609]
The `START_DATE_TIME  2021-10-21` entry in the TDIS options block triggers the following MODPATH7 message:
* MODPATH7 v.7.2.001 message: Unrecognized keyword in OPTIONS block of TDIS file.
* Flopy message: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 20: invalid continuation byte

The TDIS file was created by Flopy and the entry is fine with MODFLOW 6. I am aware that this is not a big deal, and deleting the entry solves the issue, si I'm not exepcting any resolution, but any side notes to this are welcome.

**Comment by rodrperezi** [comment]
Hi, which version of MODPATH are you using ? A recent commit in MODPATH source code solves this issue (see https://github.com/MODFLOW-USGS/modpath-v7/commit/9ac760fe5d60ed3acd08704dfad40f08a9227088)

**Comment by Paszka1** [comment]
I'm using version 7.2.001 downloaded from github (compiled on Mar 07 2022). This is the latest available version. I just downloaded it again today, but apparently it is not the patched version.

**Comment by rodrperezi** [comment]
Try this one https://github.com/MODFLOW-USGS/modpath-v7/tree/develop/msvs/bin_PROVISIONAL

**Comment by Paszka1** [comment]
Great. It is working. Thanks.
