### ISSUE TITLE
default nam file

### ISSUE THREAD

**Issue by mbakker7** [modflowpy/flopy#1627]
I suggest to make the default nam file:
modelname.nam

This is what most people do anyway, so why not make it the default?

Thoughts?

**Comment by langevin-usgs** [comment]
@spaulins-usgs, would there be any downside to implementing Mark's suggestion?  Would it be straightforward to modify createpackages.py to do this?

**Comment by mbakker7** [comment]
You are right. I got confused because there are 2 nam files. One is called mfsim.nam (and can not be changed, right?), and the other does take the modelname by default. Sorry for the noise. I guess I don't quite understand why the name file of the simulation can not be set, but I can happily live with that.

**Comment by spaulins-usgs** [comment]
@mbakker7, the simulation name file always being mfsim.nam is a MODFLOW-6 feature/limitation.  While you can not rename mfsim.nam, you also no longer have to specify the name file as a command line argument.

**Comment by mbakker7** [comment]
Thanks for the info
