### ISSUE TITLE
bug: `flopy.modpath.ParticleData` does not accept regular numpy array as input

### ISSUE THREAD

**Issue by mbakker7** [modflowpy/flopy#1628]
The `flopy.modpath.ParticleData` class does not take a regular numpy array with three columns as input. 

To reproduce:

```
import numpy as np
import flopy as fp

partlocs = np.array([(1, 1, 1),
                     (1, 1, 2)])

fp.modpath.ParticleData(partlocs=partlocs, structured=True)
```

The error message is `ValueError: could not broadcast input array from shape (2,3) into shape (2,)`. The bug seems to be in mp7particledata.py on line 168, where the dtype of the input array is changed:

```
        elif isinstance(partlocs, np.ndarray):
            dtypein = partlocs.dtype
            if dtypein != dtype:
                partlocs = np.array(partlocs, dtype=dtype)
```

This conversion to a new `dtype` does not give the desired result as can be seen:
```
newdtype = np.dtype([('k', '<i4'), ('i', '<i4'), ('j', '<i4')])
np.array(partlocs, dtype=newdtype)
```
gives
```
array([[(1, 1, 1), (1, 1, 1), (1, 1, 1)],
       [(1, 1, 1), (1, 1, 1), (2, 2, 2)]],
      dtype=[('k', '<i4'), ('i', '<i4'), ('j', '<i4')])
```
The correct conversion requires something (arguably ugly) as
```
from numpy.lib.recfunctions import unstructured_to_structured
partlocs = unstructured_to_structured(partlocs, dtype=newdtype)
```
which gives the desired
```
array([(1, 1, 1), (1, 1, 2)],
      dtype=[('k', '<i4'), ('i', '<i4'), ('j', '<i4')])
```

Incidentally, it appears that `flopy.modpath.ParticleData` also doesn't accept a list of lists such as 
```
partlocs = [[1, 1, 1], [1, 1, 2]]
```
which gives the same error. A list of tuples works fine, however.

**Comment by w-bonelli** [comment]
Thank you @mbakker7 the `unstructured_to_structured` solution was added in #1752, this should now work correctly
