### ISSUE TITLE
"possible" bug: MAXATS is not updated in the ATS file when declaring ats_perioddata in ModflowTdis

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#1632]
**Describe the bug**
I am not sure if this is a bug or my lack of knowledge of the software. By the way, I am enabling the ATS feature by using the paramenter ats_perioddata in the `flopy.mf6.ModflowTdis()` module. Everything works OK with the exception of the parameter MAXATS in the ats file automatically generated by flopy. Although I declare more than 1 stress period with ATS activated, MAXATS is always 1. To make mf6 work I have to manually edit the ATS file.

Run the following script to reproduce the issue:

```
import flopy
import numpy as np

path_ws = r'F:\Working_Folder\testing'
name = "test_ats"
h1 = 100
h2 = 90
Nlay = 10
N = 101
L = 400.0
H = 50.0
k = 1.0

sim = flopy.mf6.MFSimulation(
    sim_name=name, exe_name="mf6", version="mf6", sim_ws=path_ws
)

nam = flopy.mf6.ModflowNam(sim, continue_=True)

tdis = flopy.mf6.ModflowTdis(
                             sim, pname="tdis", time_units="DAYS", nper=1,
                             perioddata=[(1.0, 1, 1.0), (10, 10, 1.0), (10, 10, 1.0)],
                             ats_perioddata=[(1, 1, 0.01, 10, 1.1, 2.), (2, 1, 0.01, 10, 1.1, 2.)],
                            )

ims = flopy.mf6.ModflowIms(sim, pname="ims", complexity="SIMPLE")

model_nam_file = "{}.nam".format(name)

gwf = flopy.mf6.ModflowGwf(sim, modelname=name, model_nam_file=model_nam_file, )
sim.register_ims_package(ims, [gwf.name])

bot = np.linspace(-H / Nlay, -H, Nlay)
delrow = delcol = L / (N - 1)
dis = flopy.mf6.ModflowGwfdis(
    gwf,
    nlay=Nlay,
    nrow=N,
    ncol=N,
    delr=delrow,
    delc=delcol,
    top=0.0,
    botm=bot,
)

start = h1 * np.ones((Nlay, N, N))
ic = flopy.mf6.ModflowGwfic(gwf, pname="ic", strt=start)

steady = {0: True}
transient = {1: True}
npf = flopy.mf6.ModflowGwfnpf(gwf, icelltype=1, k=k, save_flows=True)
sto = flopy.mf6.ModflowGwfsto(gwf, iconvert=1, ss=1e-4, sy=0.1, steady_state=steady,
                              transient=transient)

chd_rec = []
chd_rec.append(((0, int(N / 4), int(N / 4)), h2))
for layer in range(0, Nlay):
    for row_col in range(0, N):
        chd_rec.append(((layer, row_col, 0), h1))
        chd_rec.append(((layer, row_col, N - 1), h1))
        if row_col != 0 and row_col != N - 1:
            chd_rec.append(((layer, 0, row_col), h1))
            chd_rec.append(((layer, N - 1, row_col), h1))
chd = flopy.mf6.ModflowGwfchd(
    gwf,
    pname='chd',
    maxbound=len(chd_rec),
    stress_period_data=chd_rec,
    save_flows=True,
)

iper = 0
ra = chd.stress_period_data.get_data(key=iper)

# Create the output control (`OC`) Package
headfile = "{}.hds".format(name)
head_filerecord = [headfile]
budgetfile = "{}.cbb".format(name)
budget_filerecord = [budgetfile]
saverecord = [("HEAD", "ALL"), ("BUDGET", "ALL")]
printrecord = [("HEAD", "LAST")]
oc = flopy.mf6.ModflowGwfoc(
    gwf,
    saverecord=saverecord,
    head_filerecord=head_filerecord,
    budget_filerecord=budget_filerecord,
    printrecord=printrecord,
)

sim.write_simulation()
```

**To Reproduce**
1. run the script above
2. check the file *.ats. MAXATS is 1 and it should be 2 in this particular case.

**Expected behavior**
the generation of the ats file with MAXATS = 2

**Desktop (please complete the following information):**
 - OS: windows 10
 - python environment: PyCharm 2021
 - flopy version: 3.3.6 (release candidate)

**Comment by langevin-usgs** [comment]
I just tested this and it works for me using this code:

```
    # create tdis package
    ats_filerecord = None
    tdis = flopy.mf6.ModflowTdis(
        sim,
        ats_filerecord=ats_filerecord,
        time_units="DAYS",
        nper=nper,
        perioddata=tdis_rc,
    )
    if True:
        ats_filerecord = name + ".ats"
        atsperiod = [
            (0, dt0, dtmin, dtmax, dtadj, dtfailadj),
            (7, dt0, dtmin, dtmax, dtadj, dtfailadj),
        ]
        tdis.ats.initialize(
            maxats=len(atsperiod),
            perioddata=atsperiod,
            filename=ats_filerecord,
        )
```

This is from [here](https://github.com/MODFLOW-USGS/modflow6/blob/develop/autotest/test_gwf_ats01.py).  I don't think this is a bug.  ats_perioddata is not supported input for tdis.

**Comment by giovannifi** [comment]
@langevin-usgs it seems that your workaround is based on the command `tdis.ats.initialize()`, I modified my script above with your recommendation and tested first with flopy 3.3.5 and this is what I got:

```
Traceback (most recent call last):
  File "/home/giovanni/PycharmProjects/giovanni/flopy_ats.py", line 28, in <module>
    tdis.ats.initialize(
AttributeError: 'ModflowTdis' object has no attribute 'ats'
```

I have then tested it with flopy 3.3.6 RC and it works. Was ATS made available only in the latest version of flopy?

In any case I believe that it should be working (in 3.3.6) with ats_perioddata declared in the TDIS package. Indeed, this is supported and my script posted earlier is a demonstration of that. Have you tried to run my script? It does create the ats file. The problem is that does not update the variable MAXATS

Furthermore the documentation page here: https://flopy.readthedocs.io/en/latest/source/flopy.mf6.modflow.mftdis.html and the code of the module (https://flopy.readthedocs.io/en/latest/_modules/flopy/mf6/modflow/mftdis.html) clearly show the possibility to define the parameter ats_perioddata.

**Comment by langevin-usgs** [comment]
Sorry @giovannifi, I had forgotten that we made some changes about how we are handling ATS with flopy.  The pull request [here](https://github.com/modflowpy/flopy/pull/1394) changes how this works.  I suggest that you migrate to the new method and use the release candidate (RC) version until we make a new release, which should happen within the next two weeks.
