### ISSUE TITLE
bug: MfListBudget not working and returning no errors

### ISSUE THREAD

**Issue by jklakovich-INTERA** [modflowpy/flopy#1640]
**Describe the bug**
All methods for the MfListBudget return NoneType.

**To Reproduce**
1. Run MODFLOW 6 steady-state model.
2. Create an MfListBudget object with file path as only parameter and all others parameters left to default.
3. Run methods on budget object, get nothing back. 

**Expected behavior**
I was hoping to get tabulated (or list like) budget data.

**Screenshots**
Please see list file attached. Hoping to get this information in some form:
![image](https://user-images.githubusercontent.com/112116923/204665818-8ddfd8c4-4902-4cf5-a4ff-47ec9c5d535f.png)

Instead, the MfListFile methods don't return anything:
![image](https://user-images.githubusercontent.com/112116923/204666227-60334bea-51b5-47f9-b553-5bb144cfc4b5.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - Browser Chrome
 - Chrome version 107.0.5304.121; Flopy version 3.3.5

**Additional context**
Would also be open to any suggestions about efficiently reading the rate and cumulative budgets if other workflows are recommended. Since this straightforward way hasn't been working for me, I typically default to reading the entire Cell Budget File and summing the ins and outs per category.
[osbs.lst.txt](https://github.com/modflowpy/flopy/files/10118016/osbs.lst.txt)

**Comment by jlarsen-usgs** [comment]
@jklakovich-INTERA 
Try using `Mf6ListBudget()`. The search string for modflow 6 is different from modflow-2005, therefore `MfListBudget()` won't be able to find the budget information block.

**Comment by langevin-usgs** [comment]
If you haven't seen it already, there is also a BUDGETCSV option in the MODFLOW 6 Output Control file.  MODFLOW 6 can output that information directly to a CSV file.

**Comment by jklakovich-INTERA** [comment]
`Mf6ListBudget()` worked. @jlarsen-usgs , would you say that is a common convention for `Mfxxx` objects - if they don't work just change to Mf6xxx and try again?

Thanks for the BUDGETCSV recommendation @langevin-usgs. I had forgotten about that.
