### ISSUE TITLE
bug: Error with OBS files in relative path in a loaded model.

### ISSUE THREAD

**Issue by borjav2** [modflowpy/flopy#1643]
Hello all,

**Describe the bug**
Everything is ok when a mf6 gwf model is created with obs package with a relative path to a folder where obs.csv will be stored. However if a load this model and `set_sim_path` to a new `model_ws` with a folder which is the same relative path as the original model the obs.csv file is created with no content (0 kB). I realise that the filename where obs package is stored has its observations names with extra `'`.

**To Reproduce**
A notebook:
[https://github.com/borjav2/MODFLOW/blob/master/folder/Issue_relative_path_obs.ipynb](https://github.com/borjav2/MODFLOW/blob/master/folder/Issue_relative_path_obs.ipynb)

**Expected behavior**
I expected that the model copy the obs.csv files in the same way as the original model in the original path.

**Desktop (please complete the following information):**
OS: Windows 10 22H2
flopy version: 3.3.6

Thank you in advance for any solution
Cheers

**Comment by spaulins-usgs** [comment]
@borjav2, this was a problem with how flopy was handling quoted strings.  A fix has been checked into the develop branch of flopy.  Please download the latest develop branch and verify that your problem is fixed.

**Comment by borjav2** [comment]
@spaulins-usgs  The issue is solved indeed!. Thanks.
