### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by mgozdor1** [modflowpy/flopy#1669]
when running Gridgen g.build() I get a OSError: [WinError 193] %1 is not a valid Win32 application error.  I am new to this but would be grateful if someone could point me in the right direction to fix this issue.   

![image](https://user-images.githubusercontent.com/118388190/209247276-f94e08b4-ea30-4384-abd3-eff3d8254d8a.png)

**Comment by jlarsen-usgs** [comment]
@mgozdor1 

Have you set the path to your gridgen executable using:

```python
g = Gridgen(modelgrid, model_path, exe_name=<path to my gridgen exe>)
```

**Comment by mgozdor1** [comment]
This is what I have.  see [53]

![image](https://user-images.githubusercontent.com/118388190/209251548-779a180f-a03d-4658-8d25-22166f67a3f7.png)

**Comment by jlarsen-usgs** [comment]
@mgozdor1 

I see the issue. In [53] you are pointing to a python script. The gridgen you need to point to is an executable (.exe) program for windows. You can get this program as well as the entire stack of modflow and modflow related executables from here [windows modflow exes](https://github.com/MODFLOW-USGS/executables/releases/latest/download/win64.zip). Once you download and unzip these, point to the `gridgen.exe` file.

**Comment by mgozdor1** [comment]
greatly appreciated.  Thank you.
