### ISSUE TITLE
Modflow.load path error

### ISSUE THREAD

**Issue by bbuzz31** [modflowpy/flopy#168]
There seems to be a bug when trying to load the name file.

Line 159 of mfreadnam.py:  fname = os.path.join(os.path.dirname(namfilename), tmp[2])

Both namfilename and tmp2 hold the entire file path, at least in the way I'm running running the load method:
mf = flopy.modflow.Modflow.load('wnc-ss'.nam', exe_name=MF2005, model_ws=model_path))

So it returns a double file path.  I fixed mine by using raw [-1] instead of tmp[2]  in the fname definition.
I can provide more details if necessary, thanks.

**Comment by jtwhite79** [comment]
All that pathing in the load is pretty well tested (but that doesn't mean there's not a bug).  Can you post the value of ```model_path``` that you are passing to the ```model_ws``` arg? Is the model being loaded from the same platform (PC, *nix, OSX) that the files were created on?  Just trying to guess what the issue might be...

**Comment by bbuzz31** [comment]
Sure:
if os.name == 'posix':
    model_path        = os.path.join('/','Users','BB','Google_Drive','WNC', 'Flopy', 'wnc_ss-mac')

if os.name == 'nt':
    model_path       = os.path.join('C:\\', 'Users', 'bbuzzang', 'Google_Drive', 'WNC', 'Flopy', 'wnc_ss-windows')
----
I just checked that everything was created and loaded on same platform and no go:

[Error 3] The system cannot find the path specified: 'C:\\Users\\bbuzzang\\Google_Drive\\WNC\\Flopy\\wnc_ss-windows\\Users\\bbuzzang\\Google_Drive\\WNC\\Flopy\\wnc_ss-windows/*.*'

**Comment by jtwhite79** [comment]
ok - I hoping the problem is the absolute path for ``model_path``.  Can you try using a relative path for ```model_path```: the path needed to get from where your script is running to where the namfile is?  For example, if your script is in the ``WNC/`` dir and the namfile is in the ``wnc_ss-windows/`` dir, then ``model_path=os.path.join('Flopy','wnc_ss_windows')``.

**Comment by bbuzz31** [comment]
My script is pretty far away, but I moved it into the flopy directory and reran.
Still no go, though the path it's looking for is somewhat improved.
[Error 3] The system cannot find the path specified: 'C:Users\\bbuzzang\\Google_Drive\\WNC\\Flopy\\wnc
_ss-windows/*.*'
Note also that the \ is missing after the C drive, which is definitely a problem.

**Comment by jtwhite79** [comment]
Where is your script relative to the namfile?  Are they both on the same drive (C:)?

**Comment by bbuzz31** [comment]
Yes I put the script in C:\Users\bbuzzang\Google_Drive\WNC\ and ran 
mf = flopy.modflow.Modflow.load('wnc-ss'.nam', exe_name=MF2005, model_path=os.path.join('Flopy',wnc_ss_windows')) as you suggested.

**Comment by jtwhite79** [comment]
Is it the same traceback using the relative path approach?

Can you load the model if the script is in the same dir as the namfile and the ``model_ws='.'``?

**Comment by bbuzz31** [comment]
**Short answer's: yes, no.** 
 Details below.

Traceback is the same, the path it's looking for is different (sorry, if my terminology is a bit off).

**Absolute path:**
 File  "C:\Python27\miniconda_32\envs\coupled\lib\site-packages\flopy\modflow\mf.py", line 457, in load
 raise Exception("error loading name file entries from file:\n" + str(e))
Exception: error loading name file entries from file:
[Error 3] The system cannot find the path specified: 'C:\\Users\\bbuzzang\\Google_Drive\\WNC\\Flopy\\wnc_ss-windows\\Users\\bbuzzang\\Google_Drive\\WNC\\Flopy\\wnc_ss-windows/*.*'

**Relative path: (script in WNC, model_path = os.path.join('Flopy,' wnc_ss-windows')**
 raise Exception("error loading name file entries from file:\n" + str(e))
Exception: error loading name file entries from file:
[Error 3] The system cannot find the path specified: 'C:Users\\bbuzzang\\Google_Drive\\WNC\\Flopy\\wnc
_ss-windows/*.*'

**Relative path, same dir (model_path ='.')**
 File "C:\Python27\miniconda_32\envs\flopy\lib\site-packages\flopy\modflow\mf.py", line 458, in load
    raise Exception("error loading name file entries from file:\n" + str(e))
Exception: error loading name file entries from file:
[Error 3] The system cannot find the path specified: 'C:Users\\bbuzzang\\Google_Drive\\WNC\\Flopy\\wnc
_ss-windows/*.*'

**Relative path, same dir, model_path unspecified is identical to setting model_path='.'** (which it should be, of course).

**Comment by bbuzz31** [comment]
**Update**
I'm pretty sure what I thought were 'double file path' is caused by using full paths in the name file.
See below.

`    path_load = /Volumes/BB_4TB/Thesis/Results_03-19/SLR-0.0_03-19
      return flopy.modflow.Modflow.load(self.slr_name+'.nam', model_ws=path_load) `

```
Exception: error loading name file entries from file:
[Errno 2] No such file or directory: '/Volumes/BB_4TB/Thesis/Results_03-19/SLR-0.0_03-19/Users/bb/Google_Drive/WNC/Coupled/Mar/MF'
```

`# Name file for MODFLOW-2005, generated by Flopy version 3.2.6.
#xul:400232.6478; yul:4072436.502; rotation:19; proj4_str:+init=EPSG:6347; units:meters; lenuni:2; length_multiplier:1.0 ;start_datetime:06/30/2012
LIST               2  /Users/bb/Google_Drive/WNC/Coupled/Mar/MF/SLR-0.0_03-19.list
DIS               11  /Users/bb/Google_Drive/WNC/Coupled/Mar/MF/SLR-0.0_03-19.dis `

Thanks,
Brett

**Comment by sharon92** [comment]
this needs to be updated in the upcoming versions.

flopy.utils.mfreadnam.parsefilename
`        # remove quotes in file path
        if '"' in fpath:
            fpath = fpath.replace('"', '')
        if "'" in fpath:
            fpath = fpath.replace("'", "")

        # need make filenames with paths system agnostic
        if '/' in fpath:
            raw = fpath.split('/')
        elif '\\' in fpath:
            raw = fpath.split('\\')
        else:
            raw = [fpath]
        fpath = os.path.join(*raw)

        fname = os.path.join(os.path.dirname(namfilename), fpath)`

fpath should be checked first by os.path.exists(fpath)
