### ISSUE TITLE
`numpy.distutils` is deprecated since NumPy 1.23.0

### ISSUE THREAD

**Issue by byronamerson** [modflowpy/flopy#1681]
When running block 14 in the flopy3_raster_intersection.ipynb notebook, this line of code:

dem_data = rio.resample_to_grid(
    ml.modelgrid, band=rio.bands[0], method="nearest"
)

breaks with the following message:

  `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
  of the deprecation of `distutils` itself. It will be removed for
  Python >= 3.12. For older Python versions it will remain present.
  It is recommended to use `setuptools < 60.0` for those Python versions.
  For more details, see:
    https://numpy.org/devdocs/reference/distutils_status_migration.html 

dem_data = rio.resample_to_grid(
    ml.modelgrid, band=rio.bands[0], method="nearest"
)

I downgraded to numpy version 1.21.6 (the same version as the notebook) and this fixed the problem.  Just wanted to make you aware of the issue, if you were not already aware.

Thanks

**Comment by w-bonelli** [comment]
Hi @byronamerson, it should not be required to downgrade `numpy` to run that notebook. See the CI run [here](https://github.com/modflowpy/flopy/actions/runs/3909583752/jobs/6680818835#step:8:123) for a successful run with numpy 1.24.1. FloPy only officially supports up to Python 3.11 currently &mdash; if you're running an alpha version of 3.12 I'd recommend downgrading your Python. Out of curiosity, which Python and FloPy versions are you using?

**Comment by w-bonelli** [comment]
@byronamerson great, glad it is working now.
