### ISSUE TITLE
Support environmental heads Seawat

### ISSUE THREAD

**Issue by JoerivanEngelen** [modflowpy/flopy#169]
I cannot find Flopy support for the CHDDENSOPT option (to choose between point water head, fresh water head, environmental head) of the CHD package; this option was included in version 4 of Seawat. Is this included somewhere, where I have overlooked it?

And another question (since some of the Seawat developers are active here): Is there also similar option of this for other fixed head packages, like the GHB, RIV etc?

**Comment by langevin-usgs** [comment]
@JoerivanEngelen that option is invoked by using an auxiliary variable with the name CHDDENSOPT.  You can provide auxiliary variables to flopy.  See this notebook for an example of how to specify auxiliary variables: https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_modflow_boundaries.ipynb.  

Is there a need for a similar option for GHB, RIV, etc?  It seems to me like these boundaries do not need this option.  There are a few extra controls that you can specify, however, as described in table 2 of the SEAWAT-2000 report:  http://fl.water.usgs.gov/PDF_files/ofr03_426_langevin.pdf.

**Comment by JoerivanEngelen** [comment]
Thanks for the help, much appreciated!

There is no real need for it; I'm currently using the GHB in a way it is not originally intended to be used and weird stuff is happening.
