### ISSUE TITLE
bug: trouble reading MODFLOW-2000 binary head output

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#1691]
Hi, I'm having trouble opening the attached binary head file with the following code:
```python
import flopy.utils.binaryfile as bf
hdsobj1 = bf.HeadFile('tcp2017.fhd')
hds1 = hdsobj1.get_data()
```
I've tried manually setting the precision both ways, but keep getting this error: `ValueError: array is too big; arr.size * arr.dtype.itemsize is larger than the maximum possible size.` and the nlay, nrow, ncol attributes on the HeadFile instance are very large.

I'm guessing this is some kind of issue with reading the MODFLOW-2000 header? In case it matters, I've attached two versions- the first one from running the model myself (OSX platform) and the second from the USGS model archive (presumably Windows). Thanks in advance for your help.

[tcp2017.fhd.zip](https://github.com/modflowpy/flopy/files/10482326/tcp2017.fhd.zip)

[tcp2017-original.fhd.zip](https://github.com/modflowpy/flopy/files/10482329/tcp2017-original.fhd.zip)

**Comment by jlarsen-usgs** [comment]
@aleaf 

I checked the head file and it's a formatted ascii head file. The flopy `HeadFile` class only works with binary head files. Try opening the head file with the `FormattedHeadFile()` reader:

```python
from flopy.utils.formattedfile import FormattedHeadFile

hdsobj1 = FormattedHeadFile('tcp2017.fhd')
hds1 = hdsobj1.get_data()
```

**Comment by aleaf** [comment]
doh!

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs added code a long try ago to read from ascii head files. I thought this still worked.
