### ISSUE TITLE
MultiPolygon not iterable

### ISSUE THREAD

**Issue by briochh** [modflowpy/flopy#1695]
I might be missing something in here but do we need a `intersect.geoms` on this line? I don't think MultiPolygon types are iterable (or maybe this is dependent on shapely version?)
https://github.com/modflowpy/flopy/blob/f017c0d60abd729112e2836cd5b8d5f178c42446/flopy/utils/gridintersect.py#L1987

**Comment by w-bonelli** [comment]
fixed in #1696
