### ISSUE TITLE
bug: FloPy load throws error reading .nam file for a USG model

### ISSUE THREAD

**Issue by SamanTavakoli** [modflowpy/flopy#1701]
**Describe the bug**
FloPy throws an error attemping to load a USG model. The USG model has LPF package for model properties. 

**To Reproduce**
     ml = flopy.modflow.Modflow.load("SV_SWI_uni_01j.nam" ,version = "mfusg", verbose = True, check = False)

    File D:\Software\Anaconda3\lib\site-packages\flopy\modflow\mf.py:811 in load
    dis = disnamdata.package.load(

    AttributeError: 'NoneType' object has no attribute 'load'

**Comment by cnicol-gwlogic** [comment]
I'll have to add a trap for this case, but the  correct way to load mfusg models is:

flopy.mfusg.MfUsg.load()

Give that a shot.
