### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by rafaur99** [modflowpy/flopy#1719]
**Describe the bug**
 
`wefjwjnjdfsadf`
**To Reproduce**
Steps to reproduce the behavior:hbshjansdjahj cj ashjc ssjaxca
4. See errorsfadfadsf

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jlarsen-usgs** [comment]
closing because there are no details describing the issue
