### ISSUE TITLE
plot_pathline with wrong color argument in Modpath Notebooks 

### ISSUE THREAD

**Issue by javgs-bd** [modflowpy/flopy#1732]
This is a minor thing but just noticed that in the current modpath flopy notebooks there are several calls to plot_pathline with a "color" argument that result in grey lines.

Reviewing the docs and other calls that work I believe the argument is "colors" instead.

**Comment by w-bonelli** [comment]
Thanks @javgs-bd you are right. @langevin-usgs I could add this fix to #1687, or would it be best as a separate PR?

**Comment by langevin-usgs** [comment]
I'd so go ahead and add it to #1687, and then let's merge it in.

**Comment by w-bonelli** [comment]
closed by #1687
