### ISSUE TITLE
run_model3() 'NoneType' object is not callable

### ISSUE THREAD

**Issue by wchristensen** [modflowpy/flopy#18]
I am new to flopy. I am following the "getting started" example on the page below. I have copied everything verbatim [although I believe it should be mf.run_model3()?] and I've also tried syntax from earlier examples but get an error when the model tries to run. Suggestions?

http://modflowpy.github.io/flopydoc/tutorial1.html#getting-started

![flopy](https://cloud.githubusercontent.com/assets/11322377/6516408/7f7f5048-c346-11e4-8895-af4bbaed5228.png)

**Comment by wchristensen** [comment]
I am also confused about the post-processing block a bit further down in the same tutorial.

np.arange(1,10,1) gives [1,2,3,4,5,6,7,8,9], which unless I misunderstand should become the values of the contours when passed as:

plt.contour(head[0, :, :], levels=levels, extent=extent)

If the left boundary (x=0) is specified head = 10 and the right boundary (x=1000) is specified head = 0, shouldn't the head contours be linear... i.e. head = 9 (level = 9) line up with x=100, head = 8 (level = 8) line up with x = 200, etc?

Thank you for helping me understand!

**Comment by jtwhite79** [comment]
run_model3() is no longer in mbase.  If I follow your link, the run command shown in the notebook is:
# Run the MODFLOW model
success, buff = mf.run_model()

Are you sure you are using the most current version of flopy?

**Comment by wchristensen** [comment]
Thank you for the reply.

It appears I have the most current version of flopy, unless I am missing something (see below). 

I was going back and forth between the tutorial I previously linked and this older one (https://flopy.googlecode.com/svn/sphinx/_build/html/tutorial1.html#getting-started). 

This is the error I get when I use:

success, buff = mf.run_model()

![flopy - update - buff](https://cloud.githubusercontent.com/assets/11322377/6527786/60b08506-c3d2-11e4-964f-b89c8f3d3ba5.png)

**Comment by langevin-usgs** [comment]
You need to have the MODFLOW executable in your path.  If not, then flopy
cannot run the model.

FloPy team -- we should probably do an os check on mfexe to make sure that
it exists and issue a better error.













*Christian LangevinResearch HydrologistOffice of GroundwaterU.S. Geological
Survey411 National CenterReston, VA 20192Office: 703-648-4169Fax:
703-648-6693Email: langevin@usgs.gov
<langevin@usgs.gov>https://profile.usgs.gov/langevin
<https://profile.usgs.gov/langevin>*

**Comment by wchristensen** [comment]
doh! Thanks.

**Comment by wchristensen** [comment]
Might I also suggest mentioning the requirement for python 2.7 in the
documentation for those of us who are not embedded in the python world.

Thanks for your help.

On Fri, Mar 6, 2015 at 8:03 AM, langevin-usgs <notifications@github.com>
wrote:

> You need to have the MODFLOW executable in your path. If not, then flopy
> cannot run the model.
>
> FloPy team -- we should probably do an os check on mfexe to make sure that
> it exists and issue a better error.
>
>
>
>
>
>
>
>
>
>
>
>
>
> *Christian LangevinResearch HydrologistOffice of GroundwaterU.S. Geological
> Survey411 National CenterReston, VA 20192Office: 703-648-4169Fax:
> 703-648-6693Email: langevin@usgs.gov
> <langevin@usgs.gov>https://profile.usgs.gov/langevin
> <https://profile.usgs.gov/langevin>*
>
> On Fri, Mar 6, 2015 at 10:43 AM, wchristensen <notifications@github.com>
> wrote:
>
> > Thank you for the reply.
> >
> > It appears I have the most current version of flopy, unless I am missing
> > something (see below).
> >
> > I was going back and forth between the tutorial I previously linked and
> > this older one (
> >
> https://flopy.googlecode.com/svn/sphinx/_build/html/tutorial1.html#getting-started
> ).
> >
> >
> > This is the error I get when I use:
> >
> > success, buff = mf.run_model()
> >
> > [image: flopy - update - buff]
> > <
> https://cloud.githubusercontent.com/assets/11322377/6527786/60b08506-c3d2-11e4-964f-b89c8f3d3ba5.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/modflowpy/flopy/issues/18#issuecomment-77579683>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modflowpy/flopy/issues/18#issuecomment-77583287>.
>



-- 

Wesley Christensen

Hydrologist

2730 N. Deer Run Rd.

Carson City, NV 89701

Phone: (775) 887-7711

**Comment by langevin-usgs** [comment]
This is mentioned on the main FloPy Github site:
https://github.com/modflowpy/flopy













*Christian LangevinResearch HydrologistOffice of GroundwaterU.S. Geological
Survey411 National CenterReston, VA 20192Office: 703-648-4169Fax:
703-648-6693Email: langevin@usgs.gov
<langevin@usgs.gov>https://profile.usgs.gov/langevin
<https://profile.usgs.gov/langevin>*
