### ISSUE TITLE
Gage package docstrings

### ISSUE THREAD

**Issue by emorway-usgs** [modflowpy/flopy#182]
@jdhughes-usgs the docstrings for the gage package don't elucidate what the difference is between the 'files' and 'filenames' arguments?  Also note in the following example:

```
import flopy
m = flopy.modflow.Modflow()
dis = flopy.modflow.ModflowDis(m)
spd = {(0, 0): ['print head'],
       (0, 1): [],
       (0, 249): ['print head'],
       (0, 250): [],
       (0, 499): ['print head', 'save ibound'],
       (0, 500): [],
       (0, 749): ['print head', 'ddreference'],
       (0, 750): [],
       (0, 999): ['print head', 'save budget', 'save drawdown']}
oc = flopy.modflow.ModflowOc(m, stress_period_data=spd, cboufm='(20i5)')

gages = [[-1,  -26, 1], [-2,  -27, 1]]
files = ['gage1.go', 'gage2.go']
gage = flopy.modflow.ModflowGage(m, numgage=2,
                                 gage_data=gages, files=files)

m.write_input()
```

results in gage output files that have the same exact name in the name file (i.e., it doesn't seem to honor the list that is fed into 'files').  Here is the resulting name file, notice that the two gage output files are the same and don't honor the names given in the `files` argument above:

LIST           2 modflowtest.list
DIS           11 modflowtest.dis 
OC            14 modflowtest.oc 
DATA(BINARY)  52 modflowtest.ddn REPLACE
DATA(BINARY)  53 modflowtest.cbc REPLACE
DATA          54 modflowtest.ibo REPLACE
GAGE         120 modflowtest.gage 
DATA          26 **modflowtest.got** REPLACE
DATA          27 **modflowtest.got** REPLACE

**Comment by jdhughes-usgs** [comment]
Fixed. Added test (t047_test.py) to the flopy autotest for this. The resulting name file is listed below:

```
# Name file for MODFLOW-2005, generated by Flopy version 3.2.6.
#xul:0; yul:2; rotation:0; proj4_str:+init=EPSG:4326; units:meters; lenuni:2; length_multiplier:1.0 ;start_datetime:1-1-1970
LIST               2  gage_test.list
DIS               11  gage_test.dis 
OC                14  gage_test.oc 
GAGE             120  gage_test.gage 
DATA(BINARY)      52  gage_test.ddn REPLACE
DATA              54  gage_test.ibo
DATA              26  gage1.go
DATA              27  gage2.go

```

Updated the doc strings for package.
