### ISSUE TITLE
get_ts index off

### ISSUE THREAD

**Issue by bbuzz31** [modflowpy/flopy#184]
Hi, 
Using get_ts on a formatted head file object seems to shift my columns one to the right by adding nan value at column 0.
This cuts off the last column too.
Obviously I can just make my own time series with get_data methods but figured I'd ask.
Thanks,
Brett

CODE SAMPLE ---
hds = ff.FormattedHeadFile(model + '.fhd', precision='double')

layrowcol = (0, 0, 2)
heads_ts = hds.get_ts(layrowcol)
heads = hds.get_data(kstpkper=(0,0))

print heads[0][0][1]
print heads_ts[0]

OUTPUT: 
2.93444
[ 1.       2.93444]

-----
layrowcol = (0, 0, 0) ::::: [  1.  nan]

.FHD SAMPLE ------------

FHD: 
     1    1   1.000000E+00   1.000000E+00             HEAD    51    74     1 (1X1PE13.5)         
  -9.99990E+02
   2.93444E+00
   2.89089E+00
   2.84153E+00
   2.79512E+00

**Comment by langevin-usgs** [comment]
Thanks for this.  It was fixed in pull request #185.
