### ISSUE TITLE
bug: cellid (node number, disv) supplied as int to ModflowGwfmaw written as float

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1840]
**Describe the bug**
I am providing the node number in the connection data block as an int to ModflowGwfmaw. When I query the data before writing the model input files, this value is shown as an int:

![image](https://github.com/modflowpy/flopy/assets/25184697/74f7354b-8ac4-4364-bc9e-5215add73396)

however, when I write the model files, this value is written in exponential format causing an error in mf6. 

![image](https://github.com/modflowpy/flopy/assets/25184697/329598f8-bdf8-4a53-9356-3a74e115f723)
![image](https://github.com/modflowpy/flopy/assets/25184697/78b5a368-6a27-4eed-a794-c42bbe8fe1a6)

**To Reproduce**
Put MAW in disv model with a high number of ncpl (my model has ~300k ncpl)
**Expected behavior**
ints should stay ints

**Desktop (please complete the following information):**
 - OS: windows
 - Version '3.3.7'

**Comment by spaulins-usgs** [comment]
Your connectiondata has "layer" and "node" columns.  All of the cellid information should be stored in the same "cellid" column (layer, node for disv) as a tuple.  See the description for maw connectiondata here:

https://github.com/modflowpy/flopy/blob/develop/flopy/mf6/modflow/mfgwfmaw.py

_cellid ((integer, ...)) is the cell identifier, and depends on the type of grid that is used for the simulation. For a structured grid that uses the DIS input file, CELLID is the layer, row, and column.  For a grid that uses the DISV input file, CELLID is the layer and CELL2D number..._

**Comment by w-bonelli** [comment]
The example is still up to date, the cell IDs may be provided as ints or iterables of ints. However the usage must be consistent, whichever you go with
