### ISSUE TITLE
bug: error on load of exchange pacakge

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1841]
**Describe the bug**
I am trying to load a model where a local disv (quadtree (layer, node)) is nested in a regional dis (regular (layer, row, column)) model. The model runs fine in MF6 with no errors. However, when I try and load in flopy I get:
![image](https://github.com/modflowpy/flopy/assets/25184697/0216a723-c79a-4942-85bb-862d2dd29487)

Here is the top of .exg package
![image](https://github.com/modflowpy/flopy/assets/25184697/0cc46ca9-319c-42d6-aac4-edd8983b8e49)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: flopy = '3.3.7'

**Comment by spaulins-usgs** [comment]
@RyanConway91, just merged a fix for this.  Please check out the latest develop branch and confirm that this fixes your problem.

**Comment by wpbonelli** [comment]
removing from 3.4.3 milestone as the fix for this touches files to be introduced in 3.5.0
