### ISSUE TITLE
budget binary file

### ISSUE THREAD

**Issue by bbuzz31** [modflowpy/flopy#186]
Hi, 
I upgraded to the latest version today (from 3.2.6.1493)  and I can't seem to write a uzf budget binary file anymore.
Originally I am specifying iuzfcb2=61 and 

` spd    = {(0, 0): ['save head', 'save drawdown', 'save budget']} `
`ex    = ['oc', 'fhd', 'ddn', 'cbc']`
`oc     = flopy.modflow.ModflowOc(mf, stress_period_data=spd, ... extenstion=ext) `

This worked and produced a name file with:
DATA(BINARY)  61 ...Feb/MF/Daily_02-23.uzfbt2 
DATA(BINARY)  53 ...Feb/MF/Daily_02-23.cbc REPLACE (53 is default).
#
Now with the same settings the cbc insists on using the same unit budget number:
DATA(BINARY)      61  ...MF/Develop_02-23.cbc REPLACE
 (.list) CANNOT OPEN .../Develop_02-23.cbc ON UNIT  61 BECAUSE UNIT IS ALREADY BEING USED
I've tried messing with the parameters and not saving anything but UZFB (and a bunch of other combinations) but nothing seems to work.

Note that my cbc file is blank even with the working version, so I'm probably doing something wrong.

Any help is appreciated.
Thanks,
Brett

**Comment by jdhughes-usgs** [comment]
This should be resolved now. See autotest/t036_test.py for an example of the testing done to confirm that the code is correctly using iuzfcb2.
