### ISSUE TITLE
itype 15 in SSM package

### ISSUE THREAD

**Issue by laat0003** [modflowpy/flopy#188]
Hi,

I am trying to run mass loading cells in a SEAWAT model but can't get FloPy to put them into the model input file. I updated my version to the latest release (not development) just to check if its an old issue but no luck. I have itype 1 and itype 4 in the model fine. The itype 15's are definitely in the ssm dictionary along with the itype 1's and 4's before I write the input file. A check of the input file after writing shows only the itype 1's and 4's. There are quite a few of these 15's in the model and the loading rate will vary between model runs so putting them in the input file via text editor is going to suck balls. Please help.

PS I also tried just getting one itype 15 in the input file with FloPy but struck out there too.

Thanks in advance.
Tariq

**Comment by jtwhite79** [comment]
Can you post a minimum working example of your problem? With SEAWAT henry notebook, I was able to add an ``itype`` 15 source to the ssm and it was properly accounted for and written to the file.

**Comment by langevin-usgs** [comment]
@laat0003, what is the status with this?  Are things working now?

**Comment by laat0003** [comment]
Apologies for the delay in response. I was out in the field with no internet access. Thanks for pointing out that it works with the Henry problem notebook. I checked it as well and could get an Itype 15 to appear in the input file. Sincerest apologies for not doing a check like this myself and wasting your time.
