### ISSUE TITLE
bug: Check Laytyp in MFsimulation.load with verify_data=True

### ISSUE THREAD

**Issue by martinveenvlietrhdhv** [modflowpy/flopy#1880]
Hi,

When loading an existing transient Modflow 6 model (confined layers) in Flopy, using the option verify_data=True, the check_storage definition throws an error TypeError: '<' not supported between instances of 'NoneType' and 'int' at line 424. This is because the specific yield package is not defined due to the simulation being fully confined.

It seems that, in line 383 (pakbase.py, if "laytyp" in self.__dict__:), skip_sy_check is not set to true due to "laytyp" not existing in an modflow 6 simulation. It therefore always checks whether SY exists, even if the simulation only contains confined layers.

**Comment by spaulins-usgs** [comment]
@martinveenvlietrhdhv, I just committed a fix to the develop branch of FloPy that should fix this problem.

**Comment by martinveenvlietrhdhv** [comment]
Can verify that it works in the develop branch! Thanks!
