### ISSUE TITLE
bug: *** TypeError: 'MultiLineString' object is not iterable

### ISSUE THREAD

**Issue by oscarfasanchez** [modflowpy/flopy#1922]
**Describe the bug**
I'm using the flopy tools to intersect a shapefile with a structured grid in modflow 6, but when I run the ix.intersect command I get the following error:
```python
resultq=ix.intersect(shp_geomq)
```
> *** TypeError: 'MultiLineString' object is not iterable
 in the files:
> File c:\users\oscar\documents\git_repos\thesis_mf6_pest\09_python\modelo.py:547 in setup_drn_creeks
    resultq=ix.intersect(shp_geomq)
>
>  File ~\anaconda3\envs\THESIS_MASTER\Lib\site-packages\flopy\utils\gridintersect.py:277 in intersect
    rec = self._intersect_linestring_structured(
>
>  File ~\anaconda3\envs\THESIS_MASTER\Lib\site-packages\flopy\utils\gridintersect.py:1491 in _intersect_linestring_structured
    ishp = shapely_geo.MultiLineString(ishp)
>
>  File ~\anaconda3\envs\THESIS_MASTER\Lib\site-packages\shapely\geometry\multilinestring.py:50 in __new__
    line = linestring.LineString(lines[i])
>
>  File ~\anaconda3\envs\THESIS_MASTER\Lib\site-packages\shapely\geometry\linestring.py:66 in __new__
    coordinates = [_coords(o) for o in coordinates]

**To Reproduce**
here I attach my dis package and the shapefile
the snippet is something like the following
```python
import  shapefile as sf 
from shapely.geometry import shape, MultiLineString

ix = GridIntersect(gwf.modelgrid, method="structured", rtree=False)
...
...
queb=sf.Reader(os.path.join(path_sh,"Queb_corr.shp"))

list_shp = []
for i in range(1,queb.numRecords):
        queb1=queb.shapeRecords()[i]
        firstq=queb1.shape.__geo_interface__
        # shp_geomq=shp_geomq.union(shape(firstq))
        list_shp.append(shape(firstq))
shp_geomq=MultiLineString(lines=list_shp)
resultq=ix.intersect(shp_geomq)
```
**Expected behavior**

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - running on spyder
 - Flopy Version '3.4.1'

**Additional context**
attachment
[bug.zip](https://github.com/modflowpy/flopy/files/12376718/bug.zip)

thanks in advance for any help

**Comment by mwtoews** [comment]
See #1923 for potential fix
