### ISSUE TITLE
bug: Importing cross-sectional USG model results has 3 dimensional error

### ISSUE THREAD

**Issue by CooperGarth** [modflowpy/flopy#1958]
**Describe the bug**
When importing a cross section model created in MF-USG (1 row, 7100 columns, 30 layers) an error "ValueError: Util3d: expected 3 dimensions, found shape (1058732,)"

**To Reproduce**
1. Import flopy model using: mf = flopy.mfusg.MfUsg.load('TS_50_b_iv_b.nam',exe_name="mfusg", check=False, verbose=True)
2. Error ValueError: Util3d: expected 3 dimensions, found shape (1058732,) comes up

[TS_50_b_iv_b.zip](https://github.com/modflowpy/flopy/files/12695997/TS_50_b_iv_b.zip)

**Comment by cnicol-gwlogic** [comment]
@CooperGarth  I've resolved this via #1959. If you want a quick local fix, just change [this line](https://github.com/modflowpy/flopy/pull/1959/files#:~:text=self.ksat,%3D%20Util2d() in your flopy/mfusg/mfusgbcf.py file.

**Comment by CooperGarth** [comment]
@cnicol-gwlogic that worked! thanks for the quick reply.
