### ISSUE TITLE
feature: Allow for user defined attribute columns in modpath shapefile export. 

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#1977]
If I get pathline data:
```
pathlines = PathlineFile(ptl, verbose = False)
pathline_data = pathlines.get_alldata()

```
and then add a new data column to the pathline_data recarray, and write a shapefile with

pathlines.write_shapefile(pathline_data = pathline_data,shpname=shp, mg=mg, one_per_particle=False, crs = crs)

the new data column does not get printed to the shapefile. It seems like write_shapefile only writes the base data in the original recarray?

I am working on a MP7 simulation with ~100 wells, I want to know what particle goes with what well, so I would like to add that info to the recarray before writing. Currently, I need to write the shp, reload it, add the columns I want, and write it again.

**Comment by wpbonelli** [comment]
@RyanConway91 shapefile export supports user defined fields, but there is a [10-character limit on the field name](https://en.wikipedia.org/wiki/Shapefile#Data_storage). FloPy [tries to truncate](https://github.com/modflowpy/flopy/blob/f82fdf6be34770e0e98567c70eac30d34a525794/flopy/export/shapefile_utils.py#L474)  field names longer than 10 characters, but doesn't issue a warning when this occurs or inform the caller what the shortened name is. It seems like it should.
