### ISSUE TITLE
Problems reading a transient SFR output file

### ISSUE THREAD

**Issue by Hperea** [modflowpy/flopy#198]
Can I read a transient SFR output file with Flopy? I could read only the first stress period of the ouput  TXT file. 
Is there another option to read this file? 
I appreciate any help. 
Thanks,

Hugo Perea

**Comment by aleaf** [comment]
Hi Hugo,
The SfrFile class can do this. I just submitted a [pull request](https://github.com/modflowpy/flopy/pull/201) to fix a bug in reading transient output. See the [sfr package example](https://github.com/aleaf/flopy/blob/develop/examples/Notebooks/flopy3_sfrpackage_example.ipynb) for how to read in the file (scroll to the bottom)

**Comment by Hperea** [comment]
Hi Aleaf,

I have used the new SfrFile class but I got a problem reading the SFR output file. I got the folloging error:

 time += [ts[1]] * np.abs(self.nstrm)
TypeError: bad operand type for abs(): 'NoneType'

It looks like there is not value coming out from the function get_nstrm(df). Please, see attached SFR output file.
[PHXTran1_sfr_flows.txt](https://github.com/modflowpy/flopy/files/873077/PHXTran1_sfr_flows.txt)

**Comment by aleaf** [comment]
Hi Hugo, I think I found the issue: https://github.com/modflowpy/flopy/pull/202
