### ISSUE TITLE
writing .cbc files

### ISSUE THREAD

**Issue by porterma** [modflowpy/flopy#200]
I recently installed the development version of flopy. It seems that now I am not getting updated .cbc files when I rerun models that were previously writing this file. Any thoughts on your end?

**Comment by langevin-usgs** [comment]
Can you paste into this issue the contents of your name file and output control file?

**Comment by langevin-usgs** [comment]
And the syntax of your flopy output control instantiation?

**Comment by porterma** [comment]
Here they are.

# Name file for MODFLOW-2005, generated by Flopy version 3.2.7.
#xul:0; yul:1000; rotation:0; proj4_str:+init=EPSG:4326; units:meters; lenuni:2; length_multiplier:1.0 ;start_datetime:1-1-1970
LIST               2  tutorial2.list
DIS               11  tutorial2.dis 
BAS6              13  tutorial2.bas 
LPF               15  tutorial2.lpf 
PCG               27  tutorial2.pcg 
GHB               23  tutorial2.ghb 
WEL               20  tutorial2.wel 
OC                14  tutorial2.oc 
DATA(BINARY)      51  tutorial2.hds REPLACE
DATA(BINARY)      52  tutorial2.ddn REPLACE

`oc = flopy.modflow.ModflowOc(mf, stress_period_data=spd, compact=True)`

# OC package for  MODFLOW-2005, generated by Flopy.
HEAD PRINT FORMAT   0
HEAD SAVE UNIT    51
DRAWDOWN PRINT FORMAT   0
DRAWDOWN SAVE UNIT    52
COMPACT BUDGET AUX

period 1 step 1 
print head
print budget
save head
save budget
save drawdown

period 2 step 1 
print head
print budget
save head
save budget
save drawdown

period 2 step 2 
print head
print budget
save head
save budget
save drawdown

period 2 step 3 
print head
print budget
save head
save budget
save drawdown

period 2 step 4 
print head
print budget
save head
save budget
save drawdown

period 2 step 5 
print head
print budget
save head
save budget
save drawdown

period 2 step 6 
print head
print budget
save head
save budget
save drawdown

period 2 step 7 
print head
print budget
save head
save budget
save drawdown

period 2 step 8 
print head
print budget
save head
save budget
save drawdown

period 2 step 9 
print head
print budget
save head
save budget
save drawdown

period 2 step 10 
print head
print budget
save head
save budget
save drawdown

period 2 step 11 
print head
print budget
save head
save budget
save drawdown

period 2 step 12 
print head
print budget
save head
save budget
save drawdown

period 2 step 13 
print head
print budget
save head
save budget
save drawdown

period 2 step 14 
print head
print budget
save head
save budget
save drawdown

period 2 step 15 
print head
print budget
save head
save budget
save drawdown

period 2 step 16 
print head
print budget
save head
save budget
save drawdown

period 2 step 17 
print head
print budget
save head
save budget
save drawdown

period 2 step 18 
print head
print budget
save head
save budget
save drawdown

period 2 step 19 
print head
print budget
save head
save budget
save drawdown

period 2 step 20 
print head
print budget
save head
save budget
save drawdown

period 2 step 21 
print head
print budget
save head
save budget
save drawdown

period 2 step 22 
print head
print budget
save head
save budget
save drawdown

period 2 step 23 
print head
print budget
save head
save budget
save drawdown

period 2 step 24 
print head
print budget
save head
save budget
save drawdown

period 2 step 25 
print head
print budget
save head
save budget
save drawdown

period 2 step 26 
print head
print budget
save head
save budget
save drawdown

period 2 step 27 
print head
print budget
save head
save budget
save drawdown

period 2 step 28 
print head
print budget
save head
save budget
save drawdown

period 2 step 29 
print head
print budget
save head
save budget
save drawdown

period 2 step 30 
print head
print budget
save head
save budget
save drawdown

period 2 step 31 
print head
print budget
save head
save budget
save drawdown

period 2 step 32 
print head
print budget
save head
save budget
save drawdown

period 2 step 33 
print head
print budget
save head
save budget
save drawdown

period 2 step 34 
print head
print budget
save head
save budget
save drawdown

period 2 step 35 
print head
print budget
save head
save budget
save drawdown

period 2 step 36 
print head
print budget
save head
save budget
save drawdown

period 2 step 37 
print head
print budget
save head
save budget
save drawdown

period 2 step 38 
print head
print budget
save head
save budget
save drawdown

period 2 step 39 
print head
print budget
save head
save budget
save drawdown

period 2 step 40 
print head
print budget
save head
save budget
save drawdown

period 2 step 41 
print head
print budget
save head
save budget
save drawdown

period 2 step 42 
print head
print budget
save head
save budget
save drawdown

period 2 step 43 
print head
print budget
save head
save budget
save drawdown

period 2 step 44 
print head
print budget
save head
save budget
save drawdown

period 2 step 45 
print head
print budget
save head
save budget
save drawdown

period 2 step 46 
print head
print budget
save head
save budget
save drawdown

period 2 step 47 
print head
print budget
save head
save budget
save drawdown

period 2 step 48 
print head
print budget
save head
save budget
save drawdown

period 2 step 49 
print head
print budget
save head
save budget
save drawdown

period 2 step 50 
print head
print budget
save head
save budget
save drawdown

period 2 step 51 
print head
print budget
save head
save budget
save drawdown

period 2 step 52 
print head
print budget
save head
save budget
save drawdown

period 2 step 53 
print head
print budget
save head
save budget
save drawdown

period 2 step 54 
print head
print budget
save head
save budget
save drawdown

period 2 step 55 
print head
print budget
save head
save budget
save drawdown

period 2 step 56 
print head
print budget
save head
save budget
save drawdown

period 2 step 57 
print head
print budget
save head
save budget
save drawdown

period 2 step 58 
print head
print budget
save head
save budget
save drawdown

period 2 step 59 
print head
print budget
save head
save budget
save drawdown

period 2 step 60 
print head
print budget
save head
save budget
save drawdown

period 2 step 61 
print head
print budget
save head
save budget
save drawdown

period 2 step 62 
print head
print budget
save head
save budget
save drawdown

period 2 step 63 
print head
print budget
save head
save budget
save drawdown

period 2 step 64 
print head
print budget
save head
save budget
save drawdown

period 2 step 65 
print head
print budget
save head
save budget
save drawdown

period 2 step 66 
print head
print budget
save head
save budget
save drawdown

period 2 step 67 
print head
print budget
save head
save budget
save drawdown

period 2 step 68 
print head
print budget
save head
save budget
save drawdown

period 2 step 69 
print head
print budget
save head
save budget
save drawdown

period 2 step 70 
print head
print budget
save head
save budget
save drawdown

period 2 step 71 
print head
print budget
save head
save budget
save drawdown

period 2 step 72 
print head
print budget
save head
save budget
save drawdown

period 2 step 73 
print head
print budget
save head
save budget
save drawdown

period 2 step 74 
print head
print budget
save head
save budget
save drawdown

period 2 step 75 
print head
print budget
save head
save budget
save drawdown

period 2 step 76 
print head
print budget
save head
save budget
save drawdown

period 2 step 77 
print head
print budget
save head
save budget
save drawdown

period 2 step 78 
print head
print budget
save head
save budget
save drawdown

period 2 step 79 
print head
print budget
save head
save budget
save drawdown

period 2 step 80 
print head
print budget
save head
save budget
save drawdown

period 2 step 81 
print head
print budget
save head
save budget
save drawdown

period 2 step 82 
print head
print budget
save head
save budget
save drawdown

period 2 step 83 
print head
print budget
save head
save budget
save drawdown

period 2 step 84 
print head
print budget
save head
save budget
save drawdown

period 2 step 85 
print head
print budget
save head
save budget
save drawdown

period 2 step 86 
print head
print budget
save head
save budget
save drawdown

period 2 step 87 
print head
print budget
save head
save budget
save drawdown

period 2 step 88 
print head
print budget
save head
save budget
save drawdown

period 2 step 89 
print head
print budget
save head
save budget
save drawdown

period 2 step 90 
print head
print budget
save head
save budget
save drawdown

period 2 step 91 
print head
print budget
save head
save budget
save drawdown

period 2 step 92 
print head
print budget
save head
save budget
save drawdown

period 2 step 93 
print head
print budget
save head
save budget
save drawdown

period 2 step 94 
print head
print budget
save head
save budget
save drawdown

period 2 step 95 
print head
print budget
save head
save budget
save drawdown

period 2 step 96 
print head
print budget
save head
save budget
save drawdown

period 2 step 97 
print head
print budget
save head
save budget
save drawdown

period 2 step 98 
print head
print budget
save head
save budget
save drawdown

period 2 step 99 
print head
print budget
save head
save budget
save drawdown

period 2 step 100 
print head
print budget
save head
save budget
save drawdown

period 3 step 1 
print head
print budget
save head
save budget
save drawdown

period 3 step 2 
print head
print budget
save head
save budget
save drawdown

period 3 step 3 
print head
print budget
save head
save budget
save drawdown

period 3 step 4 
print head
print budget
save head
save budget
save drawdown

period 3 step 5 
print head
print budget
save head
save budget
save drawdown

period 3 step 6 
print head
print budget
save head
save budget
save drawdown

period 3 step 7 
print head
print budget
save head
save budget
save drawdown

period 3 step 8 
print head
print budget
save head
save budget
save drawdown

period 3 step 9 
print head
print budget
save head
save budget
save drawdown

period 3 step 10 
print head
print budget
save head
save budget
save drawdown

period 3 step 11 
print head
print budget
save head
save budget
save drawdown

period 3 step 12 
print head
print budget
save head
save budget
save drawdown

period 3 step 13 
print head
print budget
save head
save budget
save drawdown

period 3 step 14 
print head
print budget
save head
save budget
save drawdown

period 3 step 15 
print head
print budget
save head
save budget
save drawdown

period 3 step 16 
print head
print budget
save head
save budget
save drawdown

period 3 step 17 
print head
print budget
save head
save budget
save drawdown

period 3 step 18 
print head
print budget
save head
save budget
save drawdown

period 3 step 19 
print head
print budget
save head
save budget
save drawdown

period 3 step 20 
print head
print budget
save head
save budget
save drawdown

period 3 step 21 
print head
print budget
save head
save budget
save drawdown

period 3 step 22 
print head
print budget
save head
save budget
save drawdown

period 3 step 23 
print head
print budget
save head
save budget
save drawdown

period 3 step 24 
print head
print budget
save head
save budget
save drawdown

period 3 step 25 
print head
print budget
save head
save budget
save drawdown

period 3 step 26 
print head
print budget
save head
save budget
save drawdown

period 3 step 27 
print head
print budget
save head
save budget
save drawdown

period 3 step 28 
print head
print budget
save head
save budget
save drawdown

period 3 step 29 
print head
print budget
save head
save budget
save drawdown

period 3 step 30 
print head
print budget
save head
save budget
save drawdown

period 3 step 31 
print head
print budget
save head
save budget
save drawdown

period 3 step 32 
print head
print budget
save head
save budget
save drawdown

period 3 step 33 
print head
print budget
save head
save budget
save drawdown

period 3 step 34 
print head
print budget
save head
save budget
save drawdown

period 3 step 35 
print head
print budget
save head
save budget
save drawdown

period 3 step 36 
print head
print budget
save head
save budget
save drawdown

period 3 step 37 
print head
print budget
save head
save budget
save drawdown

period 3 step 38 
print head
print budget
save head
save budget
save drawdown

period 3 step 39 
print head
print budget
save head
save budget
save drawdown

period 3 step 40 
print head
print budget
save head
save budget
save drawdown

period 3 step 41 
print head
print budget
save head
save budget
save drawdown

period 3 step 42 
print head
print budget
save head
save budget
save drawdown

period 3 step 43 
print head
print budget
save head
save budget
save drawdown

period 3 step 44 
print head
print budget
save head
save budget
save drawdown

period 3 step 45 
print head
print budget
save head
save budget
save drawdown

period 3 step 46 
print head
print budget
save head
save budget
save drawdown

period 3 step 47 
print head
print budget
save head
save budget
save drawdown

period 3 step 48 
print head
print budget
save head
save budget
save drawdown

period 3 step 49 
print head
print budget
save head
save budget
save drawdown

period 3 step 50 
print head
print budget
save head
save budget
save drawdown

period 3 step 51 
print head
print budget
save head
save budget
save drawdown

period 3 step 52 
print head
print budget
save head
save budget
save drawdown

period 3 step 53 
print head
print budget
save head
save budget
save drawdown

period 3 step 54 
print head
print budget
save head
save budget
save drawdown

period 3 step 55 
print head
print budget
save head
save budget
save drawdown

period 3 step 56 
print head
print budget
save head
save budget
save drawdown

period 3 step 57 
print head
print budget
save head
save budget
save drawdown

period 3 step 58 
print head
print budget
save head
save budget
save drawdown

period 3 step 59 
print head
print budget
save head
save budget
save drawdown

period 3 step 60 
print head
print budget
save head
save budget
save drawdown

period 3 step 61 
print head
print budget
save head
save budget
save drawdown

period 3 step 62 
print head
print budget
save head
save budget
save drawdown

period 3 step 63 
print head
print budget
save head
save budget
save drawdown

period 3 step 64 
print head
print budget
save head
save budget
save drawdown

period 3 step 65 
print head
print budget
save head
save budget
save drawdown

period 3 step 66 
print head
print budget
save head
save budget
save drawdown

period 3 step 67 
print head
print budget
save head
save budget
save drawdown

period 3 step 68 
print head
print budget
save head
save budget
save drawdown

period 3 step 69 
print head
print budget
save head
save budget
save drawdown

period 3 step 70 
print head
print budget
save head
save budget
save drawdown

period 3 step 71 
print head
print budget
save head
save budget
save drawdown

period 3 step 72 
print head
print budget
save head
save budget
save drawdown

period 3 step 73 
print head
print budget
save head
save budget
save drawdown

period 3 step 74 
print head
print budget
save head
save budget
save drawdown

period 3 step 75 
print head
print budget
save head
save budget
save drawdown

period 3 step 76 
print head
print budget
save head
save budget
save drawdown

period 3 step 77 
print head
print budget
save head
save budget
save drawdown

period 3 step 78 
print head
print budget
save head
save budget
save drawdown

period 3 step 79 
print head
print budget
save head
save budget
save drawdown

period 3 step 80 
print head
print budget
save head
save budget
save drawdown

period 3 step 81 
print head
print budget
save head
save budget
save drawdown

period 3 step 82 
print head
print budget
save head
save budget
save drawdown

period 3 step 83 
print head
print budget
save head
save budget
save drawdown

period 3 step 84 
print head
print budget
save head
save budget
save drawdown

period 3 step 85 
print head
print budget
save head
save budget
save drawdown

period 3 step 86 
print head
print budget
save head
save budget
save drawdown

period 3 step 87 
print head
print budget
save head
save budget
save drawdown

period 3 step 88 
print head
print budget
save head
save budget
save drawdown

period 3 step 89 
print head
print budget
save head
save budget
save drawdown

period 3 step 90 
print head
print budget
save head
save budget
save drawdown

period 3 step 91 
print head
print budget
save head
save budget
save drawdown

period 3 step 92 
print head
print budget
save head
save budget
save drawdown

period 3 step 93 
print head
print budget
save head
save budget
save drawdown

period 3 step 94 
print head
print budget
save head
save budget
save drawdown

period 3 step 95 
print head
print budget
save head
save budget
save drawdown

period 3 step 96 
print head
print budget
save head
save budget
save drawdown

period 3 step 97 
print head
print budget
save head
save budget
save drawdown

period 3 step 98 
print head
print budget
save head
save budget
save drawdown

period 3 step 99 
print head
print budget
save head
save budget
save drawdown

period 3 step 100 
print head
print budget
save head
save budget
save drawdown

**Comment by langevin-usgs** [comment]
Thanks, that all looks good.  Need two other things:
  1.  Top few lines of LPF or BCF MODFLOW file
  2.  flopy code for instantiating LPF or BCF object

**Comment by jdhughes-usgs** [comment]
You need to pass in a non-zero ipakcb during instantiation for packages you want to save budget information. So in your lpf pass a `ipakcb=53` and you will get cell-by-cell flows. We eliminated default head, drawdown, and budget output in version 3.2.6

**Comment by porterma** [comment]
Thank you. I apologize for not catching that.

**Comment by bdestombe** [comment]
Thanks, I was having some difficulties with this as well. 

Currently, tutorial 1 and 2 in Examples/Tutorials don't run because of it.
