### ISSUE TITLE
Error when exporting hds to VTK (large file)

### ISSUE THREAD

**Issue by sebmeng** [modflowpy/flopy#2007]
**Describe the bug**
I ran a modflow nwt model with 200x200 grid size, 1 layer, and 5479 daily timesteps. Then i wanted to export the HDS file in vtk format. and I got the error: "ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.""

**To Reproduce**
this is the code i used for exporting the HDS file to vtk:
```#import hds
head_file ="modflow_LRW.hed"
hds = HeadFile(head_file)

# create the vtk object and export heads
vtkobj = vtk.Vtk(mf, xml=True, pvd=True, vertical_exageration=10)
vtkobj.add_heads(hds)
vtkobj.write("heads.vtk")
```
**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - -Visual Studio Code v1.76.2
Thanks in advance for the help!

**Comment by wpbonelli** [comment]
@sebmeng any way you could share your model or provide a full error trace? Is this happening on `.add_heads()` or `.write()`? It sounds like numpy can't allocate enough memory for an array, we may be able to specify `dtype=object` somewhere to use pointers/existing references instead of new memory
