### ISSUE TITLE
bug: utils\gridgen grid refinement with shapefile

### ISSUE THREAD

**Issue by jeroenhelder** [modflowpy/flopy#2021]
Hi,

when using a shapefile for gridrefinement I receive an error: 
assert os.path.isfile(sn), f"Shapefile does not exist: {sn}"
Apparently the add_refinement_features function searches for the existence of the shapefile with an extra .shp extension.
changing line 446 seems to solve the problem (at least for me)
from
    sn = os.path.join(self.model_ws, f"{shapefile}.shp")
to 

   sn = os.path.join(self.model_ws, f"{shapefile}")

**Comment by wpbonelli** [comment]
Fixed in develop, thanks for reporting. Note the shapefile must still be in the gridgen workspace (and the argument a string), it may be better to support arbitrary path-like.
