### ISSUE TITLE
feature: Read gridgen files without Gridgen instance

### ISSUE THREAD

**Issue by martinvonk** [modflowpy/flopy#2059]
I would like to read the output of gridgen files without a `Gridgen` instance. Currently, if you have written the gridgen files (using the `build` method) all output files are written to the `model_ws`. However, if you want to read those files (separately), you need to rebuild a Gridgen instance with a ModelGrid to be able to read them. But you might not have a ModelGrid instance if you only have the gridgen files.

For instance, the `get_iac` method now does not work without a Gridgen instance, while the file qtg.iac.dat just exists:
```python
class Gridgen

    def get_iac(self):
        """
        Get the iac array
    
        Returns
        -------
        iac : ndarray
            A 1D vector of the number of connections (plus 1) for each cell
    
        """
        nodes = self.get_nodes()
        iac = np.empty((nodes), dtype=int)
        fname = os.path.join(self.model_ws, "qtg.iac.dat")
        f = open(fname, "r")
        iac = read1d(f, iac)
        f.close()
        return iac
```

**Describe the solution you'd like**
Move reading the gridgen files to a (static) method or separate function:
**Solution 1: static method**
```python
class Gridgen

    @staticmethod
    def read_iac(self, model_ws: str | Path, nodes: int):
        iac = np.empty((nodes), dtype=int)
        fname = os.path.join(model_ws, "qtg.iac.dat")
        f = open(fname, "r")
        iac = read1d(f, iac)
        f.close()
        return iac
    
    def get_iac(self):
       iac = self.read_iac(model_ws=self.model_ws, nodes=self.nodes)
       return iac
```

**Solution 2: seperate function**
```python
def read_iac(self, model_ws: str | Path, nodes: int):
      iac = np.empty((nodes), dtype=int)
      fname = os.path.join(model_ws, "qtg.iac.dat")
      f = open(fname, "r")
      iac = read1d(f, iac)
      f.close()
      return iac

class Gridgen
    def get_iac(self):
       iac = read_iac(model_ws=self.model_ws, nodes=self.nodes)
       return iac
```

**Alternatives**
Create a `Gridgen.load()` method (similar to `Modflow.load()`) to build a Gridgen instance from files only. Could be nice as well, but I don't know if all gridgen files are enough to create a gridgen instance.

**Comment by langevin-usgs** [comment]
Hey @martinvonk, this seems completely reasonable to me.  Do you want to submit a PR?  I think we'd be happy to merge it in.  FWIW, I like the @staticmethod approach.
