### ISSUE TITLE
VoronoiGrid creates "polygons" with less than 3 vertex pairs

### ISSUE THREAD

**Issue by jlarsen-usgs** [modflowpy/flopy#2073]
**Describe the bug**
In certain cases such as fine triangular refinement the VoronoiGrid class creates modflow grid nodes that have either 1) empty iverts, 2) a single ivert (point feature), or 3) 2 iverts (line feature). While the VertexGrid class of FloPy can digest this information, it is invalid for geospatial processing such as raster resampling or creating GeoDataFrames

**To Reproduce**
See the notebook [Sagehen_structured_2_voronoi_workshop.ipynb](https://github.com/jlarsen-usgs/pyhydro/blob/main/Sagehen_structured_2_voronoi_workshop.ipynb)

**Additional context**
A simple check at the end of the `tri2vor` method resolves this issue. After the code that finds unique iverts and sorts them, a few lines of code can be added to check for nodes with less than 3 iverts, remove them, and remove their xy centers from tri.verts. Here is the proposed solution

```python
        # existing code
        vor_verts = np.array(vor_verts)
        for icell in range(len(vor_iverts)):
            iverts_cell = vor_iverts[icell]
            vor_iverts[icell] = list(
                get_sorted_vertices(iverts_cell, vor_verts)
            )
        
        # new code to solve issue
        # remove empty polygons/iverts, point, and line freatures and their associated xy centers
        points = list(tri.verts)
        pop_list = []
        for icell, ivlist in enumerate(vor_iverts):
            if len(ivlist) < 3:
                pop_list.append(icell)

        for icell in pop_list[::-1]:
            vor_iverts.pop(icell)
            points.pop(icell)

        points = np.array(points)
```

**Comment by langevin-usgs** [comment]
Hey @jlarsen-usgs, it makes sense that we should filter out these invalid cells.  I think @wpbonelli also had a fix for the case where unnecessary vertices were placed along a cell edge.  Would be great if you submitted a PR with this change.  Would also be good in the future if we added some tests for these degenerate cases.

**Comment by jlarsen-usgs** [comment]
I'll submit a PR with this change today.

**Comment by wpbonelli** [comment]
The duplicate edge vertex fix went in [here](https://github.com/modflowpy/flopy/commit/a53cda7ff8f724dfc362b432ac9be8c98cc04165#diff-2c9d23f801b2bbb3a3dce0d0131163dc9007e7305b3aaff08429860d78b5c760) since it is relevant to PRT but it is not independently tested yet. I will plan to add some tests.
