### ISSUE TITLE
Segmentation fault with upw on mfnwt, mfowhm

### ISSUE THREAD

**Issue by rabbl** [modflowpy/flopy#208]
Hello Flopy-Team,
i'm creating the most simple flopy-script with mfnwt and upw-Package and all standard values.

```
import flopy.modflow as mf

ml = mf.Modflow(modelname="testmodel", exe_name='mfnwt', version='mfnwt')
dis = mf.ModflowDis(ml)
bas = mf.ModflowBas(ml)
upw = mf.ModflowUpw(ml)
pcg = mf.ModflowPcg(ml)
oc = mf.ModflowOc(ml)
ml.write_input()
ml.run_model()
```

And it returns a segmentation fault:

```warning: assuming SpatialReference units are meters
FloPy is using the following executable to run the model: /usr/local/bin/mfnwt

                                  MODFLOW-NWT-SWR1 
    U.S. GEOLOGICAL SURVEY MODULAR FINITE-DIFFERENCE GROUNDWATER-FLOW MODEL
                             WITH NEWTON FORMULATION
                             Version 1.0.9 07/01/2014                        
                    BASED ON MODFLOW-2005 Version 1.11.0 08/08/2013                       

                    SWR1 Version 1.03.0 08/30/2013                       

 Using NAME file: testmodel.nam 
 Run start date and time (yyyy/mm/dd hh:mm:ss): 2017/04/28 21:54:15


Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x102ea0132
#1  0x102e9f450
#2  0x7fff989c8b39
#3  0x102c0c750
#4  0x102cae4e5
#5  0x102d7f1ae

Process finished with exit code 0
```

This error comes on both, Darwin and Debian.
I have build mfnwt with pymake and gfortran-4.9.
I have tried mfowhm compiled with the given makefile on both systems with  gfortran-4.9.

Could you give me a hint how to proceed debugging.
I don't know if the problem is in flopy, in my compilation, gcc or in the source.
Can you reproduce this error?

Another bigger project, build with modelMuse, using upw-package is working fine with upw on mfnwt, mfowhm.

Thanks in advance, 
Ralf

**Comment by langevin-usgs** [comment]
I was able to reproduce your issue on Darwin.  MODFLOW-NWT needs the NWT solver instead of PCG.  If you make this simple change, then the problem runs successfully.  MODFLOW-NWT should probably have better error trapping for this.

#pcg = mf.ModflowPcg(ml)
nwt = mf.ModflowNwt(ml)

**Comment by rabbl** [comment]
This is an easy fix.
Thanks
