### ISSUE TITLE
bug: gwf.modeltime.steady_state inconsistent with input/output

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#2117]
**Describe the bug**
The `gwf.modeltime.steady_state` attribute appears to be returning `True` for every period entered in the `steady_state` argument to `ModflowGwfsto`, regardless of whether the entry for that period is `True` or `False`. The actual STO input file written by Flopy does not seem to be affected by this.

**To Reproduce**
```python
import flopy as fp
out_dir = 'tmp'
sim = fp.mf6.MFSimulation(sim_name='testsim',
                   version='mf6',
                   sim_ws=out_dir)
tdis_rc = [(1.0, 1, 1.0), (10.0, 120, 1.0), (10.0, 120, 1.0), (10.0, 120, 1.0)]
tdis = fp.mf6.ModflowTdis(sim, nper=len(tdis_rc),
                          perioddata=tdis_rc)
ims = fp.mf6.ModflowIms(sim)
gwf = fp.mf6.ModflowGwf(sim, modelname='testmodel')
dis = fp.mf6.ModflowGwfdis(gwf)
sto = fp.mf6.ModflowGwfsto(
    gwf,
    pname="sto",
    save_flows=True,
    iconvert=1,
    ss=1e-4,
    sy=0.2,
    steady_state={0: True, 1: False, 2: False, 3: False},
    transient={0:False, 1: True, 2: True, 3: True},
)
gwf.modeltime.steady_state
```
```
array([ True,  True,  True,  True])
```
**Expected behavior**
```
array([ True,  False,  False,  False])
```
**More broadly**, since a stress period can't be both steady-state and transient, maybe it would be better to refactor the Flopy input to a single `steady_state` dictionary of `True/False` values. Is there any reason why we wouldn't want to do this?

**Comment by aleaf** [comment]
**A related issue with loading a model:* If the STO package isn't included in the load, `gwf.modeltime.steady_state` returns all `True` for each stress period.

```python
sim.write_simulation()
loaded_sim = fp.mf6.MFSimulation.load('testsim', sim_ws=out_dir, load_only=['dis'])
loaded_gwf = loaded_sim.get_model('testmodel')
loaded_gwf.modeltime.steady_state
```
array([ True,  True,  True,  True])

Maybe `loaded_gwf.modeltime.steady_state` should be None at this point to make it clear that the model doesn't have this information?

**Comment by spaulins-usgs** [comment]
The first problem should now be fixed.

Regarding your second comment, the MF6 documentation states, "If the STO Package is not included for a model, then storage changes will not be calculated, and thus, the model will be steady state.".  Given this, I think it is reasonable for flopy's modeltime.steady_state to be true when the STO package does not exist.
