### ISSUE TITLE
bug: irch for rch and evt packages

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#2145]
**Describe the bug**
flopy cannot load existing models https://github.com/MODFLOW-USGS/modflow6-testmodels/tree/master/mf6/test001h_evt_array4 and
https://github.com/MODFLOW-USGS/modflow6-testmodels/tree/master/mf6/test001h_rch_array4. This is a recent issue that crept in sometime recently.

**To Reproduce**
1. Download the two models
2. Load with `sim = flopy.mf6.MFSimulation.load(sim_ws=".")`
3. Results in error `MFDataException: An error occurred in data element "irch" model "gwf6" package "rcha". The error occurred while setting data in the "_set_data" method.`

**Expected behavior**
Load the models without an error.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: MacOS, Linux, Windows

**Comment by wpbonelli** [comment]
confirmed models now load without error after #2146
