### ISSUE TITLE
bug in modflow.ModflowPcgn.write

### ISSUE THREAD

**Issue by hansonmcoombs** [modflowpy/flopy#215]
in lines 290 and 291 in the write function getting error associated with a non-existent global variable:

        ifrfm = self.parent.get_ifrefm()
        if ifrfm:
            # dataset 1
            line = '{} '.format(self.iter_mo)
            line += '{} '.format(self.iter_mi)
  290          line += '{} '.format(close_r) #This should be self.close_r
  291          line += '{}\n'.format(close_h) # This should be self.close_h
            f.write(line)

            # dataset 2
            line = '{} '.format(self.relax)
            line += '{} '.format(self.ifill)
            line += '{} '.format(self.unit_pc)
            line += '{}\n'.format(self.unit_ts)
            f.write(line)

**Comment by jdhughes-usgs** [comment]
Thanks. Fixed this in the development version.
