### ISSUE TITLE
NumPy 2.0 compatibility

### ISSUE THREAD

**Issue by wpbonelli** [modflowpy/flopy#2153]
Opening this (somewhat belatedly) to track support for NumPy 2.0, due out [soon](https://github.com/numpy/numpy/issues/24300). The maintainers recommend downstream projects make a compatible release before 2.0 drops. We have already made some progress updating API usages. The biggest consideration is our runtime dependencies on projects which depend on numpy (checks indicate whether the project has released 2.0 support)

- [pandas](https://pandas.pydata.org/pandas-docs/version/2.2.2/whatsnew/v2.2.2.html#pandas-2-2-2-is-now-compatible-with-numpy-2-0) (required) &check;
- [matplotlib](https://github.com/matplotlib/matplotlib/releases/tag/v3.8.4) (required) &check;
- [scipy](https://github.com/scipy/scipy/releases/tag/v1.13.0) (optional) &check;
- [pyvista](https://github.com/pyvista/pyvista/issues/5472) (optional) &check;
- [rasterio](https://github.com/rasterio/rasterio/releases/tag/1.3.10) (optional) &check;
- [shapely](https://github.com/shapely/shapely/issues/1972) (optional) &check;
- [netcdf4](https://github.com/Unidata/netcdf4-python/pull/1317) (optional) &check;

Core requirements (pandas and mpl) are already covered. If 2.0 is imminent before all our optional dependencies support it, we will need to decide whether to release immediately or wait, but it [sounds like at least a month remaining](https://github.com/numpy/numpy/issues/24300#issuecomment-1943713157), so with luck it won't come to that.

Tasks:

- [x] pin numpy<2.0 until supported
  - #2092
- [x] update deprecated/removed syntax
  - #2088
  - #2124
- [x] run `ruff` rule NPY201, all looks good
- [x] accommodate [dtype promotion changes](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion) &mdash; this may be an ongoing task, as these can easily go unnoticed where not captured by a regression/snapshot test
  - #2158 
- [x] pass all tests with numpy>=2.0.0

**Comment by wpbonelli** [comment]
Per the [latest announcement](https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448) numpy 2.0 will come out in 3.5 weeks. Flopy 3.7 is planned tomorrow to coincide with MF6.5.0, but optional dependencies have not all released np2 support. I see two paths:

- Release numpy2 support with 3.7.0, and warn that optional dependencies are not guaranteed to be compatible yet. Installs will work fine for the core flopy package, but may break for the optional dependencies if the user has np2+, as will features using them (e.g. netcdf export).
- Keep numpy pinned <2 for 3.7.0, and plan to release numpy2 support with 3.7.1+ in the next few weeks, if/when netcdf4-python does. Installs will continue to work in the meantime, but we may end up here again if a netcdf release is not forthcoming, in which case I'm not sure anything further can be done to avoid potential breakage

**Comment by jdhughes-usgs** [comment]
@wpbonelli I think we should pin to <2 for 3.7.0 and do another release later

**Comment by wpbonelli** [comment]
Netcdf4-python has made a new numpy2-compatible release (1.7.0) but there are some issues with the package. Seems like they are working on a fix, after which I think we can proceed at any time.

Should we make a new release promptly? We have a number of bugfixes and a couple new features since 3.7.0. I guess np2 support could also be considered a feature, so by semver this would be 3.8.0. If others agree I can remove the pin and get the ball rolling when netcdf4 is ready.

**Comment by langevin-usgs** [comment]
> NumPy 2.0 [came out today](https://github.com/numpy/numpy/releases/tag/v2.0.0).
> 
> Netcdf4-python has made a numpy2-compatible release (1.7.0) but there are some issues with the package. Seems like they are working on a fix, after which I think we can proceed at any time.
> 
> Should we make a new release promptly? We have a number of bugfixes and a couple new features since 3.7.0. I guess np2 support could also be considered a feature, so by semver this would be 3.8.0. If others agree I can remove the pin and get the ball rolling when netcdf4 is ready.

I like the idea of making a new release that supports numpy 2.0.  We will likely have others as this all settles in, but my opinion is to keep moving it forward.
