### ISSUE TITLE
feature:  flopy.discretization.unstructuredgrid.intersect...but in 3D!?

### ISSUE THREAD

**Issue by kerrybardot** [modflowpy/flopy#2162]
It would be nice to be able to extract the x,y,z coordinate given a node using an Unstructured Grid.
Also, on the flipside, extracting the node given an x,y,z. 

I am grateful for flopy.discretization.unstructuredgrid.intersect which does this in 2D... can we extend this to 3d please?!

Many methods for Unstructured Grids are quite useful, although still rely on layered format. 

In the meantime, I will keep working with the utilities of the vertex grid, and then convert between vertex grid node number and unstructured grid node number. This might be easier for me for now anyway, but nice to have the above methods in the near future!

**Comment by kerrybardot** [comment]
It does accept the z parameter but only returns the Cell2d number (rather than the node number), which for Unstructured Grids doesn't make sense:

![image](https://github.com/modflowpy/flopy/assets/65206513/b24633b5-2708-4130-958a-fa11dbf7564b)

**Comment by jlarsen-usgs** [comment]
@kerrybardot 
The icell2d number is the same as the node number.

From the MF6 IO guide:
"icell2d—is the cell2d number. Records in the CELL2D block must be listed in consecutive order from
1 to NODES."

**Comment by kerrybardot** [comment]
Anyway, just letting you know that when you pass the x,y,z it returns the cell2d number, and it doesn't change what it returns when you change the z layer even if it is in another layer. That's OK.. I've scripted my own fix for now!
