### ISSUE TITLE
bug: Plotting water table for Unstructured Grid

### ISSUE THREAD

**Issue by kerrybardot** [modflowpy/flopy#2163]
Unstructured grids with pinch outs (i.e. different number of cells per layer) don't seem plottable... 

Heads are in array shape [1,1,nnodes] and no longer in layer format.

Am I asking too much to detect the upper most wet cell in each "pillar" and plot the water table? This code plots blank.

head = gwf.output.head().get_data()
mm = flopy.plot.PlotMapView(model=gwf)
mm.plot_array(head, edgecolor="0.5")
mm.plot_grid()
plt.show()

![image](https://github.com/modflowpy/flopy/assets/65206513/8f62b952-b308-4c82-98bb-d42d42e6a498)

**Comment by jlarsen-usgs** [comment]
Hi @kerrybardot 

Can you zip up and attach a minimally reproducable version of the model (Discretization file and any external files associated, and a head file)? I'll take a look at it and see what the issue might be. Thanks

**Comment by langevin-usgs** [comment]
Wonder if this would work with a flatten on the end?

```
head = gwf.output.head().get_data().flatten()
```
