### ISSUE TITLE
Question to totim

### ISSUE THREAD

**Issue by rabbl** [modflowpy/flopy#218]
I have a question
Is the totim-value a 0-based value?

If let's say my timeUnit is days and the first stressperiod starts 2017-01-01,  whats the totim for this date? 

1 or 0?

**Comment by langevin-usgs** [comment]
Hi @rabbl, the start of the simulation is time zero.  So if your first stress period is 10 days, then totim at the end of the first stress period is 10.0.

BTW, we saw a presentation of your work at the MODFLOW and More conference.  Excited to see what you come up with.

**Comment by rabbl** [comment]
Thanks Chris. We are working hard on it, trying to get the whole stack working until end of the year.
As always, there is so much work to do and we don't have enough people to everything.
Thanks for answering the question, i'll close this issue.
