### ISSUE TITLE
bug: Model name in tutorial too long

### ISSUE THREAD

**Issue by pya** [modflowpy/flopy#2182]
**Describe the bug**
The model name in the first [tutorial](https://flopy.readthedocs.io/en/latest/Notebooks/mf6_data_tutorial01.html) is `tutorial01_mf6_data`. It has a length of 19 characters. But Modflow 6 only accepts names with a maximum length of 16 characters. 

**To Reproduce**

1. Execute the code form the tutorial.
2. Use `sim.write_simulation()` to write the Modflow input files.
3. Run the model with `sim.run_simulation()`.

This creates the following error report.

```raw
ERROR REPORT:

  1.     ERROR. INVALID MODEL NAME: TUTORIAL01_MF6_DATA
  2.     NAME LENGTH OF 19 EXCEEDS MAXIMUM LENGTH OF 16

UNIT ERROR REPORT:

  1. ERROR OCCURRED WHILE READING FILE 'mfsim.nam'
```

**Expected behavior**
The tutorial should use a valid model name. In addition, raising an exception when the model name is too long could be helpful.

**Screenshots**
N/A.

**Desktop (please complete the following information):**

- OS: macOS 14.3
- Browser N/A
- Version flopy 3.6.0, Modflow 6.4.1

**Comment by spaulins-usgs** [comment]
@pya, an updated tutorial with a shorter model name has been checked in to the FloPy develop branch.

**Comment by pya** [comment]
Thanks. :)
