### ISSUE TITLE
Question to Modflow Lake package input

### ISSUE THREAD

**Issue by AlexKissinger** [modflowpy/flopy#219]
I have difficulties setting up input for the Lak package. 
The documentation of the ModflowLak class is (unlike other packages of flopy I have worked with) is missing many of the parameters like sill_data, flux_data, stage_range, stages and their required types.
 
I was wondering if there is any example script or notebook using the LAK package, which I might have missed in the repository?

Thank you!

**Comment by jdhughes-usgs** [comment]
There is a lake example notebook (flopy3_lake_example.ipynb) but you probably already found it.

**Comment by AlirezaKavousi** [comment]
Dear @jdhughes-usgs,
I see this question was from a long time ago, but I also missed the ModflowLak class in the mentioned lake example (i.e., flopy3_lake_example.ipynb). The example rather consider a simple constant head lake at the middle of a model domain without using ModflowLak class.
I searched over the Gitub and internet, but could just find an example for MT3D as "flopy3_mt3d-usgs_example_with_sft_lkt_uzt.ipynb" which uses ModflowLak.
So, I wonder if you or someone can add further examples of ModflowLak class.
Thank you very much!
