### ISSUE TITLE
Python 3.X support?

### ISSUE THREAD

**Issue by stub68** [modflowpy/flopy#22]
Would it be possible to port Flopy3 to Python 3.X? In particular the binary file and plotting utilities would be very useful to have in Python 3. Thanks.

**Comment by mbakker7** [comment]
Is conversion to Python 3 (using one code base that works on Python 2 and
Python 3) something we may want to try at the MODFLOW conference?

What is the story on having both Python 2 and 3 on the same computer (else
it would be a bit hard to test)?

Mark

**Comment by jentjr** [comment]
You can setup a virtual environment to use different Python interpreters on the same computer.
http://docs.python-guide.org/en/latest/dev/virtualenvs/

If you are using the Anaconda Python distribution, it's fairly easy to create a virual environment with `conda create`

**Comment by langevin-usgs** [comment]
A group of flopy developers met at the MODFLOW conference and converted the flopy code so that it works with Python 2.x and Python 3.x.  This capability is currently on the "develop" branch but will be pulled into master for our next release.

**Comment by stub68** [comment]
Great news. Thank you.
