### ISSUE TITLE
ZoneBudget crashes with steady-state cbc file

### ISSUE THREAD

**Issue by tomvansteijn** [modflowpy/flopy#221]
the ZoneBudget utility does not seem to handle a CBC file from a steady-state calculation, where there are no stress periods defined. 

Error occurs in [https://github.com/modflowpy/flopy/blob/develop/flopy/utils/zonbud.py#L533](url)

**Comment by jdhughes-usgs** [comment]
Thanks for the bug report

**Comment by giovannifi** [comment]
Hi there,
I am experiencing the same problem even with a transient model. I get an empty list with the command:
self.cbc_times = self.cbc.get_times() (line 88)

**Comment by giovannifi** [comment]
Many apologies, I have just downloaded the file zonbud.py and replaced with the deafault one. It now works
