### ISSUE TITLE
You can't generally assume that binary records do not have a length byte pre- and postpended

### ISSUE THREAD

**Issue by Olsthoorn** [modflowpy/flopy#223]
Hi Joe,
Some compilers (not that used by USGS but indeed gfortran used on Macs and Unix) pre and postpend a byte that holds the record length for every separtely written binary record in the file. To do this is totally up to the compiler builder and not part  of the Fortran language. This implies in this case that head, drawdown, UCN and budget files may not be readable with the flopy code as it is now. For instance, I can't read the Tutorial02.hds file generated by mf2005.mac program that I compiled from source on the mac using gfortran (and used 10000 times in my mfLab code). It would generally not be a big deal to inlclude a check (see file appended) and add the extra bytes to the dtype after having figured out. I've done this in my mfLab ten years ago and it always worked.  However, your flopy implementation goes very deep and it assumes that the header_dtype can be obtained without having to inspect the binary file to be read. I find it not trivial at all to pinpoint a place to put the check and change the header_dtype to the correct one for the file (with the start and end byte in every record). Also, this change it should be taken along in the building of the pointer record. Could you have a look at it. I have included the hds file of Turorial02.hds genreated by the gfrotran compiled mf2005 executable, that contains these extra bytes. I have also included a test that shows it and determines what the correct dtype is.
With regards

Theo Olsthoorn
[tutorial2.hds.zip](https://github.com/modflowpy/flopy/files/1089462/tutorial2.hds.zip)

[test_for_debugging.py.zip](https://github.com/modflowpy/flopy/files/1089464/test_for_debugging.py.zip)

**Comment by jdhughes-usgs** [comment]
Hi Theo,

We have been using gfortran and have modified the unformatted file ```ACCESS``` to ```STREAM``` in the MODFLOW openspec.inc file to create a true binary without padding. The revised file looks like:

```
      CHARACTER*20 ACCESS,FORM,ACTION(2)
      DATA ACCESS/'STREAM'/
      DATA FORM/'UNFORMATTED'/
      DATA (ACTION(I),I=1,2)/'READ','READWRITE'/
```

You might find this to be an easy option to adopt on your end and then you won't have to deal with the padding issue any more.

We had a similar approach as your approach in earlier versions but moved away from it after we adopted ```STREAM``` ```ACCESS```.

I will look at whether we can add the functionality back. It may be an issue because we are automatically detecting whether the file is a single or double precision binary file.

Will let you know how it goes.

Joe

**Comment by Olsthoorn** [comment]
Hi Joe,
Thanks for the message and looking into it. Mark Bakker also told me about your solution. However, you have no control over files other people send to you, so it is preferable if the code detects these padding record length bytes in binary files automatically and deals with them without having to bother the user.

I think I solved the issue see your binaryfile.py attached with minor replacements to deal with these bytes. I added a function get_reclen_bytes(), which discovers whether the padding bytes are in the binary file. The call is in BinaryLayerFile.__init( ) and necessarily also in CellBudgetFile.__init__( ). The number of bytes either 0 or n (=4) are then stored in self.skip_bytes. I added the skip_bytes=self.skip_bytes in the signature of binaryread(... , skip_bytes=self.skip_bytes). The binaryread( ) skips these padding bytes wherever necessary, i.e. twice. I also included the skipping in binaryread_struct( ). It further is in the BinaryLayerFile._build_index( ), in the calls to binaryread( )  in BinaryLayerFile._read_data( ) and BinaryLayerFile._get_header, in CellBudgetFile._build_index( ) and CellBudgetFile._get_header( )
I guess I put the extra skipping of skip_bytes on as few places as possible so that the code is changed as little as possible. It seems to work well on my Mac, I can finally run the Tutorial examples using my unaltered gfortran compiled mf2005. You can just search for # TO to find all changes I made.

Some more points I found in your binaryfile.py:

line 56: was text=text[0:16], should be text=ttext[0:16]
line 320: recordlist = [] --> recordlist is never used
line 586: self.databytes may fail, as it is < 0 due to header['nlay'] <1 if model has 1 layer.
you used self.nlay = np.abs(header['nlay']) in line 576, but forgot to use np.abs in line 586. I suggest to use 
self.databytes = np.int64(header['ncol'] * \
                            np.int64(header['nrow'] * \
                            np.int64(np.abs(header['nlay']) * \
                            np.int64(self.realtype(1).nbytes)
I changed the code accordingly.

binaryfile.get_record  --> you say there that idx must be an array, but it must really be an int or otherwise the self.file.seek(ipos) crashes on line 925. From the call in the for-loop on line 876 it also follows that idx must be an int.
Because idx is an int, and not an array, the [0] brackets were removed from lines 926, 928, 931, 932 and 933.

That's all. It took me several days to fully understand the code and do it. The code is nice and deep. I guess I learned from it; I want to fully understand flopy anyway. So it was a good an intense exercise.

With the binaryfile thus added, I hope no-one should ever have to worry about these record length padding bytes that some fortran compilers add when their produced code writes any binary record. This also holds for modflow or mt3dms.
[binaryfile.py.zip](https://github.com/modflowpy/flopy/files/1118158/binaryfile.py.zip)


With kind regards

Theo

**Comment by Olsthoorn** [comment]
bug removed in binaryfile.py.zip new version. _read_data(self) back to original because skipping reclen_bytes not required here because the correct pointer position is stored in the built index.
[binaryfile.py.zip](https://github.com/modflowpy/flopy/files/1183174/binaryfile.py.zip)

**Comment by Olsthoorn** [comment]
Implementing the check for additional compiler generated record-length bytes requires too many changes to correctly read the compact budget file. Although I know exactly what needs to be done and have implemented it to 95%, this is no fun. The best way is to really apply Joe Hughes' compiler suggestion to overcome this nasty difficulty in its totality. It's straightforward with HDS, DDN and non-compact CBB files but not with the compact CBB file. Although one may run into it if binary files have to be read in generated by other Fortran compilers that implement the record length bytes, I quit it and go for Joe's suggestion.

**Comment by langevin-usgs** [comment]
Thanks for the update, Theo.  I think its probably better to move forward with a standard in which there is no byte padding.  This is what we've done in MODFLOW 6 using STREAM access, and I think what we should recommend in general.  I've been doing some work in binaryfile.py, so I will take a look at your other suggestions.  For now I will go ahead and close this issue.
