### ISSUE TITLE
change_model_ws incorrect when loading model from path including folders

### ISSUE THREAD

**Issue by tomvansteijn** [modflowpy/flopy#226]
Loading a model from namefile using a filepath including folders, e.g.:

``mf.Modflow.load('folder\subfolder\namefile.nam')``

and using change_model_ws to set the workspace to ``new_folder``, the path to namefile is set to:

``new_folder\subfolder\namefile.nam``

while this is the desired location:

``new_folder\namefile.nam``

Quickfixed this using ``os.path.basename``, see pull request. However I think ``BaseModel`` could be refactored in this aspect. For example like this:

- Namefile should be stored as basename (no folders)
- Model name should equal the basename of namefile minus extension
- Setting the namefile should set the workspace equal to the dirname of the namefile
- Is it necessary to have the namefile extension in a separate attribute?

**Comment by langevin-usgs** [comment]
So it doesn't look like your suggested change will work.  All of the tests fail with this change.  The whole pathing business has been a challenge with flopy, but I think we've settled on the current approach as the best.  I've had the most luck with loading by changing into the directory that contains the name file, loading the model,  and then changing workspace.

**Comment by tomvansteijn** [comment]
I see. I hadn't run the tests locally. Indeed I see failing tests in Travis, however for Python 3.6 just 3 out of 325 fail. But I do not want to disregard the considerations behind the current design. I am fairly new to flopy, so I might not oversee all consequences of this change.

**Comment by tomvansteijn** [comment]
Maybe I should be more careful hacking away in other people's code : )

**Comment by tomvansteijn** [comment]
Apparently the Modflow.load method also needs editing when using using a path including folders for the namefile. Otherwise the folders end up in the modelname argument. However this can be solved with a few lines of code.
