### ISSUE TITLE
flopy.modflow.mfbcf module

### ISSUE THREAD

**Issue by Menelik91630** [modflowpy/flopy#2268]
Hi,
When I load an existing modflow model with "Modflow.load", sf1 and sf2 in the bcf package are respectively specific yield and storage coefficient, the online manual says the opposite (https://flopy.readthedocs.io/en/latest/source/flopy.modflow.mfbcf.html).

**Comment by jlarsen-usgs** [comment]
From the documentation:

```
sf1 ([float](https://docs.python.org/3/library/functions.html#float) or array of floats (nlay, nrow, ncol)) – specific storage (confined) or storage coefficient (unconfined), read when there is at least one transient stress period. (default is 1e-5)

sf2 ([float](https://docs.python.org/3/library/functions.html#float) or array of floats (nrow, ncol)) – specific yield, only read when laycon is 2 or 3 and there is at least one transient stress period (default is 0.15)
```

sf1 is specific storage under confined conditions or storage coefficient (specific yield) if unconfined. This is consistent with the online documentation for modflow 2005. I think we could update the verbiage "storage coefficient" to specific yield to clarify. 

Removed the bug label and resassigned this as a documentation issue.

**Comment by Menelik91630** [comment]
Hi, thanks for the clarification.
Sorry for the disturbance.
