### ISSUE TITLE
bug(get-modflow): delayed python bin dir detection

### ISSUE THREAD

**Issue by wpbonelli** [modflowpy/flopy#2274]
**Describe the bug**
When running `get-modflow` with a fresh Python environment and flopy install, the `:` option does not resolve the environment's bin dir until deactivating/reactivating the environment.

**To Reproduce**

1. Make a new environment e.g. `python3 -m venv venv`
2. Activate the environment `source venv/bin/activate`
3. Install flopy `pip install flopy`
4. Install executables with the selection help option `get-modflow :`

**Expected behavior**
The environment's bin directory should immediately be an option. Instead we see the bin dir associated with the Python used to create the environment (option 3):

```
$ (venv) get-modflow :
select a number to extract executables to a directory:
 1: '/Users/wbonelli/dev/pyphoenix-project/venv/bin' -- previously selected bindir (':prev')
 2: '/Users/wbonelli/.local/share/flopy/bin' -- used by FloPy (':flopy')
 3: '/Library/Frameworks/Python.framework/Versions/3.12/bin' -- used by Python (':python')
 4: '/Users/wbonelli/.local/bin' -- user-specific bindir (':home')
```

Only after de/reactivation is option 3 the virtual env's bin dir

```
$ (venv) deactivate
$ source venv/bin/activate
$ (venv) get-modflow :
select a number to extract executables to a directory:
 1: '/Users/wbonelli/dev/pyphoenix-project/venv/bin' -- previously selected bindir (':prev')
 2: '/Users/wbonelli/.local/share/flopy/bin' -- used by FloPy (':flopy')
 3: '/Users/wbonelli/Desktop/flopytest/venv/bin' -- used by Python (':python')
 4: '/Users/wbonelli/.local/bin' -- user-specific bindir (':home')
```

Maybe related to the way setuptools installs the script on flopy install?

**Desktop (please complete the following information):**
Confirmed only on macOS and builtin `venv`. Have not checked if occurs on other platforms.

**Comment by mwtoews** [comment]
I suspect this issue applies only to macOS, as I cannot replicate it on Linux or Windows. My tests show the `:python` option is always the same directory where the venv python interpreter is located.

**Comment by wpbonelli** [comment]
Maybe related to https://github.com/python/cpython/issues/86478#issuecomment-1093891031, specifically https://github.com/python/cpython/issues/86478#issuecomment-1093891029 and the comment below?

I don't see a way around it so might just add a note to the docs.
