### ISSUE TITLE
ipakcb not equal to 53

### ISSUE THREAD

**Issue by OnnoEbbens** [modflowpy/flopy#232]
I create a new drn package for my existing model (which was not created with flopy). In this model the budgets are written to the cbc file on number 50. When I create a new drn package using flopy with the following code:

`drn = flopy.modflow.ModflowDrn(mf, ipakcb=50, stress_period_data=drn_spd,extension='dat')`

I notice that the ipakcb is set to 53 (instead of 50) due to the following code in ModflowDrn.__init__:

```
if ipakcb != 0:
    self.ipakcb = 53
else:
    self.ipakcb = 0  # 0: no cell by cell terms are written
```

Is there a reason why the budget file is hard coded on unit number 53?

**Comment by langevin-usgs** [comment]
The handling of the ipakcb argument has been fixed on the develop version of flopy.  You can install the develop version or wait for the next flopy release.  Let us know if it does not behave as you think it should.
