### ISSUE TITLE
bug: typo shapely function call within gridintersect

### ISSUE THREAD

**Issue by sannedesmet** [modflowpy/flopy#2342]
**Describe the bug**
Within utils/grindintesect.py  function "def _intersect_linestring_shapely2"  the function shapely.multilinestring() is called in line 969.
However this function doesn't exist and should be changed to shapely.multilinestring**s**()

**To Reproduce**
Shapely with a version above 2 has to be installed.
In specific cases if multiple parts of a linestring are within one cell this function will be called
This is quite rare, that is the reason I think this bug is not noticed before, since it has been present for quite some releases of flopy.

**Expected behavior**
I expected a multilinestring as output, however I got the error as given below

**Screenshots**
![image](https://github.com/user-attachments/assets/d8387d5b-5034-4427-927c-35fd86ba369c)

**Comment by dbrakenhoff** [comment]
Thanks @sannedesmet for the bug report, I would have thought this was captured by our tests, but I'll check it out and report back here!

Any chance you can share the shape/grid you are intersecting with?

**Comment by sannedesmet** [comment]
Thanks for the quick reply @dbrakenhoff. I wanted to use a pull request to solve this bug, as it is relatively easy. However in the codecov file of flopy of a colleague I saw that the current test functions do not cover these specific lines. I got stuck writing a test, therefore I decided to write this issue. 

The model that triggered this bug is quite large. It took me awhile to isolate the linestring that triggered the bug. 
But this is the file: [linestring_shapely2_bug.zip](https://github.com/user-attachments/files/17475919/linestring_shapely2_bug.zip)
The grid that corresponds to the error is a structured grid, with RD-coordinates: xmin = 103616, xmax = 105934, ymin =490937, ymax= 492815. With cellsize 2x2. 

Is this sufficient or do you prefer a different way of sharing the grid?
