### ISSUE TITLE
bug: gridgen/g.build does not run 

### ISSUE THREAD

**Issue by MichelCraninx** [modflowpy/flopy#2350]
Running gridgen.exe/g.build error during local grid refinement

When we try to run the gridgen.exe for local grid refinement with g.build() we get errors.
1) First there was the error missing msvrc100.dll file and msvcp100.dll file. 
2) I have updated microsoft visual c++. This did not solve the problem.
3) I have downloaded therefore manually these file and copied them into the same folder as gridgen.exe. This did not solve the problem.
4) Now I get the error (in a separate window): "The application was unable to start correctly (0xc000007b). Click OK to close the application.
5) My colleague has the same problem with the gridgen.exe. Can this be to computer settings or missing files? Is there a specific version of the dll files necessary and which is the location where I place these files? 

What can we do to run gridgen.exe/g.build correctly?

**Screenshots**
![image](https://github.com/user-attachments/assets/4a90c95c-5b4e-4706-9df3-4702ff9f6411)
![image](https://github.com/user-attachments/assets/6db062f8-948e-4e67-8c4c-fc99c5535dd6)

Windows 10
Microsoft edge

**Comment by wpbonelli** [comment]
Hi @MichelCraninx could you let us know where you got the gridgen executable / how you installed it?

**Comment by MichelCraninx** [comment]
Hi, we found the problem. It was indeed the wrong gridgen executable. We replaced the gridgen executable with the _v64 version and now it works. Thank you.

**Comment by wpbonelli** [comment]
Ok, great.
