### ISSUE TITLE
one-based arrays in mfdis.get_node

### ISSUE THREAD

**Issue by hwreeves-USGS** [modflowpy/flopy#236]
I think mfdis.get_node is using one-based arrays which does not seem compatible with the zero-based arrays used in other modules.  

node should be int( (k * nrc) ) + (i*self.ncol) + j + 1

gives the node number starting at 1 for output - could leave the 1 off to get zero-based node numbering.

HWR

**Comment by langevin-usgs** [comment]
@aleaf, any thoughts on this?  Looks like the only place it is called is in the SFR package.  This might mean that the node column in sfr.reach_data is incorrect.

```
        # assign node numbers if there are none (structured grid)
        if np.diff(self.reach_data.node).max() == 0 and 'DIS' in self.parent.get_package_list():
            # first make kij list
            lrc = self.reach_data[['k', 'i', 'j']]
            lrc = (lrc.view((int, len(lrc.dtype.names))) + 1).tolist()
            self.reach_data['node'] = self.parent.dis.get_node(lrc)
```

**Comment by aleaf** [comment]
I agree that it should be zero-based. It isn't affecting much at the moment, as it looks like it is only being used in the SFR module to check for cells that have more than 1 SFR reach.
