### ISSUE TITLE
mflpf.py line 260,   CHANI must be < 0 before swithing to read HANI not < 1

### ISSUE THREAD

**Issue by Olsthoorn** [modflowpy/flopy#237]
CHANI must be < 0 before reading HANI not < 1

This according to the MODFLOW manual. It failed when tried to set CHANI to a small value.

See correction in attached file.

[mflpf_issue.pdf](https://github.com/modflowpy/flopy/files/1236488/mflpf_issue.pdf)

**Comment by langevin-usgs** [comment]
Thanks for this!  I made one small tweak, instead of CHANI < 0., I used CHANI <= 0.  Note that I also had to handle the load too, which used the same wrong logic.  Let me know if you have a simple test problem for this.  I would be good to add a test so that this problem doesn't ever creep back in.

**Comment by andrewcalderwood** [comment]
It appears this is still an issue for flopy.modflow.mfupw where when CHANI = 0 the HANI arrays are not written because the if statement is specified as < 0 instead of <= 0.

`for k in range(nlay):
            f_upw.write(self.hk[k].get_file_entry())
            if self.chani[k] < 0:
                f_upw.write(self.hani[k].get_file_entry())
            f_upw.write(self.vka[k].get_file_entry())`
