### ISSUE TITLE
some small bugs in CBB flopy.utils.binaryfile.py

### ISSUE THREAD

**Issue by Olsthoorn** [modflowpy/flopy#238]
At some locations binaryread(...) missis [0] when reading scalar. This causes a future warning (because an np.array([scalar]) is returned instead of the scalar and then used as an int.

There are some other similar issues. I indicated all corrections with #TO behind the line in the file.
[binaryfile.py 2.zip](https://github.com/modflowpy/flopy/files/1240262/binaryfile.py.2.zip)

**Comment by pandoramix** [comment]
I just spent the whole afternoon trying to figure out why I am getting errors when trying to plot velocities form my .cbc file and luckily i stumbled upon your corrected version of the binary file. Thanks a lot for doing that and sharing it here, you made my monday a better day in the end! :)
