### ISSUE TITLE
mt3d.BTN: starting concentrations

### ISSUE THREAD

**Issue by wjzRdam** [modflowpy/flopy#24]
The following script:
import flopy

# Create the basic MODFLOW model structure
mf = flopy.modflow.Modflow('steven')

# Create the basic MT3DMS model structure and default BTN package
mt = flopy.mt3d.Mt3dms('steven', 'nam_mt3dms', mf)
btn = flopy.mt3d.Mt3dBtn(mt)

Gives an error:
Traceback (most recent call last):
  File "btn_problem.py", line 8, in <module>    btn = flopy.mt3d.Mt3dBtn(mt)
  File "C:\Anaconda\lib\site-packages\flopy\mt3d\mtbtn.py", line 186, in __init__
    self.sconc = [u3d]
  File "C:\Anaconda\lib\site-packages\flopy\mbase.py", line 584, in __setattr__
    if isinstance(old_value[0], utils.util_3d):
IndexError: list index out of range

The error is eliminated when line 186 of the file ...\Lib\site-packages\flopy\mt3d\mtbtn.py:
        self.sconc = [u3d]
is replaced by:
        self.sconc.append(u3d)

Willem Zaadnoordijk

**Comment by YonasTH** [comment]
I get the same error trying to run the 'Henry salt water intrusion' example in the Flopy documentation
http://nbviewer.ipython.org/github/modflowpy/flopy/blob/master/examples/Notebooks/henry.ipynb

**Comment by jdhughes-usgs** [comment]
This issue has been addressed in the development branch of flopy but has not been migrated to the master yet. Please pull from the development branch until the next official release.
