### ISSUE TITLE
yul used as yll in ModelCrossSection

### ISSUE THREAD

**Issue by rubencalje** [modflowpy/flopy#240]
Hi there, using the great ModelCrossSection class, it seemed to me that the yul-parameter (y coordinate for upper left corner) is used as if it is yll (y coordinate for lower left corner). Because of this, flopy thinks my crosssection-line is outside of the grid. I think the following lines should be different:

line 96:
`self.sr.yul = 0`
should be:
`self.sr.yul = self.dis.delc.sum()`

line 123:
`yp -= self.sr.yul`
should be:
`yp -= self.sr.yul-self.dis.delc.sum()`

Regards,

Ruben

**Comment by langevin-usgs** [comment]
Hi Ruben, do you have a very short script or notebook that you could send that illustrates the problem.  I think we need to see how sr is set (if it is) or created before coming instantiation of the ModelCrossSection class.

**Comment by rubencalje** [comment]
Here is a short example that gives an error:

```
import flopy
import matplotlib.pyplot as plt

mf = flopy.modflow.Modflow()

# Model domain and grid definition
flopy.modflow.ModflowDis(mf, nlay=1, nrow=10, ncol=20, delr=1., delc=1.)

fig,ax=plt.subplots()
verts=[[1.,1.], [19.,9.]]
modelxsect = flopy.plot.ModelCrossSection(model=mf, line={'line': verts},
                                          xul=mf.dis.sr.xul,yul=mf.dis.sr.yul)
linecollection = modelxsect.plot_grid()
```

If I change the line in 
```
modelxsect = flopy.plot.ModelCrossSection(model=mf, line={'line': verts},
                                          xul=mf.dis.sr.xul,yul=0)
```
the scripts is doing what I want (drawing a cross-section from x=1 and y=1 to x=19 and y=9)

**Comment by rubencalje** [comment]
A better exemple is when I actually use xul and yul:

```
import flopy
import matplotlib.pyplot as plt

mf = flopy.modflow.Modflow()

# Model domain and grid definition
flopy.modflow.ModflowDis(mf, nlay=1, nrow=10, ncol=20, delr=1., delc=1.,xul=100,yul=210)

fig,ax=plt.subplots()
verts=[[101.,201.], [119.,209.]]
modelxsect = flopy.plot.ModelCrossSection(model=mf, line={'line': verts},
                                          xul=mf.dis.sr.xul,yul=mf.dis.sr.yul)
linecollection = modelxsect.plot_grid()
```

gives an error, while

```
modelxsect = flopy.plot.ModelCrossSection(model=mf, line={'line': verts},
                                          xul=mf.dis.sr.xul,yul=mf.dis.sr.yul-mf.dis.delc.array.sum())
```

draws the cross-section I am looking for

**Comment by aleaf** [comment]
this doesn't solve Ruben's problem, but digging in a bit, it looks like the `ModelCrossSection` object resets xul and yul in `SpatialReference` if xul and yul aren't submitted as arguments. Seems like it should get these from `SpatialReference` if they aren't argued.
```        
# Set origin and rotation
if xul is None:
    self.sr.xul = 0.
else:
    self.sr.xul = xul
if yul is None:
    self.sr.yul = 0
else:
    self.sr.yul = yul
```

**Comment by aleaf** [comment]
I think this should fix the problem https://github.com/modflowpy/flopy/pull/234

**Comment by langevin-usgs** [comment]
Should be fixed now.  Let us know if you still have problems.  Thanks.
