### ISSUE TITLE
code cleanup is coming! and we need more tests...

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#242]
Kind of scary...you can inspect a specific file to see what not covered
[https://coveralls.io/github/modflowpy/flopy](https://coveralls.io/github/modflowpy/flopy)

**Comment by aleaf** [comment]
hey, 69% is like a D+ right?

**Comment by langevin-usgs** [comment]
That's awesome.

**Comment by jdhughes-usgs** [comment]
We are better than matplotlib ([https://github.com/matplotlib/matplotlib.git](https://github.com/matplotlib/matplotlib.git))
