### ISSUE TITLE
problems in plot_pathline with layer='all'

### ISSUE THREAD

**Issue by mbakker7** [modflowpy/flopy#243]
Kevin Hayley  came across a bug in the `plot_pathline` method of the `ModelMap` object in `map.py`.
When I call the `plot_pathline` function using the `layer='all'` keyword as is in the ipython notebook example nothing gets plotted. The error occurs in this part of the code (near line 649):

         if 'layer' in kwargs:
            kon = kwargs.pop('layer')
            if isinstance(kon, bytes):
                kon = kon.decode()
            if isinstance(kon, str):
                if kon.lower() == 'all':
                    kon = -1
                else:
                    kon = self.layer`

When I run through this line by line with a dictionary named kwargs with entry {'layer':'all'}
the if statement ` if isinstance(kon, bytes):` comes up as true, the decode method then converts the string `'all'` to Unicode then the if statement `if isinstance(kon, str)` ignores kon and the rest of the function is applied with kon as a Unicode version of 'all'.  when I run the function with `'layer'=-1` it plots fine. This is on Python 2.7.

**Comment by jdhughes-usgs** [comment]
[Fixed](https://github.com/modflowpy/flopy/commit/a1ec2d6d2ee9c0bda938cc1f002df936fe620291)
