### ISSUE TITLE
SFR2 options (e.g. reachinput) for mfnwt

### ISSUE THREAD

**Issue by hansonmcoombs** [modflowpy/flopy#247]
mfnwt does not support SFR options (such as reachinput) on one line and would prefer something as follows:
options
reachinput
end

I have made a personal work around to the load and write functions of SFR (attached).  Feel free to use it, or make a more comprehensive version.
[sfr_modification.txt](https://github.com/modflowpy/flopy/files/1291087/sfr_modification.txt)

**Comment by porterma** [comment]
I just ran into this same problem where flopy will not successfully load a sfr package for model running modflow nwt. The sfr package was exported from Groundwater Vistas and looks like this:

# SFR Package for MODFLOW2000
OPTIONS
REACHINPUT
END
 2080  116  0  0  1.283904e+005  1.000000e-004  51  -51 1 0 0 0
  1  214  100  1  1  331.054282  8001.750000  0.182060  2.000000  15.000000
  1  214  99  1  2  176.300226  7921.470215  0.182060  2.000000  15.000000
  1  213  99  1  3  170.011392  7920.220215  0.182060  2.000000  15.000000
  ...

I am able to get around this by deleting the OPTIONS and END lines. Just wondering if there are plans to support this format of the sfr package in flopy or if it's an outdated format. Thanks!
