### ISSUE TITLE
Change starting heads after loading pre-existing model?

### ISSUE THREAD

**Issue by porterma** [modflowpy/flopy#260]
I have loaded a model using the following command:
`mf = flopy.modflow.Modflow.load('{}.nam'.format(mfname), version=mfver, exe_name=mfexe, check=False)`

Now I want to change the starting heads in the bas6 package before I run the rerun model. How do I reassign values to strt in the bas6 package?

**Comment by porterma** [comment]
I think I figured out something that works:

`mf.get_package('bas6').strt = new_initial_heads`

Not sure if this is the best way to do it though.

**Comment by jtwhite79** [comment]
That's about how I do it (not that I'm doing the best way either):

```
>>>hds = flopy.utils.HeadFile("heads.hds")
>>>mf.bas6.strt = hds.get_data()
```

That would update the initial heads using the last head array in a headsave file.

**Comment by porterma** [comment]
That was my initial attempt except that in my haste I tried mf.bas.strt and didn't catch my typo. Thanks for the reply.
