### ISSUE TITLE
export (shapefile.shp) is producing failed geometries in arcmap 

### ISSUE THREAD

**Issue by rosskush** [modflowpy/flopy#261]
Hello all, long time user, first time issue-er.

Recently I have been using the .export() method for bringing out shapefiles for use in GIS tools. Well it turns out that for whatever reason when you bring in the shapefile into arcgis and try to run geometry in the field calculator, it'll give some wonky negative areas for the cell areas.

Now, using QGIS this is not the issues and QGIS realizes that you can't have a negative area and will get you what you need.

Either way I think we can rack another up win for open source tools, but I did want to bring it up so arc users are aware of this issue and hopefully someone can shed some light on the reason.
P.S. (I have tried this with multiple shapefiles)

**Comment by langevin-usgs** [comment]
I wonder if we're listing the cell vertices in the proper clockwise (or counter-clockwise) order.

**Comment by aleaf** [comment]
This does seem to be the issue, but mostly with ArcMap:
https://gis.stackexchange.com/questions/119150/order-of-polygon-vertices-in-general-gis-clockwise-or-counterclockwise

Shapely computes the areas correctly.
