### ISSUE TITLE
 Functions output their docstring by default?!

### ISSUE THREAD

**Issue by joha1** [modflowpy/flopy#264]
When I use flopy, everything seems to output it's docstring whenever I use it. E.g.

    In [10]: fpm.ModflowDis(model, nlay = 1, nrow=1, ncol=cols, delr=1, delc=10, top=20, botm=0)
    Out[10]:  warning: assuming SpatialReference units are meters
    
    
        MODFLOW Discretization Package Class.
    
        Parameters
        ----------
        model : model object
            The model object (of type :class:`flopy.modflow.Modflow`) to which
            this package will be added.
        nlay : int
            Number of model layers (the default is 1).
    and so on…
    lenuni = 2 (int)
    ncol = 10 (int)
    nlay = 1 (int)
    nper = 1 (int)
    nrow = 1 (int)
    nstp = <flopy.utils.util_array.Util2d object at 0x7f4bf6ecf790> ('flopy.utils.util_array.Util2d)
    perlen = <flopy.utils.util_array.Util2d object at 0x7f4bf6ecf690> ('flopy.utils.util_array.Util2d)
    sr = xul:0; yul:10; rotation:0; proj4_str:+init=EPSG:4326; units:meters; lenuni:2; length_multiplier:1.0 ('flopy.utils.reference.SpatialReference)
    start_datetime = 1-1-1970 (str)
    steady = <flopy.utils.util_array.Util2d object at 0x7f4bf6ecf890> ('flopy.utils.util_array.Util2d)
    top = <flopy.utils.util_array.Util2d object at 0x7f4bf6ecf5d0> ('flopy.utils.util_array.Util2d)
    tsmult = <flopy.utils.util_array.Util2d object at 0x7f4bf6ecf810> ('flopy.utils.util_array.Util2d)
    unit_number = 11

which makes navigating in my ipython shell a bit annoying.

I can get why you'd want to output things like `ncol = 10 (int)     nlay = 1 (int)`, but most of the other stuff does not seem to make sense to me. So:

**Is this a bug?**
**Or is there a good reason for this?**
**Or am I just doing something wrong?**

**Comment by langevin-usgs** [comment]
Easiest thing to do is just grab that information into a dis object, like this:

```
dis = fpm.ModflowDis(model, nlay=1, nrow=1, ncol=cols, delr=1, delc=10, top=20, botm=0)
```

**Comment by joha1** [comment]
Thanks for the heads up!
This is what I'm doing most of the time and it definitely makes sense to do it like that in most cases, so this is not a big issue, but I'd still be curious why this is handled like this.
