### ISSUE TITLE
ensure user specified files are used rather than passed Modflow object, modpath

### ISSUE THREAD

**Issue by hansonmcoombs** [modflowpy/flopy#265]
line 60 mp.py reads: 
            head_file = self.__mf.get_output(unit=iu) 
it should be:
            head_file = self.__mf.get_output(unit=iu) if head_file is None else head_file

similarly line 71 should read:
            budget_file = self.__mf.get_output(unit=iu) if budget_file is None else budget_file

This arises as a Modflow object must be passed to the Modpath object in order to create the ModpathBas object: (lines 76 and 77 of mpbas.py)  A dummy model (with a simple lpf) can be passed instead, but the users files must be used. I am doing this for speed

**Comment by langevin-usgs** [comment]
Can you add a new test to autotest/t049_test.py to demonstrate the functionality that you would like to see?  That would be helpful for us to see how it fails for your particular case.

**Comment by jdhughes-usgs** [comment]
closing will reopen if necessary
