### ISSUE TITLE
sfr checker with negative outseg (LAK)

### ISSUE THREAD

**Issue by briochh** [modflowpy/flopy#269]
Minor issue with sfr checker when "Checking for increasing segment numbers in downstream direction...". When sfr is routed to lake, outseg is negative which looks like a downstream segment number decrease so gives warning. Would it be reasonable to ignore negative outsegs from checker?

**Comment by jdhughes-usgs** [comment]
@aleaf-usgs did you ever see this issue? It is pretty stale but may be valid.
