### ISSUE TITLE
MT3DMS

### ISSUE THREAD

**Issue by cthrnmoore09** [modflowpy/flopy#271]
I am running MT3DMS successfully in terms of no mass balance percentage errors, meaningful concentrations, but still getting a false  message at the end of the run, i.e. (False, []).  Thoughts?

**Comment by langevin-usgs** [comment]
I bet we aren't checking for the correct termination message.  In mt3d it looks like it ends with "Program completed.".

Maybe you can try passing this string into the run_model method as 

```
m.run_model(normal_msg='Program completed.')
```

**Comment by cthrnmoore09** [comment]
Thankyou. It works perfectly.
 as m.run_model(normal_msg='Normal termination of simulation')
