### ISSUE TITLE
MF6 Simple Lake Example

### ISSUE THREAD

**Issue by dpphat** [modflowpy/flopy#273]
Hi all. Thanks so much for your work on this project.
I think it makes great steps towards reproducible models.
I am trying to follow the examples in the tutorial for MODFLOW 6.
When I run the script to make the MFSimulation:

# Create the Flopy simulation object
sim = flopy.mf6.MFSimulation(sim_name=name, exe_name='mf6', 
                             version='mf6', 
                             sim_ws = workspace, 
                             sim_tdis_file = 'simulation.tdis')

I get the following error:

  File "C:\Program Files\Anaconda3\lib\site-packages\flopy\mf6\data\mfstructure.py", line 92, in get_file_list
    files = os.listdir(dfn_path)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Anaconda3\\lib\\site-packages\\flopy\\mf6\\data\\dfn'

I am running on Microsoft Windows 7 (64bit) with Intel Xeon CPU E3-1505M v5 @ 2.8GHz and 16GB Ram
3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
numpy version: 1.13.3
matplotlib version: 1.5.3
flopy version: 3.2.7
Thanks so much.

**Comment by langevin-usgs** [comment]
Can you check and see if there is a folder with this name: C:\Program Files\Anaconda3\lib\site-packages\flopy\mf6\data\dfn.  And in that folder, there should be a bunch of files with a .dfn extensions.  The same files shown here: https://github.com/modflowpy/flopy/tree/develop/flopy/mf6/data/dfn.

Also, just out of curiosity, are you running from a different drive than C?

**Comment by dpphat** [comment]
Wow...that was fast.
There is no dfn folder within the existing
'C:\Program Files\Anaconda3\Lib\site-packages\flopy\mf6\data'
The only folder in that directory is _pycache_

I am trying to run the simulation from a different directory.
In the script I call:

'os.chdir("C:\\Users\\dpuddephatt\\Documents\\Python\\flopy")
cwd = os.getcwd()'

and then I modified the workspace example to the following:
workspace = os.path.join(cwd, 'data', 'mf6lake')
if not os.path.exists(workspace):
    os.makedirs(workspace)

Thanks so much Chris!

**Comment by langevin-usgs** [comment]
That folder has to have those dfn files in it.  I need to figure out why they are not there.

**Comment by langevin-usgs** [comment]
Okay, I think I have fixed the problem so that these files will now be included when you install flopy.  I think your best bet is to first uninstall flopy, and then install the **development** version as described on the main flopy page (https://github.com/modflowpy/flopy).  It's important that you install the development version.  Please let me know if this works by either closing this comment, or letting me know what happens why you try to run the MODFLOW 6 tutorial.  Hope this works!

**Comment by dpphat** [comment]
Thank you so much Chris.
I will try that today.

**Comment by dpphat** [comment]
Hi Chris.
I tried uninstalling flopy using:
pip uninstall flopy
This did not uninstall flopy. Does it matter that I have flopy 3.2.7
installed rather than 3.2.6?
I tried installing the development version over the existing flopy
installation but it did not create the dfn folder. Likely because the old
version was not uninstalled.
Thanks again for your assistance.
Dan Puddephatt

**Comment by langevin-usgs** [comment]
You need to eliminate that previous flopy version somehow.  You might even be able to go into your python folder under Lib/site-packages and remove the flopy folder.  And then install the develop version.

**Comment by dpphat** [comment]
Thanks Chris.
I will try manually deleting that folder.

**Comment by langevin-usgs** [comment]
By the way, I think we are also going to make a flopy bug fix release tonight in order to make these files available so the modflow 6 classes work.

**Comment by dpphat** [comment]
Thanks Chris.
I now have the dfn folder. I now get the following error:

  File "C:\...\anaconda3\lib\site-packages\flopy\mf6\mfsimulation.py", line 750, in register_package
    ex_recarray = self.name_file.exchangerecarray

AttributeError: 'NoneType' object has no attribute 'name_file_struct_obj'

after running the following function: 
sim = flopy.mf6.MFSimulation(sim_name=name, exe_name='mf6', 
                             version='mf6', sim_ws=workspace)

from the tutorial.
Thanks so much.

**Comment by langevin-usgs** [comment]
@dpphat not sure what is going on here.  I can run the mf6 tutorial notebook that is on the website without any problem.  Can you run this?

```
import os
import sys
import flopy

sim_name = 'example_sim'
sim_path = os.path.join('example_project')
sim = flopy.mf6.MFSimulation(sim_name=sim_name, version='mf6', exe_name='mf6', 
                             sim_ws=sim_path, 
                             sim_tdis_file='simulation.tdis')
```

This works for me.

**Comment by dpphat** [comment]
ok...that does work.
I'm not sure why it didn't a moment ago.
The tutorial script is also working now.
I will close this issue.
Thank you so much for your help.
