### ISSUE TITLE
Problems reading the LST file. 

### ISSUE THREAD

**Issue by Hperea** [modflowpy/flopy#274]
I'm having problems reading the LST file. This is the error.

mfl=flopy.utils.MfListBudget(model_ws,"PHX_AMA_AG_ext_file.LST")
Traceback (most recent call last):

  File "<ipython-input-21-b49492c39786>", line 1, in <module>
    mfl=flopy.utils.MfListBudget(model_ws,"PHX_AMA_AG_ext_file.LST")

  File "C:\Users\hperea\AppData\Local\conda\conda\envs\my_root\lib\site-packages\flopy\utils\mflistfile.py", line 51, in __init__
    self.f = open(file_name, 'r')

IOError: [Errno 13] Permission denied: 'h:\\PHX_Transient\\MODEL\\MF_output\\TRAN12112017120159'

How can I read the LST file?
Is this a bug?

Thanks for your help.

Hugo Perea

**Comment by langevin-usgs** [comment]
MfListBudget requires the first argument to be the name of the file.  You passed in the path and then the file name.  Try this instead:  mfl=flopy.utils.MfListBudget(model_ws+"\PHX_AMA_AG_ext_file.LST")

**Comment by Hperea** [comment]
The second option works but the first one gave and error "AssertionError: file_name PHX_AMA_AG_ext_file.LST not found". 

Thanks!
Hugo
