### ISSUE TITLE
mf6 Simple Model Notebook Example Plot Issue

### ISSUE THREAD

**Issue by kbrewerphd** [modflowpy/flopy#280]
A great example Notebook, but I noticed that if the constant head cell was changed to coordinates: N/4, N/4  (i.e., not at the center), the head plot using plt.contour do not match the head plot using the Flopy model map capabilities. I think the issue is with the location of the origin being different between the two.

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs could you take a look at this?
