### ISSUE TITLE
How to specify an MFArray

### ISSUE THREAD

**Issue by langevin-usgs** [modflowpy/flopy#281]
Can we specify a list of numpy arrays for a layered model?  The following code does not seem to work.

```
nlay = 3
nrow = 10
ncol = 10
idomain = [np.ones((nrow, ncol), dtype=np.int), np.zeros((nrow,ncol), dtype=np.int), np.ones((nrow, ncol)), dtype=np.int)]
```

**Comment by spaulins-usgs** [comment]
I think I found and fixed the problem.  Please try the latest flopy code from the development branch.
