### ISSUE TITLE
unwrapped arrays

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#283]
Is there a way to write all arrays as unwrapped arrays?

**Comment by spaulins-usgs** [comment]
The MFSimulation class contains a simulation_data attribute which contains a wrap_multidim_arrays flag: 

sim.simulation_data.wrap_multidim_arrays = False

If this is set to false the mfdataarray object's get_file_entry method will generate a file entry without using line wraps.   Note that while this feature does what it claims, printing the entire array out on a single line, I noticed MF6 does not always accept input on a single line.  For now this feature is primarily for someone who wants to generate data files of their own.  Using this feature to create MF6 input files may result in input files that MF6 will not read.  If this feature is going to be used to generate MF6 files I will need to figure out why MF6 will not always read data when it is all on a single line.
