### ISSUE TITLE
Intermittent Build Errors

### ISSUE THREAD

**Issue by spaulins-usgs** [modflowpy/flopy#285]
The Travis builds have been failing intermittently.  Yesterday the Python 3.5 build job failed with:

"AssertionError: could not run flopy3_MapExample.ipynb"

After that failure I checked in some documentation updates that should not have affected the build results, yet the next build passed.  I just checked in some more documentation updates and now the Python 3.6 build job is failing with:

"AssertionError: could not run flopy3_ZoneBudget_example.ipynb"

It looks like the jupyter notebook app is failing when it tries to bind to a TCP socket because the socket is already in use.

"File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use"

I'm guessing that Travis runs multiple builds on the same machine at the same time.  If two builds on the same machine try to test a notebook at the same time, the 2nd test will fail because the first test will already have the TCP port in use.

If this is the problem we might solve it by trying to run a notebook again on failure instead of failing the test immediately.  A limit could be set on the number of attempts so that it doesn't get caught in an infinite failure loop.  Also, on each attempt we could increment the port number using the --port switch to try and find a free port.

**Comment by langevin-usgs** [comment]
Let's keep an eye on this, Scott.  Travis has been picky this past week.  Maybe it'll settle down.  If not, then let's implement some rerun capabilities.  What a pain.
