### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by person0712** [modflowpy/flopy#286]
I am trying to creating an executable from a Python script including the flopy.utils.binaryfile Module by using PyInstaller. But I got two errors shown in the command window. One is "AttributeError: module 'enum' has no attribute 'IntFlag' " which is shown during the running process, and the other one is " AttributeError: 'str' object has no attribute 'items' " which is where the process stopped. I don't know what exactly causes (e.g. path) these errors and how to solve them. And I wonder that is the flopy module supported by the PyInstaller, which might cause the error? I appreciate any possible opinions and thoughts. Thanks!

Here is the python script:

import flopy.utils.binaryfile as bf
ccf= bf.CellBudgetFile('1997.ccf')
x1=ccf.get_record(3)
import numpy as np
np.savetxt('Sp1.txt',x1)

It is able to run with Python 3.6.4 (Anaconda custom 32-bit)
Additional information:
PyInstaller 3.3.1
flopy 3.2.8
enum34 1.1.6
numpy 1.13.3
Windows 10 64 bit

**Comment by langevin-usgs** [comment]
Looks like the answer for the enum34 issue can be found here: https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag.  I think you can uninstall enum34 and not use it.

**Comment by person0712** [comment]
Thank you for your suggestion, it works! After that although I faced issue "maximum recursion depth exceeded", I increased the setrecursionlimit to 5000 by creating a .spec file, which also worked well. I can create an executable file from my python script now, but I get an error while running it. It seems like I don't add the module "flopy" successfully into the executable file because there is not a file named "flopy" in the created file "dist". How can I do to add the module into the executable file? Thanks. 

Additional information:
test.py is shown above.
test.spec is shown below,
# -*- mode: python -*-
import sys
sys.setrecursionlimit(5000)

block_cipher = None


a = Analysis(['test.py'],
             pathex=['C:\\Users\\yche122\\Desktop\\Calibration'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='test',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='test')

The error is attached in the link.
![error](https://user-images.githubusercontent.com/34916013/35582825-98b70b1e-05b5-11e8-9246-5f56fce9daf2.png)

**Comment by lamourj** [comment]
Have you tried the latest `develop` version of PyInstaller? I have seen something similar recently and I think it might have been fixed. 
Disclaimer: (1) can't find the issue mentioning that again, (2) not sure it will do the trick for you. 
But definitely worth trying if you didn't.

**Comment by vijay-vimal** [comment]
how can i solve this problem.
Django Version: | 2.2.7

AttributeError
'str' object has no attribute 'items'
C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in prepare_headers, line 446

**Comment by jlarsen-usgs** [comment]
@person0712 

You will have to point pyinstaller to the `longnames.json` file in your spec file. This process is covered in the pyinstaller documentation [pyinstaller](https://pyinstaller.readthedocs.io/en/stable/spec-files.html).

Here is the example they provide:
```
a = Analysis(...
     datas=[ ('src/README.txt', '.') ],
     ...
     )
```
