### ISSUE TITLE
Can flopy reads subsidence output?

### ISSUE THREAD

**Issue by ougx** [modflowpy/flopy#288]
I noticed that it supports writing the sub file. But I could not find the function to read the output file. Is it not able to do that?

**Comment by jtwhite79** [comment]
The binary sub output files all follow the head-save format, so you can use HeadFile to read them
```
>>>sb  = flopy.utils.HeadFile('model.sub',text='subsidence')
```
The key is the ``text`` arg - check out ``t040_test.py`` in the autotest directory for more examples for the various sub outputs
