### ISSUE TITLE
No module named 'flopy'

### ISSUE THREAD

**Issue by mssmith63** [modflowpy/flopy#291]
After Python 2.7.14 installation on a Windows 7 system, FloPy 3.2.8 was pip installed according to the FloPy Release Notes and now exists amongst Python's site packages. The command "import flopy", in Spyder 3.2.4, returns the following message: "ModuleNotFoundError: No module named 'flopy'". An internet search does not provide useful results when seeking a resolution for this error message.

**Comment by langevin-usgs** [comment]
This is probably not a flopy issue.  There could be lots of possible causes.  A common one is that you have multiple copies of Python on your system, and you installed flopy in a different version than the one Spyder is using.
