### ISSUE TITLE
Setting the simulation workspace in flopy.mf6

### ISSUE THREAD

**Issue by driftingtides** [modflowpy/flopy#292]
I am using the flopy.mf6 module and have had some difficulties setting the simulation workspace. When I create the MFSimulation object with:

`sim = flopy.mf6.MFSimulation(sim_name=runname, sim_ws=mfdir)`

the module does not recognise that `mfdir` is an absolute path, so the files do not get saved in the right place. 

I tried debugging to see if I could find the source of the error and it looks like the the method `string_to_file_path()` (line 127 of _flopy.mf6.mfbase.py_) is not correctly reassembling the absolute filepath string that it receives - probably because this is not the intent of this method. 

I was successfully able to 'hack' the code to save everything in the correct workspace by moving line 193 of _flopy.mf6.mfbase.py_ (`path = self.string_to_file_path(path)`) to above line 198 (`self._sim_path = os.path.join(os.getcwd(), path)`). This means that if the given `_sim_path` is an absolute path then it does note get modified. This fixed the problem for me.

I haven't submitted a pull request, as I'm not sure if this hack will cause other problems elsewhere.

**Comment by spaulins-usgs** [comment]
Thanks for reporting this.  I checked in a fix so that string_to_file_path() now supports absolute paths.  Your solution is a workaround that will most likely fix the problem for you.  If you want the fix I just checked in it is in the develop branch.
