### ISSUE TITLE
Changing mf.name does not change output filenames

### ISSUE THREAD

**Issue by samzipper** [modflowpy/flopy#293]
I have created a steady-state model, and would now like to add some pumping wells to the domain and save it as a new model. My goal is to keep the input and output files for both the old model and the new model (for additional runs, postprocessing, and analysis). However, I am having an issue in which the output files are being overwritten because I cannot figure out how to update their filenames.

```
# load existing model
mf = flopy.modflow.Modflow.load("Navarro-SteadyState.nam", 
                                model_ws=os.path.join('modflow', '.'), 
                                exe_name=path2mf)

# change model name
mf.name = 'Navarro-SteadyState-WithPumping'

# write input files
mf.write_input()
```

This works for the package input files, but the output files (`riv.out`, `hds`, `ddn`) remain the same in the new `nam` file:
```
# Name file for MODFLOW-2005, generated by Flopy version 3.2.8.
LIST               2  Navarro-SteadyState-WithPumping.list
DIS               11  Navarro-SteadyState-WithPumping.dis 
BAS6              13  Navarro-SteadyState-WithPumping.bas 
RCH               19  Navarro-SteadyState-WithPumping.rch 
RIV               18  Navarro-SteadyState-WithPumping.riv 
PCG               27  Navarro-SteadyState-WithPumping.pcg 
OC                14  Navarro-SteadyState-WithPumping 
LPF               15  Navarro-SteadyState-WithPumping.lpf 
DATA(BINARY)       1  Navarro-SteadyState.riv.out REPLACE
DATA(BINARY)      51  Navarro-SteadyState.hds REPLACE
DATA(BINARY)      52  Navarro-SteadyState.ddn REPLACE
```

I also tried manually renaming the files for the affected packages, for example: 
```
riv_old = mf.riv
riv = flopy.modflow.ModflowRiv(mf, 
                               stress_period_data=riv_old.stress_period_data, 
                               ipakcb=1, 
                               filenames=['TestNewRiv.riv', 'TestNewRiv.riv.out'])

# write input files
mf.write_input()
```
However, the new namefile only updates the input RIV file, not the output:
```
LIST               2  Navarro-SteadyState-WithPumping.list
DIS               11  Navarro-SteadyState-WithPumping.dis 
BAS6              13  Navarro-SteadyState-WithPumping.bas 
RCH               19  Navarro-SteadyState-WithPumping.rch 
RIV               18  TestNewRiv.riv 
PCG               27  Navarro-SteadyState-WithPumping.pcg 
OC                14  Navarro-SteadyState-WithPumping 
LPF               15  Navarro-SteadyState-WithPumping.lpf 
DATA(BINARY)       1  Navarro-SteadyState.riv.out REPLACE
DATA(BINARY)      51  Navarro-SteadyState.hds REPLACE
DATA(BINARY)      52  Navarro-SteadyState.ddn REPLACE
```

Is there any way to rename model output files to avoid overwriting data in the same folder? Or is changing directories for each model iteration the only workaround?

Thanks,
-Sam

**Comment by jtwhite79** [comment]
I've only ever done the "change directories" way because I've usually got lots of external arrays that would otherwise get stomped on:
```>>m.change_model_ws("new_dir",update_external=True)```

**Comment by langevin-usgs** [comment]
I just ran into this today and can verify there is a bug here.  Will try to fix in preparation for an upcoming class.  Looks like the set_name() method will need to look through the output file names and possibly the name of the list file.

**Comment by jdhughes-usgs** [comment]
@langevin-usgs @jwhite-usgs Can we close this?

**Comment by jdhughes-usgs** [comment]
Reopen if this is still a valid issue.
