### ISSUE TITLE
Zonbud utilities returns time step/stress period does not exist.

### ISSUE THREAD

**Issue by rosskush** [modflowpy/flopy#296]
When the setting (compact = False) for the oc file, zonbud util returns "time specified does not exist" from the cbc file, however when using the binaryfile utils, returning the times or kstpkper works fine. That being said I can use the zonbud fine when compact = True in the oc.

**Comment by jbellino-usgs** [comment]
Ross, if you paste the error message I'll trace it back in the code to see what's going wrong.

**Comment by rosskush** [comment]
Over the weekend I did some digging on what could have caused this myself, as I would imagine zonbud would work regardless of the compact argument in the oc file. I traced some of the issues to the the recent changes on how the oc saves files in this issue **Change in default output control behavior #276** , my apologies, I didn't realize this changed and that is likely the cause of my troubles. After some changes to my code I think I solved my own issue since I cannot reproduce the error. Thank you though!
