### ISSUE TITLE
ModflowRch.load() is ``check``ing but shouldn't be

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#298]
It seems like ``ModflowRch.load()`` is still calling ``.check()`` even though I've passed ``check=False`` to the model load classmethod - it is slowing down the load considerably.  @aleaf-usgs can you ``check`` this - ha!

**Comment by aleaf** [comment]
hopefully [this](https://github.com/modflowpy/flopy/pull/299/commits/c726084288cd9c21089cdd22c7cd0473fccfe8a6) fixes it
