### ISSUE TITLE
cell budget object not returning get_times()

### ISSUE THREAD

**Issue by rosskush** [modflowpy/flopy#301]
Similar to an issue I submitted recently, it seems that when setting the compact option to False in the budget file results in the following

times = cbcobj.get_times()
print(times)

> []

whereas setting compact option to true returns the actual times

times = cbcobj.get_times()
print(times)

> [365.25, 730.5, 1095.75, 1461.0, 1826.25, 2191.5, 2556.75]

This does not seem to be the case for cbcobj.get_kstpkper(). Both compact options will return a list of time step and stress period data. 

Not sure if this is an inherent modflow thing or if there is something in the binaryfile utils that cant read times from a non compact file.

Thank you again, I really appreciate what you guys do here.

**Comment by langevin-usgs** [comment]
@rosskush, would you be able to create a very short flopy script that would help us recreate the problem?  Or past into here a small budget file that demonstrates the issue?  I know that we could do that ourselves but it would help speed up the process if you could provide those details.  Thanks for reporting the issue.

**Comment by rosskush** [comment]
Chris, that's totally fair, 

tutorial01.py will actually show the error if you change the oc. Though this will actually raise an error 

import numpy as np
import flopy
import os
# Assign name and create modflow model object
modelname = 'tutorial1'
exe_name = os.path.join('H:/','HydroPy','HydroPy','Examples','Notebooks','gw_codes','mf2005.exe')
mf = flopy.modflow.Modflow(modelname, exe_name=exe_name)

# Model domain and grid definition
Lx = 1000.
Ly = 1000.
ztop = 0.
zbot = -50.
nlay = 1
nrow = 10
ncol = 10
delr = Lx/ncol
delc = Ly/nrow
delv = (ztop - zbot) / nlay
botm = np.linspace(ztop, zbot, nlay + 1)

# Create the discretization object
dis = flopy.modflow.ModflowDis(mf, nlay, nrow, ncol, delr=delr, delc=delc,
                               top=ztop, botm=botm[1:])

# Variables for the BAS package
ibound = np.ones((nlay, nrow, ncol), dtype=np.int32)
ibound[:, :, 0] = -1
ibound[:, :, -1] = -1
strt = np.ones((nlay, nrow, ncol), dtype=np.float32)
strt[:, :, 0] = 10.
strt[:, :, -1] = 0.
bas = flopy.modflow.ModflowBas(mf, ibound=ibound, strt=strt)

# Add LPF package to the MODFLOW model
lpf = flopy.modflow.ModflowLpf(mf, hk=10., vka=10., ipakcb=53)

# Add OC package to the MODFLOW model
spd = {(0, 0): ['print head', 'print budget', 'save head', 'save budget']}
oc = flopy.modflow.ModflowOc(mf, stress_period_data=spd, compact=False)

# Add PCG package to the MODFLOW model
pcg = flopy.modflow.ModflowPcg(mf)

# Write the MODFLOW model input files
mf.write_input()

# Run the MODFLOW model
success, buff = mf.run_model()

# Post process the results
import matplotlib.pyplot as plt
import flopy.utils.binaryfile as bf

plt.subplot(1, 1, 1, aspect='equal')
hds = bf.HeadFile(modelname + '.hds')
head = hds.get_data(totim=1.0)
levels = np.arange(1, 10, 1)
extent = (delr / 2., Lx - delr / 2., Ly - delc / 2., delc / 2.)
plt.contour(head[0, :, :], levels=levels, extent=extent)
plt.savefig('tutorial1a.png')

fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(1, 1, 1, aspect='equal')

hds = bf.HeadFile(modelname+'.hds')
times = hds.get_times()
head = hds.get_data(totim=times[-1])
levels = np.linspace(0, 10, 11)

cbb = bf.CellBudgetFile(modelname+'.cbc')
kstpkper_list = cbb.get_kstpkper()
frf = cbb.get_data(text='FLOW RIGHT FACE', totim=times[-1])[0]
fff = cbb.get_data(text='FLOW FRONT FACE', totim=times[-1])[0]

modelmap = flopy.plot.ModelMap(model=mf, layer=0)
qm = modelmap.plot_ibound()
lc = modelmap.plot_grid()
cs = modelmap.contour_array(head, levels=levels)
quiver = modelmap.plot_discharge(frf, fff, head=head)
plt.savefig('tutorial1b.png')


returns

"Exception: This is an older style budget file that
                         does not have times in it.  Use the MODFLOW 
                         compact budget format if you want to work with 
                         times.  Or you may access this file using the
                         kstp and kper arguments or the idx argument."

Now this is leading me to believe this is a modflow thing more than a flopy thing. I would just keep track of times with the head file or not switch the compact format but when working the the zonal budget utilities it is best to have the cbb using times.

Thanks again Chris.

**Comment by wkitlasten** [comment]
Is .get_ts() much faster than .get_data() in a loop:

for stsp in kstpkper:
    val[stsp]=cbc.get_data(kstpkper=stsp,text=name)

If so, does it make sense to have .get_ts(), or a variant, return a time-series with the first column = time step, second column =  stress period, and the rest the cell values?

**Comment by langevin-usgs** [comment]
The .get_ts() method should be faster because it seeks head to pull out the information, instead of reading the entire array.  If we want to also add stress period and time step, which are integers, to the returned array then we'd probably need to create a recarray so we could store integers and floats.  But I'm not sure what advantage we'd gain.  You can get the stress period and time steps from the .get_kstpkper() method.
