### ISSUE TITLE
ModflowSfr

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#303]
near line 1391 in mfsfr2.py, there is conditional to check if ``irtflg`` is _less than zero_ for writing some more (sometimes present) SFR options to dataset 1c.  The online guide to modflow-nwt says if ``irtflg`` is _greater than zero_ these options should be written (``numtim, weight,flwtol``).  The only way I ever found this was repeating a load-write-load sequence for an SFR model with ``nstrm<0`` - it bombs on the second load.  I'm scared to change it myself because, well, SFR scares me.     @aleaf-usgs  - can you verify that the ``write_1c()`` conditional againt ``irtflg`` should in fact be _greater than_?

**Comment by aleaf** [comment]
just submitted [a fix](https://github.com/modflowpy/flopy/pull/299/commits/2596efa9e1f6226afb36732402df5860a1cd8b3d). I think it might have been a typo.
