### ISSUE TITLE
This breaks a simple model for me

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#304]
https://github.com/modflowpy/flopy/blob/dfd4a4e7f43e3ed7444dd230baa224790ed2bd0e/flopy/modflow/mfsfr2.py#L1008

@aleaf-usgs  - this change to mfsfr2.py has broken the load of a simple SFR model for me - here is the model:

[https://github.com/jtwhite79/pyemu/tree/develop/examples/freyberg_sfr_update](https://github.com/jtwhite79/pyemu/tree/develop/examples/freyberg_sfr_update)

Is something wrong with this model (high probability...).

**Comment by aleaf** [comment]
Sorry, that was dumb. I think I fixed it.

**Comment by jtwhite79** [comment]
Sweet as, Andy.  Works for me.
