### ISSUE TITLE
STRT option from GLO HDS file

### ISSUE THREAD

**Issue by ksed** [modflowpy/flopy#31]
I see the global process is not fully supported yet, which is likely a load of work, but it sure would be nice if someone could squeeze in support for loading STRT heads from a HDS file (e.g. using the DATAGLO option in the NAM file). Maybe adding external STRT support could be a first step toward supporting the GLO process?

**Comment by jdhughes-usgs** [comment]
Support for MODFLOW-2000 is a low priority. Closing issue will reopen if necessary.
