### ISSUE TITLE
Assign top elevation of not flat using interpolation or shape file 

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#310]
Hi All,
Is there a way to assign the layer top and bottom with more realistic values from DEM?
I looked through the notebooks. They all use constant values. 
Thanks,
Tao

**Comment by jdhughes-usgs** [comment]
To assign variable tops and bottoms to a model pass `numpy` arrays for `TOP` and `BOTM`  in the `DIS` constructor. For MODFLOW-2005, you would pass `TOP` a `numpy` array with `shape=(NROW, NCOL)` and `BOTM` a `numpy` array with `shape=(NLAY, NROW, NCOL)`.
