### ISSUE TITLE
Hubbertville problem w/ MF-NWT

### ISSUE THREAD

**Issue by juancastilla** [modflowpy/flopy#32]
Hello,

I'm trying to run the Hubbertville problem (with MF-NWT) from the new book by Anderson, Woessner and Hunt. I use a Mac, and therefore need to recompile MF-NWT. The problem is that the makefile is not included in the USGS program files (!). I tried with a compiled version available from Theo Olsthoorn's mflab project, but flopy cannot read the output files (although it runs OK). The problem seems to be that Theo's compiled mfnwt file is based on MF2005 v.1.9 whereas the example model in the book was run with v.1.11.

Could you please point me towards the makefile for MF-NWT, or the Mac-compiled version of mfnwt?

I am sure many Mac users are coming across this problem  :)

Thanks!

**Comment by langevin-usgs** [comment]
I just created a new repository called pymake (https://github.com/modflowpy/pymake).  This is a simple python package for compiling MODFLOW and related programs.  It is very beta at this time, but does work for me on mac for compiling mfnwt.  Let me know if you run into any problems by creating an issue under the pymake repository.
