### ISSUE TITLE
Confusion on the model class names mf, mp and mt 

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#323]
In the code document, the MODFLOW class is defined as flopy.modflow.**_mf_**.Modflow. However, in the example, we just use flopy.modflow.Modflow. The **_mf_** is dropped. It's same for the mt3d and modpath model. Why do we need the **_mf_** here if we don't use it?

**Comment by langevin-usgs** [comment]
This is a general question about Python namespaces, and is important, so I'll give a quick explanation for how we do things in Flopy.  As you note, you can get to the Modflow class two different ways:

```
flopy.modflow.mf.Modflow
flopy.modflow.Modflow 
```

The first way is the full path to the class.  If you look in the flopy folder you will see a file in the following location: `flopy/modflow/mf.py`.  Inside this `mf.py` file is the `Modflow` class.  So this is one way to access `Modflow`, as `flopy.modflow.mf.Modflow`.

For the other way, we have done an import from the file `flopy/modflow/__init__.py`.  In this file you will see a command that says: `from .mf import Modflow`.  This command makes the `Modflow` class available from the `flopy.modflow` namespace (as well as all the other modflow packages).
