### ISSUE TITLE
forrtl: error (72): floating overflow!

### ISSUE THREAD

**Issue by fahadkhan469** [modflowpy/flopy#329]
Hi!

This is really bugging my head! I am running a saturated groundwater model. I can run the model successfully with Model Muse. But when I am trying to do it with Python (Flopy, with Jupyter) then the model runs for all the stress periods first and then it does not terminate normally and I get the following error:

forrtl: error (72): floating overflow
Image              PC        Routine            Line        Source             
MODFLOW-NWT.exe    0151CD0F  Unknown               Unknown  Unknown
MODFLOW-NWT.exe    01879A08  Unknown               Unknown  Unknown
MODFLOW-NWT.exe    0193EF4F  Unknown               Unknown  Unknown
MODFLOW-NWT.exe    0196DCE2  Unknown               Unknown  Unknown
kernel32.dll       760D343D  Unknown               Unknown  Unknown
ntdll.dll          776A9832  Unknown               Unknown  Unknown
ntdll.dll          776A9805  Unknown               Unknown  Unknown

When I check the result files afterwards I find that the the results are there and the MASM listing file also appears to be okay, but the HOB_OUT file is empty. Basically what I realize is that when the model attempts to create the HOB_OUT file, it terminates with the "floating point error" as mentioned above. 

A few observation wells I have added to the model falls on dry/ inactive cells and yield negative simulated heads. Is this the reason for the error (because there's a too large value which exceeds the floating ranges)? The strange part is I can run the model with Model Muse, but only in Flopy I'm having this issue. But I need to eventually run the model in Flopy because I need to create a loop, running the model multiple times with changing the HK values.

Can anyone help??

Thanks in advance!

**Comment by langevin-usgs** [comment]
It's really hard to determine from your message what the problem is.  Sounds like you need to troubleshoot.  Turn off the HOB package and see if that works.  Or try HOB with only one well in a cell that you know is not dry.  Verify that you are using the latest version of MODFLOW-NWT, etc.

**Comment by fahadkhan469** [comment]
Hi, 

I've just been able to solve the issue. The problem it seems was with the inactive cells. Because I had inactive heads specified to be very large when flopy was dealing with those datasets there was the error. What I did now was assigning a smaller value (= -5) for the inactive cells and the mode ran fine. 

Thanks for your help.
