### ISSUE TITLE
dtype of the loaded stress_period_data of boundary packages 

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#331]
What is the dtype for the imported stress_period_data? 
I would expect a dictionary based on the FloPy document. 
However, I got flopy.utils.util_list.MfList calss. 

I found the to_array method in the MfList class, but it didn't work for my model. 

m_temp = flopy.modflow.Modflow()
loadpth = os.path.join('WTCHM_TR_refine','WTCHM.wel')
wel_TR = flopy.modflow.ModflowWel.load(loadpth, m_temp, nper=564)
pumping_pred_data = wel_TR.stress_period_data

test = wel_TR.stress_period_data.to_array(kper=1)

IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by jtwhite79** [comment]
``stress_period_data`` is always ``MfList`` type.  The ``dtype`` attribute of ``MfList`` is a numpy-style dtype; its a mixed type of integers and floats, depending on the requirements for the specific list-style input. You can access the dtype through the property-decorated method like this:

```>>>m.wel.stress_period_data.dtype```

**Comment by flydream0428** [comment]
Hi Jeremy, 

I guess I am a bit slow here. I closed it, then I found more questions. This MFList type is just strange for me. How can I know how many elements it has? I know I can get the data for SP1 using m.wel.stress_period_data[0]. However, even if I pass a number beyond the total number of stress period, the object still returns some values without a warning. Am I too picky here? 

Thanks,
Tao

**Comment by jtwhite79** [comment]
The number of elements in an ``MfList`` instance is different that the stress period level - you can define a different number of wells for every stress period if you want to.   The ``__getitem__`` overloaded method in ``MfList`` is just a helper - by convention, if you request entries for a stress period that is past the end of the data that were submitted to the constructor, ``MfList`` returns the last stress period entries - replicating the "-1" ``itmp`` behavior in MODFLOW
