### ISSUE TITLE
flopy is missing a forum or QA platform

### ISSUE THREAD

**Issue by joha1** [modflowpy/flopy#334]
There is quite a lot of documentation e.g. [here](http://modflowpy.github.io/flopydoc/) or in [here](https://github.com/modflowpy/flopy/blob/develop/docs/notebook_examples.md) (though the latter could be a bit easier to find), and I can open issues here, but for things that are just not covered in the docs or that I happen to just not find or where I'm not sure how to do something, this "forum" seems like it is the wrong place.

And just searching for "flopy + my issue", hoping that google pulls up something someone has written on this issue is mostly rather unsuccessful, since there's probably not too many folks that use flopy and those folks that exist get pushed to the backbenches of google since it just assumes I certainly must be searching for "floppy (disk)". And yeah, I can try to force it to look for "flopy", but now I just have mostly folks doing something with "flopy diesc"…

So what could be done to solve this issue?

Three suggestions/ideas I have come up with:

**Something here on github**
I'm not too familiar with what options github offers, but I would imagine there could be some way to interact on here besides just filling Issues with "personal" issues with flopy.

**Stackoverflow**
Seems like a natural fit for QA platform. However (assuming this becomes an active thing) it would "outsource" a lot of documentation to an external platform.
And of course it would require that there are actually folks using flopy active on there. [There are already a few questions about flopy](https://stackoverflow.com/search?q=flopy), though about half of them about the above mentioned "flopy diesc" and those that are about flopy are rather inactive. Also, apparently none of the askers has enough reputation to create a flopy tag. Would there be enough people active in flopy that are also active on SO, or willing to also sign up there?

**Modflow googlegroup**
[This](https://groups.google.com/forum/#!forum/modflow) long running google group already has a lot of good folks in there, but not a lot of flopy related content. And maybe I'm just too young for that, but it appears like mailing lists are not really a popular thing anymore…
And there would also be the outsourcing issue.

**Comment by mbakker7** [comment]
Good idea to have a SO tag. If we are active in pointing people in that
direction when they have a question, that could grow into a good database
with questions and answers.
If somebody wants to occasionally update the wiki FAQ section that would be
great as well.

**Comment by juancastilla** [comment]
How about an open-sourced Github "book" with chapters made up of Jupyter notebooks? Here is a cool example of what could be achieved:

https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers

**Comment by mbakker7** [comment]
The SO flopy tag is active, so I am closing this issue.
