### ISSUE TITLE
Loading will fail when flopy sees auxiliary in the package file

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#338]
I encounter the loading error when I try to run the Notebook example for MODPATH.
https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_Modpath_example.ipynb
After a big struggle, I can identify this is due to the auxiliary variable in the river file. 
I am wondering if this is only an issue on my machine? 
If this is a comment issue, is there a workaround?

**Comment by jdhughes-usgs** [comment]
This must be an issue on your end. See https://github.com/modflowpy/flopy/blob/develop/examples/FAQ/load_existing_model_wAUX.ipynb

**Comment by flydream0428** [comment]
Hi Joseph, 
Thanks for your reply. I guess it's an issue with Python 2.7. Someone pointed out this can happen when Pandas is used with Numpy after 1.12. However, I tried a lower version. It doesn't help. I also tested this on two other machines where I encounter the same issue. Anyway, thanks. I am creating a Python 3 environment now. Cheers, Tao

**Comment by jdhughes-usgs** [comment]
The example does not rely on Pandas but uses standard numpy functionality. Can you adapt the code in the notebook to load your model and look at the aux variables? Send the error if it does not load.

**Comment by flydream0428** [comment]
Below is the error when I switched on the verbose option. Both RIV and WEL
packages are failed.

Creating new model with name: EXAMPLE
--------------------------------------------------

Parsing the namefile --> ..\data\mp6\EXAMPLE.nam
Setting filehandles:

--------------------------------------------------
External unit dictionary:
{33: filename:..\data\mp6\EXAMPLE.LPF, filetype:LPF, 2:
filename:..\data\mp6\EXAMPLE.LST, filetype:LIST, 3:
filename:..\data\mp6\EXAMPLE.DIS, filetype:DIS, 4:
filename:..\data\mp6\EXAMPLE.BA6, filetype:BAS6, 12:
filename:..\data\mp6\EXAMPLE.WEL, filetype:WEL, 50:
filename:..\data\mp6\EXAMPLE.HED, filetype:DATA(BINARY), 14:
filename:..\data\mp6\EXAMPLE.RIV, filetype:RIV, 18:
filename:..\data\mp6\EXAMPLE.RCH, filetype:RCH, 53:
filename:..\data\mp6\EXAMPLE.BUD, filetype:DATA(BINARY), 22:
filename:..\data\mp6\EXAMPLE.OC, filetype:OC, 23:
filename:..\data\mp6\EXAMPLE.PCG, filetype:PCG}
--------------------------------------------------

ModflowBas6 free format:True

loading dis package file...
   Loading dis package with:
      5 layers, 25 rows, 25 columns, and 3 stress periods
   loading laycbd...
   loading delr...
   loading delc...
   loading top...
   loading botm...
      for 5 layers and 0 confining beds
   loading stress period data...
       for 3 stress periods
adding Package:  DIS
   DIS  package load...success
loading bas6 package file...
adding Package:  BAS6
   BAS6 package load...success
loading lpf package file...
   loading IBCFCB, HDRY, NPLPF...
   loading LAYTYP...
   loading LAYAVG...
   loading CHANI...
   loading LAYVKA...
   loading LAYWET...
   loading hk layer   1...
   loading vka layer   1...
   loading ss layer   1...
   loading sy layer   1...
   loading hk layer   2...
   loading vka layer   2...
   loading ss layer   2...
   loading hk layer   3...
   loading vka layer   3...
   loading ss layer   3...
   loading hk layer   4...
   loading vka layer   4...
   loading ss layer   4...
   loading hk layer   5...
   loading vka layer   5...
   loading ss layer   5...
Adding EXAMPLE.BUD (unit=53) to the output list.
adding Package:  LPF
   LPF  package load...success
   LIST package load...skipped
loading wel package file...
   loading <class 'flopy.modflow.mfwel.ModflowWel'> for kper     1
loading wel package file...
   loading <class 'flopy.modflow.mfwel.ModflowWel'> for kper     1
   WEL  package load...failed
   data type not understood
   DATA(BINARY) file load...skipped
      EXAMPLE.HED
loading riv package file...
   loading <class 'flopy.modflow.mfriv.ModflowRiv'> for kper     1
loading riv package file...
   loading <class 'flopy.modflow.mfriv.ModflowRiv'> for kper     1*
RIV  package load...failed
   data type not understood*
loading rch package file...
   loading rech stress period   1...
adding Package:  RCH
   RCH  package load...success
   DATA(BINARY) file load...skipped
      EXAMPLE.BUD
loading oc package file...
Adding EXAMPLE.HED (unit=50) to the output list.
adding Package:  OC
   OC   package load...success
loading pcg package file...
adding Package:  PCG
   PCG  package load...success
Warning: external file unit " +                        "3 does not
exist in ext_unit_dict.
Warning: external file unit " +                        "4 does not
exist in ext_unit_dict.
Warning: external file unit " +                        "0 does not
exist in ext_unit_dict.


   The following 6 packages were successfully loaded.
      EXAMPLE.DIS
      EXAMPLE.BA6
      EXAMPLE.LPF
      EXAMPLE.RCH
      EXAMPLE.OC
      EXAMPLE.PCG
   The following 3 packages were not loaded.
      EXAMPLE.LST
      EXAMPLE.WEL
      EXAMPLE.RIV

**Comment by flydream0428** [comment]
Everything is fine if I switch to Python 3.

**Comment by jdhughes-usgs** [comment]
Could you add a few lines of your riv package with aux variables to a comment.

**Comment by flydream0428** [comment]
The error is for the modpath example. Not my own model. I guess I have to
use the auxiliary variable to make modpath work. Anyway, if it costs too
much time to debug it, let's leave it. I will use Python 3 instead. I can
send you all the files if you want to have another look.
