### ISSUE TITLE
Changes to ZoneBudget?

### ISSUE THREAD

**Issue by porterma** [modflowpy/flopy#339]
Back in April Iworte some code to calculate zone budgets:

```
zbud = ZoneBudget('{}/{}.bud'.format(d, model_name), zones.astype(int))
kstpkper = zbud.kstpkper
ts, spd = zip(*kstpkper)

columbia_in = zbud.get_dataframes(names=['CONSTANT_HEAD_IN']).sum(axis=1)
columbia_out = zbud.get_dataframes(names=['CONSTANT_HEAD_OUT']).sum(axis=1)
columbia = columbia_in.values + columbia_out.values
umatilla = zbud.get_dataframes(names=['RIVER_LEAKAGE_OUT'], zones=['ZONE_3', 'ZONE_4', 'ZONE_5'])
drains = zbud.get_dataframes(names=['DRAINS_OUT'], zones=['ZONE_6', 'ZONE_7'])
storage_in = zbud.get_dataframes(names=['STORAGE_IN']).sum(axis=1)
storage_out = zbud.get_dataframes(names=['STORAGE_OUT']).sum(axis=1)
recharge = zbud.get_dataframes(names=['RECHARGE_IN']).sum(axis=1)
```

I got a new computer and installed flopy 3.2.9. Now the above code does not work. I now have the following code:

```
zbud = ZoneBudget('{}/{}.bud'.format(d, model_name), zones.astype(int))
kstpkper = zbud.kstpkper
ts, spd = zip(*kstpkper)

columbia_in = zbud.get_dataframes(names=['FROM_CONSTANT_HEAD']).sum(axis=1)
columbia_out = zbud.get_dataframes(names=['TO_CONSTANT_HEAD']).sum(axis=1)
columbia = columbia_in.values + columbia_out.values
umatilla = zbud.get_dataframes(names=['TO_RIVER_LEAKAGE'], zones=['ZONE_3', 'ZONE_4', 'ZONE_5'])
drains = zbud.get_dataframes(names=['TO_DRAINS'], zones=['ZONE_6', 'ZONE_7'])
storage_in = zbud.get_dataframes(names=['FROM_STORAGE']).sum(axis=1)
storage_out = zbud.get_dataframes(names=['TO_STORAGE']).sum(axis=1)
recharge = zbud.get_dataframes(names=['FROM_RECHARGE']).sum(axis=1)
```
I do not know the previous version of flopy I was using. It appears there has been a change in ZoneBudget, is that correct?

My issue is that in my previous version of flopy
`zbud = ZoneBudget('{}/{}.bud'.format(d, model_name), zones.astype(int))`
loaded and calculated zone budgets on 36 GB file in less than an hour. Now I have been waiting over 12 hours for the same code to process the same 36 GB cell-by-cell file. Do you have any thought s on what might be causing this? Is it likely something on my end? Is there a more efficient way to use ZoneBudget to get my variables of interest for all time steps and stress periods for large cell-by-cell files? 

I'm really just baffled that my code worked efficiently at a previous time and now I am having this issue. Any thoughts would greatly be appreciated. Thanks.

**Comment by jbellino-usgs** [comment]
Mark, you can try checking out tag 3.2.8, but I would be cautious as I found some bugs related to constant head cells not getting accumulated properly and the use of non-sequential zone numbers. Let me know if you see speed ups with the earlier version.

**Comment by jbellino-usgs** [comment]
Mark,
I downloaded your budget and zone files and ran them with the flopy 3.2.8 and 3.2.9 official release tags. The run times were identical on my machine so I'm not sure where things are going awry for you. I'm using numpy version 1.13.1 and pandas version 0.20.3.

![flopy_3 2 8_test](https://user-images.githubusercontent.com/8257727/40492948-af59ad48-5f3f-11e8-853a-dd5253bbdac7.png)
![flopy_3 2 9_test](https://user-images.githubusercontent.com/8257727/40492949-af74056c-5f3f-11e8-9713-73f4e395d325.png)

**Comment by jdhughes-usgs** [comment]
@porterma and @jbellino-usgs is this resolved?

**Comment by jbellino-usgs** [comment]
I haven't pursued this any further since I wasn't able to duplicate his problem with long processing times.

**Comment by jdhughes-usgs** [comment]
@jbellino-usgs I am going to close it unless you want it left open

**Comment by jbellino-usgs** [comment]
@jdhughes-usgs that's fine with me, Joe.
