### ISSUE TITLE
Read headobservation-output files

### ISSUE THREAD

**Issue by rabbl** [modflowpy/flopy#342]
With the hob-package modflow creates an hob.out-file.
I haven't found a hob.out - filereader or any example.
Is there something implemented already or an example how to read it with another reader?

If not I could do that.

**Comment by langevin-usgs** [comment]
Looks like autotest/t041_test.py just uses a simple genfromtxt:

    obs0 = np.genfromtxt(pth0, skip_header=1)

Does that work for you?

**Comment by jtwhite79** [comment]
or with ```pandas```:
```>>>obs0 = pandas.read_csv(pth0,delim_whitespace=True)```
