### ISSUE TITLE
option to suppress warning when adding duplicate package

### ISSUE THREAD

**Issue by mbakker7** [modflowpy/flopy#345]
It is fairly common to keep changing a package in a loop by adding a package that replaces the old one. Every time you add the package you get the warning that it replaces the old one. It would be great if there is an option to turn this warning off.

**Comment by spaulins-usgs** [comment]
This has been implemented in Flopy for MODFLOW6 with a "verbosity_level" option.  The verbosity_level option can be set to quiet, normal, or verbose.  Quiet does not display warning messages including the duplicate package message.  Please keep this in mind when implementing this feature in the original flopy so that we can keep the interface between the two versions as consistent as possible.

**Comment by jtwhite79** [comment]
The easiest might be to use the model-level verbose flag as a warnings flag also

**Comment by mbakker7** [comment]
I like that idea. Sounds easy enough.

**Comment by cshuler** [comment]
Here are some nice workarounds:
https://stackoverflow.com/questions/8391411/suppress-calls-to-print-python

**Comment by jdhughes-usgs** [comment]
@mbakker7 It has been a long time coming but I have a pull request in that addresses
this issue. Hope the fix is worth the wait.

**Comment by Veethahavya** [comment]
> The easiest might be to use the model-level verbose flag as a warnings flag also

Hi @jtwhite79, could you please tell me how to do this? I tried both setting the kwarg "verbosity_level" and "verbose" to 0 and "quiet" during model initialization. But the warning is still printed.
I don't know if I am doing it wrong.

Thanks in advance

**Comment by Veethahavya** [comment]
> This has been implemented in Flopy for MODFLOW6 with a "verbosity_level" option. The verbosity_level option can be set to quiet, normal, or verbose. Quiet does not display warning messages including the duplicate package message. Please keep this in mind when implementing this feature in the original flopy so that we can keep the interface between the two versions as consistent as possible.

@spaulins-usgs could you please tell me where I need to set this option?

**Comment by Veethahavya** [comment]
> The easiest might be to use the model-level verbose flag as a warnings flag also

@jtwhite79 could you please tell me how I can do this? Tried setting the kwarg "verbosity_level" and "verbose" flags to 0 and "quiet". Neither worked.

**Comment by spaulins-usgs** [comment]
I will add a VerbosityLevel example to our Notebooks.  For now you can see its use in one of our autotests.  Click on the link below and search for "verbosity_level".

[https://github.com/modflowpy/flopy/blob/develop/autotest/t504_test.py](https://github.com/modflowpy/flopy/blob/develop/autotest/t504_test.py)

**Comment by Veethahavya** [comment]
thanks to both of you!
