### ISSUE TITLE
external file path behavior: what happens when active, model, and package workspaces differ

### ISSUE THREAD

**Issue by jbellino-usgs** [modflowpy/flopy#351]
Loading of `DIS` package of model `base/base.nam` from a script `scen01/load_base_model.py` fails—`Util2D` is unable to locate the files specified with `OPEN/CLOSE` and returns an error stating the file `base/ref/top.ref` does not exist.  

```python
inmod = mf.modflow.Modflow.load("base.nam", model_ws=r"..\base")
```

File structure:
```
base/
  base.nam
    --> ../externalfiles/base.dis
externalfiles/
  ref/
    top.ref
    botm1.ref
  base.dis
    --> ref/top.ref
    --> ref/botm1.ref
scen01/
  load_base_model.py
```
The current behavior of the `load` method of the `Util2D` class is to prepend the model workspace directory to the filename specified in the package file:
https://github.com/modflowpy/flopy/blob/5b1eed63093a40821d711a4e5926e4a40a144c38/flopy/utils/util_array.py#L2650
A work around would be to prepend the name of the directory in which the package file is located, but I'm not sure how many things this will break.
```python
fname = os.path.join(os.path.dirname(f_handle.name), fname)
```
Essentially this change would make the loading of package array files "package-centric" as opposed to "model-centric" in cases where files are stored separately (such as our model archives).

**Comment by jtwhite79** [comment]
Tread with caution, Jason!  All that external path and file support is very delicate...and you are right that util2d should be linked package level rather than model level.

 What is really needed is a centralized file manager class to track the python, os, and modflow location of all the files.  Otherwise im afraid things are gonna break when you try to change model_ws.

**Comment by jbellino-usgs** [comment]
That's what I suspected—I've got a new branch with this change so I can build these scenarios and then blow it away.

**Comment by jbellino-usgs** [comment]
Here is another example I ran into recently on Pull Request #414 when adding code to autotest [t041.py](https://github.com/modflowpy/flopy/blob/develop/autotest/t041_test.py):

Input model name file:
```
LIST               2  hob_simple.list
DIS               11  hob_simple.dis 
BAS6              13  hob_simple.bas 
LPF               15  hob_simple.lpf 
PCG               27  hob_simple.pcg 
HOB               39  hob_simple.hob 
DATA              51  hob_simple.hob.out
DATA(BINARY)      53  hob_simple.cbc REPLACE
```
The above name file is imported into flopy using the `load_only` kwarg where:
```python
load_only = ['dis', 'bas6', 'pcg', 'lpf']
m = flopy.modflow.Modflow.load( namefile'.nam', model_ws=pth, load_only=pkglst)
```
and is then written back out with some additional packages:
```python
m.write_input()
```

```
LIST               2  hob_simple.list
DIS               11  hob_simple.dis 
BAS6              13  hob_simple.bas 
LPF               15  hob_simple.lpf 
PCG               27  hob_simple.pcg 
DRN               21  hob_simple.drn 
DROB              42  flwobs_simple.drob 
DATA             142  flwobs_simple.obd 
DATA              51  temp\t041\simple\hob_simple.hob.out
DATA(BINARY)      53  hob_simple.cbc REPLACE
```
The first problem is that the external data file on unit 51 associated with the `HOB` package should not have been written back out since the `HOB` package is not included in this model.

The second problem is that MODFLOW can't find `temp\t041\simple\hob_simple.hob.out` (even though it does exist from a previous test) and bails. This file path is created because the active workspace from which the model was created (`flopy\autotest\`) differed from the model workspace (`flopy\autotest\temp\test041\simple\`).

This appears to stem from the fact that the external file names stored in `model.external_fnames` include the full path from whatever the current working directory was at the time the name file was parsed; there is an opportunity for a problem if MODFLOW is run using a different working directory than the current working directory. There already seems to be a solution on [line 318](https://github.com/modflowpy/flopy/blob/0f2e5398786d4556ac89322be1e00306a41cbae6/flopy/modflow/mf.py#L318) of mf.py which uses the relative path of the file with respect to `model_ws`, but it's commented out. It fixes this problem, but causes a couple of other failures in the autotests. I'm planting this information here to preserve the detective work I did on PR #414 with the other problems of this nature that have been encountered.

**Comment by jbellino-usgs** [comment]
An additional case I've found when trying to open up a package file as listed by the `fn_path` variable. `fn_path` seems to be a join between `model_ws` and whatever the package filename is.

Again, given the file structure:
```
base/
  base.nam
    --> ../externalfiles/base.dis
externalfiles/
  ref/
    top.ref
    botm1.ref
  base.dis
    --> ref/top.ref
    --> ref/botm1.ref
scen01/
  load_base_model.py
```
One would expect that the file name path of the `DIS` package would be `..\externalfiles\fas.dis`; however, calling `model.dis.fn_path` yields `..\base\fas.dis` instead.
