### ISSUE TITLE
How to give irregular layer properties?

### ISSUE THREAD

**Issue by mustafaucr** [modflowpy/flopy#354]
I want to give more realistic  layer properties. For instance thickness of the layer can change in every axis. Moreover layers can intersect. It is a way to the this by giving every layer thicknessses -or their top and bottom elevations,as well? Is there any example or flopy promote it?

**Comment by langevin-usgs** [comment]
This is a good question, but it is not really a flopy question.  This is a general modeling question and is difficult to answer without knowing much more about your study.  You might try the MODFLOW google group: https://groups.google.com/forum/#!forum/modflow
