### ISSUE TITLE
ModFlowEvt load

### ISSUE THREAD

**Issue by laat0003** [modflowpy/flopy#36]
Hi,
Using version 3.1.1r I had to insert npar = 0 at line 174 in the load method for the EVT. Without it, npar would only be defined if "parameter" appeared in the evt package input file. Prior to this I could not load any existing evt input files. Chances are this may be fixed already.

Regards,

Tariq

**Comment by jdhughes-usgs** [comment]
Fixed in latest version (3.2.1)
