### ISSUE TITLE
I cannot generate .MAS file, and fail to plot increasing concentration of contaminant with time

### ISSUE THREAD

**Issue by yishanwu513** [modflowpy/flopy#360]
Problem 1:
I could not generate .MAS output file even though I set chkmas = True and nprmas = 10 in BTN file

Problem2:
I used flopy to execute the MT3DMS to plot the change of the concentration of solute in the injection well, and I set itype = ['WEL'] in the ssm package but the change of the concentration in the injection well will reach the plateau of concentration of contaminant (1.5 g/ m^3)

My ssm package:
import flopy
m = flopy.mt3d.Mt3dms()
itype = mt3d.Mt3dSsm.itype_dict()
ssm_data = {}
ssm_data[0] = [(25, 50, 0 , 1.5, itype['WEL'])]
ssm = flopy.mt3d.Mt3dSsm(m, stress_period_data=ssm_data)

but there is a problem that why the concentration of solute will not keep increasing with the time since I set itype = ['WEL']. It means I keep adding solute  (concentration of contaminant = 1.5 g/ m^3) in the injection well, right?! I attached the figure for the change of concentration in the injection well with time. 
![01](https://user-images.githubusercontent.com/41028556/42482128-f1f27e94-839a-11e8-9e78-ee0aa307be71.png)

**Comment by mbakker7** [comment]
This is not an issue but a question. Please submit a question to stackoverflow using the "flopy" tag.
