### ISSUE TITLE
Write binary heads file to be read by bas6 as initial heads 

### ISSUE THREAD

**Issue by porterma** [modflowpy/flopy#362]
Is there a way to write a binary heads file that can be specified in the .anm file and read by the bas6 package, rather than including the initial heads explicitly in the bas6 package? I searched for this option in the code, but did not find a method.

Thanks!

**Comment by langevin-usgs** [comment]
Take a look here: https://github.com/modflowpy/flopy/blob/develop/autotest/t017_test.py.  I'm not sure if this is exactly what you're thinking, but it is a place to start.

**Comment by porterma** [comment]
I think that's what I was looking for. thanks!
