### ISSUE TITLE
option to specify "REPLACE" for non-binary output file in NAM file?

### ISSUE THREAD

**Issue by jknightusgs** [modflowpy/flopy#363]
Hi there,

I'm using the WEL package in MODFLOW-NWT and writing the reduced pumping to an external non-binary file. This was pretty straightforward once I found the relevant lines in the code:

`mf.add_output(fname='Reduced_Wells.out', unit=50, binflag=False, package=None)`

In mf.py, the write_name_file() add's 'REPLACE' to the NAM file entry for output files only where binflag==True.

line 330 in mf.py

`        if b:
                f_nam.write(
                    'DATA(BINARY)   {0:5d}  '.format(u) + f + ' REPLACE\n')
            else:
                f_nam.write('DATA           {0:5d}  '.format(u) + f + '\n')`

I'd like to add 'REPLACE to the NAM file entry for my non-binary Reduced_Wells.out file because not every run has reduced pumping. When that happens no new output file is created and the output file from the last run with reduced pumping remains. This old file then gets pulled into my post-processing.

Could 'option' be added as an argument to the mf.add_output() method?

Thanks,

Jake

**Comment by jdhughes-usgs** [comment]
Implemented in `mf.py` in a manner similar to proposed solution. Not sure when this was implemented.
