### ISSUE TITLE
Can't change MNW2 pumping rate for single stress period

### ISSUE THREAD

**Issue by szipper** [modflowpy/flopy#365]
I've loaded a model (`mf`) and want to turn a well on for one stress period; I have tried two approaches, neither of which seems to work as I expected.

In this example, I have a bunch of wells, and I want to turn on one of them ('Well22') for the second stress period.

## Option 1: Change stress_period_data MfList object

```
>>> mf.mnw2.stress_period_data

<flopy.utils.util_list.MfList object at 0x7f97cbcf7198>
```

Let's look at the first 3 stress periods for one of my wells:

```
>>> print(mf.mnw2.stress_period_data[0]['qdes'][np.where(mf.mnw2.stress_period_data[0]['wellid']=='Well22')], 
  mf.mnw2.stress_period_data[1]['qdes'][np.where(mf.mnw2.stress_period_data[1]['wellid']=='Well22')],
  mf.mnw2.stress_period_data[2]['qdes'][np.where(mf.mnw2.stress_period_data[2]['wellid']=='Well22')])

[ 0.] [ 0.] [ 0.]
```

Now, I want to turn the well on during the second stress period:
`mf.mnw2.stress_period_data[1]['qdes'][np.where(mf.mnw2.stress_period_data[1]['wellid']=='Well22')] = -5`

However, this turns the well on during all stress periods:
```
>>> print(mf.mnw2.stress_period_data[0]['qdes'][np.where(mf.mnw2.stress_period_data[0]['wellid']=='Well22')], 
  mf.mnw2.stress_period_data[1]['qdes'][np.where(mf.mnw2.stress_period_data[1]['wellid']=='Well22')],
  mf.mnw2.stress_period_data[2]['qdes'][np.where(mf.mnw2.stress_period_data[2]['wellid']=='Well22')])

[-5.] [-5.] [-5.]
```
Accordingly, when I write the output Well22 is turned on for all stress periods in my `.mnw2` file:
```
787  Stress Period 1
...
Well22    -5.0000000E+00
...
787  Stress Period 2
...
Well22    -5.0000000E+00
...
787  Stress Period 3
...
Well22    -5.0000000E+00
...
```

Desired functionality: How can I change the `stress_period_data` MfList object for only a single well and stress period?

## Option 2: Mnw object
I also tried a different approach using the `Mnw` object, which looks correct at first glance:
```
>>> print(mf.mnw2.mnw['Well22'].stress_period_data['qdes'][0], 
  mf.mnw2.mnw['Well22'].stress_period_data['qdes'][1], 
  mf.mnw2.mnw['Well22'].stress_period_data['qdes'][2])
  
0.0 0.0 0.0

>>> mf.mnw2.mnw['Well22'].stress_period_data['qdes'][1] = -5

>>> print(mf.mnw2.mnw['Well22'].stress_period_data['qdes'][0], 
  mf.mnw2.mnw['Well22'].stress_period_data['qdes'][1], 
  mf.mnw2.mnw['Well22'].stress_period_data['qdes'][2])

0.0 -5.0 0.0

>>> mf.write_input(SelPackList=['MNW2'])
```

However, the pumping rate is not changed when I look at the `.mnw2` output file:
```
787  Stress Period 1
...
Well22    0.0000000E+00
...
787  Stress Period 2
...
Well22    0.0000000E+00
...
787  Stress Period 3
...
Well22    0.0000000E+00
...
```

Desired functionality: How can I write the output such that the updated `Mnw` objects are included?

**Comment by langevin-usgs** [comment]
I'm not sure about this, but part of the problem may be that your stress period dictionary was not constructed with a separate entry for each stress period.  If you create a stress period dictionary like this:

```
spd = {}
spd[0] = [[0, 0, 0, qwell]]
```

Then there is only data specified for the first stress period, but this data also applies to all subsequent stress periods.  So if you access spd[19], for example, then you should see this well: [[0, 0, 0, qwell]].  I'm guess that if you change the data for spd[19], then it might actually be changing the data for the first stress period, but I have not verified that, and I could be wrong.

In your case, you want things to change by stress period, so you need to repeat the data for each stress period, and change what you want each time.  You should probably do this while you create the stress period dictionary, not after it has already been added to the package.

Not sure that this is the problem you are having, but I have a hunch that it is something like that.

**Comment by szipper** [comment]
Thanks for the suggestion- it helped me crack the case (though not in either of the ways I previously mentioned). 

My solution, which is admittedly a bit kludgey, was to extract the necessary data from the original model to recreate the `Mnw2` object:
```
# grab data from existing model
nper = mf.dis.nper
itmp = mf.mnw2.itmp.copy()
nwel = itmp[0]
mnw_node_data = mf.mnw2.node_data

# set up no pumping stress period data
mnw_sp_NoPump  = mf.mnw2.stress_period_data[0].copy()

# set up pumping rate stress period
mnw_sp_Pump = mnw_sp_NoPump.copy()
mnw_sp_Pump['qdes'][mnw_sp_Pump['wellid']=='Well22'] = Qw

# update stress period data for this well
mnw_spd = {}
for sp in range(0, nper):
    if (sp==1):
        mnw_spd[sp] = mnw_sp_Pump
    else:
        mnw_spd[sp] = mnw_sp_NoPump

# create mnw package
mnw2 = flopy.modflow.ModflowMnw2(model=mf, mnwmax=nwel, 
                                 node_data=mnw_node_data,
                                 stress_period_data=mnw_spd,
                                 itmp=itmp, ipakcb=71,
                                 filenames=[modelname+'.mnw2', modelname+'.mnw2.out'])

# flip node data to avoid INTERVALS error (see FloPy issue #344)
mf.mnw2.node_data = np.flipud(mf.mnw2.node_data)

# write input (NAM and MNW2 only)
mf.write_input(SelPackList=['MNW2'])
```
