### ISSUE TITLE
This operation raises an exception

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#370]
https://github.com/modflowpy/flopy/blob/be3281f6705fa1214e881ad0321dc3510f2d0190/flopy/pakbase.py#L334

Just a heads up: this operation in the checker seems to be broken using the lastest ``miniconda``/``numpy`` install on travis.  See this log file:

[https://api.travis-ci.org/v3/job/409416294/log.txt](https://api.travis-ci.org/v3/job/409416294/log.txt)

**Comment by briochh** [comment]
Anyone cracked this one?
