### ISSUE TITLE
OSError: obtaining file position failed

### ISSUE THREAD

**Issue by geowat** [modflowpy/flopy#372]
I was trying to get DRN and GHB flows from an unstructured model (DISV, MF6). However the following code is producing an error:
```
import flopy.utils.binaryfile as bf
cbb_out = bf.CellBudgetFile('test.cbb', precision='double', verbose=True)
```
In the screen output, i can see the data going through to (kstp:2, kper: 56, text: STO-SY) and it failed with this message (I think stress period 56 could be random number): 

> c:\python36\lib\site-packages\flopy\utils\binaryfile.py in binaryread(file, vartype, shape, charlen)
>     154         # find the number of values
>     155         nval = np.prod(shape)
> --> 156         result = np.fromfile(file, vartype, nval)
>     157         if nval == 1:
>     158             result = result  # [0]
>  OSError: obtaining file position failed.

The model has more than 300 stress periods, and it ran to the end. I tested with another cbb which produced the same error. I'm hoping **CellBudgetFile** works for an unstructured grid (quadtree),? Any help is appreciated. Thanks

**Comment by langevin-usgs** [comment]
Two thoughts: (1) can you use the version of zonebudget that comes with MODFLOW 6 to read that file?  Easiest way is to just assign a zone number of 1 everywhere, and see if zonebudget can read the file.  (2) Can you create a very short script that reproduces the problem with a small model?  Is this due to the number of stress periods or something else?

**Comment by geowat** [comment]
Zonebudget works fine on the same cbb, but there are too many drain cells to use zonebudget for this task. There might be a bottleneck in that stress period in binary file? Although I had no problem post processing outputs so far (zonebudget using cbb or hds processed with flopy). I might have a go with a smaller model to replicate the problem.

**Comment by langevin-usgs** [comment]
How big is your cbb file?  It could be that we need to use a long integer to store file positions.

**Comment by langevin-usgs** [comment]
And does it tell you the position (ipos) of the record just before and after the problem time step?

**Comment by geowat** [comment]
cbb file size is close to 20Gb. The model has 40,000 nodes in each layer (5 layers). So it's not the biggest model to struggle? Let me know if I need to cast any number to a long integer as a temporary solution in utils\binaryfile.py

**Comment by langevin-usgs** [comment]
It looks like it is related to the size of the integer, so something is not switching to a long integer.  The following is the range of a regular 4 byte integer, which corresponds exactly to the file position that you are having problems with: "Signed integer value from --2,147,483,648 to 2,147,483,647 (--2**31 to 2**31--1)".  Let me know if you take a look.  I will plan to do so, but I may not get to it right away.

**Comment by jlarsen-usgs** [comment]
I experienced this same issue recently while working with a large formatted head file. 

In line 139 of formattedfile.py, I changed
```
self.file.seek(ipos + self._data_size)
```
to
```
try:
    self.file.seek(ipos + self._data_size)
except IOError:
    self.file.seek(self._data_size, 1)
```
which seemed to solve the issue in my case.

**Comment by geowat** [comment]
The same error seems to be happening on HDS file as well. I tried to edit the code following @jilarsen-usgs reply, but that hasn't helped. It works on some machines but doesn't work on others (all 64-bit windows). I'm surprised that the problem has not been raised by others - it would be very much appreciated if you could add this problem to your actions log. Many Thanks!

**Comment by geowat** [comment]
Ok I think I got to the bottom of the problem. Apparently, this OSError only happens when Python 32-bit or Anaconda 32-bit is used. Obviously the default download from python.org is 32-bit unless 64-bit is selected.
