### ISSUE TITLE
Read bct package output file (.con)

### ISSUE THREAD

**Issue by edimunv** [modflowpy/flopy#374]
I was trying to read .con file for a transport simulation made with modflow usg, like i can do with hds file.
Is there a way to read .con file using flopy? I tried something like this:

import flopy.utils.binaryfile as bf
con_file = 'results.con'
conobj = bf.HeadFile(con_file, text = 'concentration', precision = 'single')

but i get this error:

File "C:\Users\emunozv\AppData\Local\Continuum\anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 221, in _get_header
    return header[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

I know bf.HeadFile is incorrect, but it was a test. I don't know the header of .con file.

Thanks for helping

**Comment by rosskush** [comment]
Instead of `bf.Headfile`, you could try `bf.UcnFile`

I don't think it's any different than using non modflow usg. 

You can read about both of them here:
https://modflowpy.github.io/flopydoc/binaryfile.html

**Comment by langevin-usgs** [comment]
I have processed USG concentrations in the past.  I found this code that shows how to do it.  If I remember right, the conc shape is different from what you might expect, but hopefully you can figure it out.

```
concobj = bf.HeadFile(concfile, text=’conc’)
times = concobj.get_times()
print ’Number of times in file: ’, len(times)
tm = times[-1]
conc = concobj.get_data(totim=tm)
print ’conc min and max: ’, conc.min(), conc.max()
```

**Comment by edimunv** [comment]
Thanks @langevin-usgs 
it works

**Comment by giovannifi** [comment]
I know that this has been closed but I have a problem that the recommended solution does not solve. The con file I have contains two species. They are labelled with 'CONC01' and 'CONC02' from what I could read by opening the binary file with a text editor. The only command that was able to open something sensible was:

`ucnobj = bf.HeadUFile('mymodel.con', precision='single', text='conc')`

I tried to replace text='conc' with text='conc01' or text='conc02' to get the individual species. However the script seems frozen and takes for ever to load the data. On the contrary the command above takes litteraly a few seconds to load. However when I try:

`ucnobj.get_data(totim=6.2)`

I get the concentrations only for species 2. I have the feeling that it is not possible to get data from multispecies simulations. Is this the case?

thanks

**Comment by giovannifi** [comment]
Never mind, I manged to find a solution for my case. I created a custom function that allows me to access the multispecies:

`def get_conc(ucnobj, text=None, nlay=1, totim=0.0):
    indices = np.where((ucnobj.recordarray["totim"] == totim) & (ucnobj.recordarray["text"] == text))[0]
    data = nlay * [None]
    for idx in indices:
        ipos = ucnobj.iposarray[idx]
        ilay = ucnobj.recordarray["ilay"][idx]
        nstrt = ucnobj.recordarray["ncol"][idx]
        nend = ucnobj.recordarray["nrow"][idx]
        npl = nend - nstrt + 1
        ucnobj.file.seek(ipos, 0)
        data[ilay - 1] = bf.binaryread(ucnobj.file, ucnobj.realtype, shape=(npl,))
    return data`

for the text I actually used the following command:

`text_component1 = ucnobj.recordarray['text'][0]`
`text_component2 = ucnobj.recordarray['text'][nlay]`

then I executed the function above:

`get_conc(ucnobj, text=text_component1, nlay=15, totim=6.2)`
