### ISSUE TITLE
flopy.utils.modpathfile Module only for MODPATH 6?

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#378]
It seems that the current implementation of the flopy.utils.modpathfile Moduleis only works for MODPATH 6. Will this be updated soon?

**Comment by jdhughes-usgs** [comment]
There is support for MODPATH 7. In general, support for MODPATH 7 is better than support for MODPATH 6. There are a few MODPATH 7 notebook examples. Closing issue will reopen if necessary.
