### ISSUE TITLE
Possible bugs in combining stress_period_data dictionary

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#390]
https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_modflow_boundaries.ipynb
In the notebook for boundary handling, if you go to the end of the notebook, there is an example that shows how to combing stress period data. However, the append function doesn't make sense to me. For example, how come can you get two bores at stress period 9 when there is only one bore in Wel2? 
          2         0 # stress period 9
        10         3         5   4.0000000E+00
         2         3         5   4.0000000E+00

**Comment by jtwhite79** [comment]
I think it's working right.  `wel1` implicitly has an active well in stress period 9 because of the `-1` ( the well is defined in stress period 6).  So 2 wells in stress period 9 of the combined instances.
