### ISSUE TITLE
Flopy import crashes Python

### ISSUE THREAD

**Issue by sdmcclure** [modflowpy/flopy#397]
I'm running the Anaconda distribution with python 3.5.1. When attempting to import flopy either with jupyter notebook or a script, the python interpreter crashes ("Python has stopped working. A problem caused the program to stop working correctly").

I'm guessing the problem started after a recent update of my python environment. 

I was running an older flopy version that was installed through pip, so I tried uninstalling and installing a newer version though conda. conda installed flopy 3.2.9 from the conda forge channel. This didn't fix the problem.

flopy is the only package I've used so far that has caused the crash.

P.S. I love Flopy, thank you so much for your efforts and for sharing this tool!

**Comment by langevin-usgs** [comment]
I don't have a solution at the moment, but this is the second time I've heard of this happening.

**Comment by sdmcclure** [comment]
I tried testing import for some of the dependencies. numpy, matplotlib, and pandas are fine.

I got tracebacks that pyshp and netcdf4 that sad the libraries where not installed. pyshp was listed in my environment but netcdf4 was not. But after installing netcf4, I still get the same error.

Attempting to import these dependencies does not result in a crash though.

**Comment by jtwhite79** [comment]
Can you run this command and post `spec-file.txt` here:
``conda list --explicit > spec-file.txt``

**Comment by sdmcclure** [comment]
> 
> 
> Can you run this command and post `spec-file.txt` here:
> `conda list --explicit > spec-file.txt`

# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/ca-certificates-2018.03.07-0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/conda-env-2.6.0-h36134e3_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/icc_rt-2017.0.4-h97af966_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/libdynd-0.7.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/mkl-2017.0.3-0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/node-webkit-0.10.1-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandoc-2.2.1-h1a437c5_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/patch-2.5.9-1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/vs2015_runtime-14.00.23026.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/bzip2-1.0.6-vc14_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/geos-3.4.2-vc14_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/launcher-1.0.0-4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libspatialindex-1.8.5-vc14_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/miktex-2.9.6621-h2fa13f4_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/python-3.5.1-4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/snappy-1.1.7-vc14_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/sqlite-3.13.0-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/vc-14-0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/zlib-1.2.11-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/alabaster-0.7.7-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/anaconda-custom-py35h64770cb_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/beautifulsoup4-4.4.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/bitarray-0.8.1-py35_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/blosc-1.14.3-he51fdeb_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/boost-cpp-1.66.0-vc14_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/boto-2.39.0-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/certifi-2018.8.24-py35_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/chardet-3.0.4-py35h177e1b7_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/click-6.7-py35h10df73f_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cloudpickle-0.1.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/colorama-0.3.7-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/comtypes-1.1.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cython-0.23.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/decorator-4.0.9-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/dill-0.2.4-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/docutils-0.14-py35h8ccb97f_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/entrypoints-0.2.3-py35hb91ced9_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/et_xmlfile-1.0.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/expat-2.2.5-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/fastcache-1.0.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/greenlet-0.4.9-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/hdf5-1.8.18-vc14_3.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/heapdict-1.0.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/icu-58.2-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/idna-2.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/ipython_genutils-0.1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/itsdangerous-0.24-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/jdcal-1.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/jedi-0.9.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/jpeg-9b-vc14_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/jsonschema-2.4.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/kiwisolver-1.0.1-py35hc605aed_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/krb5-1.14.6-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/lazy-object-proxy-1.3.1-py35he996729_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/libboost-1.65.1-he51fdeb_4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libiconv-1.14-vc14_4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libpng-1.6.34-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libsodium-1.0.16-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/llvmlite-0.23.2-py35he51fdeb_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/locket-0.2.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/lxml-3.6.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/lzo-2.10-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/markupsafe-0.23-py35_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/mccabe-0.6.1-py35hcf31250_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/menuinst-1.3.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/mistune-0.7.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/mkl-service-1.1.2-py35_3.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/mpmath-0.19-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/multipledispatch-0.4.8-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/nltk-3.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/nose-1.3.7-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.14.2-py35h5c71026_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/olefile-0.45.1-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/openssl-1.0.2p-hfa6e2cd_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pandocfilters-1.4.2-py35h978f723_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/path.py-8.1.2-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pep8-1.7.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/ply-3.8-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/proj4-4.9.3-vc14_5.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/psutil-4.1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/py-1.4.31-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyasn1-0.1.9-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pycosat-0.6.3-py35h456c199_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pycparser-2.14-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pycrypto-2.6.1-py35_3.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyflakes-1.1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pygments-2.1.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyparsing-2.0.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyreadline-2.1-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/pyshp-1.2.12-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pytz-2016.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pywin32-220-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyyaml-3.11-py35_3.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyzmq-15.2.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/qtpy-1.4.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/requests-2.12.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/rope-0.9.4-py35_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/rtree-0.8.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/ruamel_yaml-0.11.14-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/simplegeneric-0.8.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/sip-4.19.8-py35h6538335_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/six-1.10.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/snowballstemmer-1.2.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/sphinx_rtd_theme-0.1.9-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/sqlalchemy-1.0.12-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/testpath-0.3.1-py35h06cf69e_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/tk-8.6.7-vc14_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/toolz-0.9.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/tornado-4.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/unicodecsv-0.14.1-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/webencodings-0.5.1-py35h5d527fb_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/werkzeug-0.11.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/wheel-0.29.0-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/wincertstore-0.2-py35hfebbdb8_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/wrapt-1.10.11-py35h54666f7_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/xerces-c-3.2.0-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/xlrd-0.9.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/xlsxwriter-0.8.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/xlwt-1.0.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/xz-5.2.4-h2fa13f4_4.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/babel-2.2.0-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/boost-1.66.0-py35_vc14_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/bottleneck-1.2.1-py35h8a3671c_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cffi-1.5.2-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cftime-1.0.0b1-py35h452e1ab_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/chest-0.2.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/click-plugins-1.0.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cligj-0.4.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/configobj-5.0.6-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/console_shortcut-0.1.1-py35_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cycler-0.10.0-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/cytoolz-0.9.0.1-py35hfa6e2cd_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/dynd-python-0.7.2-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/freetype-2.8.1-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/freexl-1.0.2-vc14_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/gevent-1.1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/h5py-2.8.0-py35hf7173ca_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/hdf4-4.2.13-vc14_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/html5lib-1.0.1-py35h047fa9f_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/kealib-1.4.7-vc14_3.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libpq-9.6.3-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libssh2-1.8.0-vc14_2.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libtiff-4.0.9-vc14_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libxml2-2.9.5-vc14_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/munch-2.3.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/networkx-1.11-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/numba-0.38.1-py35h830ac7b_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/numexpr-2.6.2-np113py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/openpyxl-2.3.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pickleshare-0.5-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pytest-2.8.5-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/python-dateutil-2.5.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pywavelets-0.5.2-py35h7c47ace_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/qt-5.6.2-vc14_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/qtawesome-0.3.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/scipy-0.19.1-np113py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/setuptools-39.2.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/shapely-1.6.2-py35h2f425f0_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/singledispatch-3.4.0.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/sockjs-tornado-1.0.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/sympy-1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/traitlets-4.2.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/xlwings-0.7.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/argcomplete-1.0.0-py35_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/astroid-1.6.5-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/astropy-2.0.7-py35h452e1ab_1.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/bleach-2.1.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/clyent-1.2.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cryptography-1.7.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/curl-7.60.0-vc14_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/datashape-0.5.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/geotiff-1.4.2-vc14_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/ipython-4.1.2-py35_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/isort-4.3.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/jinja2-2.8-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/jupyter_core-4.1.0-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libcurl-7.61.0-h7602738_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libkml-1.3.0-vc14_6.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libspatialite-4.3.0a-vc14_11.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/openjpeg-2.3.0-vc14_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pandas-0.20.3-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/patsy-0.5.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pillow-4.2.1-py35hd7da350_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pip-9.0.1-py35_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/psycopg2-2.7.5-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyproj-1.9.5.1-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/free/win-64/pyqt-5.6.0-py35_2.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pysal-1.14.3-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/pytables-3.4.4-py35_8.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/scikit-learn-0.19.0-np113py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/anaconda-client-1.4.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/bokeh-0.11.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/flask-0.10.1-py35_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/imageio-2.3.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/jupyter_client-4.2.2-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libnetcdf-4.5.0-vc14_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/matplotlib-2.2.2-py35h153e9ff_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/nbformat-4.4.0-py35h908c9d9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/odo-0.4.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/partd-0.3.2-py35_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pylint-1.9.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyopenssl-16.2.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/sphinx-1.3.5-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/statsmodels-0.9.0-py35h452e1ab_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/anaconda-project-0.8.2-py35h06aeb26_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/conda-manager-0.4.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/dask-0.8.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/descartes-1.1.0-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/flask-cors-2.1.2-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/flopy-3.2.9-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/ipykernel-4.3.1-py35_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libgdal-2.2.4-vc14_5.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/nbconvert-5.3.1-py35h98d6c46_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/netcdf4-1.3.1-py35hf721a91_2.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/anaconda-navigator-1.8.4-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/blaze-0.9.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/gdal-2.2.2-py35h202a4aa_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/jupyter_console-4.1.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/notebook-4.2.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/qtconsole-4.3.1-py35hc47b0dd_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/scikit-image-0.13.1-py35hfa6e2cd_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/fiona-1.7.10-py35hefe5c53_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/ipywidgets-4.1.1-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/spyder-3.0.2-py35_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/geopandas-0.3.0-py35_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/jupyter-1.0.0-py35_4.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/conda-4.5.11-py35_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/conda-build-1.20.0-py35_0.tar.bz2

**Comment by jtwhite79** [comment]
I can't repro this problem on a Win10 VM using python 3.5.1 and flopy 3.2.9 (via conda forge).  Not sure what else we can do besides leave this issue open...

**Comment by sdmcclure** [comment]
> 
> 
> I can't repro this problem on a Win10 VM using python 3.5.1 and flopy 3.2.9 (via conda forge). Not sure what else we can do besides leave this issue open...

Thanks for looking into it.

**Comment by sdmcclure** [comment]
I noticed the following error is showing up on the command prompt that's tracking Jupyter Notebook:
`Warning: Fiona:PROJ data files not located, PROJ_LIB not set`
importing Fiona doesn't cause a crash though.

Is that info at all helpful?

**Comment by sdmcclure** [comment]
I fixed it (sort of), it looks like it was an environment issue.

I switched to conda-forge as my primary channel and updated all my packages to the conda-forge versions.  Flopy is now importing successfully.

As a side note, unfortunately this broke geopandas due to this issue with #pyproj conda-forge/basemap-feedstock#30
