### ISSUE TITLE
BAS load method issue

### ISSUE THREAD

**Issue by mnfienen** [modflowpy/flopy#40]
Ran into an error trying to load a BAS file.

Error is on `np.fromfile` saying it needs to be passed a file pointer rather than a filename.

    /Users/mnfienen/Documents/GIT/flopy/flopy/utils/util_array.pyc in load_bin(shape, file_in, dtype, bintype)
        937         else:
        938             header_data = None
    --> 939         data = np.fromfile(file_in,dtype=dtype,count=nrow*ncol)
        940         data.resize(nrow, ncol)
        941         return [header_data, data]

    IOError: first argument must be an open file

The doc for `np.fromfile` indicates it can accept either a file handle or a filename, so seems strange. We could change the static method `load_bin` in `util_2d` so that a file handle is opened prior to calling `np.fromfile` but I want to make sure that doesn't break other stuff prior to implementing the fix.

The extra strange thing is that it appears a file handle is already being passed, so the issue may be a little deeper....

**Comment by mnfienen** [comment]
OK - the issue was more insidious than I thought. The actual reason this failed is that the BAS file I was trying to load calls external HDS file for starting heads.

Here's the bottom of the file:
    1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  0
    -1.000e+10
    -666   1.00000(10e12.4)                   -1     STARTING HEADS Layer   1
    -666   1.00000(10e12.4)                   -1     STARTING HEADS Layer   2
    -666   1.00000(10e12.4)                   -1     STARTING HEADS Layer   3
      
So, I think we just need an error trap at the point where the filehandle is opened. As it is now, it just tries to call `np.fromfile` on a file that doesn't exist.

**Comment by langevin-usgs** [comment]
Isn't it more tricky than that?  I think the binary hds files have a header at the top, which MODFLOW skips automatically.

**Comment by mnfienen** [comment]
Yeah - the header stuff is all implemented just fine. The issue here (which I got to in a roundabout way) is that the file (referred to in the name file as unit=666) just wasn't present. So, I think when flopy is using unit numbers to open files, it would be helpful to put in an error trap on either existence of the file or successful opening of the file and report it missing/failed if it can't be opened
