### ISSUE TITLE
Bugs in mtlkt.py

### ISSUE THREAD

**Issue by gdefilippis** [modflowpy/flopy#402]
1) Lines 167 - 174 should be replaced by:

```
self.coldlak = [Util2d(model, (nlkinit,), np.float32, coldlak,
                             name='coldlak', locat=self.unit_number[0],
                             array_free_format=False)]
```

This is because you would get an error at line 190, saying that the method append cannot be used if self.coldlak is an Util2d object instead of a list.

2) Line 227 should be replaced by:

```
for coldlak in self.coldlak:
    f_lkt.write(coldlak.get_file_entry())
```

This is because in the .lkt file you would get coldlak values for the first species only

3) Line 446 should be replaced by:

```
for icomp in range(1, ncomp): 
```

**Comment by langevin-usgs** [comment]
Thanks @gdefilippis, we are taking a look.

**Comment by emorway-usgs** [comment]
@gdefilippis thanks for bringing this to our attention.  I'm going to work
on putting together a multi-species test problem with LKT.  If you have a
small example already put together that builds the model from scratch, and
wouldn't mind sharing, I will incorporate that instead.

Thanks, Eric

**Comment by gdefilippis** [comment]
I have a model I used to integrate the LKT package in the QGIS-based FREEWAT interface (www.freewat.eu), which uses flopy for writing codes input files.
The flow model, including 3 lakes, is reasonable, meaning that it runs successfully and it is based on a real-world case study. The transport model has been set with totally unreasonable concentration values, because I used it just to test if the .lkt file was written correctly.
I hope you can benefit from this anyway.

Thank you,
Giovanna
[lkt_test.zip](https://github.com/modflowpy/flopy/files/2463807/lkt_test.zip)

**Comment by emorway-usgs** [comment]
@gdefilippis If you pull the latest changes on the develop branch, your problem should be working with the changes made under pull request #412   Thanks for your patience.  Let us know if something doesn't look quite right.

**Comment by jdhughes-usgs** [comment]
@emorway-usgs should this issue be closed?

**Comment by gdefilippis** [comment]
Dear all,
I am sorry for delay.
I tested this new version and it works fine.
Thank you,
Giovanna
