### ISSUE TITLE
The program mf2005 does not exist or is not executable.

### ISSUE THREAD

**Issue by Oalmanza** [modflowpy/flopy#42]
run example of lake and all of folder flopy master, but model not run, install flopy in anaconda with pip, the version install is 3.2.1, , it is installed in enviroment Mac OS X.
Sorry for my bad English.
Thanks 
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-9-e78c68141033> in <module>()
      2 oc = mf.ModflowOc(ml)
      3 ml.write_input()
----> 4 ml.run_model()

/Users/Oscar/anaconda/lib/python2.7/site-packages/flopy/mbase.pyc in run_model(self, silent, pause, report)
    375         if exe is None:
    376             s = 'The program {} does not exist or is not executable.'.format(self.exe_name)
--> 377             raise Exception(s)
    378         else:
    379             if not silent:

Exception: The program mf2005 does not exist or is not executable.

**Comment by langevin-usgs** [comment]
You need to have the MODFLOW-2005 executable, which you can download from the USGS.  This executable (mf2005.exe) needs to be in your system path.
