### ISSUE TITLE
pyshp / shapefile.py API has changed as of version 2.0.0

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#426]
Just a heads up that it seems the latest version of `pyshp` has changed the `Writer` API.  It is not backward compatible and is the default version on `pip`.  What used to be `w = shapefile.Writer()`
now requires the `target` filename:`w = shapefile.Writer(target="some.shp")` and also has `w.close()` that needs to called.  I'm sure some of the shapefile support in the `export` module will need to be patched...more fun stuff!

**Comment by juancastilla** [comment]
For the moment, this can be resolved by pinning Flopy to an older version of pyshp — `conda install flopy pyshp=1.2.12` solved the problem for me
