### ISSUE TITLE
Well ID and comments in stress period data

### ISSUE THREAD

**Issue by rosskush** [modflowpy/flopy#429]
Sorry if this has been asked before, I could not find anything on it.

I would like to assign a commented out Well ID number to my well file, (also do the same for ghb cells) but I cannot find anything on how to do so.

I wrote something to create my own ghb file but if I try to load it back into my flopy mf class, and later write it out my other packages with mf.write_input() the comments do not stay and it gets overwritten. 

I know in mf.wrtie_input() I can specify what packages to write out, and if I take away the ghb file I made earlier (or well file) then the original file does not get written over which is good.

But I would like to know if there is a way to straight up add comments to the stress_period_data for each package so I can keep it all contained in the flopy class. 

Thanks,

**Comment by jtwhite79** [comment]
Hey Kush - can you ask this question on stackoverflow and tag it with the flopy tag?

[https://stackoverflow.com/questions/tagged/flopy](https://stackoverflow.com/questions/tagged/flopy)

**Comment by rosskush** [comment]
Moved to Stackoverflow

https://stackoverflow.com/questions/53249936/well-id-and-other-comments-in-stress-period-data-in-flopy
