### ISSUE TITLE
error creating disu object

### ISSUE THREAD

**Issue by corcorf** [modflowpy/flopy#438]
I've been following the [gridgen example notebook](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_gridgen.ipynb) to create a Quadtree grid. I can create and plot a grid ok (although I had to decrease the starting number of cells in my model to start with to avoid gridgen crashing) but when I try to convert it to a disu object for inclusion in the model, I get an exception: 
'Exception: Util2d:self.shape: (157724,) does not match value.shape: (1, 157724)'

Is this a bug, or am I doing something wrong?

My code:

> ml = flopy.modflow.Modflow(modelname=model_name,model_ws=model_ws, exe_name=modflow_v, version=modflow_v)
> 
> dis = flopy.modflow.ModflowDis(ml,nlay=nlay,nrow=nrow,ncol=ncol,
>                                steady=True,
>                                delr=grid_size,delc=grid_size,
>                                start_datetime=start_datetime,
>                                top=top_file,botm=botm_files)
> 
> g = Gridgen(dis, model_ws=model_ws)
> 
> boundary_poly = os.path.join(GMS_path,'Boundary_polys')
> g.add_active_domain(boundary_poly, range(nlay))
> 
> 
> springs_shp = os.path.join(ibnd_path,'springs')
> g.add_refinement_features(springs_shp, 'point', 3, range(nlay))
> 
> g.build(verbose=True)
> 
> disu = g.get_disu(ml)

The full error:

> ---------------------------------------------------------------------------
> Exception                                 Traceback (most recent call last)
> <ipython-input-45-cd4ae767b25f> in <module>
>      30 g.build(verbose=True)
>      31 
> ---> 32 disu = g.get_disu(ml)
> 
> ~\Miniconda3\envs\flopy\lib\site-packages\flopy\utils\gridgen.py in get_disu(self, model, nper, perlen, nstp, tsmult, steady, itmuni, lenuni)
>     702                            ivc=ivc, cl1=cl1, cl2=cl2, cl12=cl12, fahl=fahl,
>     703                            perlen=perlen, nstp=nstp, tsmult=tsmult,
> --> 704                            steady=steady)
>     705 
>     706         # return dis object instance
> 
> ~\Miniconda3\envs\flopy\lib\site-packages\flopy\modflow\mfdisu.py in __init__(self, model, nodes, nlay, njag, ivsd, nper, itmuni, lenuni, idsymrd, laycbd, nodelay, top, bot, area, iac, ja, ivc, cl1, cl2, cl12, fahl, perlen, nstp, tsmult, steady, extension, unitnumber, filenames, start_datetime)
>     344 
>     345         # calculate layer thicknesses
> --> 346         self.__calculate_thickness()
>     347 
>     348         # Add package and return
> 
> ~\Miniconda3\envs\flopy\lib\site-packages\flopy\modflow\mfdisu.py in __calculate_thickness(self)
>     359             thk.append(self.top[k] - self.bot[k])
>     360         self.__thickness = Util3d(self.parent, (nlay, nrow, ncol),
> --> 361                                    np.float32, thk, name='thickness')
>     362         return
>     363 
> 
> ~\Miniconda3\envs\flopy\lib\site-packages\flopy\utils\util_array.py in __init__(self, model, shape, dtype, value, name, fmtin, cnstnt, iprn, locat, ext_unit_dict, array_free_format)
>     558                     append(self.name_base[k].replace(' ', '_'))
>     559 
> --> 560         self.util_2ds = self.build_2d_instances()
>     561 
>     562     def __setitem__(self, k, value):
> 
> ~\Miniconda3\envs\flopy\lib\site-packages\flopy\utils\util_array.py in build_2d_instances(self)
>     810                                  ext_filename=ext_filename,
>     811                                  locat=self.locat,
> --> 812                                  array_free_format=self.array_free_format)
>     813                     u2ds.append(u2d)
>     814 
> 
> ~\Miniconda3\envs\flopy\lib\site-packages\flopy\utils\util_array.py in __init__(self, model, shape, dtype, value, name, fmtin, cnstnt, iprn, ext_filename, locat, bin, how, array_free_format)
>    1719         self.name = name
>    1720         self.locat = locat
> -> 1721         self.parse_value(value)
>    1722         if self.vtype == str:
>    1723             fmtin = "(FREE)"
> 
> ~\Miniconda3\envs\flopy\lib\site-packages\flopy\utils\util_array.py in parse_value(self, value)
>    2593                 raise Exception('Util2d:self.shape: ' + str(self.shape) +
>    2594                                 ' does not match value.shape: ' +
> -> 2595                                 str(value.shape))
>    2596             if self.dtype != value.dtype:
>    2597                 value = value.astype(self.dtype)
> 
> Exception: Util2d:self.shape: (157724,) does not match value.shape: (1, 157724)

**Comment by langevin-usgs** [comment]
This should be fixed now. It was something minor.  Sorry it took so long to get to it.
