### ISSUE TITLE
load STR package?

### ISSUE THREAD

**Issue by fahadkhan469** [modflowpy/flopy#447]
Hi,

I have a Modflow-NWT model in which I am using the STR package (streamflow package as boundary). I have created the STR file using ModelMuse, but now I want to automate things with Flopy scripts. I have done so for many other packages but cannot seem to load and change the .STR file. Is there any way to load the STR file using FLOPY? From the existing documents/tutorials I tried the following script to load the STR file:

```
m = flopy.modflow.Modflow(version='mfnwt', model_ws=model_ws, verbose=False,
                               check=False, exe_name="MODFLOW-NWT")
strm = flopy.modflow.ModflowStr.load('regional_v4.str', m, nper=470)
```

But this leads to the following error:

_> ---------------------------------------------------------------------------
> Exception                                 Traceback (most recent call last)
> <ipython-input-102-959f65b27c36> in <module>()
>       1 m = flopy.modflow.Modflow(version='mfnwt', model_ws=model_ws, verbose=False,
>       2                                check=False, exe_name="MODFLOW-NWT")
> ----> 3 strm = flopy.modflow.ModflowStr.load('regional_v4.str', m, nper=470)
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\flopy\modflow\mfstr.py in load(f, model, nper, ext_unit_dict)
>     697                                     t.append(v)
>     698                             if len(tt) != len(current.dtype.names) - 3:
> --> 699                                 raise Exception
>     700                         else:
>     701                             ipos = [5, 5, 5, 5, 5, 15, 10, 10, 10, 10]
> 
> Exception:_ 

I would be thankful if someone can post a script with which I will be able to load the STR file using Flopy, and then manipulate the data within. Thanks!

**Comment by langevin-usgs** [comment]
@jlarsen-usgs is working on a robust solution for loading the ever-challenging SFR Package.  Hopefully we'll have something soon.

**Comment by emorway-usgs** [comment]
@fahadkhan469 if your model input, including the STR input file created by ModelMuse, is relatively small, could you zip it up and attach it to this github issue?  That would help the debug process.

**Comment by jdhughes-usgs** [comment]
I suspect you need to load a discretization file prior to loading the STR or create appropriate discretization prior to the load.

BTW. This is likely not a bug and should be asked on [stackoverflow](https://stackoverflow.com/search?q=flopy) instead of submitting an issue.

**Comment by samzipper** [comment]
I'm running into the same exception with the [Republican River model](http://www.republicanrivercompact.org/v12p/index.html). Here is a link to [download the model input files](https://kansas-my.sharepoint.com/:u:/g/personal/s947z036_home_ku_edu/EUzdZ3Zq87pIhseLiceGP-8B7zYvYWuQrmEhvSeK9EK2sQ?e=o6Z9MO).

@fahadkhan469 , did you ever find a solution to this problem?

I can load most packages in the model, including the discretization file:
```
# Load model
>>> mf = flopy.modflow.Modflow.load('RRCA12p.nam', 
exe_name='C:/Users/Sam/OneDrive - The University of Kansas/Research/Models/MODFLOW/mf2k.1_19/bin/mf2k.exe', 
version='mf2k', forgive=True)

>>> mf.get_package_list()

Out[4]: ['DIS', 'BAS6', 'LPF', 'OC', 'PCG', 'DRN', 'EVT', 'RCH', 'WEL', 'HYD']
```
However, `STR` does not load:
```
>>> stream = flopy.modflow.ModflowStr.load(f='RRCA12p.str', model=mf, nper=mf.dis.nper)
Traceback (most recent call last):

  File "<ipython-input-5-15c6d11dd323>", line 1, in <module>
    stream = flopy.modflow.ModflowStr.load(f='RRCA12p.str', model=mf, nper=mf.dis.nper)

  File "C:\ProgramData\Anaconda3\lib\site-packages\flopy\modflow\mfstr.py", line 703, in load
    raise Exception

Exception
```

Not sure if it's informative, but if I run the model outside of FloPy I can load and investigate the CellBudgetFile output from STR.

**Comment by jlarsen-usgs** [comment]
Downloaded the files and looked into the issue.

It looks like in the comparison on line 698:

```
if len(tt) != len(current.dtype.names) - 3:
--> 699 raise Exception
```
it is comparing the raw, split, string to the dtype size. If an identifier is used such as "Hugh Butler" (in this case) after the data line, the load process crashes. Since the dtype is a fixed length, a better comparison might be

```
if len(tt) < len(current.dtype.names):
    raise Exception
```

I can look further into this to find a more robust solution.
>

**Comment by fahadkhan469** [comment]
Hi @Sam Zipper,

I never succeeded with this. Instead I built python scripts to edit the
text files (.STR file) directly.

Fahad



On Thu, Feb 28, 2019 at 4:25 PM Sam Zipper <notifications@github.com> wrote:

> I'm running into the same exception with the Republican River model
> <https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.republicanrivercompact.org%2Fv12p%2Findex.html&data=02%7C01%7Cfahad.khadim%40uconn.edu%7C8a0d3da8536c4b87347808d69dc330f7%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636869859022170513&sdata=TnAcAgt4wioGziQR%2Ft4%2BOsLdhMY86r1gpdCCBK5A1gc%3D&reserved=0>.
> Here is a link to download the model input files
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkansas-my.sharepoint.com%2F%3Au%3A%2Fg%2Fpersonal%2Fs947z036_home_ku_edu%2FEUzdZ3Zq87pIhseLiceGP-8B7zYvYWuQrmEhvSeK9EK2sQ%3Fe%3Do6Z9MO&data=02%7C01%7Cfahad.khadim%40uconn.edu%7C8a0d3da8536c4b87347808d69dc330f7%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636869859022170513&sdata=lAMGaw5yk8wqguVF3mHEAby5fJvkb6y4NjzfygAzbKI%3D&reserved=0>
> .
>
> @fahadkhan469
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffahadkhan469&data=02%7C01%7Cfahad.khadim%40uconn.edu%7C8a0d3da8536c4b87347808d69dc330f7%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636869859022180527&sdata=yPfQ0bqIiGrbJ92d1hrRUL4%2F%2Bfvxm5evt5LekZSYClc%3D&reserved=0>
> , did you ever find a solution to this problem?
>
> I can load most packages in the model, including the discretization file:
>
> # Load model
> >>> mf = flopy.modflow.Modflow.load('RRCA12p.nam',
> exe_name='C:/Users/Sam/OneDrive - The University of Kansas/Research/Models/MODFLOW/mf2k.1_19/bin/mf2k.exe',
> version='mf2k', forgive=True)
>
> >>> mf.get_package_list()
>
> Out[4]: ['DIS', 'BAS6', 'LPF', 'OC', 'PCG', 'DRN', 'EVT', 'RCH', 'WEL', 'HYD']
>
> However, STR does not load:
>
> >>> stream = flopy.modflow.ModflowStr.load(f='RRCA12p.str', model=mf, nper=mf.dis.nper)
> Traceback (most recent call last):
>
>   File "<ipython-input-5-15c6d11dd323>", line 1, in <module>
>     stream = flopy.modflow.ModflowStr.load(f='RRCA12p.str', model=mf, nper=mf.dis.nper)
>
>   File "C:\ProgramData\Anaconda3\lib\site-packages\flopy\modflow\mfstr.py", line 703, in load
>     raise Exception
>
> Exception
>
> Not sure if it's informative, but if I run the model outside of FloPy I
> can load and investigate the CellBudgetFile output from STR.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmodflowpy%2Fflopy%2Fissues%2F447%23issuecomment-468444247&data=02%7C01%7Cfahad.khadim%40uconn.edu%7C8a0d3da8536c4b87347808d69dc330f7%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636869859022180527&sdata=CPwnWTL%2BVR58YNyb362egmyLcK2wm9YySqfmTGDl7qA%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAlIODI7HzNjo_oAMcX1e7EdGf7UosCh-ks5vSEkpgaJpZM4ZlCwY&data=02%7C01%7Cfahad.khadim%40uconn.edu%7C8a0d3da8536c4b87347808d69dc330f7%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C636869859022190541&sdata=L%2BezrWrb%2FXK0GumR%2BkNbIaoHX1PG0cmAqtoWBgYa80c%3D&reserved=0>
> .
>


-- 
Regards

Fahad Khan Khadim
Graduate Research Assistant,
Department of CEE, UConn




*Address: 38 W Park St, Willimantic, CT 06226*
*mobile: +1-561-563-4687*
*email: fkk469@gmail.com <http://gmail.com/>; fkhadim2015@fau.edu
<fkhadim2015@fau.edu>; fahad.khadim@uconn.edu <fahad.khadim@uconn.edu>*

**Comment by samzipper** [comment]
Thanks @jlarsen-usgs - I just removed all the identifiers and can confirm that the STR package now loads properly.

**Comment by langevin-usgs** [comment]
@jlarsen-usgs that would be great if you could fix the issue, even if it's just the simple fix that you proposed.
