### ISSUE TITLE
issue with use of TemporalReference and `SpatialReference`

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#45]
UCN file does not have `pertim` in header (in `temporalreference_from_binary_headers`). Added hack to deal with issue in Henry notebook. Is `tsmult` needed for spatial reference? If not can we remove it. Should `tsmult` in instantiationation of `TemporalReference` be `tsmults`? Why is there a `tsmult` and `tsmults`??

In flopy3boundaries notebook a package cannot be created without a `dis` because of issue with `mflist` when there is no spatial reference (`self.sr = self.model.dis.sr`). Added `try` `except` hack to deal with issue but probably needs a closer look.

**Comment by jtwhite79** [comment]
ok - I stripped out the temporal reference stuff.  I think it needs some more thought before it gets to woven in.  Might be able to pull it off with a thin wrapper about some of the ```pandas``` datetime utilities.  So its gone for now...
