### ISSUE TITLE
Zone Budget Example

### ISSUE THREAD

**Issue by SimonKrause** [modflowpy/flopy#451]
Hello,

Just a quick heads up that the [zone budget example](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_ZoneBudget_example) leads to a broken link.

Cheers,
Simon

**Comment by jbellino-usgs** [comment]
Hi Simon, the link you posted is missing the ".ipynb" file ending. The link provided on the examples page works fine on this end: https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_ZoneBudget_example.ipynb

**Comment by SimonKrause** [comment]
My apologies, it seems to be an issue with a plug-in I am using with Firefox (Gesturefy, in case anyone else is using it). Thanks for the help!
