### ISSUE TITLE
Get mf2005 executable

### ISSUE THREAD

**Issue by 1DChristopher** [modflowpy/flopy#452]
Hi everyone,

I think I have a really small issue with the installation of flopy and google or the other issues on GitHub are giving me the right answer (or I do miss interpreted). The problem is that after I installed flopy I tried to run it using this simple tutorial script: https://modflowpy.github.io/flopydoc/tutorial1.html
But I got the following error message: 
***
Traceback (most recent call last):
  File "<ipython-input-1-76fcd6518fce>", line 48, in <module>
    success, buff = mf.run_model()
  File "/Users/Christopher/anaconda3/lib/python3.7/site-packages/flopy/mbase.py", line 970, in run_model
    normal_msg=normal_msg)
  File "/Users/Christopher/anaconda3/lib/python3.7/site-packages/flopy/mbase.py", line 1376, in run_model
    raise Exception(s)
Exception: The program mf2005 does not exist or is not executable. 
***
I'm running Spyder using the Anaconda Navigator and installed Flopy using conda on my Mac (OSX 10.14.3). The import of flopy gives no error.  I'm currently running pyhton version 3.7.1.

I'm working in Python for a while now but I have no experience in setting paths or make files executable.

Hope someone can help me out!

**Comment by jdhughes-usgs** [comment]
You need to download MODFLOW from [https://water.usgs.gov/ogw/modflow/mf2005.html](https://water.usgs.gov/ogw/modflow/mf2005.html) and put the executable in a directory that is in your path statement. 

If you are using OSX or a linux flavor you will need to get the executables from [https://github.com/MODFLOW-USGS/executables](https://github.com/MODFLOW-USGS/executables) or compile them for yourself.

**Comment by 1DChristopher** [comment]
Downloaded them both, add them to my paths using PYTHONPATH manager is Spyder. Restarted Anaconda and Spyder but got the same error message.

**Comment by mbakker7** [comment]
I am afraid that means it is not in the directory that you think it is.

**Comment by 1DChristopher** [comment]
Thanks for your answers (both). I put them both on my desktop and added the new paths just to be sure but still it isn't working. Do I have to paste them in a certain folder? Can't find any information about that.
