### ISSUE TITLE
add binaries to flopy?

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#453]
Hey y'all - I've been wondering if it is worth adding the MODFLOW-family binaries to flopy ( statically-linked for the three main platforms).  We could append to the PATH env var programmatically when flopy is imported, so these binaries would only be available in a python session(and by appending, won't override any existing PATH-registered binaries) but I think a move towards tighter integration between flopy and the model might be useful, esp for beginners.  thoughts?

**Comment by langevin-usgs** [comment]
That is definitely something to consider.  But I do think we are a lot closer now that we have this:
    https://github.com/MODFLOW-USGS/executables
Is this enough?  Or do we need something more sophisticated?

**Comment by rabbl** [comment]
We're using for modflow-webservice a ready to use docker-container, where all binaries are build with pymake on a debian-linux. For local development it could be useful too. 

If there is some interest in this solution a can provide a actual and refactored version of the container.
The source you can find here:

https://github.com/inowas/flopy-calculation-service/tree/master/worker

**Comment by jdhughes-usgs** [comment]
@langevin-usgs should we close this one?

**Comment by langevin-usgs** [comment]
MODFLOW and related executables can be found here: https://github.com/MODFLOW-USGS/executables, so will close this issue for now.
