### ISSUE TITLE
Modflow 6 idomain array can be written as float; should be int array

### ISSUE THREAD

**Issue by tomvansteijn** [modflowpy/flopy#464]
The idomain array in the DIS package can be written as float. The MF6 executable has no problem with this. However the convert_data method  in mfdata.py can only read int's from the DIS package.

Is it perhaps more robust to enforce int for the idomain array?

By (a) converting to int before writing, or (b) an error message if something other than int is supplied by the user.

**Comment by spaulins-usgs** [comment]
To test the problem you reported I manually created a MF6 file with an idomain array containing "1.0 1.0 1.0...".  This produced an error in MF6 'Bad integer for item 1 in list input'.

I then loaded this dis file with flopy and flopy produced an error that includes the text, '(1) Data "idomain" with value "1.0" can not be converted to int.'.  I get a similar error in flopy if I try to create a dis object with an idomain array of floats.

Can you give a specific example where the MF6 executable has no problem with floats? Also, can you give a specific example where flopy is not supplying an error message when idomain contains floats?

**Comment by tomvansteijn** [comment]
Thanks for the test. Do you use list or array input for the idomain variable?

The flopy code for our model is on github: 

https://github.com/tomvansteijn/mf6brabant/blob/master/notebooks/run_mf6.ipynb

* We read the idomain array from a geotiff file. The shape is nrow, ncol. 
* It is broadcast to 3D (nlay, nrow, ncol)
* The variable is then supplied as an argument for the construction of the DIS package. 

We use flopy 3.2.10. The resulting package files can be downloaded here:

https://we.tl/t-iSQTxkGA5Z

**Comment by spaulins-usgs** [comment]
Thanks for providing an example.  I have a fix that converts floats to an int before writing.  I still need to run some benchmarks with the fix since it is in a block of code that can get called a lot.  In the mean time you can try this fix by replacing flopy's mfdata.py file with the one here:

https://github.com/scottrp/flopy/blob/develop/flopy/mf6/data/mfdata.py

**Comment by tomvansteijn** [comment]
Thanks. For the moment I have solved this using a cast to int before the initialization of `ModflowGwfdis`.
