### ISSUE TITLE
could not run flopy3_MT3DMS_examples.ipynb

### ISSUE THREAD

**Issue by mwtoews** [modflowpy/flopy#466]
While running autotest_notebooks.py on Python 3.7, a new issue is found. See traceback starting here:
https://travis-ci.org/modflowpy/flopy/jobs/499596952#L1137

**Comment by langevin-usgs** [comment]
This is an intermittent issue that I haven't been able to figure out.  For some reason, flopy is having a hard time reading the concentration file, but only some times.  I can reproduce it locally sometimes.  Strange.

**Comment by jtwhite79** [comment]
I've got this problem now too on the `feature_drt` branch I've been working in with py3.7 and the MT3DMS notebook on travis.  I fired up a py37 notebook on ubuntu and can run to completion (using a fresh mt3dms builds with gcc7).  It is possible to install a travis docker image but I don't have the bandwidth at the mo.  Any thoughts?

**Comment by mwtoews** [comment]
This issue has nothing to do with flopy or Python. It's with gfortran-compiled mt3dms; see https://github.com/MODFLOW-USGS/mt3d-usgs/pull/46 for a possible fix.

**Comment by emorway-usgs** [comment]
@mwtoews offered [this pull request](https://github.com/MODFLOW-USGS/mt3d-usgs/pull/46) on the MT3D-USGS repo which has been adopted in the latest release of MT3D-USGS that is now up [on the web](https://www.usgs.gov/software/mt3d-usgs-groundwater-solute-transport-simulator-modflow).  Hopefully the initialization of the velocity array in MT3D-USGS fixes this issue.  Does that mean that a new MT3D-USGS executable needs to be stored somewhere for the flopy testing to use?

**Comment by langevin-usgs** [comment]
We'll need to update the path to the distribution file.  I'll take a look at it.
