### ISSUE TITLE
Some bugs in tutorial 1

### ISSUE THREAD

**Issue by 2359181042** [modflowpy/flopy#469]
The error is :
 ' File "e:\ProgramData\Anaconda3\lib\site-packages\flopy\utils\binaryfile.py", line 750, in _skip_record
    self.file.seek(nbytes, 1)

OSError: [Errno 22] Invalid argument'

I have read a similar questions and the anwers is about this “lpf = flopy.modflow.ModflowLpf(mf, hk=10., vka=10., ipakcb=53)” the ipakcb should be adjusted to 51, I tryed in my laptop but it didnt work , do you know how to fix if ? Thanks !

**Comment by langevin-usgs** [comment]
This is not a bug.  Please read about how to get help for flopy.
