### ISSUE TITLE
Problem with mf.dis.delc.array and mf.dis.delr.array?

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#476]
I have just came across with a strange behaviour of flopy and I put together a very simple script where:
I create a 2D model with the following discretisation characteristics:
Lx = 10000.
Ly = 15000.
ztop = 0.
zbot = -200
nlay = 1
nrow = 1500
ncol = 1000
delr = Lx / ncol
delc = Ly / nrow
 
In the script I define the DIS package only. After the definition of the DIS package, I read the total number of NCOLs and NROWs using 3 methods:
 
For columns:
Method 1:  “mf.ncol”
Method 2: “mf.dis.ncol”
Method 3:  “len(mf.dis.delc.array)”
 
I repeated the same for the rows. If you run the script you would notice the inconsistency of the third method. I have the impression that the command “mf.dis.delc.array” returns the array of “delr” rather than “delc” (“mf.dis.delr.array” returns delc rather than delr) . Is this a normal behaviour?

My script is as follows:

import numpy as np
import flopy

path_exe = r'C:\Program Files (x86)\modflow'
path_model = r'C:\Working_Folder\test_models\modflow'

# Assign name and create modflow model object
modelname = 'Testing'
mf = flopy.modflow.Modflow(path_model + '\\' + modelname, exe_name=path_exe + '\\' + 'mf2005')
mf.change_model_ws(path_model)

# Model domain and grid definition
Lx = 10000.
Ly = 15000.
ztop = 0.
zbot = -200
nlay = 1
nrow = 1500
ncol = 1000
delr = Lx / ncol
delc = Ly / nrow
delv = (ztop - zbot) / nlay
botm = np.linspace(ztop, zbot, nlay + 1)

# Create the discretization object
dis = flopy.modflow.ModflowDis(mf, nlay, nrow, ncol, delr=delr, delc=delc, top=ztop, botm=botm[1:])

# recalculate Ncol and Nrow
recalc_ncol = mf.ncol
recalc_nrow = mf.nrow

recalc_ncol2 = mf.dis.ncol
recalc_nrow2 = mf.dis.nrow

recalc_ncol3 = len(mf.dis.delc.array)
recalc_nrow3 = len(mf.dis.delr.array)

# print everything
print('Recalcualted NCOL:')
print('the result of "mf.ncol" is: ' + str(recalc_ncol))
print('the result of "mf.dis.ncol" is: ' + str(recalc_ncol2))
print('the result of "len(mf.dis.delc.array)" is: ' + str(recalc_ncol3))
print('\n')
print('Recalcualted NROW:')
print('the result of "mf.ncol" is: ' + str(recalc_nrow))
print('the result of "mf.dis.nrow" is: ' + str(recalc_nrow2))
print('the result of "len(mf.dis.delc.array)" is: ' + str(recalc_nrow3))

**Comment by langevin-usgs** [comment]
I think your method 3 is incorrect.  delr is the dx spacing.  So:

```
ncol = len(mf.dis.delr.array)
```

or probably better:

```
ncol = mf.dis.delr.array.shape[0]
```

I'm going to close this, because I don't think it's an issue.

**Comment by giovannifi** [comment]
Hi Dr Langevin,
Many thanks for your kind reply and many apologies if I insist with this, but I do not get how the array "delr" could be the array of dx. The name is confusing or at least is not consistent with the command that creates the DIS package:

dis = flopy.modflow.ModflowDis(mf, nlay, nrow, ncol, delr=delr, delc=delc, top=ztop, botm=botm[1:])

where according to the help (https://modflowpy.github.io/flopydoc/mfdis.html?highlight=flopy%20modflow%20modflowdis) delr is dy:

"delr : float or array of floats (ncol), optional
An array of spacings along a row (the default is 1.0)."

Regards
Giovanni

**Comment by langevin-usgs** [comment]
You are right that it is confusing.  The term DELR comes from the idea that it is the "spacing along a row."  There was even a note published in Groundwater back in 1992 to draw attention to this.  I've attached it here.
[Stillwater_et_al-1992-Groundwater.pdf](https://github.com/modflowpy/flopy/files/2945767/Stillwater_et_al-1992-Groundwater.pdf)

**Comment by giovannifi** [comment]
Many thanks for your kind and very comprehensive answer and apologies for the time waste with this.
