### ISSUE TITLE
UZF package example

### ISSUE THREAD

**Issue by fahadkhan469** [modflowpy/flopy#477]
Hi Everyone,

I am looking for an IPython example that shows how to deal with the UZF package outputs (for example, simulated ET, simulated Recharge etc.). There is a file in the list of IPython notebook examples (https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_uzf_example) but it says the file is removed.

Can someone help??

More specifically, I am looking for a script to see and plot my UZF ET values. I am simulating the ET and Recharge with my model. When I open the list file, I can see that there is a separate summary water budget component printed (which has the UZF ET IN and UZF ET OUT results). However when I try the following command, I can only see the GW ET IN and GW ET OUT (not the UZF portion).

```
mfl = flopy.utils.MfListBudget("nameofmodel.lst")
df_flux1, df_vol = mfl.get_dataframes(start_datetime="01-01-2008")
```

If anyone can suggest how to check the ET values from the vadose zone (UZF ET) from a flopy script I would highly appreciate!

Thanks!

**Comment by emorway-usgs** [comment]
Have you specified a non-zero value for the variable "IUZFCB1" in dataset
1B of the UZF input file?  Without specifying this value, MODFLOW won't
write the UZF cell-by-cell fluxes to the binary file that flopy
post-processes.

**Comment by fahadkhan469** [comment]
Hi Emorway,

Thanks for your comment. I tried setting IUZFCB1 vaue to +1 in the UZF file. But still when I read the cbc file using:

import flopy.utils.binaryfile as bf

cbb = bf.CellBudgetFile('localkoga_v5_3.cbc')
cbb.list_records()

The UZF ET doesn't show up in the CBB file. The same thing happens with the LIST file as well. If I open the LIST file with the notepad, I can see a UZF budget summary printed but I cannot read it with FLOPY with the command I typed in my original post. Is there a different command to read the UZF package outputs?

For your convenience, I have uploaded the model input files, the CBC file and the LIST file in following google drive folder. I would highly appreciate if you can help me with this. This might be something simple but I'm a beginner with FLOPY and PYTHON.

Model Files (Google Drive):
https://drive.google.com/drive/folders/127CUd6rVDeBv5VToV-JUQmo8tZOWBApH?usp=sharing

**Comment by emorway-usgs** [comment]
I think in your specific case, you are going to want to set IUZFCB1 = 9,
since in your name file that is the unit number you use for the cbc file.
Then, when you run do a cbb.list_unique_records() on your binary file
object, you should see the UZF terms show up.

**Comment by fahadkhan469** [comment]
Hi @emorway-usgs 

I tried this but it didn't work. I can actually try to read the list file (as a text) and write a code to read the UZF ET component. But I was wondering what happened with the flopy.utils.MfListBudget command. It reads all the saturated zone fluxes but not the Unsaturated Budgets.

**Comment by emorway-usgs** [comment]
I can see that the unsat terms are in fact in the cbc file that you sent:

[image: uz_terms.png]

>

**Comment by fahadkhan469** [comment]
Could you please tell me which flopy commands you used to access the CBC file? As I said I can also see the summarized water budget components when I simply open the LIST file with notepad. But for some reason they are not read when I try reading with flopy.utils.MfListBudget() command. Could that be an issue with flopy versions?

**Comment by emorway-usgs** [comment]
You could use:

import flopy.utils.binaryfile as bf

cbc = bf.CellBudgetFile('localkoga_v5_3.cbc')
cbc.get_unique_record_names()
# ['         STORAGE', '   CONSTANT HEAD', 'FLOW RIGHT FACE ',
#  'FLOW FRONT FACE ', 'FLOW LOWER FACE ', '  STREAM LEAKAGE',
#  '           GW ET', '    UZF RECHARGE', ' SURFACE LEAKAGE',
#  '       HORT+DUNN', '  STORAGE CHANGE']

tm = cbc.get_kstpkper()

dat = cbc.get_data(kstpkper=tm[0], text = '           GW ET')

import numpy as np
dat = np.array(dat)
dat.shape
# (1L, 46L, 31L)

**Comment by fahadkhan469** [comment]
Hi @emorway-usgs

I have been able to figure this out before. I was only interested in reading the UZF ET. In the list file it exists but is there a way to directly read the UZF ET from Flopy?

Fahad

**Comment by emorway-usgs** [comment]
Can you send a truncated version of your UZF input file, perhaps only
includes the first 2 stress periods of input?

>

**Comment by fahadkhan469** [comment]
Hi @emorway-usgs 

Apologies for my delay. I have uploaded the necessary files in:

https://drive.google.com/open?id=127CUd6rVDeBv5VToV-JUQmo8tZOWBApH

Please be informed that the folder has all the modflow input files (titled "testmodel"), but only for 10 stress periods. It also has the UZF file (testmodel.uzf). I would really appreciate if you take some time to see what's happening. The only thing I need to read is the UZF ET (from the CBC file because that's how I can see the UZF ET distribution). 

Regards,

Fahad

**Comment by emorway-usgs** [comment]
Please switch IUZFCB1 from "9" to "-9" and you should get the terms you need.  If you do, would you mind closing this issue?  I don't have permissions to close.  Thanks.

**Comment by fahadkhan469** [comment]
Hi @emorway-usgs 

This worked! Thanks a lot.

Fahad
