### ISSUE TITLE
add utility to extract average concentration from mnw2 mt3d-usgs - enhancement

### ISSUE THREAD

**Issue by johnrobertcraven** [modflowpy/flopy#485]
enhancement to utils 

create utility to extract/calculate mixed concentration extracted by mnw2 well that spans multiple layers.

*I would like to add this enhancement if there is interest. Thanks.

**Comment by langevin-usgs** [comment]
I should know this, but I don't.  Doesn't MT3D-USGS calculate and write the mixed concentration for an MNW well?  If not, then it probably should as part of its group source/sink capability.  Or maybe it's only in the TOB package?

**Comment by jdhughes-usgs** [comment]
@langevin-usgs can this issue be closed?

**Comment by langevin-usgs** [comment]
Not sure what the status on this request is.  Feel free to reopen if there is interest.
