### ISSUE TITLE
bug in plotutil.py

### ISSUE THREAD

**Issue by jknightusgs** [modflowpy/flopy#486]
There seems to be a bug in plotutil.py within the saturated_thickness() method. It reads in a top array of size (nrow,ncol) but then tries to reshape it to (nlay,ncpl) where ncpl=nrow*ncol. This doesn't cause a problem in single layer models like the freyberg example, but broke my script that plots discharge vectors in a multilayer model.
problem line is 1548 in plotutil.py. I made the following change to my local copy and it restored the plot_discharge functionality for me:
#top.shape = (nlay, ncpl)
 top.shape = (ncpl)

**Comment by langevin-usgs** [comment]
@jlarsen-usgs, would you mind taking a look at this?

**Comment by jlarsen-usgs** [comment]
I will take a look at it
