### ISSUE TITLE
version 3.2.11 release

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#488]
@langevin-usgs @jlarsen-usgs @jbellino-usgs @spaulins-usgs @jtwhite79 @emorway-usgs @mwtoews we are going to make a new flopy release at the end of the week. Can you make sure there is a description of your significant changes since the release of **v. 3.2.10** in the [version_changes](https://github.com/modflowpy/flopy/blob/develop/docs/version_changes.md) markdown file.

An example of something significant would be the new plotting functionality and grid class that @spaulins-usgs and @jlarsen-usgs worked on.

Please have your updates in by the end of the day on Wednesday.

**Comment by jdhughes-usgs** [comment]
Also feel free to close as many issues as you can.

**Comment by mwtoews** [comment]
Should these change be staged in the wiki? I've copied the latest version changes to [Version-3.2.11-release](../wiki/Version-3.2.11-release) (similar to the [previous release](../wiki/Version-3.2.10-release)), which can be edited this without requiring a PR.

**Comment by langevin-usgs** [comment]
Good suggestion, @mwtoews.  I made some edits to the wiki.

**Comment by jdhughes-usgs** [comment]
Last chance for changes. I am going to start making the release tomorrow morning 9 AM EDT. 

Let me know if there is some reason not to start on the release.

**Comment by jdhughes-usgs** [comment]
No more changes for 3.2.11. I am in the process of making the release.
