### ISSUE TITLE
MF96 capability

### ISSUE THREAD

**Issue by laat0003** [modflowpy/flopy#49]
Hi, is there a way to make FloPy load an old MF96 model? Apologies if this is the wrong place to post a question like this. Leads to my second question. Is this the place to post user questions or should they also be posted on the MODFLOW users group?

**Comment by langevin-usgs** [comment]
Hello Tariq, flopy will not load a MODFLOW-96 model, and I'm not sure that we will support that anytime soon.  There is, however, a program that comes with MODFLOW-2000 (http://water.usgs.gov/nrp/gwsoftware/modflow2000/modflow2000.html) that will convert a 96 model into a 2000 model.  Perhaps you should give that a shot.

Questions like this are fine to post here, as well as requests for bug fixes or other new capabilities.  If you have general questions about how to use Python or flopy, then we'd prefer that you try a users group.  Good luck!

**Comment by laat0003** [comment]
Thanks Chris,

I have since downloaded the tool and recompiled it to work with larger models. FloPy rocks!

Tariq
