### ISSUE TITLE
MODFLOW 6 support for binary lists

### ISSUE THREAD

**Issue by langevin-usgs** [modflowpy/flopy#506]
@spaulins-usgs, Flopy is almost there for binary lists too.  Here is some good test code to show you what's going on.  Here I'm writing a binary list file using numpy.tofile.  This doesn't work with flopy though, because flopy writes FACTOR 1.0 for lists in the CHD file on the open/close line, which doesn't work with MODFLOW 6.  So a couple things: 
(1) can you get rid of the FACTOR when writing lists (I tried None and that didn't work either);  
(2) can you get it to actually write the list too by also including 'data' in the dictionary?  
(3) we also need to load this stuff, and make it available through chd.stress_period_data[0],
(4) also need support for auxiliary variables; and we should bomb if boundnames are encountered;
(5) will need to be some manipulation because of the cellid tuple and converting to one based, but you should be able to handle that on your end; I think we want the listdata to be in the same form as if you pass it to the package directly.  

```
sim = flopy.mf6.MFSimulation(exe_name=config.mf6exe, 
                             sim_ws=model_ws)
tdis = flopy.mf6.modflow.mftdis.ModflowTdis(sim)
ims = flopy.mf6.modflow.mfims.ModflowIms(sim)
gwf = flopy.mf6.ModflowGwf(sim)

# set up grid information
nlay, nrow, ncol = 3, 12, 10
top = 0.
dz = 1.
botm = [top - (k + 1) * dz for k in range(nlay)]
dis = flopy.mf6.ModflowGwfdis(gwf, nlay=nlay, nrow=nrow, ncol=ncol,
                              top=top, botm=botm)
ic = flopy.mf6.ModflowGwfic(gwf)
npf = flopy.mf6.ModflowGwfnpf(gwf)

dt = [('layer', np.int32), ('row', np.int32), ('col', np.int32), ('head', np.float64)]
dt = np.dtype(dt)
a = [(0, i, 0, 0.) for i in range(nrow)]
a += [(0, i, ncol - 1, 1.) for i in range(nrow)]
a = np.array(a, dtype=dt)
a['layer'] += 1
a['row'] += 1
a['col'] += 1

fname = 'model.chd.sp0'
fout = open(os.path.join(model_ws, fname), 'wb')
a.tofile(fout)
fout.close()

chd_spd0 = {'filename': fname, 'binary': True}
chd_spd = {0: chd_spd0}
chd = flopy.mf6.ModflowGwfchd(gwf, stress_period_data=chd_spd, maxbound=nrow*2)
```

**Comment by spaulins-usgs** [comment]
Binary list support has been added. The tutorial notebook has an example and t505_test.py has some test cases.
