### ISSUE TITLE
flopy3_MT3D-USGS_example.ipynb

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#507]
@emorway-usgs this note book still produces different comparison results than what is in the repo. I seem to remember that the issue was related to results produced by a development version of MODFLOW-NWT. Would be nice if this could be resolved for the next release (v.3.2.12)

**Comment by emorway-usgs** [comment]
Traced the first occurrence of the problem back to these two commits on the [MF-NWT repo](https://github.com/rniswon/mfnwt), 'develop' branch:

On October 27, 2017 11:40:26 AM with commit [bedcf73](https://github.com/rniswon/mfnwt/commit/bedcf732e0a5407a4bfbd7c15d74b32455f3cb4c) MF-NWT provides a linker file with non-zero volumes in the SFR channels that are in fact conveying water.  This is correct.

On November 22, 2017 10:50:57 AM with commit [0c3902f](https://github.com/rniswon/mfnwt/commit/0c3902fd4663aaccf3da6bc2b7e4b49311ba818a) MF-NWT writes 0.0 for the volume of water in the SFR channel but still writes flow between SFR reaches, obvious incorrect.

Need to see what other changes have happened in SFR to make sure there are no other issues.

Also, perhaps related, but not the quite the same problem is [this issue](https://github.com/rniswon/mfnwt/issues/13).

**Comment by emorway-usgs** [comment]
A log of changes to the SFR file in the MF-NWT repo:

![Log_of_SFR_work](https://user-images.githubusercontent.com/3236576/54865990-dc82c180-4d2b-11e9-8d0e-ac548bd2807f.png)

**Comment by emorway-usgs** [comment]
See 4/25/2019 comments on [issue #13](https://github.com/rniswon/mfnwt/issues/13) on MF-NWT repo.  Also, see 4/25/2019 comments on [issue #19](https://github.com/MODFLOW-USGS/mt3d-usgs/issues/19) on MT3D-USGS repo.

**Comment by emorway-usgs** [comment]
@jdhughes-usgs, this source of this issue is with the linker file created by MF-NWT for MT3D-USGS.  Channel volume was being calculated as 0 and passed to MT3D-USGS this way.  For more detailed information, refer to the links in the previous comment on this thread.  The next MODFLOW-NWT release should have the fix.

**Comment by jdhughes-usgs** [comment]
Any chance there will be a NWT release before the end of May?

**Comment by emorway-usgs** [comment]
@jdhughes-usgs Nope, can't get to it before the end of May.  However, possibly before the end of October, I'll check in with Rich to see what the latest estimate is.

**Comment by jdhughes-usgs** [comment]
@emorway-usgs Do you know the status of this issue?

**Comment by emorway-usgs** [comment]
@jdhughes-usgs with the last release of [MF-NWT](https://www.usgs.gov/software/modflow-nwt-a-newton-formulation-modflow-2005) and the fixes that were in LMT, I think this issue can be closed.  

![release](https://user-images.githubusercontent.com/3236576/84189159-aa04d780-aa49-11ea-98e4-6246ff5de107.png)

I just pulled the repo to make sure I was up-to-date, ran the notebook, and the plot at the end looks as expected:

![looks_as_expected](https://user-images.githubusercontent.com/3236576/84188966-4da1b800-aa49-11ea-99f5-290f1bee5227.png)

As long as the latest version of NWT is available, this notebook works.  I'm not sure if a particular autotests pulls the MODFLOW suite of binaries, but if so, we would just want to make sure it is pulling the latest version of NWT.

**Comment by jdhughes-usgs** [comment]
Perfect. Closing this issue.
