### ISSUE TITLE
Read MT3DMS

### ISSUE THREAD

**Issue by Jmodel91** [modflowpy/flopy#511]
Hello,
I'm a absolutly beginner.
I have created some transportmodels (MT3DMS) with the GUI ModelMuse for Modflow.
So I have already output files.

Now, I want read out the files. 
Finally, I want get back the results  as a graphic. 

So which files I have to use?  

Thanks for your answers.

**Comment by langevin-usgs** [comment]
Sorry, this is not a problem with flopy.  You'll need to read the instructions for how to get help with flopy.
