### ISSUE TITLE
MFLGR 2005 - problem with head and flux exchange units

### ISSUE THREAD

**Issue by wjzRdam** [modflowpy/flopy#512]
flopy writes them as binary, but mflgr.exe expects differently
can be fixed by adapting .\flopy\modflowlgr\mflgr.py:
```
class ModflowLgr(BaseModel):
.
    def __init__(self, modelname='modflowlgrtest', namefile_ext='lgr',
.
        # convert iupbhsv, iupbhsv, iucbhsv, and iucbfsv units from
        # external_files to output_files
        ibhsv = self.iupbhsv
        ibfsv = self.iupbhsv
        if ibhsv > 0:
            self.parent.add_output_file(ibhsv, binflag=False)
        if ibfsv > 0:
            self.parent.add_output_file(ibfsv, binflag=False)
```

**Comment by langevin-usgs** [comment]
Hey @wjzRdam , I'm working to add fixes to these issues that you pointed out regarding MODFLOW-LGR.  Would it be possible for you to send me a small python script that uses the mflgr functionality so that we can add it as a test for flopy?  This would make sure that we don't break anything else in the future.  You can also just add the script to this issue here if you like.  Thanks!

**Comment by wjzRdam** [comment]
Hi Chris - I am not at hone today. I will send extra information on the fix tomorrow and send you a script. Best wishes, willem zaadnoordijk
P.S. The fix I added to the issue is not correct - the binflag should be added a gew lines down to the child units - my apologies for this - wjz

 
 
  Op za, mrt. 30, 2019 om 12:50 schreef langevin-usgs<notifications@github.com>:   
Hey @wjzRdam , I'm working to add fixes to these issues that you pointed out regarding MODFLOW-LGR. Would it be possible for you to send me a small python script that uses the mflgr functionality so that we can add it as a test for flopy? This would make sure that we don't break anything else in the future. You can also just add the script to this issue here if you like. Thanks!

**Comment by wjzRdam** [comment]
A couple of lines down, the binflag=False should be added also.
```
            if ibhsv > 0:
                child.add_output_file(ibhsv, binflag=False)
            if ibfsv > 0:
                child.add_output_file(ibfsv, binflag=False)
```
it is not perfect yet because in the parent.nam file no file is added for  ibfsv/iupbfsv when this argument of __init__ is greater than zero.
I attach two python files which prepare, run and view an lgr model
[512.zip](https://github.com/modflowpy/flopy/files/3026941/512.zip)
