### ISSUE TITLE
MODFLOW-USG now broken for flopy because of modelgrid changes

### ISSUE THREAD

**Issue by langevin-usgs** [modflowpy/flopy#513]
Someone recently updated to Python 3.7 and installed the latest flopy and then tried to run a usg model. The following error appeared which didn't happen withj Python 2.7 and flopy. 

![image](https://user-images.githubusercontent.com/3372403/55274084-45da7580-52d4-11e9-9466-73b95f16f46b.png)

**Comment by spaulins-usgs** [comment]
I submitted a pull request that fixes this. The pull request creates a base grid class for the MODFLOW-USG case to store the model's coordinate information. This allows MODFLOW-USG to store coordinate data and work as previously designed. However MODFLOW-USG lacks vertex information so it still has the same exporting and plotting limitations.
