### ISSUE TITLE
xll, yll and projection are no longer written to .nam

### ISSUE THREAD

**Issue by wjzRdam** [modflowpy/flopy#515]
```
xul = 50985.00
yul = 416791.06
proj4_str = "EPSG:28992"
    dis = flopy.modflow.ModflowDis(mf,
        xul=xul, yul=yul, proj4_str=proj4_str)
```

# Name file for MODFLOW-2005, generated by Flopy version 3.2.9.
#xul:50985; yul:416791.06; rotation:0; proj4_str:+init=EPSG:28992; units:meters; lenuni:2; length_multiplier:1.0 ;start_datetime:28/2/2019

# Name file for MODFLOW-2005, generated by Flopy version 3.2.11.
#**xll:0; yll:0; rotation:0; proj4_str:EPSG:4326**; units:meters; lenuni:2; length_multiplier:1 ;start_datetime:28/2/2019

**Comment by spaulins-usgs** [comment]
I submitted a pull request with a fix. In the pull request the model grid coordinate reference information is modified by any information passed to dis. On the mf2005 side this required changing ModflowDis init so that its rotation parameter defaults to None. Before it defaulted to 0.0, making it difficult to tell whether the 0.0 was a user entered value that should override the existing rotation or just the default value.

**Comment by JackFoodRanger** [comment]
@wjzRdam I had similar issues once I update to 3.2.11.

I also have a question related to spatial reference while I am testing it for a project and was going to create a new thread under issue. (I am new to GitHub and not sure if that would be an appropriate place to post question). I see your thread discuss projection, so I follow up this thread with my question. I apologize if I interrupt the discussion, let me know, I will move the question to a new thread. It would be also appreciated if you could give some instruction on post questions on flopy in GitHub, 

My question/issue is when using SpatialReference.getrc() fuction, it doesn't return the correct row, column information. I further investigate using the SpatialReference.get_extent(), it seems doesn't return the correct extent as well. However, when I just print(SpatialReference) object, it gives the correct Xul, Yul information), which is different than get_extent() method. Below is the code that I've test out:

sr = SpatialReference(delr = delr[variable array], delc = delc[variable array], lenuni = 1, xll = 2161202.0, yll = 338429.5, rotation = -42.0, units = 'feet', epsg = 26742)

print(sr) ---> xul:2205587.099; yul:387544.1467; rotation:-42; proj4_str:+proj=lcc +lat_1=39.83333333333334 +lat_2=38.33333333333334 +lat_0=37.66666666666666 +lon_0=-122 +x_0=609601.2192024384 +y_0=0 +ellps=clrk66 +datum=NAD27 +to_meter=0.3048006096012192 +no_defs ; units:feet; lenuni:1; length_multiplier:1.0 (xul, yul are correct)

print (sr.get_extent()) --->2161202.0 338249.5 2205587.099228038 387544.1466745947 (xul, yul are wrong)

print(sr.get_rc(2224875.0, 351562.8)) ---> (357, 114) , which is wrong, it supposed to be (40, 228)

Can you please enlighten? Thanks.

**Comment by rubencalje** [comment]
SpatialReference (mf.sr) is deprecated. Flopy now uses StructuredGrid (mf.modelgrid). But as wjzRdam and spaulins-usgs mentioned, xul and yul are not passed from creating the dis-object to mf.modelgrid in the current master-branch. To fix this in your script (for a model with no rotation), calculate yll from yul (yll = yul - mf.dis.delc.sum()) and add the following, after adding the dis-file:

`mf.modelgrid.set_coord_info(xoff=xul,yoff=yll,proj4=proj4_str)`
