### ISSUE TITLE
Problem with the command export() (aka to_shapefile() )

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#516]
I am running the following script to create a shape file of the recharge using flopy version 3.2.10:

```
import numpy as np
import flopy

path_exe = r'C:\Program Files (x86)\modflow'
path_model = r'C:\Working_Folder\modflow'

# Assign name and create modflow model object
modelname = 'Testing'
mf = flopy.modflow.Modflow(path_model + '\\' + modelname, exe_name=path_exe + '\\' + 'mf2005', model_ws=path_model)

# Model domain and grid definition
Lx = 1000.
Ly = 1000.
ztop = 0.
zbot = -200
nlay = 1
nrow = 20
ncol = 20
delr = Lx / ncol
delc = Ly / nrow
delv = (ztop - zbot) / nlay
botm = np.linspace(ztop, zbot, nlay + 1)

# Create the discretization object
dis = flopy.modflow.ModflowDis(mf, nlay, nrow, ncol, delr=delr, delc=delc, top=ztop, botm=botm[1:])

# Create recharge pkg
rch_rate = 0.001 * np.ones(shape=(nrow, ncol))
rch_rate[1, :] = 0.002
rch = flopy.modflow.ModflowRch(mf, rech=rch_rate)

# export rch to shape file
mf.export(path_model + '\\' + 'rch.shp')
```

However I got the following error messages:

```
Traceback (most recent call last):
  File "H:/scripts/python/testing_scripts/bug_mf.py", line 34, in <module>
    mf.export(path_model + '\\' + 'rch.shp')
  File "C:\Python27\lib\site-packages\flopy\mbase.py", line 191, in export
    return utils.model_helper(f, self, **kwargs)
  File "C:\Python27\lib\site-packages\flopy\export\utils.py", line 355, in model_helper
    **kwargs)
  File "C:\Python27\lib\site-packages\flopy\export\shapefile_utils.py", line 237, in model_attributes_to_shapefile
    write_grid_shapefile(filename, ml.sr, array_dict)
  File "C:\Python27\lib\site-packages\flopy\export\shapefile_utils.py", line 78, in write_grid_shapefile
    wr = shapefile.Writer(shapeType=shapefile.POLYGON)
  File "C:\Python27\lib\site-packages\shapefile.py", line 1069, in __init__
    raise Exception('Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.')
Exception: Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.
```

To partially solve the problem I opened the file: **C:\Python27\lib\site-packages\flopy\export\shapefile_utils.py** and changed the following two lines:

Line 78 replaced with:  `wr = shapefile.Writer(filename, shapeType=shapefile.POLYGON)`
Line 102 replaced with: `wr.poly(polys=[pts])`

I did run my code again and I am now able to create the desired shapefile. However, now I get an error for line 106 of the same file:

```
File "C:\Python27\lib\site-packages\flopy\export\shapefile_utils.py", line 106, in write_grid_shapefile
    wr.save(filename)
AttributeError: 'Writer' object has no attribute 'save'
```

I am not sure what to do now. I hope the above makes sense.

**Comment by langevin-usgs** [comment]
The latest version of pyshp has a different call signature.  This has been a problem for us that required adding traps everywhere shapefile is used. It looks like you are using python 2.7, which poses a possible challenge.  What version of pyshp are you using?

**Comment by giovannifi** [comment]
I tested the code with both python 2.7 and python 3.6. My version of pyshp is 2.1.0. By the way I have just updated flopy to version 3.2.11 and everything seems to work OK.

**Comment by juancastilla** [comment]
For the moment, this can be resolved by pinning Flopy to an older version of pyshp — conda install flopy pyshp=1.2.12 solved the problem for me

**Comment by langevin-usgs** [comment]
This should work with pyshp 1.x and 2.x, if not then please reopen.
