### ISSUE TITLE
Problem loading OC file when no ext_unit_dict passed

### ISSUE THREAD

**Issue by corcorf** [modflowpy/flopy#518]
Using the `flopy.modflow.ModflowOc.load` method appears to fail if no `ext_unit_dict` is passed.

Variable `filenames` is initiated as a list with `fname` in the first position, but `fname` is only initiated `if ext_unit_dict is not None` (lines 920 - 928 of mfoc.py in the develop version).

Calling: 
`oc = flopy.modflow.ModflowOc.load('model.oc',model=ml)`
leads to error:
` ~/miniconda3/envs/flopy/lib/python3.7/site-packages/flopy/modflow/mfoc.py in load(f, model, nper, nstp, nlay, ext_unit_dict)`
`    926 `
`    927         # initialize filenames list`
`--> 928         filenames = [fname, None, None, None, None]`
`    929 `
`    930         # fill remainder of filenames list`

`UnboundLocalError: local variable 'fname' referenced before assignment`

**Comment by jdhughes-usgs** [comment]
Can you provide additional information for this error:

1. Have you loaded a discretization (`DIS`) package prior to `flopy.modflow.ModflowOc.load()` or passed in `nper`, `nstp`, and `nlay` to `flopy.modflow.ModflowOc.load()`.
2. Does your oc file use [words or numeric codes](https://water.usgs.gov/ogw/modflow/MODFLOW-2005-Guide/index.html?oc.htm)?

**Comment by corcorf** [comment]
Apologies for the delayed response. In answer to your questions:

1. Yes, I did successfully load a `DIS` package first.

2. The `OC` file uses words.

I haven't been able to test the fix yet but will let you know if I run into any more problems with it.
Thanks 
Flann
