### ISSUE TITLE
Well package fails to load with NWT

### ISSUE THREAD

**Issue by laat0003** [modflowpy/flopy#523]
I have a MFNWT well package input file formatted as below. I am loading using 'mfnwt' as version in the model load and everything loads fine except the well package. It fails when reaching 'end' because it is expecting an int(). Flopy rulz boyeeee.

#Modflow Well Package
options
specify
end
      136                50                  AUX              IFACE.......

**Comment by langevin-usgs** [comment]
@jlarsen-usgs I think you are the options guy.  Can you have a look?

**Comment by jlarsen-usgs** [comment]
@laat0003, @langevin-usgs 

I'm looking into this error. Are you providing phiramp and iunitramp when you use the specify option?

Ex. 
#Modflow Well Package
options
specify 0.05 50
end
136 50 AUX IFACE

Please correct me if I am wrong, but it is my understanding that these parameters are supposed to be declared with the specify option. After I added these two parameters, flopy was able to load the option block.

**Comment by laat0003** [comment]
Cheers for the rapid response.

Model was originally developed by someone else using GWVistas (...Meh!). The options section of the well package input file has values for phiramp and iunitramp (my apologies, I should have included the values in the original issue) but the phiramp is in scientific notation. Exact line with the specify option is below with one space between the Y and 1 and two spaces between the 2 and 0. The model runs fine with any MFNWT.exe so I'm assuming that the formatting is legit.

SPECIFY 1.000000e-002  0

Tariq

**Comment by jlarsen-usgs** [comment]
@laat0003 

The formatting is legit. I'm still not able to reproduce the error on my end though. Two questions:

1) Can you upload a copy of your well file and the script you're working with so I can dig into this issue a little deeper?

2) Are you using the most recent version of flopy? As of version 3.2.11 the options handling methods were updated. You can check the version by calling

```
print(flopy.__version__)
```

**Comment by laat0003** [comment]
Well that will probably solve the problem. I am using 3.2.9. I did the install and upgrade via Conda a few days ago but it seems 3.2.9 is all you get that way. I assumed whatever came via Conda forge was the latest (doh!). My bad.
 
I know I can get 3.2.11 via pip but it fails when trying to downgrade numpy because I don't have write access to a part of the drive that pip wants to use (Curses!). I'm on secondment to federal government in AUS and the IT department locks everything down then takes their sweet-ass time to get around to access permissions request. Anyway, I'm sure that if it works for you, I should be fine when I can get 3.2.11 version installed. 

Apologies to have wasted your time. Keep up the good work. You guys rock.

Tariq

**Comment by jlarsen-usgs** [comment]
@laat0003 

It definitely wasn't a waste of time. When looking through your issue, I did find potential bug in the options reader routine that I'll be providing a fix for after testing it.

Best
Josh
