### ISSUE TITLE
HOB package error on multi-node observations

### ISSUE THREAD

**Issue by matejgedeon** [modflowpy/flopy#528]
I run into the following error when reading or constructing the HOB package:

``loading hob package file...``
``   HOB  package load...failed``
``   sum of dataset 4 proportions must equal 1.0 - sum of dataset 4 proportions = 0.9999999999999999``

I thing this has to do with the way Python treats the numbers when dividing. As you see above, 1.0 is practically 0.99999999999999.

I think it would be helpful to ease up the condition on the sum of observation proportions for the checker and loader or make it a warning only.

**Comment by jdhughes-usgs** [comment]
Could you provide a simple HOBS file and associated simple discretization file for testing? Ideally a discretization file with one row, one column, and however many layers you have and the offending observation.

**Comment by ConstableCatnip** [comment]
I have run into this same issue. Attached is a zipped notebook based on the flopy3_working_stack_demo.ipynb that reproduces the error or attached dis and hob files that should as well. I'll also do a commit with the solution I used.

DIS and HOB files:
[MultiLayerHOB_LoadFail_DisHob.zip](https://github.com/modflowpy/flopy/files/3074997/MultiLayerHOB_LoadFail_DisHob.zip)

Notebook:
[MultiLayerHOB_LoadFail.zip](https://github.com/modflowpy/flopy/files/3074939/MultiLayerHOB_LoadFail.zip)
