### ISSUE TITLE
Mt3D compilation for Mac

### ISSUE THREAD

**Issue by 2012konrad77** [modflowpy/flopy#53]
I am trying to compile Mt3d using gfortran to run on mac.

The Terminal announces the following errors:
Undefined symbols for architecture x86_64:
  "_getcl_", referenced from:
      _MAIN__ in mt3dms5.o
  "_hss5al_", referenced from:
      _MAIN__ in mt3dms5.o
  "_hss5bd_", referenced from:
      _MAIN__ in mt3dms5.o
  "_hss5fm_", referenced from:
      _MAIN__ in mt3dms5.o
  "_hss5rp_", referenced from:
      _MAIN__ in mt3dms5.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status

Can you please advise what I need to do to make the compilation successful?

Thanks!

**Comment by langevin-usgs** [comment]
What command did you use to compile?  

I'll see if I can create a pymake (https://github.com/modflowpy/pymake) script for MT3D this weekend.

**Comment by 2012konrad77** [comment]
I created makefile as suggested by Theo Olsthoorn in another post and run it using make command. The file was adapted from mf2k and looks as follows:

SOURCELOC = 
UTILITYLOC = 
NEWMOD = 
PROGRAM = mt3dms5
INCDIR= .

# Define the Fortran compile rand its flags
F77= gfortran
F90= gfortran
F77FLAGS=
F90FLAGS=

# Define the C compiler and its flags
CC= gfortran

# -D_UF defines UNIX naming conventions for mixed language compilation.
CFLAGS= -D_UF -O3

# Define the libraries
SYSLIBS=  -lc
USRLIB = 

# Define all object files which make up Modtools
OBJECTS= \
		mt3dms5.o \
		mt_utl5.o \
		mt_adv5.o \
		mt_btn5.o \
		mt_dsp5.o \
		mt_fmi5.o \
		mt_gcg5.o \
		mt_rct5.o \
		mt_ssm5.o \
		mt_tob5.o

SRCS= $(OBJECTS:.o=.f)

install: $(PROGRAM)

# Define Task Function Program Modtools
all: $(PROGRAM)

# Define what Modtools is
$(PROGRAM): $(OBJECTS)
	-$(F77) $(F77FLAGS) -o $(PROGRAM) $(OBJECTS) $(GMG) $(USRLIB) $(SYSLIBS)

# Pth_Object codes of Modtools
%.o: %.for
	$(F77) $(F77FLAGS) -c $<

#  end

**Comment by langevin-usgs** [comment]
I added a download and build script for mt3d.  This was added to pymake:

https://github.com/modflowpy/pymake

It compiles fine, but I haven't tried running it yet.
