### ISSUE TITLE
write_simulation silent=None

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#552]
@spaulins-usgs would it be possible to add a `silent` option to `write_simulation()` like we have for `run_simulation()`??

**Comment by spaulins-usgs** [comment]
The Flopy for MF-6 code currently has a global verbosity level setting. A verbosity level of 0 is quiet/silent. Verbosity level can be set when loading or creating a simulation with the verbosity_level parameter. It can also be set in the simulation's simulation_data attribute.  To set it to quiet for a simulation "sim" you would type:

sim.simulation_data.verbosity_level =0

If you see value in a silent option specifically for write_simulation I can add an optional silent option parameter to write_simulation which sets the verbosity level to 0 just for that operation.

**Comment by jdhughes-usgs** [comment]
I would like a `silent` option. Don't know if anyone would oppose it.

**Comment by spaulins-usgs** [comment]
Silent option for the write_simulation method has been added.
