### ISSUE TITLE
MNW2: fails for multiple wells with differnt number of nodes

### ISSUE THREAD

**Issue by khayley** [modflowpy/flopy#556]
I am getting errors when trying to combine multiple mnw objects into a single ModflowMnw2 object, the issue/bug is in the make_node_data method and it fails when there are multiple mnw objects with node data recarray's that have different  lengths.
I have attached a zip file with 2 python scritps inside
Test_MNW2.py is an example that highlights the problem
make_node_data.py has the alterations that I made to my local flopy version to make it work

My flopy version is 3.2.11 using Anaconda Python 3.7

[make_node_data.zip](https://github.com/modflowpy/flopy/files/3168697/make_node_data.zip)

**Comment by jlarsen-usgs** [comment]
Hi @khayley,

I'm looking into this issue. It looks like a simple rewrite of how make_node_data() creates and sets nodes to the node_data recarray. Thanks for providing a sample problem, it was a big help for tracking down the problem.

**Comment by langevin-usgs** [comment]
Should be fixed with https://github.com/modflowpy/flopy/pull/567
