### ISSUE TITLE
online help for "flopy.utils.reference Module" is empty 

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#56]
Hi Guys, I noticed the online help for the "flopy.utils.reference Module" is empty. Is this a bug? Or it was pulled off due to some reasons?

**Comment by langevin-usgs** [comment]
Are you looking on the develop branch?

**Comment by flydream0428** [comment]
No, it's the lone guide. http://modflowpy.github.io/flopydoc/reference.html

**Comment by jtwhite79** [comment]
Sorry for the lacking docs - the reference modules is still in flux.  I'll try to get something up there by the end of the week.
