### ISSUE TITLE
Head binary file is not being read properly

### ISSUE THREAD

**Issue by geowat** [modflowpy/flopy#563]
I have used `flopy.utils.HeadFile` for a number of models quite successfully - regular and unstructured (MF6). However, the utility is not reading the binary data properly for a model which was built in Groundwater Vistas (quite irrelevant but just mentioning) - unstructured grid - using MF-USG code. The binary data can be imported into Groundwater Vistas to visualize the head contours. Even though flopy is reading the file without any errors `ho = flopy.utils.HeadFile("test.hds")`. However, there is an error saying that `kstpkper not found` when particular stress period heads are tried to be accessed - `ho.get_data(kstpkper=(2,99))`. Also, `ho.get_kstpkper()` is returning `[(0,0)]` (it is a transient model with hundreds of stress periods). It's worth mentioning that the number of rows and cols are as expected in `ho`, however `ho.nlay` is returning 2 which is quite wrong as the model has more layers. What could be the potential reason for the utility not being able to read the binary file?

**Comment by langevin-usgs** [comment]
For MODFLOW-USG unstructured grids, you have to use the `HeadUFile` class because the variables in the file are a little different.  That is not the case for the MODFLOW 6 unstructured grids.
