### ISSUE TITLE
v 3.2.12 release

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#565]
@langevin-usgs @spaulins-usgs @jlarsen-usgs @aleaf-usgs @jtwhite79 @mwtoews @jbellino-usgs @rubencalje @dbrakenhoff @emorway-usgs 

I want to make another FloPy release prior to the MODFLOW and More FloPy class. The target release date is 5/30/2019. Everyone get your changes/bug fixes in. Don't forget to update  the [version changes wiki](https://github.com/modflowpy/flopy/wiki/v-3.2.12-version-changes) and [notebook examples](https://github.com/modflowpy/flopy/blob/develop/docs/notebook_examples.md) if you add any notebooks to the repo.

**Comment by langevin-usgs** [comment]
Sounds good.  I will update the flopy documentation pages too, so please review and cleanup docstrings as necessary.

**Comment by jdhughes-usgs** [comment]
@langevin-usgs @spaulins-usgs @jlarsen-usgs @aleaf-usgs @jtwhite79 @mwtoews @jbellino-usgs @rubencalje @dbrakenhoff @emorway-usgs

**Just a reminder that you should get your changes in by tomorrow. Don't forget to update the [version changes wiki](https://github.com/modflowpy/flopy/wiki/v-3.2.12-version-changes)**
