### ISSUE TITLE
load a bas6 package with external binary usg starting heads

### ISSUE THREAD

**Issue by Dani-gwmodels** [modflowpy/flopy#585]
Hi. 

First of all, im new in python an flopy. Sorry about that...

Im trying to load a package which was made with GWV. It uses external files for the starting heads.

the bas at some point calls unit number 44  like this:

EXTERNAL -44  1  (BINARY)  -1  Starting Heads Layer 1
EXTERNAL -44  1  (BINARY)  -1  Starting Heads Layer 2
EXTERNAL -44  1  (BINARY)  -1  Starting Heads Layer 3...

44 is a binary HeadU (usg) file.

I tried the basic script:

bas = flopy.modflow.ModflowBas.load('bas.bas',m)

but it gets and error (which actually make sense to me), asking for an external dictionary so he would be able to understand what 44 unit number is.

According to my low experience, the dictionary object needs an 'filename' attribute.

How do i create this dictionary?

**Comment by jlarsen-usgs** [comment]
Hi @Dani-gwmodels,

This is not really an issue, a better place to ask this question is [](https://stackoverflow.com/questions/tagged/flopy).

Your solution is to pass a dictionary formatted {unit_number : file name} into the ModflowBas.load() function.

```
ext_unit_dict = {1, "myfile"}
bas = flopy.modflow.ModflowBas.load('bas.bas', m, ext_unit_dict=ext_unit_dict)
```
