### ISSUE TITLE
PlotMapView.contour_array() is broken

### ISSUE THREAD

**Issue by mnfienen-usgs** [modflowpy/flopy#587]
It seems that the new generalization of the contouring for both structured and unstructured arrays has broken the ability to contour an array that uses `np.nan` to mask it. 

This can reproduced by assigning a single element of any array as `np.nan` and then trying to call `contour_array()`. The result is an empty plot. I believe this is a difference from using `plt.tricontour()` to generate the contours rather than `plt.contour()`. 

One solution would be to bring back `plt.contour()` in the context of structured grids. It seems `plt.tricontour()` has a known issue with `np.nan` for masking https://stackoverflow.com/questions/28964453/set-mask-for-matplotlib-tricontourf

**Comment by langevin-usgs** [comment]
Wonder if it wouldn't be better to switch to masked arrays (np.ma)?

**Comment by mnfienen-usgs** [comment]
masked arrays are a good way to do it, but the fact that it worked before has now broken a bunch of things that worked before.

**Comment by langevin-usgs** [comment]
I see.  But maybe we can make one small change before contouring where we mask nan's instead of trying to contour them?

**Comment by jwhite-usgs** [comment]
+1 for np.NaN

**Comment by jlarsen-usgs** [comment]
@mnfienen 

I'm looking into a fix for this issue. It seems as if there is a problem with how contour arrays are masked during the triangulation.  I agree, we should be able to pass np.NaN through and still contour an array.

**Comment by mnfienen-usgs** [comment]
Thanks @jlarsen-usgs. I played around with a couple options but didn't get far. Let me know if you'd like to discuss at all

**Comment by jlarsen-usgs** [comment]
Fixed with PR #589
