### ISSUE TITLE
DISV plot issue

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#588]
For the attached problem, @raoulcollenteur had to slice a `DISV` head array to plot correctly. Seems that the modelgrid object should tell the plot routine how to plot this data type. It is only a 1 layer model. It did the same for me so appears to be a real problem.

[disv_plot_issue.zip](https://github.com/modflowpy/flopy/files/3263713/disv_plot_issue.zip)

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs 

I put together a fix for this issue and will submit alongside of #587 after testing.

On looking through the issue, I have a question about the extra dimension coming from the HeadFile object. In the example provided by @raoulcollenteur the shape of head1 is

```
head1.shape = (1, 1, 218)
```
for a one layer vertex grid model at `idx = -1`. What is this extra dimension used for? It seems like the shape should be `(nlay, ncpl)` to be consistent with other vertex model grid based arrays.

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs the header format in the binary files is the same for all of the files. DISV is always (nlay, 1, ncpl) and DISU is always (1, 1, nodes). Right now the head reader does not know anything about the grid type of the model.

**Comment by jlarsen-usgs** [comment]
@jdhughes-usgs thanks for the clarification. I understand why the header is consistent across binary files, since it would require more IO routines to check the grid type and store the data.
