### ISSUE TITLE
not able to load SFR that previously was loading

### ISSUE THREAD

**Issue by jwhite-usgs** [modflowpy/flopy#607]
The attached nam, dis, and sfr files are part of an autotest for pyemu that was working but now is not. Im not anywhere near smart enough to decipher the sfr input rules... is this sfr file not valid or is something broken in flopy?  

[Archive.zip](https://github.com/modflowpy/flopy/files/3353367/Archive.zip)

**Comment by mwtoews** [comment]
The first item on ds6a must be a regular sequence 1, 2, 3 etc., but I see a power-of-eight sequence 1, 256, 6561. Try these fixes to the sfr file:
```diff
--- supply2.sfr	2018-05-23 19:37:38.000000000 +1200
+++ supply2.sfr.fixed	2019-07-03 17:23:48.973599150 +1200
@@ -46,6 +46,6 @@
 5.0 1.0 4347792138496.0 25600000000.0 
-256 1 6561 0 50000.0 0 0 0 0.05000000074505806 
+2 1 6561 0 50000.0 0 0 0 0.05000000074505806 
 5.0 1.0 6888538283006.25 25600000000.0 
 5.0 1.0 4347792138496.0 25600000000.0 
-6561 1 0 0 0 0 0 0 0.05000000074505806 
+3 1 0 0 0 0 0 0 0.05000000074505806 
 5.0 1.0 4347792138496.0 25600000000.0 
```

**Comment by jwhite-usgs** [comment]
Thanks @mwtoews - I can deal with that!  How does one know that segments must be a regular sequence?  I didn't see that in the online guide... (I think flopy actually assigned those seg numbers long ago...)

**Comment by aleaf** [comment]
@jwhite-usgs, good point. Looking at the actual manual (which sometimes has more info than the online guide), I can't find anything saying that segments have to be a regular sequence. But if I take the [test1ss example](https://github.com/modflowpy/flopy/blob/develop/examples/data/mf2005_test/test1ss.sfr) and change segment 1 to 10, and 2 to 20, I get this error from MODFLOW:
`SEGMENT NUMBER (NSEG) OUT OF RANGE:     10`
changing NSS from 8 to 20 causes an end of file error when reading the reach data.

**Comment by mwtoews** [comment]
On further inspection, the segments don't need to be in sequential order, but they must be within the range of NSS. For instance if you have 8 segments, then you can't try to define data for segment 10, since it's out of range. But you could re-arrange data set 6 in a mix-up order, e.g. defining segment 2 before segment 1, and this works with test1ss without error.

The [MFNWT Online Guide for SFR](https://water.usgs.gov/ogw/modflow-nwt/MODFLOW-NWT-Guide/sfr.htm) sort of states this twice (in notes 9 and 21):
> The data need not be defined in sequential order by stream segment number. All active segments in the stream network must be defined for each stress period through a combination of ITMP and Item 6 and NP and Item 7.

**Comment by jdhughes-usgs** [comment]
@jwhite-usgs this seems closed. Will close but let me know if it needs to be reopened.
