### ISSUE TITLE
Time units in SEAWAT

### ISSUE THREAD

**Issue by jonathanqv** [modflowpy/flopy#611]
I´ve tried making inputs of time units equal to 1E9 seconds, but when I run SEWAT it returns me output values equal to 0.1 seconds, is it a bug or is it made in purpose?
Thank you!

**Comment by langevin-usgs** [comment]
There is a FIRSTDT argument for SEAWAT in the VDF input file.  You might need to change this too.  You also need to make sure that DT0 is set correctly for the MT3D model.  I don't think this is a flopy issue, so I'm closing.

**Comment by jonathanqv** [comment]
Thanks! I´ll check that option.
Kind regards.
