### ISSUE TITLE
Loading MODFLOW-6 model with multiple same type packages

### ISSUE THREAD

**Issue by kyledavis-usgs** [modflowpy/flopy#614]
I have loaded a MODFLOW-6 model with multiple packages of the same type into flopy. I'm using flopy 3.2.13 (develop). For example I have 21 well packages (broken up by watershed in our model), 3 recharge packages (two list-based recharge packages for irrigation areas and one array-based recharge packages for basin-wide recharge), and 2 drain packages (one for ephemeral streams and one for perennial).

I've created a model instance (_MI_) for the MF6 model, and the packages appear to load into the instance. But when I try to access them, it doesn't seem to be retaining multiple packages of the same type in flopy for the WEL and DRN packages; however, our multiple recharge packages (2 of type rch and 1 of type rcha) loaded properly. When I access the _MI_.drn or _MI_.wel, it only returns one package for each type as opposed to _MI_.rch[0] or _MI_.rch[1] allows me to access the various recharge packages.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, can you look at this?  I know that you've made changes to this recently.  For some reason, it does seem difficult (or at least the syntax is difficult to remember) to retrieve models and packages for MODFLOW 6 models.  I think you can get a list of the package names, and then retrieve packages by name or by file type, as Kyle is trying to do here.  I wonder if there is some way we can get the syntax into the docstrings somehow.  

@kyledavis-usgs, I'm pretty sure the m.get_package('wel-1')style syntax is working now, which is an alternative to m.wel, but you need to know the package name.

**Comment by kyledavis-usgs** [comment]
@langevin-usgs I can confirm that the .get_package() method works for me in this case and is probably a little more convenient that m.rch[0] or m.drn[0], etc

**Comment by kyledavis-usgs** [comment]
Sorry to tag onto this issue again. I tested the .get_package() method with RCH and DRN packages but not WEL packages before I responded. All of our WEL Packages are loaded with the package name = wel, so I still can't seem to access the separate well packages once the model is loaded into flopy. Each WEL package has a time-series file and an observation file associated, and those packages load in sequentially (wel_1_obs, wel_1_ts; wel_2_obs, wel_2_ts; etc) but all the WEL packages are named wel

**Comment by spaulins-usgs** [comment]
I tested and confirmed these problems. Fixes for these problems can be found in this fork here:

https://github.com/spaulins-usgs/flopy/tree/develop/flopy

Please replace your site-packages/flopy folder with this one.

**Comment by kyledavis-usgs** [comment]
@spaulins-usgs your fix worked for me. I can access the WEL Packages from my model instance (ML) using ML.wel[0], ML.wel[1], etc or using get_package('pack-nam')

**Comment by langevin-usgs** [comment]
@spaulins-usgs, are you going to submit this through a PR?
