### ISSUE TITLE
Transient2d.export("to.shp") broken

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#616]
Trying to export a Transient2d instance to shapefile is broken:
`m.rch.rech.export("rech.shp")` yields `AttributeError: 'ModelTime' object has no attribute 'sim_time'`

**Comment by spaulins-usgs** [comment]
I have checked in a fix here:

https://github.com/spaulins-usgs/flopy

You should only need to update flopy/export/utils.py

**Comment by jtwhite79** [comment]
sweet - thanks @spaulins-usgs

**Comment by langevin-usgs** [comment]
@spaulins-usgs, PR on the way for this?

**Comment by spaulins-usgs** [comment]
@langevin-usgs, yes PR for this and three other issues getting sent now

**Comment by spaulins-usgs** [comment]
@langevin-usgs, github gave an error message when I tried a pull request (generic "Looks like something went wrong!" error. Now when I try to access my fork I get the same error. I will try the PR again later today.
