### ISSUE TITLE
Loading MF6 RCH or EVT arrays for repeated stress periods

### ISSUE THREAD

**Issue by kyledavis-usgs** [modflowpy/flopy#617]
Working again with a MODFLOW6 model using flopy 3.2.13 (develop). Running a model with a steady-state stress period followed by monthly stress periods where recharge is specified for steady-state, then at 6 month intervals (specified recharge in SPs 1, 2, 8, 14, etc.). MODFLOW6 uses recharge from SP 2 for 3-7 and from 8 for 9-13, etc. However, when loading the model in flopy, the "in between" stress periods aren't populated. Is this the intent?

![flopy recharge reading](https://user-images.githubusercontent.com/5942647/61230610-36463780-a6df-11e9-821a-2ed8d4655359.png)

**Comment by spaulins-usgs** [comment]
Yes this is as designed. The idea is to provide a placeholder "None" in the dictionary for any stress period where data is not explicitly entered. This makes it easy to see where data was not explicitly entered and also lets you build out your stress period data without having to make multiple copies of potentially large arrays.
