### ISSUE TITLE
Inheriting MODFLOW free-format header properties for an MT3D fixed-format array

### ISSUE THREAD

**Issue by emorway-usgs** [modflowpy/flopy#619]
I am in need of advice on how to properly address a possible bug in uzt, though I need to first confirm it is a bug. 

After loading a free format modflow model I use flopy to generate a companion MT3D-USGS model.  For the UZT package, I need to fetch IUZFBND from the MF object, which is easy enough with:

`iuzfbnd = mf.uzf.iuzfbnd`

After instantiating UZT with:

```
cuzinf = np.zeros((nrow, ncol), dtype=np.float32) 
cuzfet = np.zeros((nrow, ncol), dtype=np.float32)
uzt = mt3d.Mt3dUzt(mt, iuzfbnd=iuzfbnd, cuzinf=cuzinf, cuzfet=cuzfet)
```
it would seem that the `Util2d` header information in `iuzfbnd` is still in MODFLOW's free format, which makes sense.  The problem arises when writing the MT3D input files; currently, the `mtuzt.py` package does not auto-correct the `Util2d` header information from MODFLOW-free format for the case when MT3D-USGS is expecting fixed format (which is the default with MT3D).  Thus, I'm wondering if I should add code that checks the status of `MODFLOWStyleArrays` in `BTN` and makes appropriate edits? Or, is this such a nuanced case that one would expect the user to account for this in their script, assuming there is a way to manually manipulate the `Util2D` properties?  What is the correct flopy approach?

**Comment by langevin-usgs** [comment]
Can you set iuzfbnd = mf.uzf.iuzfbnd.array so that you bring in the actual numpy array and let Mt3dUzt handle the array control record and formatting?

**Comment by emorway-usgs** [comment]
Thanks @langevin-usgs that seemed to be all it needed.  Oh, the subtleties...
