### ISSUE TITLE
Reassigning values to stress period data arrays for well, drain, recharge etc. packages

### ISSUE THREAD

**Issue by RebeccaDoble** [modflowpy/flopy#628]
I've opened a MF2005 model in flopy and discovered that there's an error in the well fluxes. I want to divide fluxes from all wells at all times by 6. 

arr = m.wel.stress_period_data.array["flux"]
arr *= 0.16666666667
m.wel.stress_period_data.array["flux"]=arr

When I plot arr, it is correct. When I plot m.wel.stress_period_data.array["flux"], it has not been reassigned the new flux values. What brackets or element identifiers have I missed?! Is there any way I can do this? Or do I have to go back to my original model and change the well file when it is generated? 

Thanks,
Rebecca

**Comment by MJKnowling** [comment]
Hey Rebecca,
Given that you want to perform a simple global operation (modify all well fluxes in the same way), there no real need to use pandas like we were doing for similar things in the class. So not much more than what you have is required.
It is cleaner not to assign in-place of the package. And also better to use `stress_period_data.data` when dealing with packages that are of list type. This should work..

```
wel = m.wel.stress_period_data.data
spd = {}
for kper,lrcq in wel.items():
    spd.update({kper: [[lrcq[wi].k, lrcq[wi].i, lrcq[wi].j, lrcq[wi].flux / 6] for wi in range(len(wel[kper]))]})
flopy.modflow.ModflowWel(model=m,stress_period_data=spd,) # specify other attributes of your orig wel package here too!
m.wel.stress_period_data.data  # please check!
```

**Comment by RebeccaDoble** [comment]
Thanks Matt.

Far out I have a long way to go. I ended up changing the well flux data where I generated the dictionaries in the first place. But I’ll keep this code in case I need to change anything conditionally – which I did for ghb and hk. It’s good to know how to handle it properly. Even though it is presented as an array, it doesn’t really act that way.

Rebecca.

**Comment by langevin-usgs** [comment]
I'm going to close this issue as I'm not sure it is a bug in FloPy.  Feel free to reopen if I'm mistaken.
