### ISSUE TITLE
FloPy arcade game example

### ISSUE THREAD

**Issue by philipphoehn** [modflowpy/flopy#638]
Attached are a few lines of code to run a little arcade game using FloPy. It’s based on a simple box-type model for now, but it should be easy to increase levels of difficulty, manipulate the reward function and widen the action space.

The idea here is to ensure safe transport of a particle from left to right by adjusting the bottom specified head during the simulation with the up/down key. As a pumping well is distorting the flow field, reward is earned for minimizing travel distance while avoiding arrival in the well and the left and bottom specified head cells: the shorter the travel distance, the higher the score.
 
Just wanted to try and see if FloPy provides an environment fit to generally collect data for reinforcement learning on groundwater models of arbitrary complexity. For my purposes here, it is doing an enchanting job – even though bits and pieces are hardcoded to replace the particle I am chasing through the model domain after every episode. Probably my bad, as I am not really regularly using MODFLOW, currently. I absolutely appreciate the massive effort you are investing into creating this interface!
 
Running FloPyArcadePlay.py – after specifying your local path to MF2005 and MP6 at the top of the file – kicks it off. I tested on Linux and Windows. I am happy to make any changes necessary based on review. Tried adhering to the general OpenAI Gym convention in terms of what is returned per timestep.

[FloPyArcade.zip](https://github.com/modflowpy/flopy/files/3553010/FloPyArcade.zip)

**Comment by jdhughes-usgs** [comment]
Not sure how to incorporate this in flopy (or if it should be). Reopen this issue if someone has a suggestion for how to do something with this interesting effort.
