### ISSUE TITLE
MfList error: cannot set stress_period_data for MODFLOW-USG's WEL package

### ISSUE THREAD

**Issue by ChrisLHY** [modflowpy/flopy#641]
An initial MODFLOW-USG model is generated using the line below.

`m = fp.modflow.Modflow(version = 'mfusg')`

Then an externally generated DISU file is imported, followed by the line below to set the stress period data for the WEL package:

`fp.modflow.ModflowWel(model = m, stress_period_data={0:[1, 50, -2]})`

where 1 is the layer number, 50 is the cell number and -2 is the pump rate. The following error is returned:

`AssertionError: MfList error: ndarray shape (1, 3) doesn't match dtype len: 4`

It seems that Flopy still wants the format of [layer, row, column, rate], despite the version being used is MODFLOW-USG.

My Flopy version is 3.2.12. Any help on this matter would be greatly appreciated.

**Comment by langevin-usgs** [comment]
Try this:

```
m = fp.modflow.Modflow(version='mfusg', structured=False)
```
