### ISSUE TITLE
plot_discharge when confining beds are present

### ISSUE THREAD

**Issue by jclaus88** [modflowpy/flopy#656]
I get faulty discharge plots for my model which contains confining beds.

e.g. my model with 4 layers and 3 confining beds has a saturated thickness array with 7 layers, but for calculation of the specific discharge, the iteration is over the number of layers (range(nlay)), thus taking the wrong index for the calculation

currently I added these 2 lines of code after calculation of the saturated thickness, to drop the  layers of the confining beds.

            drop_idx = np.cumsum([2 if a == 1 else 1 for a in self.model.dis.laycbd.array[:-1]])-1
            sat_thk = np.delete(sat_thk, drop_idx, axis=0)

**Comment by langevin-usgs** [comment]
Not surprising there is an error in here.  Quasi-3D confining units probably aren't supported very well.  It would be possible to calculate velocity vectors for these layers by assuming horizontal velocity is zero and dividing Q lower face by the cell area.  If anyone wants to tackle this, I think we'd accept a PR on it.

**Comment by rubencalje** [comment]
I think I am dealing with the same problem when plotting cross-sections with quasi-3d confining beds. I think I can do a PR on this.

Can you (or anybode else) explain why you chose to set the nlay-property of the modelgrid to nlay+np.sum(laycbd)?

This causes the nlay-property in the modelgrid object to differ from the nlay-property of the model object (for models with quasi-3d confining beds). I see there is also the modelgrid-property nlay_nocbd, which is equal to the nlay-property of the model. In my opinion it would have been better to have a property called nlay_wcbd, with a value of nlay+np.sum(laycbd), that is used when needed. In that way, the nlay-property of the modelgrid and the model is equal. Most of the time you would want to do something only with the actual layers, so with nlay (and not nlay+np.sum(laycbd).

There can be two solutions to the current problem:
1 Set nlay of modelgrid to nlay of model. Remove nlay_nocbd and introduce nlay_wcbd.
2 Replace nlay by nlay_nocbd in a lot of locations (in cross_section.py for example, the only one I have looked at for now) 

I cannot oversee the consequence of solution 1. There may be good reasons for the current setup.

**Comment by spaulins-usgs** [comment]
Yes it is a little confusing.  Modelgrid was set up to represent the entire model grid including the layers defined as confining layers. The idea was to make sure that nlay corresponded to the number of layers in botm, which defines the number of layers in the model grid. I agree that it would be less confusing to have nlay mean the same thing everywhere. If you implement solution #1 you will need to update the StructuredGrid class’s xyzcellcenters method to use nlay_wcbd for models with confining layers.

**Comment by rubencalje** [comment]
Thanks for your explanation. I made the pull request #819 , where I set nlay of the modelgrid to nlay of the model. In the end I did not alter the StructuredGrid class’s xyzcellcenters method, as these centers were not used by the cross section method.

I also added a test-script. Please let me know if I need to change anything.
