### ISSUE TITLE
Modflow6 no obs6 argument in flopy.mf6.ModflowGwfsfr()

### ISSUE THREAD

**Issue by porterma** [modflowpy/flopy#657]
I am updating an existing modflow 6 model for which there is already a model_sfr.obs file created to write out stream data. I do not see any 'obs6=' argument option to point to the existing file. There is an 'observations=' argument but that appears to write an observation file for the data of interest. The documentation clearly indicates that OBS6 is a keyword in the options block, that should be followed by the obs6_filename, so I would expect and obs6 argument that is equal to a string of the file name. In my existing model.sfr package I am using the OBS^ keyword option. Is there another way to tell modflow 6 to write observations based on model_sfr.obs file?

Thanks!

**Comment by langevin-usgs** [comment]
Maybe we do not support the actual filename itself at the moment.  And if so, then that might be something we should add.  @spaulins-usgs, can we supply and existing filename argument for observations?  If not, is this something you could add?

Options for specifying the observations argument are described here.  
https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_mf6_obs_ts_tas.ipynb

**Comment by spaulins-usgs** [comment]
Flopy for MF6 does not currently support loading a preexisting observation package from another simulation. Probably the easiest way to reuse your old obs package is to use the observations= parameter to create an empty observation package, write your simulation out, and then either manually or programmatically copy the observation package you want to use over the empty observation package. The code might look something like this:

	obs_dict = {'filename': 'my_old_sfr.obs', 'digits': 10, 'print_input': True}

	sfr_package = ModflowGwfsfr(model, observations=obs_dict, ...

	sim.write_simulation()

@langevin-usgs: The lack of an option to use a preexisting package from another simulation is not unique to obs. Flopy for MF6 is currently all or nothing, you either load an entirely preexisting simulation using sim.load() or you create a simulation from scratch. To add an existing package to a new simulation you have create an empty placeholder package, save the simulation, and then replace the placeholder package with the package you want to use. I can implement an interface that allows you to add preexisting individual packages to a new simulation/model/package. If I am going to do that I also recommend that I implement an interface that allows you to add preexisting models to a new simulation. Let me know if this is something you would like me to implement.

**Comment by porterma** [comment]
I am currently loading a modflow-nwt model and a modflow 6 model that was converted using mf5tomf6.exe. I am using data from both models to interpolate data onto an unstructured grid that I created with the Gridgen class. So I am switching from the dis package to the disv package. When I go to build the new mf6 model I remove the package I am updating and then redefine using flopy.mf6.ModflowGwfxxx(). I am only updating the packages I think need to be updated because of the new grid. As of today, I have the whole model converted to a quadtree gird, but I am running into some convergence issues I did not have in the mf6 model on the regular grid. I suspect I am overlooking something in one of the packages.  I am a fan of being able to easily plug packages from a previous model into a new model that I have updated or need to update. So I would vote for implementing a feature that allows you load preexisting packages into a new simulation. 

Thanks for pointing to the example regarding the observations argument. I'll look into it. It appears that maybe I don't need to specify the obs6  filein filename.txt in the options if I am using the observations argument.

**Comment by langevin-usgs** [comment]
@porterma, one thing you might consider (which you may have already done) is to go through your process using the DISV grid created with gridgen, but not adding any refinement.  This way you could recreate your model with DISV to ensure that you are getting the same results as before.  Just a thought.

**Comment by porterma** [comment]
Thanks for the advice. I am pretty sure I have things working now. My convergence issue was with my solver settings in the .ims package. I inadvertently loaded a model for which I was testing solver parameters. It had nothing to do with my interpolating procedures. I'm going to close this issue.
