### ISSUE TITLE
I am new to flopy and currently working with tutorial 1 of flopy from github. https://modflowpy.github.io/flopydoc/tutorial1.html#getting-started. But I am having trouble running the head contours as I am getting error with :hds = bf.HeadFile(modelname+'.hds') .Please help

### ISSUE THREAD

**Issue by Deepak294** [modflowpy/flopy#662]

**Comment by rabbl** [comment]
If the headfile does not exist it is very probable that your modflow-executable is not working properly. 

Possible reasons are:

* no executable with the name mf2005 or mf2005.exe (for Windows) exists
* the executable exits but your PATH-variable is not properly adapted
* you have a not working executable

I have created a notebook to check this issue, and it's working properly.
Please try to run it on your machine and report your errors.
