### ISSUE TITLE
Converting head boundary cells to active with MF6 CHD package

### ISSUE THREAD

**Issue by jvklak** [modflowpy/flopy#665]
Hi, 
I'm trying to figure out how to create a CHD file with flopy.mf6.modflow.mfgwfchd.ModflowGwfchd class such that head boundary cells may become active. MF6 will convert a head boundary cell to active if it encounters an empty period block in the CHD file, e.g.,

BEGIN PERIOD
END PERIOD

I'm currently passing a Python dictionary to the stress_period_data argument with key:value pairs of stress_period:[(lay, row, col), head].
In an attempt to have flopy write an empty period block, I've tried including a key:value pair of stress_period:None and also stress_period:[]. Neither have worked. Does anyone know the correct procedure for writing an empty period block?

Thanks!
Jeff

**Comment by langevin-usgs** [comment]
How about this (note the double brackets):

```
sim = flopy.mf6.MFSimulation()
tdis = flopy.mf6.ModflowTdis(sim, nper=3, 
                             perioddata=([(1., 1, 1.) for k in range(3)]))
gwf = flopy.mf6.ModflowGwf(sim)
dis = flopy.mf6.ModflowGwfdis(gwf)
chd = flopy.mf6.ModflowGwfchd(gwf, stress_period_data={1: [[(0, 0, 0), 1.]],
                                                       2: [[]]})
sim.write_simulation()
!cat model.chd
```

It gives:

```
writing simulation...
  writing simulation name file...
  writing simulation tdis package...
  writing model model...
    writing model name file...
    writing package dis...
    writing package chd_0...
INFORMATION: maxbound in ('gwf6', 'chd', 'dimensions') changed to 1 based on size of stress_period_data
BEGIN options
END options

BEGIN dimensions
  MAXBOUND  1
END dimensions

BEGIN period  2
  1 1 1       1.00000000
END period  2

BEGIN period  3
  
END period  3
```

**Comment by jvklak** [comment]
That did it!  Thanks, Chris.
