### ISSUE TITLE
3D visualization support for parameters in a disv grid in MF6 

### ISSUE THREAD

**Issue by porterma** [modflowpy/flopy#666]
I have been searching for an export option so that I can visualize hydrogeologic properties such as K in 3D. I was thinking there would be a vtk option, but I can't seem to find it for MF6. Looking at the code for the Vtk class appears to only support a structured grid and applies to the .dis package only. Am I missing something in this class? I have my unstructured grid loaded in Paraview using the .vtu file provided by the Gridgen module. It appears that flopy.export.utils.package_export() only supports shapefile files and netcdf. Is this correct? I tried
`npf = flopy.mf6.ModflowGwfnpf(mdl, save_specific_discharge=True, icelltype=[1, 1, 1], k=hk_qt, k33=vk_qt)`
`npf.export('_netcdf/npf.nc')`
and
`flopy.export.utils.package_export('_netcdf/npf.nc', npf)`
In both cases I received the same error: Exception: Grid type vertex not supported. So it appears the netcdf export option does not support unstructured grids.

Are there any 3D export options to visualize hydrogeologic parameters?

**Comment by langevin-usgs** [comment]
We are presently retooling the export functionality to support vtk export for all of our grid types, including unstructured grids.  We have a prototype for this on a developer's branch, but it has not been folded back into the flopy develop branch.  We are probably looking at a month or two to get it rolled in.  We are close, but I'm afraid you'll have to just stay tuned for the moment.  Sorry.

**Comment by porterma** [comment]
No worries! I look froward to the updated export features. In the meantime, I I have some ideas I can test on updating the existing .vtu file with the scalar K data. Thanks!
