### ISSUE TITLE
HFB Package loading issue

### ISSUE THREAD

**Issue by John1205** [modflowpy/flopy#675]
Hello I am loading the USGS groundwater built by a [GSFLOW](https://ca.water.usgs.gov/sustainable-groundwater-management/gwm/archive1/SIR2014-5052_Santa_Rosa_Plain-input.zip), of which MODFLOW is used. In this model, HFB package cannot be successfully loaded by using NAM file. I tried to load using the Load function  (hfb = flopy.modflow.ModflowHfb.load('SRPgsf_AddAdjHFBcorr_041513_Copy.hfb', ml)). The error messages are below. Please see the attached files for the details. 

[HFB files.txt](https://github.com/modflowpy/flopy/files/3731657/HFB.files.txt)

hfb = flopy.modflow.ModflowHfb.load('SRPgsf_AddAdjHFBcorr_041513_Copy.hfb', ml)
loading hfb6 package file...
   loading parameter "sebas_win1"...
Traceback (most recent call last):

  File "<ipython-input-136-c5f3b06e06b7>", line 1, in <module>
    hfb = flopy.modflow.ModflowHfb.load('SRPgsf_AddAdjHFBcorr_041513_Copy.hfb', ml)

  File "C:\Users\liqia\AppData\Local\Continuum\anaconda3\lib\site-packages\flopy\modflow\mfhfb.py", line 296, in load
    pak_parms = mfparbc.load(f, nphfb, dt, model.verbose)

  File "C:\Users\liqia\AppData\Local\Continuum\anaconda3\lib\site-packages\flopy\modflow\mfparbc.py", line 114, in load
    bnd.append(float(t[jdx]))

IndexError: list index out of range

**Comment by langevin-usgs** [comment]
This looks like a dreaded parameter issue.  Not sure we have ever tested loading of an hfb package with parameters.  We'll have to leave this issue open until someone has a chance to look at it.  Any parameter fans want to take a look?

**Comment by jlarsen-usgs** [comment]
@langevin-usgs, @John1205 

I can take a look at the parameter issue. We have a lot of older models (including the SRP model) that were setup with parameters that I could test the code against.

**Comment by John1205** [comment]
@jlarsen-usgs Thanks for figuring out the SRP model. I have a couple of issues loading the SRP model in Flopy, such as the SRF, HFB, HOB, and Wel packages. I am glad you have original model and run tests over your end. Thanks.

**Comment by John1205** [comment]
@jlarsen-usgs @langevin-usgs SRF package in the SRF domain has been solved. HFB issue is still open.

**Comment by John1205** [comment]
Thanks for your work, @langevin-usgs @jlarsen-usgs I have modified the code for the HFB package. However, it is still not working on my end.

**Comment by jlarsen-usgs** [comment]
Hi @John1205, 

are you using the most recent version of the develop branch?

**Comment by John1205** [comment]
solved!
