### ISSUE TITLE
read_from_cnf is untested and does not work

### ISSUE THREAD

**Issue by mwtoews** [modflowpy/flopy#687]
While working on #686 there are several issues with `read_from_cnf`:
```
$ flake8 --select F821
./flopy/modflow/mfdis.py:602:32: F821 undefined name 'model'
./flopy/modflow/mfdis.py:604:32: F821 undefined name 'model'
./flopy/modflow/mfdis.py:606:31: F821 undefined name 'model'
./flopy/modflow/mfdis.py:619:32: F821 undefined name 'model'
```
this method is not tested anywhere, and appears to be untouched for the past 5 years. I see that it is used to create a `ModflowDis` object, perhaps like this?
```python
import flopy
m = flopy.modflow.Modflow()
dis = flopy.modflow.ModflowDis(m)
dis.read_from_cnf('MT3D.CNF')
```
(this will raise "NameError: name 'model' is not defined")
Is this method needed? If so, what for? It should either be refractored (perhaps as a classmethod) or removed.

**Comment by langevin-usgs** [comment]
The offending lines

https://github.com/modflowpy/flopy/blob/develop/flopy/modflow/mfdis.py#L536-L622

were retained from a much older flopy version.  Unless we hear an objection in the next day or so, I say we remove this method.  It doesn't work, so clearly nobody is using it.
