### ISSUE TITLE
load_only functionality for MF6 version of flopy?

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#693]
Is there any equivalent functionality to the `load_only` argument (e.g. to `flopy.modflow.Modflow.load`) in the MF6 version of flopy? This would be extremely useful for instances when only a few packages are needed, or when `flopy.mf6.MFSimulation.load` crashes trying to load an unneeded package.

**Comment by spaulins-usgs** [comment]
There currently is not. However it should be easy to implement.

**Comment by spaulins-usgs** [comment]
This feature is now implemented.
