### ISSUE TITLE
loading mf6 packages with data for extra periods

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#694]
MODFLOW-6 appears to allow stress packages have data for periods beyond `nper` (e.g. period 97 when nper is only 60). However, trying to load one of these packages with `flopy.mf6.MFSimulation.load` results in something like `flopy.mf6.mfbase.FlopyException: FlopyException: Stress period value sp_num (<nper +1>) is greater than the number of stress periods defined in nper. ()` It's nice to have the ability to change the number of periods without having to edit all of the relevant package files, so it seems like flopy should support this too.

**Comment by spaulins-usgs** [comment]
Stress periods beyond nper now permitted in flopy.
