### ISSUE TITLE
shapely dependence should not be a requirement

### ISSUE THREAD

**Issue by emorway-usgs** [modflowpy/flopy#697]
I recently started getting the message below when trying to `import flopy`  If the user is not intending to make use of the `gridintersect.py` class, should this dependence be a requirement as it now seems to be?

![shapely](https://user-images.githubusercontent.com/3236576/67593302-c3554f80-f716-11e9-9f59-dae2cbaa4a7b.png)

**Comment by jwhite-usgs** [comment]
On the `develop` branch, I think the shapely deps are wrapped in a try-except.  Are you using `develop`?

**Comment by emorway-usgs** [comment]
Affirmative, on the `develop` branch

**Comment by jwhite-usgs** [comment]
python 2?  Looks like there is some trapping for py2 right above the shapely imports

**Comment by emorway-usgs** [comment]
python `3.5.3` (see top of screen shot in first post of thread)

**Comment by jwhite-usgs** [comment]
alright, Im giving up then!

**Comment by langevin-usgs** [comment]
I've seen this too.  @jwhite-usgs, remember when you added the import of gridintersect to the __init__.py file?  At that point, I think it became a requirement, because then it is imported when you import flopy.  We probably need a try and except in the gridintersect.py file.

**Comment by jwhite-usgs** [comment]
there is a try-except but just before that, there is a re-def of importerror to some other form of exception if python=2.  I think that logic might be what we are seeing here

**Comment by langevin-usgs** [comment]
Right, and ModuleNotFoundError isn't defined otherwise.

**Comment by langevin-usgs** [comment]
Should probably put the imports into the methods of `gridintersect.GridIntersect()` that need them.
