### ISSUE TITLE
Docstrings, docstrings, and more docstrings

### ISSUE THREAD

**Issue by langevin-usgs** [modflowpy/flopy#7]
Just wanted to check in with everyone about docstrings.  I am going to be updating the flopy3 sphinx documentation over the next couple of days (in preparation for our class in 2 weeks).  If you get the chance to update the docstrings for your assigned files, that would be great.  The wiki with the file assignments is at:

https://github.com/modflowpy/flopy/wiki/Docstring-Assignments

thanks!

**Comment by jjstarn** [comment]
It's still on my to-do list; just a little behind schedule.

On Tue, Jan 27, 2015 at 10:10 AM, langevin-usgs <notifications@github.com>
wrote:

> Just wanted to check in with everyone about docstrings. I am going to be
> updating the flopy3 sphinx documentation over the next couple of days (in
> preparation for our class in 2 weeks). If you get the chance to update the
> docstrings for your assigned files, that would be great. The wiki with the
> file assignments is at:
>
> https://github.com/modflowpy/flopy/wiki/Docstring-Assignments
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modflowpy/flopy/issues/7>.
>



-- 
Jeff Starn Ph.D.
Research Hydrologist
USGS National Water-Quality Assessment
101 Pitkin Street,  East Hartford, CT 06108

jjstarn@usgs.gov
office: (860) 291-6746
cell: (860) 335-8381

**Comment by mbakker7** [comment]
Absolutely.
Need to get that done,
Mark

**Comment by mbakker7** [comment]
All,

I think the doc string of the mfghb.py file may serve as a template for
other
layer-row-column-data type packages. If you have suggestions to improve the
'template' let me know. We should try to keep the docs of these
 layer-row-column-data type packages similar, I think,

Mark

**Comment by mnfienen-usgs** [comment]
I believe mine are up to date. Let me know if I’m wrong.

Mike

**Comment by jjstarn** [comment]
thanks for that suggestion. I was planning on using one of the other
packages as a template, now I know which one to use...

On Tue, Jan 27, 2015 at 4:01 PM, mbakker7 <notifications@github.com> wrote:

> All,
>
> I think the doc string of the mfghb.py file may serve as a template for
> other
> layer-row-column-data type packages. If you have suggestions to improve the
> 'template' let me know. We should try to keep the docs of these
> layer-row-column-data type packages similar, I think,
>
> Mark
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modflowpy/flopy/issues/7#issuecomment-71726967>.
>



-- 
Jeff Starn Ph.D.
Research Hydrologist
USGS National Water-Quality Assessment
101 Pitkin Street,  East Hartford, CT 06108

jjstarn@usgs.gov
office: (860) 291-6746
cell: (860) 335-8381
