### ISSUE TITLE
Maximum number of observation points in mtbtn module

### ISSUE THREAD

**Issue by nish-ant** [modflowpy/flopy#701]
I am providing an array of length 250 to the `obs` parameter of the module `flopy.mt3d.mtbtn.Mt3dBtn`. I get the error `MAXIMUM NUMBER OF OBSERVATION POINTS IS 200. INCREASE DIMENSION OF [MXOBS] IN MAIN PROGRAM`. 

I cannot find how I can change the `MXOBS` parameter in the FloPy or MT3DMS documentation. How can I change it?

**Comment by emorway-usgs** [comment]
@nish-ant Can you provide an example set of input files or the script you are using?  This will help us resolve the issue that is affecting your setup.

**Comment by nish-ant** [comment]
You can find the script attached. It is slightly modified version of the tutorial code [MT3DMS Example 2](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_MT3DMS_examples.ipynb).

[main_p02.py.txt](https://github.com/modflowpy/flopy/files/3784667/main_p02.py.txt)

When the variable `ncol` is set to more than 200, the `Mt3dBtn` module raises the error that I have mentioned in the first post. Setting it to a value less than or equal to 200 works.

**Comment by emorway-usgs** [comment]
@nish-ant In your script, when I changed the following (line 20)

`exe_name_mt = 'mt3dms'`

to

`exe_name_mt = 'mt3d-usgs'`

the model ran to completion.  MT3D-USGS is intended to be a backward compatible update to MT3DMS.  If you have MT3D-USGS on your path, then I think this will get you on your way the quickest.  If you're OK with this fix, would you mind closing the issue?

**Comment by nish-ant** [comment]
@emorway-usgs Thanks. Using MT3D-USGS works.
