### ISSUE TITLE
MF6 - add ability to specify simulation name file options from simulation __init__

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#704]
@spaulins-usgs it looks like the simulation name file options (`continue`, `nocheck`, `memory_print_option`, and `maxerrors`) can only be specified after the simulation is initialized. It would be nice if these could be specified when initializing a simulation.

**Comment by spaulins-usgs** [comment]
@jdhughes-usgs the name file options "continue", "nocheck", and "memory_print_option" I can easily implement. It looks like maxerrors is a new option that is not yet part of the official MODFLOW release. Is the upcoming flopy release going to occur at the same time as the MODFLOW release? If not would you like maxerrors implemented in flopy for the upcoming flopy release or would you prefer to wait for a flopy release that is closer to the MODFLOW release?

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs  I think the MODFLOW release will be later than the next flopy release so we should wait until the next release to include `maxerrors`

**Comment by spaulins-usgs** [comment]
Flopy now allows you to set "continue", "nocheck", and "memory_print_option" during initialization.
