### ISSUE TITLE
adding to irch?

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#715]
https://github.com/modflowpy/flopy/blob/7cbc48929051e03ce193b3fbf375f8c9c4a38d8c/flopy/modflow/mfrch.py#L144

Does anyone know why we are adding 1 to the `irch` variable?  It doesnt work for me on a model with `nrchopt = 2` because `Transient2d` doesnt define the `__add__` operator. I can add/hack if needed but just wanted to make sure we should be adding 1 to `irch`

**Comment by langevin-usgs** [comment]
Well irch is the layer number, so it would make sense to add 1 to it.  Ironically, I noticed today that we do not add 1 to the mf6 version of irch, which I am intending to fix.

**Comment by jtwhite79** [comment]
ok, fair enough, but we dont subtract 1 from `irch` in the load.  So should `irch` be zero-based?  If, we probably shouldnt add 1 except at during write, agree?

**Comment by langevin-usgs** [comment]
Ahh, yes.  We shouldn't add 1 in `__init__`.  That does look screwy.  I wonder why we did it that way.  Must be a residual from the old days.  Should subtract 1 on load, and add 1 on write.

**Comment by langevin-usgs** [comment]
Close with https://github.com/modflowpy/flopy/commit/7cbc48929051e03ce193b3fbf375f8c9c4a38d8c
