### ISSUE TITLE
layer input for the plot_discharge() function?

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#718]
It seems like the function `plot_discharge(frf=None, fff=None, flf=None, head=None, istep=1, jstep=1, normalize=False, **kwargs)` is only able to return the discharge for the top model layer? I tried to pass `mflay` to it, but it doesn't support it. Am I right here or I am doing something wrong? 

I also noticed that the example script for plotting discharge doesn't work for me in the notebook https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_PlotMapView_demo.ipynb. To get the discharge data, I have to use,
`frf = bud.get_data(idx=0,text='FLOW RIGHT FACE',full3D=True)[0]`
rather than `frf = bud.get_data(idx=0,text='FLOW RIGHT FACE')[0]`

**Comment by jlarsen-usgs** [comment]
@flydream0428 
Instead of passing mflay to `plot_discharge()`, pass the `layer=` parameter when instantiating the `PlotMapView` class. Example.

```
pmv = PlotMapView(model=model, layer=2)
discharge = pmv.plot_discharge(frf=frf, fff=fff)
```

I'll check out the notebook and see if I can recreate the issue.

**Comment by flydream0428** [comment]
Gosh, a silly ignorance. Thanks a lot!

**Comment by jlarsen-usgs** [comment]
@flydream0428.

I wasn't able to reproduce the error you noted in the PlotMapView_demo notebook. What version of flopy are you working with?
