### ISSUE TITLE
Mismatch on tutorial02.py

### ISSUE THREAD

**Issue by mhannonj** [modflowpy/flopy#719]
This is not really a pressing issue, but I noticed a mix-up on how a couple of variables are defined in the Tutorial 2 Python script.  They have to do with following lines (11 to 14):
```
nrow = 10
ncol = 10
delr = Lx / ncol
delc = Ly / nrow
```
The denominators in the `delr` and `delc` definitions should be switched:
```
nrow = 10
ncol = 10
delr = Lx / nrow
delc = Ly / ncol
```
Since `nrow` and `ncol` are both set to the same value, it has no bearing on the output of this file as-written, but should someone want to toggle those values, it'll give inaccurate results.

**Comment by mwtoews** [comment]
See https://github.com/modflowpy/flopy/issues/476#issuecomment-470912210

**Comment by mhannonj** [comment]
Oops... looks like I got confused by the same thing. Thanks for your help!
