### ISSUE TITLE
test_util2d_external_free_nomodelws in t004

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#72]
test_util2d_external_free_nomodelws in t004 needs to be fixed so that it does not write files to autotest directory but in autotest/temp/ subdirectory.

**Comment by jdhughes-usgs** [comment]
Not fixed. Still writes modflowtest.dis, modflowtest.lpf, modflowtest.nam, and test_0.ref to autotest directory instead of autotest/temp/ directory.

**Comment by jtwhite79** [comment]
Oh great and mighty File King, how can I appease thee!  I toil with unit tests, yet your vengeance is strong!  

Should be fixed now...

**Comment by jdhughes-usgs** [comment]
perfect...
