### ISSUE TITLE
Error when exporting shape file

### ISSUE THREAD

**Issue by mustafaucr** [modflowpy/flopy#720]
If you try to export any package of flopy as shapefile pyshp (shapefile) whose version is 2.1.0; shapefile is created but it is broken. I install pyshp 1.2.1 it works but `shp2recarray `function does not work.

**Comment by jlarsen-usgs** [comment]
@mustafaucr, can you give me more information about the issue, so I can look into it. What is broken in the shapefile with version 2.1.0? What error message are you getting with pyshp 1.2.1? Thanks!

**Comment by mustafaucr** [comment]
Okey, here is my code to produce a shape file:

```
ghbPath = os.path.join(model_dir, 'ghb.shp')
ghbObject.export(f=ghbPath)
```
When I run this code with shapefile 2.1.0. It creates a *.shp file. I can add it to GIS software (I use QGIS) and open it on canvas. But when I try to get information from the layer, it produces wrong values. Moreover, if I try to zoom to layer more and more; layer disappears suddenly. It also shows that layer is broken.

On the other hand, if I work with 1.2.1 it gives me the error below.
![Screenshot_2](https://user-images.githubusercontent.com/36263724/68709510-e00ed580-05a6-11ea-9e19-9fe784193003.png)

Finally, if I work with flopy whose version is from old ones (I will write it when I back to office) and shapefile 1.2.1 there is no problem.

**Comment by jlarsen-usgs** [comment]
@mustafaucr 

Hi, I can't recreate the error you're describing with pyshp 2.1.0, but I've dug into the pyshp 1.2.1 error and think they may be related. In the "new" shapefile exporting code, integers were being stored as floating point values. I'll submit a PR for this issue later today.

**Comment by mustafaucr** [comment]
Yes there is no error actually. It seems that shapefile is created without no error but there is something wrong with shapefile. I can not explain that with giving error message, but if I can explain it clearly, I will share it with you.

**Comment by jtwhite79** [comment]
I also noticed recently that the grid-based shapefiles aren’t drawing the polygons as closed.  I think This is because the shapefile spec says the vertices should “close the loop” so to speak.  That’s why sr adds the coordinates of the first corner again, so there are 5 verts for each square.  The order of the verts matters too.  Maybe this is part of the problem?

**Comment by jlarsen-usgs** [comment]
@jtwhite79 

Can you supply an example problem where grid based shapefiles aren't drawing the polygons as closed? 

I've checked the shapefile exporting code and:
1) the exterior vertices are ordered in the clockwise direction and interior vertices are ordered counterclockwise according to the shapefile spec.
2) I've tested with pyshp 2.1.0 and pyshp 1.2.1 and none of our example problems have shown this issue.

**Comment by jtwhite79** [comment]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/1770912/68797643-38c78800-0612-11ea-8d91-e806a9ce6206.png">
 That is a screen shot from qgis showing the un-closed polygons in the first column (the others arent closed either, but are masked by their neighbors).  Here is the script that makes it:

```import os
import flopy 

xll,yll = 468970,3478635
xur,yur = 681010,3716462

spacing = 2000

ncol = int((xur - xll) / spacing)
nrow = int((yur - yll) / spacing)
print(nrow,ncol)

m = flopy.modflow.Modflow("test.nam",proj4_str="EPSG:32614",xll=xll,yll=yll)

flopy.modflow.ModflowDis(m,delr=spacing,delc=spacing,nrow=nrow,ncol=ncol)

m.dis.export("dis.shp")
```

**Comment by jlarsen-usgs** [comment]
@jtwhite79 

After digging into the code, It looks like pyshp v. 2.1.0 doesn't automatically close polygons like pyshp v. 1.2.1. This issue doesn't seem to affect polygon rendering ArcGIS. However, it is apparent that un-closed polygons are not displayed the same way in qgis.

**Comment by jlarsen-usgs** [comment]
Pull Request #721 should take care of this issue
