### ISSUE TITLE
Update flopy author list in the software citation

### ISSUE THREAD

**Issue by langevin-usgs** [modflowpy/flopy#727]
This software citation in readme.md should probably be updated based on the information in setup.py:  

Bakker, M., Post, V., Langevin, C.D., Hughes, J.D., White, J.T., Starn, J.J., and Fienen, M.N., 2019, FloPy v3.3.0 — release candidate: U.S. Geological Survey Software Release, 18 November 2019, http://dx.doi.org/10.5066/F7BK19FH

**Comment by jentjr** [comment]
This is something I think I can help with if you would like some assistance. I was thinking to import and convert the `__author__` string from `flopy/__init__.py` to a citation string in `make-release.py` at lines 240-241, and also at 296-308 for the USGS and PyPi release notes.

**Comment by langevin-usgs** [comment]
Hey @jentjr, thanks for offering to do this, but this might not be as straightforward you might think.  With our different branches, our protocols for building documentation, and the way we make releases, this could get tricky.  You are of course welcome to submit a PR based on what you're suggesting and we'll take a look, but we may end up having to do something more comprehensive.
