### ISSUE TITLE
None type error while loading Mt3dms 

### ISSUE THREAD

**Issue by mustafaucr** [modflowpy/flopy#732]
I try to load created mt3dms file whose extension is *.mtnam. However I can not load it.

here is my nam file for modflow and mt3dms respectively:

```
C:\HT_Projeler\hjo\Kaynak\Hidrojeoloji\hidrojeoloji.nam
C:\HT_Projeler\hjo\Kaynak\Hidrojeoloji\hidrojeoloji.mtnam
```

I try to load like that:

```
fileDir = r"C:\HT_Projects\hjo\Source\Hydrogeology"
model = Modflow.load("hydrogeology.nam", model_ws=fileDir)
mt = Mt3dms.load(f="hydrogeology.mtnam", model_ws=fileDir, load_only=["DSP"], modflowmodel=model)
```

There is no problem while loading model but it does not load mt3dms file. How can I load that?

Content of the `hidrojeoloji.mtnam` below:
![image](https://user-images.githubusercontent.com/36263724/69219160-4eddc700-0b83-11ea-9ea3-6800a02d47e5.png)

**Comment by langevin-usgs** [comment]
Not sure what you mean by "mt3dms" file.

**Comment by emorway-usgs** [comment]
@mustafaucr In addition to the previous question, are the input files small enough to attach to this issue?

**Comment by mustafaucr** [comment]
Thanks for response. I found my solution:

```
fileDir = r"C:\HT_Projects\hjo\Source\Hydrogeology"
model = Modflow.load("hydrogeology.nam", model_ws=fileDir )
mt = Mt3dms.load("hidrojeoloji.mtnam", model_ws=fileDir, modflowmodel=model)
dspFile = os.path.join(self._gv.hjoSourcedir, "hidrojeoloji.dsp")
ext_unit_dict = parsenamefile(os.path.join(fileDir , "hidrojeoloji.mtnam"), model.mfnam_packages)
dsp = Mt3dDsp.load(dspFile, self.mt, ext_unit_dict=ext_unit_dict)
```

I think there is problem with my directories. Additon I had a problem with loading package. It is solved also by using `ext_unit_dict ` parameter.
