### ISSUE TITLE
Syntax error in BTN file

### ISSUE THREAD

**Issue by SHuizer** [modflowpy/flopy#74]
First of all, thanks creating and updating this python package! I upgraded my Flopy version yesterday from version 2.2.353 to the most recent version (3.2.3). SEAWAT gives a format syntax error, when trying to read the BTN-file. I have figured out that the error occurs due to an extra spacing in the control record. The self.format.fortran has shifted one space to the right in comparison with the previous version. When I delete this space in all control records of the BTN-file the error is gone. 

I have fixed this problem now in my FloPy version in the def get_control_record (in util_array), by changing {2:>20s} in to {2:>19s}. However in the previous version of FloPy the value was also 20s. I could not figure out the true cause of this error, perhaps this is caused by my shift from Python 2.7 to Python 3.4.3?

![format syntax error flopy 2 3 2](https://cloud.githubusercontent.com/assets/16304580/11810362/bbe46d08-a32d-11e5-86fe-83ffbba5cc12.png)

**Comment by langevin-usgs** [comment]
I was unable to reproduce your error using python 2.7 and the develop version of flopy.  It looks like there have been a couple of changes to that format statement since we made the last release.  Note, that we are now using: '{0:10.0f}{1:10.0f}{2:20s}{3:10.0f} #{4}\n' Can you try with the develop version and see if that fixes it?

**Comment by jtwhite79** [comment]
I think That same fix to get_control_record() has already been applied to the develop branch

**Comment by SHuizer** [comment]
Yes, the update to the develop version solved the problem. Thanks.
