### ISSUE TITLE
Remove redundancy and consolidate plotting notebooks

### ISSUE THREAD

**Issue by jlarsen-usgs** [modflowpy/flopy#741]
I started looking at the plotting notebooks for the planned FloPy version 3.3.0 release and there is quite a bit of redundancy that could be removed or consolidated. Right now there are 7 notebooks that display plotting functionality:

_flopy3_PlotArrayExample_ (shows how to use the built in .plot() methods)

_flopy3_mf6_plotting_freyberg_ (shows basic plotting using `PlotMapView` using the Freyberg model. This was introduced during development of the `PlotMapView` classes)

_flopy3_mf6_BasicPlotting_ (shows basic structured grid and cvfd plotting using `PlotMapView` and modflow 6 models)

_flopy3_UnstructuredGridPlotting_ (shows unstructured grid plotting)

_flopy3_PlotCrossSection_demo_ (shows `PlotCrossSection` functionality and backward compatibilty to the `ModelCrossSection` class. Displays use cases for both `StructuredGrid` and `VertexGrid` models)

_flopy3_PlotMapView_demo_ (shows `PlotMapView` functionality and backward compatibility with the `ModelMap` class. Displays use cases for `StructuredGrid`, `VertexGrid`, and `UnstructuredGrid` models)

_flopy3_MapExample_ (shows `PlotMapView` and `PlotCrossSection` functionality for structured grids)

I think we can reduce this to two or three notebooks depending on how we want to present these classes and showcase this functionality:

**Notebook 1)** A map view plotting notebook that covers `PlotMapView` plotting that includes examples from `StructuredGrid`, `VertexGrid`, and `UnstructuredGrid` models. Also use a combination of MF6 and MF2005/USG models for this notebook
**Notebook 2)** A cross sectional plotting notebook that covers `PlotCrossSection` plotting that includes examples from `StructuredGrid` and `VertexGrid`
**Notebook 3)** Maintain the current _flopy3_PlotArrayExample_ notebook.

Are there any thoughts or other ways that make sense to structure these sets of notebooks?

**Comment by jlarsen-usgs** [comment]
I put together a draft set of notebooks for the plotting libraries and folded in many of the examples that were presented in the seven notebooks that were listed in my previous comment. 

The ipython notebooks for `PlotMapView` and `PlotCrossSection` can be viewed at:
[flopy3.3_PlotMapView](https://github.com/jlarsen-usgs/flopy/blob/develop/examples/Notebooks/flopy3.3_PlotMapView.ipynb)
[flopy3.3_PlotCrossSection](https://github.com/jlarsen-usgs/flopy/blob/develop/examples/Notebooks/flopy3.3_PlotCrossSection.ipynb)

I propose that we maintain the current version of the _flopy3_PlotArrayExample_ notebook.

Is there anything missing? Or anything else that should be shown in these Notebooks?

**Comment by langevin-usgs** [comment]
Hey @jlarsen-usgs, I took a quick look and think it looks great.  There is always more to add, but I think what you've done here is a nice synthesis.  Looks good to me.
