### ISSUE TITLE
flopy3_MT3DMS_examples model run result problem

### ISSUE THREAD

**Issue by mustafaucr** [modflowpy/flopy#744]
I control if mt3d model runs correctly by using return values of `run_model` function:

`success, mfoutput = mt.run_model(silent=False, pause=False, report=True)`

However `success` value gives me `False `every time. In flopy example documentaion, as well.

https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_MT3DMS_examples.ipynb

I try **Example 6. Concentration at an Injection/Extraction Well example** and it gives me `False `but it creates results. Is this a bug?

**Comment by langevin-usgs** [comment]
For mt3d, you have to set normal_msg correctly as a run_model argument.  I forget what it is offhand, but it should be the string that mt3d reports to the screen at the end of a successful run.
