### ISSUE TITLE
Same script cannot run on Mac (installed OS-version flopy and seawat executable file)

### ISSUE THREAD

**Issue by hLiu006** [modflowpy/flopy#747]
Hi, recently I'm trying to run a given script which applies seawat package. However, the same code which runs well on the Windows computer does not work on my Macbook.  And I was announced that '_**Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.**_'. Besides , according to the list file, it seems that the model doesn't work successfully since it stops before simulating the first stress period simulation. As a result, there is no generated hds file. By the way , the SEAWAT-henry-problem in example file runs well on my laptop. Thus I guess the seawat executable file is fine.

**Comment by rabbl** [comment]
Can you please provide the script?

**Comment by mbakker7** [comment]
This problems needs further investigation before it is posted here. I will work with hLiu006 (who is my student) and he will come back with a clear question if we can not solve it ourselves.
