### ISSUE TITLE
Origin/Rotation in DIS Package is Unintuitive

### ISSUE THREAD

**Issue by geouke** [modflowpy/flopy#749]
I tried to use FloPy (again) and ran into what seems like strange default behavior. I defined an origin at the upper left of my model grid in real world coordinates, per the documentation. I then tried to apply a rotation and realized that my grid was not where I expected. Come to find out, the axis of rotation is a different point (the lower left). 

It seems to make more sense to define the lower left corner in the DIS package since it will still be a real coordinate after the rotation is applied. 

![flopy_issue](https://user-images.githubusercontent.com/7731014/70368321-7cef2680-1866-11ea-8dde-3fa477b02651.png)

**Comment by langevin-usgs** [comment]
We've gone round and round on this for years, and most of it is my fault.  The approach that you suggest is the default for the MODFLOW 6 model, but not for MODFLOW-2005.  It is also the default for the new underlying grid object.  We probably won't change this again for mf2005/nwt models at this point, but we recognize the issue.  Fortunately, the mfdis docstrings do indicate that the rotation is about the lower left corner.

**Comment by geouke** [comment]
Thanks for the reply. It's an easy enough transformation to make.
