### ISSUE TITLE
MF6 HeadFile.plot() not masking inactive cells

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#753]
If you pass the model instance to `HeadFile` with the MF2005/MFNWT instances, `HeadFile.plot()` will mask `ibound==0` so you can see the simulated values in the colormap.  The same call for an MF6 model does show the idomain inactive areas as black, but the array isnt being masked before plotting, so you get extreme values:
![image](https://user-images.githubusercontent.com/1770912/70566255-f336a600-1b50-11ea-9eca-776ceff7cf9b.png)

**Comment by jlarsen-usgs** [comment]
@jtwhite79 
The reason that mf2005 and mfnwt models are automatically masked is because the `_plot_array_helper` function queries hnoflo and hdry which are defined in the BAS and LPF/UPW files. MODFLOW-6 doesn't have this information natively. I'll add a small subroutine to extract these values based on the location(s) of inactive cells and add it to the `_plot_array_helper` function, provided that an idomain array is accessible within the model or modelgrid object.

**Comment by jwhite-usgs** [comment]
Sweet as @jlarsen-usgs .  I saw those conditionals but wasn’t sure why the idomain was plotting but the masking wasn’t happening.  Maybe it’s a better approach to mask with ibound/idomain instead of relying on those specific values?

**Comment by langevin-usgs** [comment]
MODFLOW 6 doesn't allow those values to be specified.  They are set to nodata-like values.  From the mf6 IO document:

"In the present MODFLOW 6 version, the TEXT value is specified as “HEAD”. Cells that have been assigned an IDOMAIN value of zero or less are assigned a head value of 1.0 x 1030. Cells that have converted to dry are assigned a dry value of −1.0 x 1030. The large negative value allows the results from a previous simulation to be used as starting heads for a subsequent simulation. Cells assigned a large negative value as an initial condition will start the simulation as dry. Note that the dry value is not used if the Newton-Raphson For- mulation is active. In this case, a dry cell will have a calculated head value that is below or at the bottom of the cell."

I'm sure you can filter on these really large and small values.

**Comment by jlarsen-usgs** [comment]
Yes, we can definitely filter on those values, and it'll be much more efficient than filtering based on the ibound array. Thanks for the clarification @langevin-usgs!
