### ISSUE TITLE
A few typos in modflow\mfnwt

### ISSUE THREAD

**Issue by wzell-usgs** [modflowpy/flopy#76]
BACKFLAG parameter is 'backflag' in docstring but 'backflg' in object init.

Change 'levfil' to 'levfill' in the write_file call

  File "C:\Anaconda\lib\site-packages\flopy\modflow\mfnwt.py", line 267, in write_file
    f.write('{0:10d}'.format(self.levfil))
AttributeError: 'ModflowNwt' object has no attribute 'levfil'

**Comment by langevin-usgs** [comment]
Fixed.  Thanks.
