### ISSUE TITLE
Empty hds file

### ISSUE THREAD

**Issue by hLiu006** [modflowpy/flopy#773]
Hi everyone,
I'm trying to modelling aquifer thermal energy storage by flopy. But it turns out that the generated head file is empty which confused me for a long time and I couldn't find a solution for this. The related files are posted below. Hope you could give me some ideas why it happens and how to solve this.
[ControlOutput.zip](https://github.com/modflowpy/flopy/files/4031152/ControlOutput.zip)

**Comment by rabbl** [comment]
Hi @hLiu006, could you provide the python script for your model?

**Comment by mbakker7** [comment]
This problems needs further investigation before it is posted here. I will work with hLiu006 (who is my student) and he will come back with a clear question if we can not solve it ourselves.
