### ISSUE TITLE
Linking MT3D-USGS to MODFLOW6 model

### ISSUE THREAD

**Issue by mattijn** [modflowpy/flopy#775]
Hi all, new MODFLOW user here! 
According to the [documentation](https://water.usgs.gov/water-resources/software/MODFLOW-6/mf6io_6.1.0.pdf#page=25) of MF6 it is possible to link a MF6-model to a MT3D-USGS model as long as it is a regular grid:

> The GWF Model described in this report does not support the following list of packages and capabilities.
> - Link to the MT3DMS Contaminant Transport Model (Zheng and others, 2001). However, MT3D- USGS can read the head and budget files created by MODFLOW 6, but only if the GWF Model uses the DIS Package. MT3D-USGS will not work with GWF output if the DISV or DISU Pack- ages are used.

Which is confirmed in the [documentation](https://github.com/mattijn/datasets/blob/master/Input_Instructions.pdf#page=4) of MT3D-USGS:
> **Notes on Notes on FT6 Option Starting with Version 1.1.0**
> [..]
> In order to use MT3D-USGS with MODFLOW 6 (Langevin and others, 2017), the user needs to ensure that the selected grid type in MODFLOW 6 is a regular MODFLOW grid consisting of layers, rows, and columns.

But when I try to connect the models using FloPy (reproducable notebook [here](https://github.com/mattijn/datasets/blob/master/MF6%20with%20MST3D-USGS.ipynb)) it seems not working:

Using:
```python
flopy.mt3d.Mt3dms(
    modflowmodel=sim  
)
```
Gives the following error during the next function call of the BTN package:

```python
#BTN file
icbund = idomain.copy()
icbund[0, 15, 15] = -1 #constant concentration

btn = flopy.mt3d.Mt3dBtn(
    model=mt_model, 
    sconc=0.0, 
    prsity=0.3, 
    thkmin=0.01, 
    munit='g', 
    icbund=icbund
)
```

> Exception: BTN error. Required input is None, but no modflow model. If no modflow model is passed to Mt3dms, then values must be specified in the BTN constructor for: nlay, nrow, ncol, nper, laycon, delr, delc, htop, dz, perlen, nstp, and tsmult.

Changing the `flopy.mt3d.Mt3dms()` into:
```python
flopy.mt3d.Mt3dms(
    modflowmodel=gwf  
)
```
Gives the following error during de `flopy.mt3d.Mt3dBtn()` call:

> AttributeError: 'ModflowGwfdis' object has no attribute 'nper'

Changing the `flopy.mt3d.Mt3dBtn()` call into:
```python
btn = flopy.mt3d.Mt3dBtn(
    model=mt_model, 
    sconc=0.0, 
    prsity=0.3, 
    thkmin=0.01, 
    munit='g', 
    icbund=icbund,
    nper=tdis.nper  # <--- from the time discretization package
)
```
results in the following error:

> AttributeError: 'MFArray' object has no attribute 'get_value'

which is true since:
```python
gwf.dis.delr.get_value()
```
is not existing. There exists a `gwf.dis.delr.get_data()` function, but not sure if that should be used. 

Again, all is available in this [notebook](https://github.com/mattijn/datasets/blob/master/MF6%20with%20MST3D-USGS.ipynb).

But it seems FloPy is not yet ready to integrate MF6 with MT3D-USGS? If so, what would be the best approach to make this possible?

**Comment by langevin-usgs** [comment]
Sorry, and thanks for pointing this out @mattijn.  Doesn't look like flopy is set up yet to link MODFLOW 6 with MT3D-USGS.  We'll leave this open so it's on the list of things to implement.  Maybe @emorway-usgs can look into this.

**Comment by emorway-usgs** [comment]
@mattijn @langevin-usgs I'll have a look at this one.  Please do leave it open

**Comment by jdhughes-usgs** [comment]
@emorway-usgs do you think you will be able to address this prior to the code freeze on Thursday? If not would you give it the 3.3.2 milestone?

**Comment by emorway-usgs** [comment]
@jdhughes-usgs  It'll have to get pushed back to the next release.  I won't be able to get to it this week.

**Comment by jdhughes-usgs** [comment]
@emorway-usgs can this be closed?

**Comment by michelob23** [comment]
Did this ever get addressed? I'm running into the same problem trying to connect a MF6 model to a MT3D-USGS model. I'm running into a lot of numerical instability with the MF6 GWT process, which is why I'm giving MT3D-USGS a shot. 

 File "/modflow/lib/python3.9/site-packages/flopy/mt3d/mtbtn.py", line 252, in __init__
    self.setmodflowvars(
  File "/modflow/lib/python3.9/site-packages/flopy/mt3d/mtbtn.py", line 458, in setmodflowvars
    self.nper = mf.dis.nper
AttributeError: 'ModflowGwfdis' object has no attribute 'nper'

**Comment by emorway-usgs** [comment]
Hello @michelob23, this is still an issue.  Does your MF6 simulation use any of the advanced packages?  If so, then that would preclude the use of MT3D-USGS with MF6. 

However, I would anticipate that the GWT process would be as stable as MT3D-USGS, unless maybe you want to use the MOC or HMOC methods?

**Comment by FlorisTeuling** [comment]
Hi @emorway-usgs, I see that this issue has moved with the milestones for some time. I'm interested in using MT3D USGS with MF6 in flopy, so am wondering (and will cheekily ask): are you working on solving the issue and what are your plans for this issue towards the future?

**Comment by emorway-usgs** [comment]
@FlorisTeuling, Since transport is available within MODFLOW 6, including full support in flopy - I don't think it was back in 2020 when this issue was created - hopefully it ([GWT](https://pubs.usgs.gov/publication/tm6A61)) can meet your needs as further development to support a MODFLOW 6/MT3D-USGS coupling has likely passed.

**Comment by FlorisTeuling** [comment]
Thanks for the update!

**Comment by emorway-usgs** [comment]
@FlorisTeuling, you can retrieve my email [here](https://www.usgs.gov/staff-profiles/eric-morway) if you want touch base some more about your needs.  I'm going to close this issue given that GWT was released in the time since this issue was originally opened.
