### ISSUE TITLE
Update bottom elevation data in the DIS object

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#777]
I am trying to update some layers' elevation based on some conditions. It seems like the elevation values will stay the same even an assignment is conducted. What is the right way to do this? 

`mf_new.dis.botm.array[k]=new_botm`

**Comment by langevin-usgs** [comment]
Great question.  The .array property return a copy of the botm array.  What you want is this:

```
import flopy
mf = flopy.modflow.Modflow()
dis = flopy.modflow.ModflowDis(mf, nlay=2)
dis.botm[1] = -99
dis.botm.array

array([[[  1.,   1.],
        [  1.,   1.]],

       [[-99., -99.],
        [-99., -99.]]], dtype=float32)
```

You can set dis.botm by layer or for the whole thing.  The other MODFLOW-2005/NWT arrays in flopy will work this way too.  Under they hood they are Util3d arrays.  MODFLOW 6 works a little differently I think.  For those, I think they have a "set_data" method.

Hope this helps.  Closing...

**Comment by mbakker7** [comment]
This would have been a great question for the stacksoverflow page. You want
to re-post it there so we can answer again and people can find it back?
