### ISSUE TITLE
Possible bug in get_center() in the Gridgen class

### ISSUE THREAD

**Issue by porterma** [modflowpy/flopy#782]
I came across some discrepancies in my (x, y) center locations returned by the get_center() function and those returned by the centroid method of shapely. The flopy code for get_center() is below.

```
def get_center(self, nodenumber):
        """
        Return the cell center x and y coordinates
        Parameters
        ----------
        nodenumber
        Returns
        -------
         (x, y) : tuple
        """
        vts = self.get_vertices(nodenumber)
        xmin = vts[0][0]
        xmax = vts[1][0]
        ymin = vts[2][1]
        ymax = vts[0][1]
        return ((xmin + xmax) * 0.5, (ymin + ymax) * 0.5)
```
In my quadtree grid that I am working with, the combination of xmin and xmax does not return the center point of my polygon. It returns the center of an edge. In my case the grid is rotated by -39 degrees. See below.

![Node1_vertices](https://user-images.githubusercontent.com/18117829/72562967-e43ac600-3869-11ea-81f0-57226bd28ce0.png)

The vertices of the polygon are also shown in the above image. The get_center() function returns [2757650.6776684 , 1207827.59289415], whereas the shapely centroid returns [2.757449e+06  1.207828e+06], which is consistent with the center coordinates shown in the bottom right corner of the arcmap image above. If xmax = vts[2][0] then the correct x center location is returned. 

Hope this helps and that I am not missing something on my end here. Thanks for providing the terrific flopy tool, it makes my life way easier.

**Comment by langevin-usgs** [comment]
@porterma, you're right.  It looks like the logic under the hood does not work for a rotated grid.  Thanks so much for pointing this out.  I'll work on a fix.

**Comment by langevin-usgs** [comment]
This was an easy fix, @porterma.  Glad you mentioned the problem.  Thanks!
