### ISSUE TITLE
applying spatial reference to mf6 model

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#785]
Hello, are there any examples of applying a spatial reference to an existing mf6 model?

Particularly, I want to create a sr class from my mf6 model to pass to another code (sfrmaker).

**Comment by spaulins-usgs** [comment]
The SpatialReference class has been deprecated and has been replaced with the grid classes. All models, including mf6 models have a modelgrid attribute to get the model's grid. The grid classes have a set_coord_info method to set coordinate (spatial reference) information. You can find examples of this in the flopy3.3PlotMapView.ipynb python notebook.

To set your new model grid's spatial reference information to that of your old model, you could do something like this:

old_mg = old_model.modelgrid
new_model.model_grid.set_coord_info(xoff=old_mg .xoffset, yoff=old_mg .yoffset, angrot=old_mg .angrot, proj4=old_mg .proj4)
