### ISSUE TITLE
Heat transport using MODFLOW and MT3DMS / MT3D-USGS

### ISSUE THREAD

**Issue by mattijn** [modflowpy/flopy#793]
I'm trying to comprehend the following heat transport tutorial based on MODFLOW-2005 and MT3DMS: http://gmstutorials-10.1.aquaveo.com/MT3DMS-HeatTransport.pdf ¹
Which also is available on [YouTube](https://www.youtube.com/watch?v=-nsY-vKv4FQ).

The tutorial and video are created for GMS but I like to use Flopy (I don't have GMS).

The model is adapted from example 9 of the 1999 MT3DMS report (see [jupyter notebook](https://nbviewer.jupyter.org/github/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_MT3DMS_examples.ipynb#Example-9.-Two-Dimensional-Application-Example)):

Basically the area contains a low K-zone (purple area in right chart). There is an injection well (green point in right chart) and an extraction well (blue point in right chart). And there is a slope in head from 250 meter at top to 240 meter at bottom (see left chart)

<img width="568" alt="image" src="https://user-images.githubusercontent.com/5186265/73142053-b2580980-408a-11ea-9431-236f7e280e82.png">

After lots of reading and trying with Flopy model code I cannot get the heat transport to produce similar results to the tutorial. I started with using MT3D-USGS, but I get similar behaviour using the MT3DMS model.

I always end up with the same or almost the same result, that looks like the following:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/5186265/73141998-21812e00-408a-11ea-86a4-c5e1dd00d60a.png">

The flowing pattern seems to be in line with the tutorial. First a bit to the north and then over time around the low K-zone towards the extraction well.
But the temperature values are around 0 (and even below 0), where the units are Kelvin! Thats very cold flowing water.. I was hoping to see heat transport values close to the injection temperature of 298 Kelvin.

I would _greatly appreciate_ if someone can have a look what I must be doing wrong. The reproducible notebook is located [**here**](https://github.com/mattijn/datasets/blob/master/MF2005%20with%20MT3DMS.ipynb):

At the same time this issue also aims to create some documentation for doing heat transport using Flopy, since this information seems to be scarce on the internet (I can't find it).

¹ The GMS MODFLOW model can be found at: http://gmstutorials-10.1.aquaveo.com/heat_transport.zip

**Comment by dbrakenhoff** [comment]
There is some documentation on doing heat transport calculations using MT3DMS in the [SEAWAT doumentation](https://pubs.usgs.gov/tm/tm6a22/pdf/tm6A22.pdf). It's not specifically written for flopy, but it does provide some extra information that might be useful...?

**Comment by langevin-usgs** [comment]
From your results, it's clear that the correct temperature is not being assigned to injected well water.  This suggests a problem with SSM.  Your lines below are incorrect.  ssm_data is a dictionary in your case, which means the keys should be stress period, and the values should be lists of ssm entries.  Your key appears to be the column number.  Looking in the files themselves and comparing with the documentation would have also helped you find the error.

This is not a flopy bug, so I'm closing this issue.  Stackoverflow would be a better place to ask this question.

```
ssm_data = {}
# heads on 278 Kelvin
for i in range(ncol):
    ssm_data[i] = [(0, 0, i, 278, itype['CHD'])]
for i in range(ncol):
    ssm_data[i+ncol] = [(0, nrow, i, 278, itype['CHD'])]  
# injection well on 298 Kelvin 
ssm_data[ncol+ncol] = [(0, 9, 15, 298, itype['WEL'])] 
```

**Comment by mattijn** [comment]
Much appreciated for the responses. Setting `ssm_data[I]`, `ssm_data[i+ncol]` and `ssm_data[ncol+ncol]` to `ssm_data[0]` did indeed provide much better results.

Thanks for the pointers to the SEAWAT documentation and how to debug hurdles like these within Flopy. Thumbs up!
