### ISSUE TITLE
How to learn why model does not run properly?

### ISSUE THREAD

**Issue by mustafaucr** [modflowpy/flopy#794]
I want to learn why my model does not run successfully. Because I can not know which package must be rearranged. I use code below:

`success, mfoutput = model.run_model(silent=False, pause=False, report=True)`

However it gives me only this message from `mfoutput ` parameter:

**' FAILED TO MEET SOLVER CONVERGENCE CRITERIA            1  TIME(S)'**

**Comment by langevin-usgs** [comment]
This is not a flopy bug.
