### ISSUE TITLE
error in write_gridlines_shapefile

### ISSUE THREAD

**Issue by hwreeves-USGS** [modflowpy/flopy#797]
I am getting an error in write_gridlines_shapefile()

'''
flopy.export.shapefile_utils.write_gridlines_shapefile(os.path.join(home,
                                                                    'postproc',
                                                                    'shps',
                                                                    'badger_inset_14LL.shp'), 
                                                       mf.modelgrid)
'''

Its throwing:  
'''
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-3b8a4d579ab3> in <module>
      3                                                                     'shps',
      4                                                                     'badger_inset_14LL.shp'), 
----> 5                                                        mf.modelgrid)

C:\ProgramData\Anaconda3\lib\site-packages\flopy-3.2.13-py3.7.egg\flopy\export\shapefile_utils.py in write_gridlines_shapefile(filename, mg)
     68             category=DeprecationWarning)
     69     else:
---> 70         grid_lines = mg.grid_lines()
     71     for i, line in enumerate(grid_lines):
     72         wr.poly([line])

TypeError: 'list' object is not callable

'''

I think it should be `grid_lines = mg.grid_lines`  in the routine.  (not  grid_lines())

**Comment by jdhughes-usgs** [comment]
@jlarsen-usgs and ideas?

**Comment by jlarsen-usgs** [comment]
This issue was fixed with PR #799. Closing issue.
