### ISSUE TITLE
Problem loading existing model

### ISSUE THREAD

**Issue by grajh** [modflowpy/flopy#800]
Hi!

I am having problem loading existing model files, which were generated with GMS software package (https://www.aquaveo.com/software/gms-modflow). What am I doing wrong? Any help would be very much appreciated.

My input files are located here: [model_29012020.zip](https://github.com/modflowpy/flopy/files/4150288/model_29012020.zip)

Bests, Gregor

Python 3.8.1 | packaged by conda-forge | (default, Jan 29 2020, 14:55:04) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
**>>> import flopy**
flopy is installed in /home/gregor/anaconda3/envs/flopy/lib/python3.8/site-packages/flopy
**>>> mf = flopy.modflow.Modflow.load('model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.mfn', version='mf2005', verbose=True, check=False)**

Creating new model with name: model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA

Parsing the namefile --> ./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.mfn

External unit dictionary:
{702: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.out, filetype:LIST, 730: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.hed, filetype:DATA(BINARY), 740: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.ccf, filetype:DATA(BINARY), 718: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.lmt, filetype:LMT6, 751: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.hob, filetype:HOB, 755: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.chob, filetype:CHOB, 775: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA._os, filetype:DATA, 771: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.asp, filetype:ASP, 719: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.dis, filetype:DIS, 703: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.ba6, filetype:BAS6, 704: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.lpf, filetype:LPF, 715: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.oc, filetype:OC, 707: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.hfb, filetype:HFB6, 709: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.wel, filetype:WEL, 713: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.chd, filetype:CHD, 714: filename:./model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.pcg, filetype:PCG}

ModflowBas6 free format:True

loading dis package file...
   Loading dis package with:
      3 layers, 100 rows, 100 columns, and 1 stress periods
   loading laycbd...
   loading delr...
   loading delc...
   loading top...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gregor/anaconda3/envs/flopy/lib/python3.8/site-packages/flopy/modflow/mf.py", line 730, in load
    dis = disnamdata.package.load(disnamdata.filehandle, ml,
  File "/home/gregor/anaconda3/envs/flopy/lib/python3.8/site-packages/flopy/modflow/mfdis.py", line 881, in load
    top = Util2d.load(f, model, (nrow, ncol), np.float32, 'top',
  File "/home/gregor/anaconda3/envs/flopy/lib/python3.8/site-packages/flopy/utils/util_array.py", line 2661, in load
    cr_dict = Util2d.parse_control_record(f_handle.readline(),
  File "/home/gregor/anaconda3/envs/flopy/lib/python3.8/site-packages/flopy/utils/util_array.py", line 2801, in parse_control_record
    locat = np.int(line[0:10].strip())
ValueError: invalid literal for int() with base 10: 'HDF5 1.0 -'

**Comment by jlarsen-usgs** [comment]
Hi the issue here is really with how GMS is storing your array data. USGS MODFLOW products do not accept HDF5 as a file location (locat variable). I'd suggest 1st using h5py to access the hdf5 file that GMS has stored your array data in. Write out each of the arrays as an ASCII file in a folder called Arrays. And then manually change your input files to use an OPEN/CLOSE statement for external array data. Here's a quick example on how to do this.

**python**
```
# grab the top array from your hdf5 file and write it to ASCII
import h5py

hdf_file = "model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.h5"
f = h5py.File(hdf_file, "r")
top = f['Arrays/top1'].value

np.savetxt("Attays/top.txt", top, delimiter="  ", fmt='%.6f')

```

Then in your modflow DIS file, you'd need to change 
```
HDF5 1.0 -1 "model_29012020_MANJSA_MREZA_KOCKAPOTOPLJENA.h5" "Arrays/top1" 1 0 10000
```
to 
```
OPEN/CLOSE  Arrays/top.txt 1.0 (FREE) -1
```

You will need to do this for all HDF5 references in each of your input files if you'd like to run and process this model outside of GMS. 

Because this is not an issue with FloPy, I am closing this issue

**Comment by grajh** [comment]
I understand now. Thanks a lot.
