### ISSUE TITLE
AttributeError when loading model

### ISSUE THREAD

**Issue by drewbost** [modflowpy/flopy#802]
I am getting an error when trying to load an external model. I am using flopy v 3.3.0 and python 3.6.7 (64-bit) from an Anaconda environment on Windows 10.
Error message:

  File "modelrun.py", line 16, in <module>
    ml = flopy.modflow.Modflow.load(nam_file, exe_name = mf2000, model_ws = model_ws, check= False)
  File "c:\Users\dbost\AppData\Local\Continuum\anaconda3\envs\flopy330\lib\site-packages\flopy\modflow\mf.py", line 697, in load
    ml.glo.unit_number = [unitnumber]
  File "c:\Users\dbost\AppData\Local\Continuum\anaconda3\envs\flopy330\lib\site-packages\flopy\mbase.py", line 533, in __getattr__
    raise AttributeError(item)

Here is what I am using to load the model:
    mf2000 = 'exepath\\MF2k.exe'
    model_ws = 'workspacepath\\'
    nam_file = 'WS5914.nam'
    ml = flopy.modflow.Modflow.load(nam_file, exe_name = mf2000, model_ws = model_ws, check= False)

I was able to load and run the model fine when using an environment with flopy 3.2.9 and python 3.5.5, but since switching to 3.3.0 I have been unable to load it. Other models from the examples folder run just fine (freyberg, mf2k_test, mf6).

**Comment by jlarsen-usgs** [comment]
Hi @drewbost 

It looks like one of your packages is not loading into FloPy. Previously the default behavior of FloPy was to keep running instead of crashing when a package didn't load. This behavior has been changed. Try loading your model using the `forgive` flag

```
ml = flopy.modflow.Modflow.load(nam_file, exe_name = mf2000, model_ws = model_ws, check= False, forgive=True)
```
and then print out the list of loaded packages and compare this to the packages in your nam file to see what hasn't loaded:
```
print(ml.packagelist)
```

**Comment by drewbost** [comment]
Thanks for your reply @jlarsen-usgs 

Unfortunately I am getting the same error. There is a portion of the error code I did not include originally that was written at the top: 

<class 'AttributeError'>
glo

Is it possible the GLO package is being misread?

Here are all the packages listed in my .nam file:
GLOBAL 6 WS5914.glo
LIST 7 WS5914.lst
BAS6  1 WS5914.bas
DIS  10 WS5914.dis
LPF 11 WS5914.lpf
ZONE 40 WS5914.zone
OBS 51 WS5914.obs
HOB 52 WS5914.hob
GAGE 28 WS5914.gag
WEL 25 WS5914.wel
DRN 21 WS5914.drn
RCH 18 WS5914.rch
HFB6 22 WS5914.hfb
OC  24 WS5914.oc
PCG 19 WS5914.pcg
LAK 29 WS5914.lak
DATA(BINARY) 32 WS5914.cbb
DATA 34 WS5914_gage_lak.dat
DATA(BINARY) 30 WS5914.hds
DATA(BINARY) 31 WS5914.ddn

**Comment by jlarsen-usgs** [comment]
@drewbost 

I think I've tracked down the issue. Can you try using `version='mf2k'` in your model load statement. There is an issue that you've found, but this may serve as a work around until it is fixed.

```
ml = flopy.modflow.Modflow.load(nam_file, exe_name=mf2000, model_ws=model_ws, check=False, version='mf2k')
```

**Comment by drewbost** [comment]
Looks like that worked @jlarsen-usgs , thanks for your help. Should I keep this open?

**Comment by jlarsen-usgs** [comment]
Keep this open for now. There is still an issue that needs to be fixed.

**Comment by drewbost** [comment]
Hi @jlarsen-usgs , it seems I am getting a new error msg now. Let me know if I should open in a new ticket:

<class 'ValueError'>
sum of dataset 4 proportions must equal 1.0 - sum of dataset 4 proportions = 1.008 for observation name CypLwn_2.
  File "X:\UserAssistance\Data_Infrastructure_Projects\ModelInputConverter\scripts\WestsideBasinmodel.py", line 16, in <module>
    ml = flopy.modflow.Modflow.load(nam_file, version = 'mf2k', exe_name = mf2000, model_ws = model_ws, check= False)
  File "c:\Users\dbost\AppData\Local\Continuum\anaconda3\envs\flopy330\lib\site-packages\flopy\modflow\mf.py", line 799, in load
    check=False)
  File "c:\Users\dbost\AppData\Local\Continuum\anaconda3\envs\flopy330\lib\site-packages\flopy\modflow\mfhob.py", line 438, in load
    names=names))
  File "c:\Users\dbost\AppData\Local\Continuum\anaconda3\envs\flopy330\lib\site-packages\flopy\modflow\mfhob.py", line 585, in __init__
    raise ValueError(msg)

**Comment by jlarsen-usgs** [comment]
@drewbost 

I'd start by looking in your HOB file to double check that the sum of the PR values for observation CypLwn_2 equals exactly 1.0. If they don't FloPy will purposely raise an error. Please check these values. Here is a link to the online documentation of [HOBS](https://water.usgs.gov/ogw/modflow-nwt/MODFLOW-NWT-Guide/index.html?hob.htm)

**Comment by drewbost** [comment]
@jlarsen-usgs 

I checked and they add up to 1.008. I don't understand why this does not raise an error in my flopy v=3.2.9.

**Comment by jdhughes-usgs** [comment]
I remember that we reworked the hobs package at some point (after 3.2.9) to make sure the total is 1.0.
