### ISSUE TITLE
Default budget file unit number (ipakcb)

### ISSUE THREAD

**Issue by etiennebresciani** [modflowpy/flopy#803]
I have a few remarks and a proposition regarding packages that require an ipakcb parameter.

### Remarks
1. The default behavior seems to be always ipakcb=0, but the documentation is sometimes inconsistent with this. For example, ModflowLpf and ModflowBcf doc strings indicate that the default is ipakcb=53, which is actually not true.
2. The documentation is also incomplete: it only says that ipakcb is "A flag that is used to determine if cell-by-cell budget data should be saved. If ipakcb is non-zero cell-by-cell budget data will be saved.". However, not only should ipakcb be non-zero, but also should it be exactly equal to the required cell-by-cell file unit number. In particular, the latter must NOT be the same as the unit number of any existing package, otherwise no output will be written.
3. It is not easy to know which unit number can actually be used. However, it seems that unit number 53 is conventionally used, as this number does not clash with any package default unit numbers. But this is quite cryptic for a non-expert user.

### Proposition
In the `__init__` of relevant packages, add the following:
`if ipakcb == ‘default’:`
`    ipakcb = model.defaultcbcunit()`
Where the function `defaultcbcunit()` would be defined in the Modflow class and would return 53.
Thus, the user could create an instance of ModflowLpf (for example) as:
`lpf = flopy.modflow.ModflowLpf(mf, hk=hk, vka=vka, ipakcb=’default’)`
Of course, the doc strings should also be updated.

**Comment by jdhughes-usgs** [comment]
The default condition is probably to not save CBC data and force the user to turn it on. So I would say the default condition would be `ipakcb=None` which would set it to zero. The user could also specify `ipakcb='default'` which would do what you indicated.

Would you be interested in implementing you proposed approach with this change? It would be great if you cleaned up the inconsistencies in the docstrings.

**Comment by etiennebresciani** [comment]
Ok, I'll try to get to it in the coming days.
