### ISSUE TITLE
OC package warnings

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#804]
I always get the warning below when I load a model. 
What does this mean? Or is this a bug? 

OC package: action(s) defined in OC stress_period_data ignored as they are not part the stress periods defined by DIS

**Comment by jdhughes-usgs** [comment]
You must have OC data for periods that exceed `NPER` defined in the `DIS` package. If you were to rewrite the input files, OC data would be truncated to data within `NPER`.
