### ISSUE TITLE
Issue exporting HDS file to shapefile using output_helper

### ISSUE THREAD

**Issue by drewbost** [modflowpy/flopy#807]
I am getting an error when using the export.utils.output_helper function to export my model's .hds file as a shapefile. I'm using flopy 3.3.0, Python 3.6 (64 bit) on Windows 10.

<class 'NotImplementedError'>
unrecognized export argument:X:\filepath\freyberg_hds.shp
  File "c:\Users\dbost\AppData\Local\Continuum\anaconda3\envs\flopy_hds\lib\site-packages\flopy\export\utils.py", line 343, in output_helper
    ":{0}".format(f))

I've quadruple checked all my folder paths for typos. Here is my script:

    import os
    import sys
    import traceback
    import flopy

    nam_file = 'freyberg.nam'
    
    model_ws = 'X:\\path\\freyberg\\'
    shapefile_ws = 'X:\\path\\freyberg\\shapefiles\\'
    ml = flopy.modflow.Modflow.load(nam_file, model_ws = model_ws, check= False)
    proj4_str = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
    ml.modelgrid.set_coord_info(xoff=123456.7, yoff=765432.1, angrot=15.0, proj4=proj4_str)
    hds = flopy.utils.binaryfile.HeadFile(model_ws + 'freyberg.hds')
    flopy.export.utils.output_helper(shapefile_ws + ml.name + '_hds.shp', ml, {"hds":hds})    

I've been able to export the .hds file using '.to_shapefile', only it does not export with the model grid properties or projection system.

**Comment by jlarsen-usgs** [comment]
@drewbost 

You can pass in the modelgrid to `flopy.utils.binarfile.HeadFile` before exporting using `.to_shapefile()`. You will then be able to export the .hds file with modelgrid properties and projection.

Here's a code snippet:
```
hds = flopy.utils.binaryfile.HeadFile(model_ws + 'freyberg.hds', modelgrid=ml.modelgrid)
hds.to_shapefile('myshapefile.shp')
```
The output_helper class does need to be updated for shapefile exporting. I can take care of this.

**Comment by drewbost** [comment]
Thank you @jlarsen-usgs, works great on freyberg as well as my own model.
