### ISSUE TITLE
Issues with build_exes.py

### ISSUE THREAD

**Issue by etiennebresciani** [modflowpy/flopy#810]
I am running into a number of problems when executing `nosetests -v build_exes.py` (as suggested in CONTRIBUTING.md).
1.	Bug when trying to copy executables when the folder ~/.local/bin does not exist.
2.	Bug due to inconsistent removing of vs2dt from targets.
3.	Bug when `os.system(cmd)` is run in the function `list_json()`. The output here is:

> build_exes.test_list_json ...   File "\<string\>", line 1
> 'from
>         ^
> SyntaxError: EOL while scanning string literal

I am able to resolve bugs 1 and 2 (and could potentially submit a PR).
Bug 3 is trickier. In fact, I am able to resolve the above Syntax Error, but then I obtain:

> build_exes.test_list_json ... Traceback (most recent call last):
>   File "\<string\>", line 1, in \<module\>
>   File "C:\Users\ADmin\\.conda\envs\Etienne_env\lib\site-packages\pymake\usgsprograms.py", line 326, in list_json
>     raise IOError(msg)
> OSError: could not load json file "C:\\Workspace\\ebrescia\\flopy\\flopy_forked\\code.json".

The file exists, and so the latter seems to point to a bug in pymake.

Why am I getting all these problems? Am I doing something wrong?

Configuration:
* python 3.7.6
* Up-to-date with flopy develop (commit 0d152513d4ecb84fd474cb0495dd0676f05d5b72)
* Windows 10

**Comment by langevin-usgs** [comment]
Hi @etiennebresciani, thanks for wanting to help us out with flopy.  We certainly need the help!  Part of the problem is certainly that most of us are using Macs, and so we probably haven't done enough testing on Windows to make sure that everything is working right.  While it would be good to get the build_exes() working for you, the autotests should all still run even if the executables are not present.  In this case, it looks to find the executables, and if they're not present, then it just skips the running part.  Do the autotests work for you if the executables are not present?  If you are having problems with pymake, then it would be good to file an issue there.  At some point, it would be good to get all our tests running on Appveyor.  It is my understanding that it works like Travis, but can run on Windows.

**Comment by etiennebresciani** [comment]
Thanks for the welcoming message @langevin-usgs!

The fact that most of you are using Mac can indeed explain some of the errors I've been running into. I have solved most issues in a way that should (hopefully) work regardless of the platform.

However, I am still having doubts regarding the json file. I am realizing that this file may or may not be downloaded as part of the executables. In my case (Windows), it is not. For a Mac configuration, it is (I checked by manually downloading from https://github.com/MODFLOW-USGS/executables/releases). Thus, I could simply fix this issue by adding lines to the `list_json()` function so as to do nothing if there is no json file downloaded. Do you want me to do that?

I also found a json file at the root of the flopy directory. I initially tried to use this file, and this is when I ran into the loading error reported in my first post above. I am now realizing that this file is obsolete: at least it is quite different from the file I found by manually downloading from https://github.com/MODFLOW-USGS/executables/releases. This likely explains the loading error I got. Perhaps this file should be removed?

PS: yes, I can still run the autotests (even with all the downloaded executables, as I got this part running)

**Comment by langevin-usgs** [comment]
I'm looking at that build_exes script and it seems overly complicated for what you need.  All you really need to do is make sure you have those executables somewhere they are accessible through the PATH variable.  If you want to try and fix build_exes() to work for you then that's okay, but I personally don't ever use it.  I think it is mainly used for Travis testing.  I agree that it would be good to have it die more gracefully.  I also get the following error, which isn't very informative.  

``
elapsed time (hh:mm:ss.ms): 0:00:00.047499

copying exe_download\triangle.exe -> C:\Users\langevin\.local\bin\triangle.exe
copying exe_download\gridgen.exe -> C:\Users\langevin\.local\bin\gridgen.exe
copying exe_download\zonbud3.exe -> C:\Users\langevin\.local\bin\zonbud3.exe
copying exe_download\crt.exe -> C:\Users\langevin\.local\bin\crt.exe
  File "<string>", line 1
    'from
        ^
SyntaxError: EOL while scanning string literal
``

**Comment by etiennebresciani** [comment]
Well, I might have been overly disciplined by closely following the contribution guidelines, where the command `nosetests -v build_exes.py` is indicated...

Anyways, I fixed the bugs and created a PR. However, please make sure that it still does what it needs to do on Mac/Linux, as I did not test it on these platforms.
