### ISSUE TITLE
SFR exports shapefile incorrectly

### ISSUE THREAD

**Issue by andyrich** [modflowpy/flopy#816]
When trying to export sfr, the locations of the cells do not overlap model grid. The dis grid retains the modelgrid coordinates but the sfr grid does not.

`
from flopy.utils.reference import SpatialReference
from flopy.discretization.structuredgrid import StructuredGrid
import flopy
from platform import python_version
print(f'python version: {python_version()}')

print(f'flopy version: {flopy.__version__}')
delr, delc = np.ones((157))*660, np.ones((168))*660
xul = 6306015.91393092
yul = 1982413.68616024
sr = SpatialReference(delr=delr, delc=delc, xul=xul, yul=yul, units='feet',
                    proj4_str='EPSG:2226', rotation=0 , lenuni = 1, length_multiplier = 1.0 )

#make strurctured grid from model grid above.
mg = StructuredGrid(delc=sr.delc, delr=sr.delr, xoff=sr.xll, yoff=sr.yll, angrot=0, 
            epsg=2226, lenuni=1)

ml = flopy.modflow.Modflow.load('SRP_mf.nam',load_only = ['DIS','BAS6','SFR'], model_ws=workspace,verbose =False)
ml.modelgrid = mg

print('exporting dis')
ml.dis.export('GIS\ml_dis.shp',epsg=2226)
print('exporting sfr')
ml.sfr.export('GIS\ml_sfr.shp',epsg=2226)

import geopandas as gpd
dis = gpd.read_file('GIS\ml_dis.shp')
ax = dis.plot()
ax.set_title('dis')
sf = gpd.read_file('GIS\ml_sfr.shp')
ax = sf.plot()
ax.set_title('sfr')

print(f'the total bounds for dis shapefile is: {dis.geometry.total_bounds}')
print(f'the total bounds for sfr shapefile is: {sf.geometry.total_bounds}')
`
![image](https://user-images.githubusercontent.com/16653125/75389340-36c0c680-589b-11ea-867c-0c4a169f2b65.png)

[inputs.zip](https://github.com/modflowpy/flopy/files/4258239/inputs.zip)

**Comment by jlarsen-usgs** [comment]
@andyrich 

I can take a look at this. It looks like modelgrid information is not getting passed properly to the export routine for sfr.

**Comment by jlarsen-usgs** [comment]
@andyrich 

Just submitted a PR to fix this issue.

If you'd like to avoid building a SpatialReference and then StructuredModelGrid object from scratch you could use this code snippet instead to set the coordinate info of the modelgrid that is automatically built when you load in your DIS and BAS file:

```
xul = 6306015.91393092
yul = 1982413.68616024

xll = ml.modelgrid._xul_to_xll(xul)
yll = ml.modelgrid._yul_to_yll(yul)
ml.modelgrid.set_coord_info(xoff=xll, yoff=yll, epsg=2226)
```

**Comment by andyrich** [comment]
Thanks josh!
@jlarsen-usgs
