### ISSUE TITLE
Issue with the Water Mover Package (WMR)

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#818]
It is a long time I have not used flopy. I wrote a simple script last year that I run with flopy 3.2.10 and it was working OK. The script was using the water mover package: the provider was a single drain cell whilst the receiver was an injection well defined with the MAW package. Below I report a portion of the script that it was working before:

```
nper = 31
modelname = 'inj_opt'

mvr_perioddata = {}
for sp in range(nper):
    mvr_perioddata[sp] = [('drn', 0, 'maw', 0, 'EXCESS', 0.0)]

mvr = flopy.mf6.modflow.mfgwfmvr.ModflowGwfmvr(gwf, pname='mvr', print_flows=True, maxmvr=2, maxpackages=2, packages=['drn', 'maw'], perioddata=mvr_perioddata)
```

when I run the above with the new version 3.3.0 I get the following errors:

`{MFDataException}An error occurred in data element "packages" model "inj_opt" package "mvr". The error occurred while setting data in the "__init__" method.
Additional Information:
(1) An error occurred when storing data "packages" in a recarray. packages data is a one or two dimensional list containing the variables "<pname>" (some variables may be optional, see MF6 documentation), but data "[('drn', 'maw')]" was supplied.
(2) Error occurred while adding dataset "packages" to block "packages"`

I verified the page with the updates from version 3,2,10 and I have not noticed any modification to the WMR package. I wonder if I am doing something wrong. The old flopy version was able to create the WMR package file and run the model using the code above mentioned.
Any help will be appreciated

Many thanks in advance

**Comment by spaulins-usgs** [comment]
Try changing:

packages=['drn', 'maw']

to:

packages=[('drn',), ('maw',)]

Flopy is storing the packages information in a numpy recarray, which in this case is a single column recarray (column "pname").  While flopy's preprocessing will do some cleanup on your data, it is not very good at figuring out the intended dimensions of user defined recarray data.  It is therefore best to build the flopy list/recarray data as if you were going to create the recarray yourself:

new_data = np.rec.array([('drn',), ('maw',)], [('pname', np.str)])

**Comment by giovannifi** [comment]
It worked.  thanks a lot !
