### ISSUE TITLE
question on Modflow.load() 

### ISSUE THREAD

**Issue by hwreeves-USGS** [modflowpy/flopy#82]
I am following the 'making maps and cross-sections' notebook to load an existing model.
I am getting a message  '... load method not complete', although the model packages are being generate and the model is running.  How should I interpret the not complete message?

In the notebook:
ml = flopy.modflow.Modflow.load('LPR_SS11Final_8_23_15.nam', model_ws=loadpth, 
                                exe_name=mfexe, version=version)
ml.change_model_ws(new_pth=modelpth)
ml.write_input()
success, buff = ml.run_model()

Output:
 ZONE package load...success
  ...load method not completed. default nwt file created.

changing model workspace...
   HWR
FloPy is using the following executable to run the model: C:\WRDAPP\MODFLOW-NWT_1.0.9\bin\MODFLOW-NWT_64.exe

then it seems to be running fine, although I changed the names of output packages in the original .nam file, and these changed names are not retained in the version that flopy writes to my new working directory - all the package names have the same base.

Thanks

**Comment by jdhughes-usgs** [comment]
Looks like the error is just related to the nwt load. Previously the NWT load didn't read the actual NWT data and created a default NWT object (with default NWT parameters). We recently finished a complete load for NWT. You can get the version with a complete NWT load from the development branch. BTW. We will be making a new FloPy release at the end of the week (it will include the new NWT load method).

**Comment by hwreeves-USGS** [comment]
thanks - I'll give the development branch version a try -

**Comment by jdhughes-usgs** [comment]
We have tested it on a variety of NWT files so let us know if it fails for you case and we can add you NWT file to our test suite.

**Comment by jdhughes-usgs** [comment]
One thing that we added is the version needs to be set to 'mfnwt' (version='mfnwt') when the model is instantiated. Otherwise it will throw an exception. It will also throw an exception for UPW if the version is not 'mfnwt'.

**Comment by jjstarn-usgs** [comment]
thanks for the heads-up on that--it will impact our notebooks

On Tue, Feb 2, 2016 at 12:26 PM, Hughes, J.D. <notifications@github.com>
wrote:

> One thing that we added is the version needs to be set to 'mfnwt'
> (version='mfnwt') when the model is instantiated. Otherwise it will throw
> an exception. It will also throw an exception for UPW if the version is not
> 'mfnwt'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modflowpy/flopy/issues/82#issuecomment-178700366>.
>



-- 
Jeff Starn Ph.D.
Research Hydrologist
USGS National Water-Quality Assessment
101 Pitkin Street,  East Hartford, CT 06108

jjstarn@usgs.gov
office: (860) 291-6746
cell: (860) 335-8381

**Comment by mnfienen-usgs** [comment]
On loading, wouldn't it make sense to set version = 'mfnwt' automagically if a NWT package is found? It seems to me to violate the general ease of loading to force the user to specify the type a priori but only in the case of MFNWT?

**Comment by jdhughes-usgs** [comment]
Maybe. I'll look into could probably do the same if GLO (mf2k) or SMS (mfusg) is found.

**Comment by mnfienen-usgs** [comment]
Yeah - I like that idea. Of course, it depends on people creating the name file correctly, but it seems going that extra step would be good and dealing with errors further down the chain would be good.

**Comment by jdhughes-usgs** [comment]
Ok added something for MODFLOW so that model version is reset if NWT or UPW is present during load (mfnwt). Also added similar for DISU and SMS (mfusg) and GLO (mf2k).

Let me know if there are any issues.

**Comment by mnfienen-usgs** [comment]
Rad! Just tested it with a NWT model and worked like a champ. Thanks for doing that!
