### ISSUE TITLE
Error loading .dis file

### ISSUE THREAD

**Issue by RyanConway91** [modflowpy/flopy#826]
I am using flopy version 3.3.0 in python 3 and I am having issues loading models. This is happening in scripts that used to work.

I am getting the following error.

![image](https://user-images.githubusercontent.com/25184697/76465933-a020f900-63b4-11ea-9749-e645f6fd74e0.png)

I am using:

```
import flopy as fp
m_path = "mccoy_hfb_mf.nam"
m = fp.modflow.Modflow.load(m_path)
```
I have attached model files

[run_0.zip](https://github.com/modflowpy/flopy/files/4320987/run_0.zip)

**Comment by emorway-usgs** [comment]
@RyanConway91 Your model loaded just fine with flopy version '3.3.1'.  You might try upgrading and seeing if that clears up the issue.

**Comment by emorway-usgs** [comment]
@RyanConway91  ![snippet](https://user-images.githubusercontent.com/3236576/76470941-a14f2780-63ae-11ea-9f4c-5a4c502a916e.png)

**Comment by giovannifi** [comment]
How do I upgrade to 3.3.1? I tried

`pip install flopy --upgrade`

but it says that 3.3.0 is the latest version.

Thanks

**Comment by langevin-usgs** [comment]
3.3.1 is the development version.  Follow the instructions for installing the development version.
