### ISSUE TITLE
.cbc budget file with Modflow NWT

### ISSUE THREAD

**Issue by jonathanqv** [modflowpy/flopy#827]
Hello! I´ve trying to create a .cbc file with UPW as the same way I do with LPF but instead of creating a unique .cbc file it creates me a .UPW.cbc file, is that a bug or am I doing something wrong? I am trying to create pathlines with modpath6, I´ve tried in Modelmuse and it works like a charm, but I am having this problems with Flopy.
kind regards.

**Comment by jdhughes-usgs** [comment]
The `UPW` unit number for `IPAKCB` has to be the same as the existing unit number for the CBC file you want to use. A default name is specified if `IPAKCB` is a positive integer and there isn't file with that unit number in the list of output files.

Does this apply to your problem? You can look at the `UPW`, `OC`, and `name` files to determine this.

**Comment by jonathanqv** [comment]
Yes! It solved it! Thank you very much!
