### ISSUE TITLE
Flopy will write incomplete input to MF6 SFR package

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#831]
In putting together #830, I also discovered that flopy will write package data that is incomplete. For example, if you change the sfr package creation step in #830 to 

```python
sfr = mf6.ModflowGwfsfr(model, packagedata=[
    (0, (0, 0, 9),  35.5, 1.76, 0.448, 293.2, 1.0, 1.0, 0.037, 1, 1.0, 0),
    (1, (0, 0, 8),  35.5, 1.76, 0.448, 293.2, 1.0, 1.0, 0.037, 1, 1.0)],
                        connectiondata=[(0, 1),
                                       ]
)
```
(where the last value for reach 1 is missing), the simulation writes OK, but presumably the input is invalid (and flopy can't load it back in).

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs Is this resolved yet?

**Comment by spaulins-usgs** [comment]
@jdhughes-usgs yes sorry I forgot to close this one
