### ISSUE TITLE
Problem with the str package const parameter 

### ISSUE THREAD

**Issue by OnurSahin20** [modflowpy/flopy#832]
I'm working with the time unit as days in the str package so I have to take the const = 1.486*86400 but than some problem arise like in the list

 FILE UNIT  118 : ERROR CONVERTING "1128390.000" TO AN INTEGER IN LINE:
      40         3         2         0         1128390.000  (enter icalc and const together in here)      -1         0                                                                                                                        

if I take the constant less than 100,000 than no problem has occurs

**Comment by langevin-usgs** [comment]
do this instead: 

`const = int(1.486 * 86400)`

**Comment by OnurSahin20** [comment]
I tried before the post it is not working.

**Comment by langevin-usgs** [comment]
Sorry.  My answer doesn't make sense.  That number should be a floating point, not an integer.  Which model and package is this for?

**Comment by langevin-usgs** [comment]
For the stream package, the variables must be formatted correctly according to this.

![image](https://user-images.githubusercontent.com/3372403/77329297-ce270700-6ceb-11ea-8997-6b4955c90362.png)

**Comment by OnurSahin20** [comment]
if I take the const less than 100,000 than the model runs successfully but after the 6 digits arise error mention before. I'm thinking to format is correct.
icalc=0   then  FILE UNIT  118 : ERROR CONVERTING "0128390.400" TO AN INTEGER IN LINE:
icalc =1 then   FILE UNIT  118 : ERROR CONVERTING "1128390.400" TO AN INTEGER IN LINE:

i think program handle icalc and const together not separate those two parameters

**Comment by langevin-usgs** [comment]
What version of MODFLOW are you using? And can you copy and paste the line from the STR Package?  The line from your first post does not seem to be valid at all, because it is not formatted with 10 characters per entry.  

```
40 3 2 0 1128390.000 (enter icalc and const together in here) -1 0
```

The flopy STR class uses this format to write that line:

```
        line = '{:10d}{:10d}{:10d}{:10d}{:10d}{:10.3f}{:10d}{:10d}'.format(
            self.mxacts, self.nss,
            self.ntrib, self.ndiv,
            self.icalc, self.const,
            self.ipakcb, self.istcb2)
        for opt in self.options:
            line += ' ' + str(opt)
        line += '\n'
        f_str.write(line)
```

**Comment by OnurSahin20** [comment]
# STR package for  MODFLOW-2005, generated by Flopy.
40         3         2         0         1128390.400        -1         0  -----  str package format for const =128390

 40         3         2         0         1 86400.000        -1         0------   str package format for const =86400

**Comment by langevin-usgs** [comment]
and what version of flopy?

**Comment by OnurSahin20** [comment]
3.3 last version I uploaded yesterday

**Comment by langevin-usgs** [comment]
Can you post your script that creates this STR Package?  I don't see how flopy.modflow.ModflowStr can create that line you are showing, but maybe I'm missing something.

**Comment by OnurSahin20** [comment]
# transient 3 years confined hypothetical confined aquifer
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import flopy
import flopy.utils.binaryfile as bf

flopypth = os.path.join('..', '..', 'flopy')
if flopypth not in sys.path:
    sys.path.append(flopypth)

lx = 6000
ly = 5000
ztop = 0
zbot = -1
nlay = 1
nrow = 25
ncol = 30
delr = lx / ncol
delc = ly / nrow
dev = (ztop - zbot) / nlay
botm = np.linspace(ztop, zbot, nlay + 1)
T = 5000
ss = 0.05
ibound = np.ones((nlay, nrow, ncol), dtype=np.int32)
ibound[:, 0, :] = -1
ibound[:, -1, :] = -1

strt = np.ones((nlay, nrow, ncol), dtype=np.float32)
k = 0
for i in range(0, 6000, 200):
    strt[:, 0, k] = 100.5 - 0.0025 * i
    strt[:, -1, k] = 80.5 - 0.0025 * i
    k += 1

nper = 12
perlen = [92,91,91,91,92,91,91,91,92,91,91,91]
nstp = [1] * 12
steady = [False] * 12
# perlen.insert(0, 1)
# nstp.insert(0, 1)
# steady.insert(0, True)
# print(perlen, steady)

model_name = 'AHLFELD_EXAMPLE2'
mf = flopy.modflow.Modflow(model_name, exe_name='mf2005.exe')
dis = flopy.modflow.ModflowDis(mf, nlay, nrow, ncol, delr=delr, delc=delc,
                               top=ztop, botm=botm[1:],
                               nper=nper, perlen=perlen, nstp=nstp, steady=steady, lenuni=1,tsmult=1.5)
bas = flopy.modflow.ModflowBas(mf, ibound=ibound, strt=strt)
lpf = flopy.modflow.ModflowLpf(mf, hk=T, vka=T, ss=ss, ipakcb=53)
#pcg = flopy.modflow.ModflowPcg(mf)
sip = flopy.modflow.ModflowSip(mf)
rech = {}
for i in range(0, 12, 4):
    rech[i] = 0.0005
    rech[i + 1] = 0.002
    rech[i + 2] = 0
    rech[i + 3] = 0.001

recharge = flopy.modflow.ModflowRch(mf, rech=rech)
q1 = -3483.3
q2a = -50000
q2b = -27553.93
q2c = -26902.26
q2d = -26739.37
q4a = -48962.78
q4b = -8068.63
q3 = 0
well1 = [[0, 11, 10, q1], [0, 15, 16, q2a]]
well2 = [[0, 11, 10, q1], [0, 15, 16, q2b], [0, 13, 24, q4a]]
well3 = [[0, 11, 10, q1], [0, 15, 16, q2c]]
well4 = [[0, 11, 10, q1], [0, 15, 16, q2d], [0, 13, 24, q4b]]
well5 = [[0, 11, 10, q1], [0, 15, 16, q2a], [0, 10, 21, q3]]
well6 = [[0, 11, 10, q1], [0, 15, 16, q2b], [0, 13, 24, q4a], [0, 10, 21, q3]]
well7 = [[0, 11, 10, q1], [0, 15, 16, q2c], [0, 10, 21, q3]]
well8 = [[0, 11, 10, q1], [0, 15, 16, q2d], [0, 13, 24, q4b], [0, 10, 21, q3]]
well9 = [[0, 11, 10, q1], [0, 15, 16, q2a]]
well10 = [[0, 11, 10, q1], [0, 15, 16, q2b], [0, 13, 24, q4a]]
well11 = [[0, 11, 10, q1], [0, 15, 16, q2c]]
well12 = [[0, 11, 10, q1], [0, 15, 16, q2d], [0, 13, 24, q4b]]
wells_data = {0: well1, 1: well2, 2: well3, 3: well4, 4: well5, 5: well6, 6: well7, 7: well8, 8: well9, 9: well10,
              10: well11, 11: well12}


str8 = flopy.modflow.ModflowStr.load('supply2.str',nper=12,model=mf)

# mxacts=40
# nss=3
# ntrib=2
# icalc=1
# const = 128390
# str_period = {}
# str_period[0] = final
# segment_data = {0:[[2,3,0,0,0,0,0,0,0,0,0]]}
#

# final_x=final.tolist()
# print(final[0])
# list = []
#
# for i in range(40):
#     list.append(final_x[i])
# print(list)
# str_period[0] = list
# str8 = flopy.modflow.ModflowStr(mf,mxacts,nss,ntrib,0,1,const,stress_period_data=str_period,segment_data=segment_data,istcb2=1)
stress_period_data2 = {}
for kper in range(nper):
    for kstp in range(nstp[kper]):
        stress_period_data2[(kper, kstp)] = ['save head',
                                             'save budget',
                                             'print head',
                                             'print budget']
oc = flopy.modflow.ModflowOc(mf, stress_period_data=stress_period_data2,
                             compact=True)

mf.write_input()

# Run the model
success, mfoutput = mf.run_model(silent=True, pause=False, report=True)
if not success:
    raise Exception('MODFLOW did not terminate normally.')
headobj = bf.HeadFile(model_name + '.hds')
cbb = bf.CellBudgetFile(model_name + '.cbc')

**Comment by OnurSahin20** [comment]
[documents.zip](https://github.com/modflowpy/flopy/files/4370388/documents.zip)

**Comment by langevin-usgs** [comment]
Let's not communicate on this thread here anymore.  I don't think there is a bug.  This is what flopy creates for me, which looks to be valid.   If you are still having problems, then contact me through email.

```
# STR package for  MODFLOW-2005, generated by Flopy.
        40         3         2         0         1128390.000        -1         0
```

**Comment by langevin-usgs** [comment]
@OnurSahin20, we looked deeper and there is an issue that you've discovered.  The USGS online guide for SFR (the image shown above) is incorrect and so is flopy regarding what to do when the FREE flag is set in the Basic Package.  MF2005 will read the stream package input using free format as shown by the mf2005 code below:

```
      IF(IFREFM.EQ.0) THEN
         READ(LINE,3)MXACTS,NSS,NTRIB,NDIV,ICALC,CONST,ISTCB1,ISTCB2
         LLOC=81
      ELSE
         LLOC=1
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,2,MXACTS,R,IOUT,IN)
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,2,NSS,R,IOUT,IN)
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,2,NTRIB,R,IOUT,IN)
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,2,NDIV,R,IOUT,IN)
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,2,ICALC,R,IOUT,IN)
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,3,I,CONST,IOUT,IN)
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,2,ISTCB1,R,IOUT,IN)
         CALL URWORD(LINE,LLOC,ISTART,ISTOP,2,ISTCB2,R,IOUT,IN)
      END IF
```

We need to fix the flopy STR class to handle this correctly, so I will reopen this issue.

**Comment by OnurSahin20** [comment]
Thanks a lot for your attention

**Comment by jdhughes-usgs** [comment]
You should change the model to free format using `m.set_ifrefm()`. Let me know if #838 does not fix your issue and I will reopen this issue.
