### ISSUE TITLE
Handling of inactive cells in mf6 package list-type datasets

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#835]
Currently, it looks like flopy doesn't check cellids in list-type input against the idomain array. For example, the line below would be written to the sfr file packagedata block as-is if cellid 1, 13, 24 were inactive. So it is on the user to identify cellids that are inactive and either remove them or convert to None. This applies to at least the sfr packagedata and GWF exchangedata, but presumably to other list input as well. Not sure if this is intentional or not, but thought I'd flag it case others were having issues. I can provide a working example if needed.

```
BEGIN packagedata
  1  1 13 24     191.72587585       1.79218234       0.05142112     296.43347168       1.00000000       1.00000000  0.03700000047683716  1       1.00000000  0
```

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs can we close this issue?
