### ISSUE TITLE
Contour plot error

### ISSUE THREAD

**Issue by jhpark16** [modflowpy/flopy#850]
This is similar to "PlotMapView.contour_array() is broken #587" but it looks like a different issue. The current flopy sometimes fail to use masked floating point values. For example, the following contour plot produces a colour map with a range from -1e+20 to 0.
h = flopy.utils.formattedfile.FormattedHeadFile(os.path.join(os.getcwd(),"Run/ModeloDrenajeInfraestructura.fhd"),model=ml)
h.plot(totim=2.73312e+08, contour=True, mflay=2, grid=False, colorbar=True, 
       figsize=(10,10), masked_values=[-2.e+20, -1.e+20]);

In the figure, the masked_values (-2.e+20, -1.e+20) are not masked. The issue is the line 152 of plot/map.py and np.ma.masked_equal sometimes fails to check equality with floating point numbers. The following three lines should be replaced with the next five lines.
        if masked_values is not None:
            for mval in masked_values:
                plotarray = np.ma.masked_equal(plotarray, mval)

        if masked_values is not None:
            for mval in masked_values:
                if isinstance(mval, int):
                    plotarray = np.ma.masked_equal(plotarray, mval)
                else:
                    plotarray = np.ma.masked_values(plotarray, mval)

If you have questions, please let me know. Thanks.

Cheers,
Jungho

**Comment by jlarsen-usgs** [comment]
@jhpark16 

Thanks for pointing out this issue. It seems that we can change

`np.ma.masked_equal(plotarray, mval)`
to
`np.ma.masked_values(plotarray, mval)`

without any conditional statements. The documentation for masked_values states that it behaves like masked_equal when integers are passed to the method.

Submitting a PR today to fix this issue.
