### ISSUE TITLE
current docs are for 3.2.13

### ISSUE THREAD

**Issue by dbrakenhoff** [modflowpy/flopy#852]
The [documentation](http://modflowpy.github.io/flopydoc/) is for 3.2.13 (that's the documentation page says), while 3.3.0 was released in December 2019.

**Comment by jdhughes-usgs** [comment]
@langevin-usgs is this something you can fix for the upcoming release?

**Comment by langevin-usgs** [comment]
I'll update the documentation concurrent with the next release.
