### ISSUE TITLE
Model name: upper case letters converted to lower case letter (MF6)

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#858]
In one of my code I defined a model name as follows: RH_modflow_model with the command:

`modelname = 'RH_modflow_model'`
`sim = flopy.mf6.MFSimulation(sim_name=modelname, version='mf6', exe_name=path_exe, sim_ws=workspace)`

when I run the command:

`print(sim.name)`

I get: 'rh_model_name'

in other words the capital letters are not respected. This could be a problem when post-processing the results as the command:

`gwf = sim.get_model('**RH**_modflow_model')`

does not work. Actually returns an empty value

**Comment by spaulins-usgs** [comment]
@giovannifi I was not able to reproduce this.  When I run:

print(sim.name)

I get "RH_modflow_model".  However, you do bring up a good point that sim.get_model should do a case insensitive search for the model name should the case sensitive search fail.  I have added a case-insensitive search to sim.get_model so it will return your model even if the case is incorrect.
