### ISSUE TITLE
Add zonebudget support for MODFLOW 6

### ISSUE THREAD

**Issue by jdhughes-usgs** [modflowpy/flopy#860]
Based on question by @LudovicSchorpp

Need to add options MODFLOW version. Maybe just passing in the GRB file name would be enough. Also need to make sure CellBudgetFile is set to `double` and use `flow-ja-face` for cell flows.

**Comment by jdhughes-usgs** [comment]
@jbellino-usgs maybe you would be interested in being involved in this.

**Comment by jbellino-usgs** [comment]
@jdhughes-usgs keep me in the loop. I'm working on a number of things at the moment, but would be interested to help out here wherever needed. Any timeline on it?

**Comment by jbellino-usgs** [comment]
Do you have a branch started?

**Comment by jdhughes-usgs** [comment]
I did but ditched it. I have started thinking that because of the multiple grid types in MODFLOW 6 and the advanced packages that maybe a thin wrapper around the MODFLOW 6 zone budget exe is a better way to go for this feature.

**Comment by jlarsen-usgs** [comment]
ZoneBudget6 class added in PR #1149
