### ISSUE TITLE
Error reading SFR Budget File with sfroutputfile Module of flopy

### ISSUE THREAD

**Issue by ccooledge** [modflowpy/flopy#861]
Hi Folks,

I am using the sfroutputfile module in flopy to read the SFR budget output file to a pandas dataframe. The code shown below worked under a previous build of flopy (v3.2.12) executed with python27. Trying to execute the code again with Python3 and flopy v3.3.0 produces an error when calling the get_dataframe() function.

`import os
import numpy as np
import pandas as pd
import flopy as fp
import flopy.utils.binaryfile as bf
from flopy.utils.sfroutputfile import SfrFile

inSFROut = './OUT_TR/SPV.sfrbud'
loadSFROut = SfrFile(inSFROut)
df = loadSFROut.get_dataframe()`

Error:
ValueError: invalid literal for int() with base 10: '5.5742E+01'

The value shown in the error is the first entry in the FLOW INTO STRM. RCH. column (column 6) of the SFR output file. The function seems to be looking for an integer in this column but is finding the value shown.

Thanks,
Craig

**Comment by jlarsen-usgs** [comment]
@ccooledge 

Hi Craig,

I'll take a look at the issue. Will you zip or 7zip a copy of your SFR output file and share it here. 

Thanks!

**Comment by ccooledge** [comment]
See attached. Thanks for taking a look!
[SPV_TR_V001.zip](https://github.com/modflowpy/flopy/files/4554850/SPV_TR_V001.zip)
