### ISSUE TITLE
error in translating ivertcon for flopy.mf6.modflow.mfgwfuzf.ModflowGwfuzf

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#862]
I have a problem with the UZF package. When I use the function "flopy.mf6.modflow.mfgwfuzf.ModflowGwfuzf" and If I assign ivertcon = 1 (under the block packagedata) in my python script, the uzf package reports 2 instead of 1. To get the package with ivertcon = 1 I have to assing ivertcon = 0 in the python script.

**Comment by emorway-usgs** [comment]
@giovannifi This behavior is what is expected with 0-based indexing, which is what the UZF package uses.  So for example, in a 1D model with 3 layers (3 cells total), the iuzno for the upper most cell would be 0, followed by 1 for the middle layer, and 2 for the bottom layer.  In this example, one would assign ivertcon values of 1, 2, and -1 to layers 1, 2, and 3, respectively.  When flopy writes the uzf package, the resulting vertical connections would all be incremented by +1.  Keep in mind that for the lowest layer, which has no vertical connection, you will want to set ivertcon=-1.  That way, when flopy writes the UZF input file for MF6, ivertcon is set to 0 for the bottom layer.

**Comment by giovannifi** [comment]
@emorway-usgs 
thanks for your kind reply. 
According to the documentation available ivertcon should not be 0-indexed. This is what I read from the manual ("mf6io.pdf"):

> "ivertcon—integer value set to specify underlying UZF cell that receives water flowing to bottom of  cell. If unsaturated zone flow reaches the water table before the cell bottom, then water is added to the GWF cell instead of flowing to the underlying UZF cell. A value of 0 indicates the UZF cell is not connected to an underlying UZF cell."<

It is my understanding from the definition above that ivertcon can have only two values 0 or any positive number.

This is the definition I car read from the flopy documentation (https://modflowpy.github.io/flopydoc/mfgwfuzf.html?highlight=uzf#module-flopy.mf6.modflow.mfgwfuzf)

> "ivertcon (integer) integer value set to specify underlying UZF cell that receives water flowing to bottom of cell. If unsaturated zone flow reaches the water table before the cell bottom, then water is added to the GWF cell instead of flowing to the underlying UZF cell. A value of 0 indicates the UZF cell is not connected to an underlying UZF cell."<

This definition is identical to the above. Therefore one would expect that by assigning ivertcon=0 in a python script this would be translated in ivertcon = 0 in the actual uzf file.

Same problem for  iuzno is 0-indexed.

I hope you can understand where I am coming from.

**Comment by emorway-usgs** [comment]
@giovannifi I don't disagree with the citations. For MF6 input, which is what the mf6io.pdf document aligns with, values need to be 1-based as the definitions state.  However, when working in python, and more specifically, flopy, UZF-related values like iuzno will be 0-based.  At some point in your flopy script, you'll do something akin to `sim.write_simulation()`, and when you do, flopy will adjust all of the 0-based values, like iuzno, to 1-based for MF6 (i.e., fortran).

**Comment by giovannifi** [comment]
@emorway-usgs never mind, I got the rule now and it is fine. However I believe that the available documentation is confusing.

Just a final question: in a full 3D model ivertcon should be the layer number of the cell receiving the flow. Is this right?

**Comment by emorway-usgs** [comment]
@giovannifi By way of example, consider a 2 x 2 x 2 model (8 cells total).  For layer 1, you could set:

lay 1 row 1 col 1: iuzno = 1 & ivertcon = 5
lay 1 row 1 col 2: iuzno = 2 & ivertcon = 6
lay 1 row 2 col 1: iuzno = 3 & ivertcon = 7
lay 1 row 2 col 2: iuzno = 4 & ivertcon = 8

and for layer 2 you could set:

lay 2 row 1 col 1: iuzno = 5 & ivertcon = 0
lay 2 row 1 col 2: iuzno = 6 & ivertcon = 0
lay 2 row 2 col 1: iuzno = 7 & ivertcon = 0
lay 2 row 2 col 2: iuzno = 8 & ivertcon = 0

If working in flopy, you'll need to make the appropriate adjustments (in other words, add -1 to all these values, including layer, row, column, iuzno, and ivertcon values.  In this way, when flopy writes the UZF input file, everything will come out with 1-based indices)

**Comment by giovannifi** [comment]
thanks a lot. it makes sense now.

**Comment by langevin-usgs** [comment]
@spaulins-usgs, because we know from the definition files which MODFLOW 6 variables are "index" variables, can we supplement the flopy docstrings with a statement that says: "This argument is an index variable, which means that it should be treated as zero-based when working with FloPy and Python.  Flopy will automatically subtract one when loading index variables and add one when writing index variables."  I think this will save people a lot of headache.

**Comment by spaulins-usgs** [comment]
@langevin-usgs, no problem, this is done.  I added the change to the PR #864 since it has not been committed yet.
