### ISSUE TITLE
length of records in tables argument to mf6.ModflowGwflak

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#867]
This is a new issue within the last week or two. According to the docstring, the records in tables should be `[lakeno, tab6_filename]`, but when just two items are entered, I get this error:
```python
E           flopy.mf6.mfbase.MFDataException: An error occurred in data element "tables" model "pleasant_mf6" package "lak_0". The error occurred while setting data in the "__init__" method.
E           Additional Information:
E           (1) Data line (0, './external/600059060_stage_area_volume.dat') only has 2 entries, minimum number of entries is 4.
E           (2) Error occurred while adding dataset "tables" to block "tables"
```
When I change the records in tables to `(lakeno, tab6_filename, 'junk', 'junk')`, everything works as expected (no error, and the output file is written correctly).

**Comment by langevin-usgs** [comment]
I'm seeing this too.  It's related to some of the checking that was implemented recently.  I think @spaulins-usgs is out this week, but will get it taken care of soon.

**Comment by aleaf** [comment]
Thanks @langevin-usgs, sounds good. Great that more checking is getting implemented.

**Comment by spaulins-usgs** [comment]
@aleaf The length checking has been fixed.  Please try the latest develop code.
