### ISSUE TITLE
Make a MODFLOW archive?

### ISSUE THREAD

**Issue by hwreeves-USGS** [modflowpy/flopy#87]
are there classes or methods written for flopy that will output a standard model archive structure by generating the required folders and structure from GW Technical memos  (00.02 and others) and then put relevant files accessible through flopy in the appropriate folders.  I'd be interested in starting such a utility method if it or plans for it does not exist.

**Comment by jdhughes-usgs** [comment]
Not yet but has been an item on our list of future improvements. We are working on some revisions to the model archive structure to facilitate online data release requirements. So it would be good to consider the new structure (or how to generalize it) and the best way to implement a defined archive structure in flopy. Maybe we could talk about it sometime. I will create an issue.
