### ISSUE TITLE
create a new ims package from a loaded mf6 model

### ISSUE THREAD

**Issue by oscarfasanchez** [modflowpy/flopy#870]
Hello I hope you can help me with this, I am loading a modflow 6 model created in modelmuse, the problem is that i want to change the ims package(create a new one) , but I get two ims package and I cant delete the first one, I get two files when I use "presa_sim.write_simulation()", and the mfsim.nam has 2 im6 files too, it is shown below.

(BEGIN SOLUTIONGROUP  1
  MXITER  1
  ims6  Modelo_Presa_Itabira_Stru_2stg.ims  modflow
  ims6  Modelo_Presa_Itabira_Stru_2stg_0.ims  MODFLOW
END SOLUTIONGROUP  1)

the script that I am using is the following:

import os
import numpy as np
import flopy as fp
import pandas as pd
import matplotlib.pyplot as plt

#directorios importantes
sim_name='Modelo_Presa_Itabira_Stru_2stg'
sim_path='../Presa_Itabira'
model_name='MODFLOW'

#cargar modelo existente
presa_sim=fp.mf6.MFSimulation.load(sim_name= 'Modelo_Presa_Itabira_Stru_2stg', version='mf6',exe_name='../mf6.exe',sim_ws=sim_path)
presa_model=presa_sim.get_model()

#create new path
save_folder=os.path.join(sim_path, 'sim_modified')
#create folder
presa_sim.simulation_data.mfpath.set_sim_path(save_folder)
#create new folder to save the new models
if not os.path.isdir(save_folder):
    os.makedirs(save_folder)

#building a new ims package
ims=fp.mf6.modflow.mfims.ModflowIms(presa_sim,print_option='SUMMARY',complexity='SIMPLE')
presa_sim.register_ims_package(ims,['MODFLOW'])

#Create files
presa_sim.write_simulation()

#run simulation
success,buff=presa_sim.run_simulation()
print('\nsuccess is: ', success)

BY THE WAY, I TRIED WITH THIS FUNCTIONS WITHOUT SUCCESS:
presa_sim.get_ims_package('MODFLOW')
presa_sim._replace_ims_in_solution_group
maybe I don't know very well how to use them, please I need some help
Thanks!!

**Comment by jlarsen-usgs** [comment]
@oscarfasanchez 
Have you tried the built in method `remove_package()`.

```
presa_sim.remove_package('ims')

# then build your new ims pacakage
...
```

**Comment by oscarfasanchez** [comment]
> @oscarfasanchez
> Have you tried the built in method `remove_package()`.
> 
> ```
> presa_sim.remove_package('ims')
> 
> # then build your new ims pacakage
> ...
> ```yes it works for the problem described above,  thanks
but now show up a new problem  when I used:


#a try to erase the existent ims package
presa_sim.remove_package('ims')

#building a new ims package
ims=fp.mf6.modflow.mfims.ModflowIms(presa_sim,pname='ims', print_option='SUMMARY',complexity='COMPLEX')
presa_sim.register_ims_package(ims,['MODFLOW'])

**MODFLOW SAYS:**

ERROR REPORT:

    ****ERROR. ILUT ERROR:  7
![Modflow_error](https://user-images.githubusercontent.com/39230212/81246824-300ea800-8fde-11ea-8a3c-b189d36dca2e.PNG)

**Comment by jlarsen-usgs** [comment]
@oscarfasanchez 

can you attach your model files to this issue, for debugging purposes?

**Comment by oscarfasanchez** [comment]
> @oscarfasanchez
> 
> can you attach your model files to this issue, for debugging purposes?

Sure.

https://correouisedu-my.sharepoint.com/:u:/g/personal/oscar_sanchez2_correo_uis_edu_co/EX7POjFFPwlPlC1Ryrt2XM8Bhes-oEXUJ2m2FvCXR7nhrA?e=Sdowsj

also I have to say that I modified mfsim file manually from modelmuse because it had absolute paths in names, but flopy run modflow without problems after this modification(before change the ims package), I did it because flopy write almost all the file in the old path instead of the new path


[mfsim.zip](https://github.com/modflowpy/flopy/files/4593573/mfsim.zip)

**Comment by oscarfasanchez** [comment]
i've  succesfully  installed flopy 3.3.1 by pip install https://github.com/modflowpy/flopy/zipball/develop
but I get the same mistake shown above
What am I doing wrong?

**Comment by jlarsen-usgs** [comment]
@oscarfasanchez

try running the pip install command again like this:

```
pip install https://github.com/modflowpy/flopy/zipball/develop --upgrade
```

Also try

```
ims = presa_sim.ims
presa_sim.remove_package(ims)

# then build and register your new ims pacakage
```

**Comment by oscarfasanchez** [comment]
I did it, but doesn't work
Modflow says the same thing,
if I use Complexity "SIMPLE" 
![SimpleError](https://user-images.githubusercontent.com/39230212/82494516-55f07e00-9aaf-11ea-95c0-9a03c3107b4a.PNG)
the error changes to this:

**Comment by jlarsen-usgs** [comment]
@oscarfasanchez 

I found the issue (actually two issues). 

1)  The `register_ims_package()` method is case sensitive. I'll put in another PR to fix this issue. Until then use lowercase:

```
presa_sim.register_ims_package(ims, ['modflow'])
```

2) You are using the UZF package in your model, which is non-linear, so you'll need to specify MODERATE complexity instead of SIMPLE in your IMS file.

**Comment by jlarsen-usgs** [comment]
@oscarfasanchez 

Here is the code snippet I'm using to run your model.

```
import flopy as fp
import os

wd = os.path.abspath(os.path.dirname(__file__))
outdir = os.path.join(wd, "temp")
ws = os.path.join(wd, "..", "Presa_Itabira")

sim = fp.mf6.MFSimulation.load("mfsim", sim_ws=ws)

ims = sim.ims
sim.remove_package(ims)

ims = fp.mf6.ModflowIms(sim, print_option="SUMMARY", complexity="MODERATE")
sim.register_ims_package(ims, ['MODFLOW'])
sim.set_sim_path(outdir)

sim.write_simulation()

success, buff = sim.run_simulation()
```

**Comment by oscarfasanchez** [comment]
it worked, thanks!!!
