### ISSUE TITLE
Output format for external MODFLOW6 files using `set_all_data_external`

### ISSUE THREAD

**Issue by mnfienen-usgs** [modflowpy/flopy#871]
I've invoked `set_all_data_external` which is doing a good job of making all array and list-directed data pushed out to external files. Super helpful for PEST!

However, the files are only writing 20 values per line resulting in old-school file formats that can't be correctly read back into Python using tools like `np.loadtxt` unless you happen to have a multiple of 20 columns in the model. It would be more Pythonic and much more useful to write these files as nrow x ncol instead.

**Comment by emorway-usgs** [comment]
@mnfienen-usgs you've undoubtedly come up with a sophisticated work around for the 2nd part of your post, but for those that need a quick work around that unfortunately requires a small amount of manual labor, I'm posting a script I've used in the past.  It requires that the user extract the block-style array and paste it in a dedicated file - `rcha_1.txt` in the example below:

```
import numpy as np
import os

# Users must set the following variables on a case-by-case basis
nrow = 64
ncol = 133
pth = r'c:\temp\'
arr_file = 'rhca_1.txt'  

f = open(os.path.join(pth, arr_file),'r')

ls = []
for line in f:
    m_arr = line.strip().split()
    for itm in m_arr:
        ls.append(float(itm))


f.close()

ls_arr = np.array(ls)
ls_org = ls_arr.reshape((nrow,ncol))

fname = os.path.join(pth, arr_file + '.new')
np.savetxt(fname, ls_org, fmt='%12.6f', delimiter='')    # %12.3f # %15.6e

```

**Comment by spaulins-usgs** [comment]
@mnfienen-usgs the maximum number of values per line is being controlled by the "max_columns_of_data" property.  This can be set by:

sim.simulation_data.max_columns_of_data = <positive integer value>

where sim is you MFSimulation object and <integer value> is a positive integer value.  When max_columns_of_data  >= to the number of columns in your model, flopy should write these files out as nrow x ncol.

**Comment by spaulins-usgs** [comment]
@mnfienen-usgs Assuming that setting max_columns_of_data solved the problem.  If it didn't message me and I will look into it.

**Comment by andyrich** [comment]
I would argue for having the max_columns_of_data be set to a very large number by default in flopy. If people want to have formatted-like files, then they can set that up. I, for example, just spent a couple hours searching for this setting, and it seems, given the conduit to pyemu, rasterio, etc, having these regular grid-like arrays makes more sense than having a default of 20 rows.

**Comment by wpbonelli** [comment]
@andyrich  may be worth making a separate issue/discussion, so we can keep this mind for future development

**Comment by jtwhite79** [comment]
@andyrich I completely agree.  Let's move beyond punch card requirements! haha
