### ISSUE TITLE
Cannot get data from Mf6Obs object with 1 row

### ISSUE THREAD

**Issue by dbrakenhoff** [modflowpy/flopy#874]
As I was testing the observations options for Modflow6, I came across the following error when attempting to get the data from an obs file using `flopy.utils.Mf6Obs`. 

```python
IndexError: tuple index out of range
> /flopy/flopy/utils/observationfile.py(100)get_data()
     98         """
     99         i0 = 0
--> 100         i1 = self.data.shape[0]
    101         if totim is not None:
    102             idx = np.where(self.data['totim'] == totim)[0][0]
```

My obs file has a single time at which there is data. This somehow results in a numpy rec-array with no shape (shape is an empty tuple). This causes all the methods that use the shape attribute to crash.

The `riv_flows.csv` file:
```
time,RIV1,RIV2
1.0,200.0,100.0
```

This probably doesn't happen too often, but should be easy to fix? Or am I doing something wrong?

**Comment by langevin-usgs** [comment]
![image](https://user-images.githubusercontent.com/3372403/81632870-eb658100-93d0-11ea-8a51-b78fc5e0c4e4.png)

Not sure what's going on there.  I wonder if we need a skiprows=1 in the numpy loadtxt?  Of course a pandas read_csv might be much easier for reading the ascii version of the mf6 obs output.

**Comment by langevin-usgs** [comment]
Scratch that last comment.  Looks like when there is only one record the numpy loadtxt returns a shape as an empty tuple, as you said in your post.  We should fix this.  Thanks for pointing it out.

**Comment by spaulins-usgs** [comment]
@langevin-usgs this can be fixed by setting ndmin equal to 1 in np.loadtxt:

            self.data = np.loadtxt(self.file, dtype=self.dtype, delimiter=',', ndmin=1)

I will add this fix to the fork I am currently working on and include it in my next PR.

**Comment by spaulins-usgs** [comment]
@dbrakenhoff this should be fixed now.  Please try again with the latest flopy code.

**Comment by dbrakenhoff** [comment]
Yep, it works now! Thanks! I took the liberty to close the issue.
