### ISSUE TITLE
Flopy.utils.zoneBudget does not match USGS zone buget when there are zone zero sections

### ISSUE THREAD

**Issue by hansonmcoombs** [modflowpy/flopy#882]
I have found that the flopy implementation does not appropriately replicate the outputs of USGS zone budget when there are zone zero areas which have a ibound==1.

I believe the problems are in lines 708 and 724 (line numbers relate to version 3.3.0 which was the most up to date version of zonebud.py at time of writing).  My understanding of the point of this line is to remove the values that would need a column name for zone 0, but instead idx will be all False if tz or fz ==0, respectively.  I am not submitting a pull request as I have not used modflow6 and I would not want to cause unexpected problems with that.

my proposed fix:
* line 708
   * currently:  idx = np.logical_not(np.array([item in tz for item in [0] * len(tz)]))
   * suggested correction: idx = tz  != 0
* line 724
   * currently:  idx = np.logical_not(np.array([item in fz for item in [0] * len(fz)]))
   * suggested correction: idx = fz  != 0

So that you can fully check the issue I have attached a zip file with a .cbc, my zone arrays, and a script to run the flopy zone budget.  I have also included the outputs, (.zlist) and .exe for the usgs zone budget program for comparison.  
[test_zone_bud.zip](https://github.com/modflowpy/flopy/files/4625613/test_zone_bud.zip)

**Comment by jbellino-usgs** [comment]
@hansonmcoombs, I can't seem to replicate the budget discrepancies based on the attached files. I reran the Zonbudget analysis using the "CSV 2" output option to make comparison easier. Here is what I came up with:

![2020-05-18_11-59-00](https://user-images.githubusercontent.com/8257727/82234147-079c7d00-98ff-11ea-9d2f-768400edb7f7.png)

![2020-05-18_11-47-00](https://user-images.githubusercontent.com/8257727/82233444-07e84880-98fe-11ea-826f-04c7383b458d.png)

**Comment by jbellino-usgs** [comment]
I misunderstood the situation, please disregard. I see that there are discrepancies in zones 2–5 and will look into the issue.

**Comment by jdhughes-usgs** [comment]
@jbellino-usgs is this something you can address this week (week of 6/8/2020)?

**Comment by jbellino-usgs** [comment]
@jdhughes-usgs It's on my radar, I will do my best to get it done before the next release. The use of zone 0 as a zone of interest was not something I had anticipated so some of the work will be in finding the hard-coded bits to release the constraint.

**Comment by hansonmcoombs** [comment]
@jbellino-usgs   I think you may still be mis-interpreting my issue; apologies for not being clear enough.  I was not interested in zone zero, but it if zone 0 contains active cells, I found that when there is any flow from zone 0 to a named zone (e.g. zone1)  passed to _update_budget_fromfaceflow, all flows are not added to the budget array. 

 For example if fz=[0,1,2,1] and tz=[1,2,0,2] from passed from _accumulate_flow_frf then none of the frf flows are added to the budget.  

This is because in line 708: idx = np.logical_not(np.array([item in tz for item in [0] * len(tz)])) for the example idx = [False, False, False, False].  708 as it is currently written is identical to:  np.repeat((0 not in tz), len(tz))

this makes 709: fzi = np.array([])
 and 710: tzi = np.array([])

if done correctly, idx = [True, True, False, True] so that the flow from zone 0 to zone 1 is added to the budget along with the flow from zone 1 to zone 2, but not the flow from zone 2 to zone 0.

This would mean that:
 fzi=[0,1,1] 
tzi=[1,2,2]

my suggested correction for 708: idx = tz != 0 yields that result and provides identical results to the published USGS ZoneBudget  

724 is the same but with fz replacing tz

**Comment by jbellino-usgs** [comment]
@hansonmcoombs you are correct, thanks for the sample code. I'll use that to update the utility and develop a test for the condition where there are active cells in zone 0 to ensure flow from those cells gets incorporated into the face-flow arrays as the should.
