### ISSUE TITLE
potential SFR numbering issue

### ISSUE THREAD

**Issue by hwreeves-USGS** [modflowpy/flopy#883]
I exported a modelgrid to a shapefile using mf.modelgrid.write_shapefile(), later I read the grid into a dataframe so I have 'node, row, column'.  I selected a subset of model cells and then joined the resulting table to a dataframe of SFR reach_data using 'node' as the index.  The problem is that the (row, column) and (i,j) numbering is inconsistent:  i is one less than row making me think that row is in MODFLOW numbering and i is in zero-based; but j is the same as column.

Here is what I used:
reach_df = pd.DataFrame.from_records(mf.sfr.reach_data)
reach_df.set_index('node', inplace=True)
sel_df.set_index('node',  inplace=True)  # my subset of target cells
target_reach_df = sel_df.join(reach_df, how='inner')

cutting out some of the columns: here is the top of the join:

	row	column	k	i	j
node					
68572	106	322	0	105	322
68573	106	323	0	105	323
68574	106	324	0	105	324
69220	107	320	0	106	320
69221	107	321	0	106	321

**Comment by jlarsen-usgs** [comment]
@hwreeves-USGS 

It looks like the issue you're running into is that the "node" field in `sfr.reach_data` is zero based. If you use `reach_df.node += 1` before performing your join with the shapefile record you will have a one based row, column field and a zero based k, i, and j field as expected.
