### ISSUE TITLE
flopy+MF6+quadtree+rewetting NPF writing package error

### ISSUE THREAD

**Issue by manupy-hub** [modflowpy/flopy#884]
Hi, I am building a model in flopy+MF6+quadtree+rewetting. My problem is when I create the npf package I have an error and I don't understand the reason. this error appears when I write the package. it is like it does not create the rewet option in the npf package. Do you have any idea how to resolve it?
wetfct=1
iwetit=1
ihdwet=0
 npf = flopy.mf6.ModflowGwfnpf(gwf, pname='npf', save_flows=True, icelltype=[1,1], k=k_template,
                              k22=k_template,k33=k_template,rewet_record=[wetfct, iwetit, ihdwet] ,wetdry=wetdry)

error

An error occurred in data element "rewet_record" model "Model1_rewet" package "npf". The error occurred while converting data to a string in the "_get_file_entry_record" method.
Additional Information:
(1) An error occurred while converting data to a string. This error occurred while processing "rewet_record" line iwetit data item "1".(data path: ('Model1_rewet', 'npf', 'options', 'rewet_record')).
(2) Error occurred while writing data "rewet_record" in block "options" to file

Thank you!

**Comment by langevin-usgs** [comment]
How about something like this:

```
rewet_record = [('WETFCT', 1.0, 'IWETIT', 1, 'IHDWET', 0)]
```

**Comment by manupy-hub** [comment]
Great! thanks! it works :)

**Comment by sebmeng** [comment]
when defining the rewet record, is neccesary to also define the wetdry parameter?
