### ISSUE TITLE
origin_loc attribute in flopy.discretization.grid.Grid

### ISSUE THREAD

**Issue by hwreeves-USGS** [modflowpy/flopy#885]
I am using discretization.structuredgrid() to set a modelgrid object and then reading the
usgs.model.reference file.  

mf.modelgrid = flopy.discretization.structuredgrid.StructuredGrid(mf.dis.delc, mf.dis.delr)
mf.modelgrid.read_usgs_model_reference_file(os.path.join(source_dir, 'usgs.model.reference'))

I tried putting origin_loc='ul' in the call when the object was made; but flopy didn't recognize it.

The model reference file specifies a UL corner and rotation, but the modelgrid object is 
computing a LL corner (without rotation) from the information in the reference file and then
rotating around the LL.  Now that I see what's happening I can deal with it in the 
client code; but the documentation says the grid object should have a origin_loc attribute
and I can't seem to set it right.

**Comment by jlarsen-usgs** [comment]
@hwreeves-USGS 

I put in a pull request to address this issue. As you had stated, the model wasn't being rotated prior to calculating xll and yll from xul and yul, which was causing the modelgrid vertices to be projected in the wrong location. The `read_usgs_model_reference_file()` method now rotates the modelgrid, before calculating xll and yll when xul and yul are read in.
