### ISSUE TITLE
Modflow 6 flopy Ss and Sy

### ISSUE THREAD

**Issue by ebake310** [modflowpy/flopy#888]
I am trying to specify different Ss and Sy values for each layer in a 3 layer model. I found some code in one of the tutorials but cannot seem to get it to work even before I try to modify it (it throws an error when I try to run the simulation). Wondering how to get it to work/if this code does not actually do what I think it does? How would I modify it to specify a different Sy value for each layer?

sy = flopy.mf6.ModflowGwfsto.sy.empty(gwf, layered=True)
for layer in range(0,2):
    sy[layer]['data'] = 0.2  
ss = flopy.mf6.ModflowGwfsto.ss.empty(gwf, layered=True)
sto = flopy.mf6.ModflowGwfsto(gwf, pname='sto', save_flows=True, iconvert=0, 
                              ss=ss, sy=sy, steady_state={0:True},
                              transient={1:True})

**Comment by emorway-usgs** [comment]
@ebake310 what about trying something like this:
```
sy_1 = np.ones((nrow, ncol)) * 0.28
sy_2 = np.ones((nrow, ncol)) * 0.30
sy_3 = np.ones((nrow, ncol)) * 0.32

sy   = [sy_1, sy_2, sy_3]
```
Then, in the constructor, just pass the sy list above to the sy argument, just as you showed it:
```
sto = flopy.mf6.ModflowGwfsto(gwf, ..., sy=sy, ...
```

**Comment by ebake310** [comment]
Thank you so much, that worked!
