### ISSUE TITLE
UZF package MODFLOW6 and Unstructured Grids

### ISSUE THREAD

**Issue by newuser2021** [modflowpy/flopy#930]
Regarding the current status of MODFLOW6. I was hoping someone could answer a basic question for me. Is it possible to simulate UZF flow using unstructured grids DISV6/DISU6 with MODFLOW6? Or is this type of functionality in the pipeline?

**Comment by jdhughes-usgs** [comment]
This is a MODFLOW 6 question not a flopy question. The UZF package can be used with all MODFLOW 6 discretization types. You have to specify the correct `cellid` type for the grid (layer row column for DIS, layer node for DISV, and node for DISU).
