### ISSUE TITLE
How to give a name to UCN file instead of MT3Dxxx.UCN?

### ISSUE THREAD

**Issue by mustafaucr** [modflowpy/flopy#935]
I want to give a name to MT3Dxxx.UCN file name(s) instead of default names (MT3D001.UCN, MT3D002.UCN, MT3D003.UCN etc.). I found a parameter in `Mt3dBtn` and it's name is `species_names`. But it does not work for me it still generate default UCN file names. 

Is there a way to give different names for *.UCN files that will be generated?

**Comment by mwtoews** [comment]
This is documented in the [MT3DMS v5.3 manual](https://hydro.geo.ua.edu/mt3d/mt3dms_v5_supplemental.pdf) around page 5 with an example on page 7. With flopy use [`flopy.mt3d.mt.Mt3dms.add_output`](https://modflowpy.github.io/flopydoc/mt.html#flopy.mt3d.mt.Mt3dms.add_output), e.g.:

    mt = ...  # however you create the mt3d object
    mt.add_output('first_species.ucn', 201, binflag=True)

**Comment by mustafaucr** [comment]
Many thanks!
