### ISSUE TITLE
FloPy ETS package support

### ISSUE THREAD

**Issue by krlo-s** [modflowpy/flopy#939]
Greetings FloPy development team.

First of all I want to thank you for this excellent Python project, my most sincere admiration for all your hard work. I would like to ask you if you could add support for the MODFLOW ETS package please.

Thank you for all your hard work and effort put in this project,
Kind regards

**Comment by jdhughes-usgs** [comment]
@krlo-s I have tagged this as a suggested enhancement. The MODFLOW 6 ET package can be configured to simulate segmented evapotranspiration and there is full support for the MODFLOW 6 ET package in flopy.

**Comment by jdhughes-usgs** [comment]
@krlo-s Adding additional functionality for previous versions of MODFLOW is low-priority. If ETS support is critical for you we would welcome a pull request (PR) with the enhancement and one or more autotests. Reopen this issue if you decide to tackle this enhancement.
