### ISSUE TITLE
Bugs in plotting shape files 

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#94]
In the notebook for maps (http://nbviewer.jupyter.org/github/modflowpy/flopy/blob/master/examples/Notebooks/flopy3_MapExample.ipynb), there is a bug in In [21]. facecolors should be changed to facecolor in the following line. 

patch_collection = modelmap.plot_shapefile(shp, #**facecolors**='none', 
                                           edgecolors='green', linewidths=2, alpha=0.5)

**Comment by langevin-usgs** [comment]
Fixed these errors in the notebook.  Thanks.
