### ISSUE TITLE
Saving observations for CHD in MF6.

### ISSUE THREAD

**Issue by haugwitz** [modflowpy/flopy#940]
When I try adding observations for named bounds in CHD, in this example the bound called INF.

cont_obs = ['CHD1','CHD','INF']

obs = flopy.mf6.modflow.mfutlobs.ModflowUtlobs(model, digits=8, print_input=True, continuous=cont_obs)#, filename=None, pname=None, parent_file=None

I get an error:

ERROR REPORT:

  1. *** ERROR OPENING FILE "mf6NHTModel.obs" ON UNIT 1013
  2. *** FILE ALREADY OPEN ON UNIT: 1011
  3.       SPECIFIED FILE STATUS: OLD
  4.       SPECIFIED FILE FORMAT: FORMATTED
  5.       SPECIFIED FILE ACCESS: SEQUENTIAL
  6.       SPECIFIED FILE ACTION: READ
  7.         IOSTAT ERROR NUMBER: -1
  8.  -- STOP EXECUTION (openfile)

I also tried manually fixing the OBS file, the Nam and the CHD files and got the same error when executing the simulation with flopy. 

I have tried with mf6.0.1 and 6.1.1 and running flopy 3.3.0

I have not found any documentation showing the use of observations on flows in cells in the constant head package besides the example file in the modflow6 manual.

I am not entirely sure if this is a modflow issue or a flopy issue.

**Comment by emorway-usgs** [comment]
@haugwitz Are you able to share your model input files (trimmed of transient input > stress period 1 or 2)?  Or share the flopy script that generates the model input?

**Comment by haugwitz** [comment]
I used another example to do it and it worked well.
