### ISSUE TITLE
irch being read as 1-based from MODFLOW 6 input files?

### ISSUE THREAD

**Issue by mnfienen-usgs** [modflowpy/flopy#941]
In reading a MODFLOW6 model with flopy, the data for `irch` in the `rcha` package is indicating a layer ID for highest active layer, but flopy is reading the data as 1-based. Assuming this should be converted to 0-based (important because was reading it to use for assigning particles to highest active layer in MODPATH, so had to subtract 1 to have the right values in flopy)

**Comment by jdhughes-usgs** [comment]
@spaulins-usgs Could you take a look at this?

**Comment by spaulins-usgs** [comment]
@mnfienen-usgs a fix was just merged into the latest version of flopy.  Please let me know if it solves your problem.
