### ISSUE TITLE
flopy.modflow.mfdisu Module

### ISSUE THREAD

**Issue by Muhammad-waqas-ahmad1122** [modflowpy/flopy#952]
Hello,
I am trying to create a sewer network model and then i have to analyse it for containment spreading via ModFlow and MT3d. For this I have to draw a network from some random coordinates of nodes(which i have in txt file) and connecting pipes between these nodes in Flopy.
Can anyone suggest how to define these coordinates in Flopy.
As i am at beginner level in Python, so your help is appreciated.
Thank you.

**Comment by langevin-usgs** [comment]
Sorry, but this is not an issue with FloPy.  Suggest you try an alternative resource, such as the MODFLOW google groups page.  https://groups.google.com/forum/#!forum/modflow
