### ISSUE TITLE
write_file() / util_array array2string speed

### ISSUE THREAD

**Issue by cnicol-gwlogic** [modflowpy/flopy#961]
I am finding writing large arrays (like JA in a disu file) using package_object.write_file() really really slow (many hours for a JA of size ~10M - ridiculous model size I know, but not hugely uncommon). 

My experimentation suggests that the bottleneck is in utils/util_array.py() in function array2string, which uses the string += "more" and s = s + "more" methods. This is [known to scale badly with size](https://stackoverflow.com/questions/1316887/what-is-the-most-efficient-string-concatenation-method-in-python). 

For formatting/concatenating an array of size 1 million, my tests suggest:
1) ~9 secs for string = string + "more" method.
2) ~1 sec for "".join([output_format.format(value) for value in array]) method (with if...else for new lines at row ends, etc). And this is pretty quick for my real case.

I also tested for 10M element arrays, and gave up waiting for method (1), and method (2) was ~12 secs. I can provide the notebook that shows this if anyone is interested.

_<edit: I also tried numpy.array2string() - but it seems it culls the length of the string (inserts "...") for big arrays. Testing when turning this off (using the "threshold" parameter) looks significantly slower than both options tested above. So I don't think this is a good option.>_

In  Flopy util_array() array2string function, if I use: 

```python
len_data = len(data.flatten())
str_fmt_data = [
    output_fmt.format(d) + "\n"
    if (((i + 1) % column_length == 0.0) and (i != 0 or ncol == 1))
    or ((i + 1 == ncol) and (ncol != 1))
    or (i + 1 == len_data)
    else output_fmt.format(d)
    for i, d in enumerate(data.flatten())
]
s = "".join(str_fmt_data)
```

...preliminary testing suggests that I can replicate flopy's existing formatting behaviour, but I need to test more comprehensively to be sure. The one thing this approach does not cater for is error trapping on an element by element basis as is currently implemented - but I don't see this as a real problem; and we could have a fallback to trap for it if desired, albeit using the current slow method (i.e. try: new method / except: old method). 

Before I implement and more fully test this for a pull request, I wanted to canvas opinion/interest/acceptability for such a change. Thoughts appreciated. Thanks a lot,

Chris.

**Comment by jwhite-usgs** [comment]
@cnicol-gwlogic - this sounds like a reasonable switch to me.  I wonder how much time is being spent in the error trapping?  Do you profile any of this?

**Comment by cnicol-gwlogic** [comment]
Thanks for the feedback @jwhite-usgs, appreciate it. I hadn't profiled this, but now I have :) 

It certainly confirms what I thought: that the existing flopy method in my case spends 1594 seconds  in array2string, of 1613 seconds total disu.write_file() time. But I can't work out how to see where time was spent within that array2string call using cprofile. Using my revised "".join() method above, it uses only 13 of a total of 18 seconds (i.e. ~90x speedup, which would be massively beneficial in a pest / flopy run, for example).

I'll submit a pull request and see what happens; it passes all tests, so I am comfortable it is robust. Thanks a lot.
