### ISSUE TITLE
How to correctly activate the Newton-Raphson formulation in flopy modflow 6

### ISSUE THREAD

**Issue by ebake310** [modflowpy/flopy#968]
Trying to use/activate the Newton-Raphson formulation in modflow 6 using flopy. First I added 'newtonoptions=True' to the ModflowGwf line:
gwf = flopy.mf6.ModflowGwf(sim_sub, modelname=name, newtonoptions=True)
(newtonoptions=True activates the Newton-Raphson formulation for groundwater flow between connected, convertible groundwater cells. Cells will not dry when this option is used)

However, I received this error message:
MODEL PO_MODEL_SUB PRODUCES AN ASYMMETRIC COEFFICIENT MATRIX, BUT THE    
      CONJUGATE GRADIENT METHOD WAS SELECTED. USE BICGSTAB INSTEAD.
 ERROR OCCURRED WHILE READING FILE:
   /Users/emilybaker/Documents/Italy_postdoc/Model_outputs/Sub_extent/Po_model_sub.ims

I looked through the documentation for BICGSTAB and found it under ims, so I added "linear_acceleration='BICGSTAB' " and "complexity='MODERATE' " to the Ims line in my code:
ims = flopy.mf6.ModflowIms(sim_sub, complexity='MODERATE', linear_acceleration='BICGSTAB')

However, I then received this error message:
 Error: Required block "NONLINEAR" not found. Found block "LINEAR" instead.
 ERROR OCCURRED WHILE READING FILE:
   /Users/emilybaker/Documents/Italy_postdoc/Model_outputs/Sub_extent/Po_model_sub.ims

Looking through the documentation on the ims file I could not find a way to specifically write the nonlinear block. I did manually go into the ims file and added the lines:
BEGIN nonlinear
END nonlinear

This made the model run successfully, but I did not want to have to make this manual alteration every time. So then I tried adding the command "outer_hclose=0.01" to the ims line in flopy since **this is part of the set of outer iteration commands which to me appear to be what is the nonlinear block? Is this the correct way of thinking of the nonlinear block?** 
ims = flopy.mf6.ModflowIms(sim_sub, complexity='MODERATE', linear_acceleration='BICGSTAB', outer_hclose=0.01)

This addition to this line makes the model run without needing to make any manual alterations to the ims file (The code will also run when  "complexity='MODERATE'" is left out of the code). **However, is this the correct way to be implementing the newton method? Are there any other commands I should be adding?**

**Comment by ebake310** [comment]
Ok, thank you for the direction to the google group. Also, the instructions at the above link for activating the Newton-Raphson in modflow 6 still gives an error:

#code modified from notebook:
gwf.name_file.newtonoptions = ('')
(originally model.name_file.newtonoptions = ('') )

Produces error:
MODEL PO_MODEL_SUB PRODUCES AN ASYMMETRIC COEFFICIENT MATRIX, BUT THE
CONJUGATE GRADIENT METHOD WAS SELECTED. USE BICGSTAB INSTEAD.

**Comment by jdhughes-usgs** [comment]
You need to use a different linear accelerator (`BICGSTAB`) if you are using the Newton-Raphson formulation. You can use the `complexity="complex"` in the `IMS` package or set the linear accelerator manually to `BICGSTAB`. There are examples of this in the `*mf6*.ipynb` Notebooks.
