### ISSUE TITLE
ZoneBudget error with MODFLOW 6

### ISSUE THREAD

**Issue by ebake310** [modflowpy/flopy#974]
I am trying to run Zonebudget on a Modflow 6 model in Flopy. However when I try to run ZoneBudget I get an error that the row/col dimensions do not match. When I explore the .cbc file 17078876 is the length of the cobj.get_data(text='FLOW-JA-FACE'). Should the length of the .cbc  'FLOW-JA-FACE' file match the number of cells in the model domain because currently the length of the .cbc  'FLOW-JA-FACE' file is much longer? Is the .cbc  'FLOW-JA-FACE' file not generating correctly or is zonebudget not reading the cbc  'FLOW-JA-FACE' file correctly? I cannot find any other arrays besides the .cbc 'FLOW-JA-FACE' file with a length of 17078876 so I am guessing the zonebudget error is related to the .cbc  'FLOW-JA-FACE' file?

#cobj.list_unique_records()
#RECORD           IMETH
#----------------------
#FLOW-JA-FACE         1
#DATA-SPDIS           6
#RCH                  6
#CHD                  6

## Set up zones
nlay, nrow, ncol = 3, 1631, 1474 # dimensions of model grid
shape3d = (nlay, nrow, ncol)
zones = np.ones(shape3d, dtype=np.integer)
zones[0][500] = 2

## Run zone budget for MODFLOW 6
cbc_f = '//Users/Documents/Model_outputs/Full_extent/model.cbc'
zb = flopy.utils.zonbud.ZoneBudget(cbc_file=cbc_f, z=zones)

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-69-5e3307d54c37> in <module>
      6 # Run zone budget for MODFLOW 6
      7 cbc_f = '//Users/emilybaker/Documents/Italy_postdoc/Model_outputs/Full_extent/Po_model.cbc'
----> 8 zb = flopy.utils.ZoneBudget(cbc_file=cbc_f, z=zones)

/opt/miniconda3/envs/pyclass/lib/python3.8/site-packages/flopy/utils/zonbud.py in __init__(self, cbc_file, z, kstpkper, totim, aliases, verbose, **kwargs)
    122             ' do not match model row/col dimensions {}'.format(z.shape,
    123                                                                self.cbc_shape)
--> 124         assert z.shape[-2] == self.nrow and \
    125                z.shape[-1] == self.ncol, s
    126 

AssertionError: Row/col dimensions of zone array (3, 1631, 1474) do not match model row/col dimensions (1, 1, **17078876**)

**Comment by jdhughes-usgs** [comment]
@ebake310 flopy zonebudget functionality does not work for MODFLOW 6. This is on our list of flopy enhancements for the next version (see issue #860).

**Comment by jlarsen-usgs** [comment]
Issue addressed with PR #1149
