### ISSUE TITLE
'MtListBudget' object has no attribute 'get_budget' error

### ISSUE THREAD

**Issue by mustafaucr** [modflowpy/flopy#977]
[In flopy documentation](http://modflowpy.github.io/flopydoc/mtlistfile.html#flopy.utils.mtlistfile.MtListBudget) says `MtListBudget `can be read as dataframe by using `get_budget()`

But in my code it does not work:

```
from flopy.utils.mtlistfile import MtListBudget

budget_file = r"D:\Projects\mt3d_example\hidrojeoloji.list"
budgetObj = MtListBudget(budget_file)
print(budgetObj.get_budget())
```
It gives me that error:

`AttributeError: 'MtListBudget' object has no attribute 'get_budget'`

**Comment by jdhughes-usgs** [comment]
@mustafaucr The example in the documentation is clearly wrong.

@langevin-usgs do you know why there is a separate `MtListBudget` class rather than inheriting from `ListBudget`??

**Comment by jdhughes-usgs** [comment]
The documentation has been moved to Read the Docs, although there is no `MtListBudget` example. Several example showing use of `MtListBudget` are given in `autotest\t055_test_mt3d_list.py`. We probably need to consolidate `MtListBudget` into `ListBudget`.
