### ISSUE TITLE
AttributeError when access modelname attribute 

### ISSUE THREAD

**Issue by flydream0428** [modflowpy/flopy#992]
`# create flopy objects for packages`
`modelname = 'P10'`
`mf = flopy.modflow.Modflow(modelname=modelname, exe_name='mfnwt_64.exe', version='mfnwt', model_ws='pred_m') `
`mf.modelname`

**The code above will return an AttributeError as follows when I try to get the modelname attribute.** 

AttributeError                            Traceback (most recent call last)
<ipython-input-13-6a6f7d7022ac> in <module>
----> 1 mf.modelname

~\AppData\Local\Continuum\miniconda3\envs\wtc2\lib\site-packages\flopy\mbase.py in __getattr__(self, item)
    633         if item == 'modelgrid':
    634             return
--> 635         raise AttributeError(item)
    636 
    637     def get_ext_dict_attr(self, ext_unit_dict=None, unit=None, filetype=None,

AttributeError: modelname

**Comment by mwtoews** [comment]
You should find this attribute with `mf.name`

There used to be a `modelname` attribute that returned `None`, but this was dropped before version 3.2.12.

**Comment by jdhughes-usgs** [comment]
Reopen the issue if this did not solve your issue.
