### ISSUE TITLE
modpath7 issues with flopy.utils.modpathfile

### ISSUE THREAD

**Issue by dryter-usgs** [modflowpy/flopy#993]
I'm using flopy 3.3.1
The model is MF6, and ModPath 7. The model is too big to upload but I uploaded the ModPath files.
[mpath.zip](https://github.com/modflowpy/flopy/files/5247502/mpath.zip)

Problems with:
get_destination_pathline_data
and get_destination_endpoint_data
and get_destination_timeseries_data

There are two things happening.
I cannot select destination cells using [(k, i, j)], I have to use node number. if I try it with this code
p = flopy.utils.PathlineFile(fpth)
pw7 = p.get_destination_pathline_data(dest_cells=[(0, 31, 43)])
I get the error: "ValueError: could not assign tuple of length 3 to structure with 1 fields."

When I use node number, only the paths entering the cell from the left side are selected (see attachment). And sometimes the paths selected aren't even entering the cell. I don't remember having this problem in 3.3.0

I attached the script and two figures I saved, one with only pathlines that end up in the well 32H1S, and another will all lines. I hope it isn't my code. I've gone over it and over it and can't figure out why it doesn't work. 

![pathmap_forward_pathlines_5_0 3_all](https://user-images.githubusercontent.com/7771493/93630109-ab2d9500-f9a6-11ea-80a9-3fd3d49fc71d.png)
![pathmap_forward_pathlines_5_0 3_slice](https://user-images.githubusercontent.com/7771493/93630119-ad8fef00-f9a6-11ea-9214-4e7a070cd9d1.png)

[mpath_forward.zip](https://github.com/modflowpy/flopy/files/5247395/mpath_forward.zip)

**Comment by langevin-usgs** [comment]
It is true that for mp7, the get_destination_pathline_data() method requires a grid node number, and not layer, row, column, so the docstring should be updated.  The notebook linked below shows that these methods are working fine for the MODFLOW 6/MODPATH 7 combination for a multilayer structured grid model.  If you can reproduce your problem with a small example we'd be happy to have a look.

https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_modpath7_structured_example.ipynb

**Comment by jdhughes-usgs** [comment]
@langevin-usgs is this resolved?
